import type { Formule } from '../../../engine/types';

const M11 = '11-histoire-crises';

export const formules: Formule[] = [
  {
    id: 'm11-f-01',
    moduleId: M11,
    nom: 'Levier de bilan',
    nomEn: 'Balance-sheet leverage',
    latex: '\\lambda = \\frac{\\text{actifs totaux}}{\\text{fonds propres}}',
    commentaire: 'LA variable commune à toutes les catastrophes du module : un multiple sans unité — 25 signifie 25 € d\'actifs pour 1 € de fonds propres, le reste est de la dette. Les repères historiques à réciter : levier 10 pour le spéculateur de 1929 sur call loans (marge de 10 %), ≈ 27 pour LTCM début 1998 (125 Md$ d\'actifs sur 4,7 Md$ de capital), ~31 pour Lehman en 2007, 1 pour l\'investisseur au comptant — qui ne fait jamais faillite par les prix. La première question à poser devant toute bulle : qui porte du levier, et combien (ch. 1) ?',
    commentaireEn: 'THE variable common to every catastrophe in the module: a unitless multiple — 25 means €25 of assets per €1 of equity, the rest is debt. The historical benchmarks to recite: leverage 10 for the 1929 speculator on call loans (10% margin), ≈ 27 for LTCM in early 1998 ($125bn of assets on $4.7bn of capital), ~31 for Lehman in 2007, 1 for the unlevered cash investor — who never goes bankrupt through prices. The first question to ask about any bubble: who carries leverage, and how much (ch. 1)?',
  },
  {
    id: 'm11-f-02',
    moduleId: M11,
    nom: 'La formule du malheur : impact du levier sur les fonds propres',
    nomEn: 'The misfortune formula: leverage impact on equity',
    latex: '\\Delta FP\\,\\% = \\lambda \\times \\Delta \\text{actifs}\\,\\%',
    commentaire: 'La dette ne partage pas les pertes : les fonds propres absorbent TOUTE la variation d\'actifs, multipliée par le levier. Au levier 25, −4 % d\'actifs font −100 % de fonds propres ; au levier 10 (1929), −10 % suffisent. Et elle marche dans les deux sens — c\'est pour cela qu\'on se levier : au levier 25, +2 % d\'actifs font +50 % de fonds propres. Voilà l\'asymétrie comportementale de toutes les bulles : la phase de boom fabrique des « génies », la panique révèle qu\'ils n\'étaient que leviérés (ch. 1, 2, 3).',
    commentaireEn: 'Debt does not share losses: equity absorbs the ENTIRE asset move, multiplied by leverage. At leverage 25, −4% on assets makes −100% of equity; at leverage 10 (1929), −10% is enough. And it works both ways — that is why people lever up: at leverage 25, +2% on assets makes +50% of equity. That is the behavioural asymmetry of every bubble: the boom phase manufactures "geniuses", the panic reveals they were merely levered (ch. 1, 2, 3).',
  },
  {
    id: 'm11-f-03',
    moduleId: M11,
    nom: 'La distance à la mort : variation d\'actifs fatale',
    nomEn: 'The distance to death: fatal asset move',
    latex: '\\Delta \\text{actifs}_{\\text{fatal}} = -\\frac{100}{\\lambda}',
    commentaire: 'Le choc qui efface exactement les fonds propres — la carte d\'identité de la fragilité d\'un bilan. Levier 10 (le boursicoteur de 1929) : mort à −10 %, une mauvaise semaine — et le lundi noir (−12,8 %) puis le mardi noir (−11,7 %) dépassaient CHACUN ce seuil. Levier 27 (LTCM) : mort à −3,7 %, une mauvaise journée. Levier 31 (Lehman) : −3,2 %, sur des actifs dont personne ne connaissait plus le prix. Levier 1 : il faut que tout tombe à zéro — le comptant ne meurt que d\'ennui (ch. 1, 2, 3, 5).',
    commentaireEn: 'The shock that exactly wipes out equity — the identity card of a balance sheet\'s fragility. Leverage 10 (the 1929 retail speculator): dead at −10%, a bad week — and Black Monday (−12.8%) then Black Tuesday (−11.7%) EACH exceeded that threshold. Leverage 27 (LTCM): dead at −3.7%, a bad day. Leverage 31 (Lehman): −3.2%, on assets nobody could price anymore. Leverage 1: everything must go to zero — cash only dies of boredom (ch. 1, 2, 3, 5).',
  },
  {
    id: 'm11-f-04',
    moduleId: M11,
    nom: 'Drawdown pic-à-creux',
    nomEn: 'Peak-to-trough drawdown',
    latex: '\\text{drawdown} = \\left(\\frac{\\text{creux}}{\\text{pic}} - 1\\right) \\times 100',
    commentaire: 'La carte d\'identité chiffrée de chaque krach, en % signé (négatif). Le musée du module : DJIA 381,17 → 41,22 (1929-1932) = −89,19 % ; Dow 2 722,42 → 1 738,74 (août-octobre 1987) = −36,1 %, dont −22,6 % en une seule séance ; Nasdaq 5 048,62 → 1 114,11 (2000-2002) = −77,9 % en 31 mois ; S&P 500 1 565,15 → 676,53 (2007-2009) = −56,8 % ; COVID 3 386,15 → 2 237,40 = −33,9 % en 23 séances. Le piège de 1987 : ne pas confondre le pire JOUR (−22,6 %) et le drawdown pic-à-creux (−36,1 %) (ch. 1-7).',
    commentaireEn: 'Each crash\'s numbered identity card, in signed % (negative). The module\'s museum: DJIA 381.17 → 41.22 (1929-1932) = −89.19%; Dow 2,722.42 → 1,738.74 (August-October 1987) = −36.1%, including −22.6% in a single session; Nasdaq 5,048.62 → 1,114.11 (2000-2002) = −77.9% over 31 months; S&P 500 1,565.15 → 676.53 (2007-2009) = −56.8%; COVID 3,386.15 → 2,237.40 = −33.9% in 23 sessions. The 1987 trap: never confuse the worst DAY (−22.6%) with the peak-to-trough drawdown (−36.1%) (ch. 1-7).',
  },
  {
    id: 'm11-f-05',
    moduleId: M11,
    nom: 'Gain requis pour récupérer une perte',
    nomEn: 'Required gain to recover a loss',
    latex: '\\text{gain requis} = \\frac{100}{100 - p} - 1 \\quad (p\\ \\text{en magnitude positive})',
    commentaire: 'LE piège d\'arithmétique le plus rentable en entretien : les pertes sont asymétriques, la fonction est convexe et explose. Après −50 %, il faut +100 % (doubler !) ; après le −89 % du Dow de 1932, +809 % ; après le −78 % du Nasdaq de 2002, +354,5 % ; et le lundi noir (−22,6 %) n\'exige « que » +29,2 % — d\'où la récupération en deux ans quand le crédit tient. La symétrie naïve (« −50 % se répare avec +50 % ») laisse à −25 % du compte. Devant tout drawdown : calculer le gain requis AVANT de parler de rebond (ch. 1).',
    commentaireEn: 'THE most profitable arithmetic trap in interviews: losses are asymmetric, the function is convex and explodes. After −50%, you need +100% (double!); after the Dow\'s −89% of 1932, +809%; after the Nasdaq\'s −78% of 2002, +354.5%; and Black Monday (−22.6%) requires "only" +29.2% — hence the two-year recovery when credit holds. Naive symmetry ("−50% is repaired by +50%") leaves you at −25% of the account. Facing any drawdown: compute the required gain BEFORE talking about a rebound (ch. 1).',
  },
  {
    id: 'm11-f-06',
    moduleId: M11,
    nom: 'Années de récupération à croissance composée',
    nomEn: 'Recovery years at compound growth',
    latex: 'n = \\frac{\\ln\\left(\\frac{1}{1 - p}\\right)}{\\ln(1 + g)}',
    commentaire: 'Le corollaire temporel de l\'asymétrie des pertes : combien d\'années de croissance composée à g %/an pour effacer une perte p (en magnitude positive). Récupérer −50 % à 7 %/an : 10,2 ans ; récupérer −89 % : 32,6 ans — l\'ordre de grandeur des 25 ans du Dow pour revoir 381 points (novembre 1954, la déflation et les dividendes ayant un peu adouci le prix seul). Le Nikkei de 1989 en a pris 34 ; le S&P de 2020, cinq mois — la croissance retenue est la variable héroïque, et le pompier décide du reste (ch. 1, 2, 7).',
    commentaireEn: 'The temporal corollary of loss asymmetry: how many years of compound growth at g%/year to erase a loss p (positive magnitude). Recovering −50% at 7%/year: 10.2 years; recovering −89%: 32.6 years — the order of magnitude of the Dow\'s 25 years to see 381 again (November 1954, deflation and dividends having slightly softened the price-only story). The 1989 Nikkei took 34; the 2020 S&P, five months — the assumed growth is the heroic variable, and the firefighter decides the rest (ch. 1, 2, 7).',
  },
  {
    id: 'm11-f-07',
    moduleId: M11,
    nom: 'Financement obtenu en repo',
    nomEn: 'Funding raised through repo',
    latex: '\\text{financement} = V \\times (1 - h)',
    commentaire: 'La valeur des titres fois un moins le haircut : le prêteur garde h comme coussin — 100 de titres à 2 % de haircut lèvent 98. Le run de 2008 fut une ruée SUR CE NOMBRE (Gorton) : quand le haircut sur le même portefeuille passe de 2 % à 25 %, le financement fond de 98 à 75 — il faut trouver 23 le jour même, car le repo se renouvelle au jour le jour. Comment ? En vendant — et la spirale s\'enclenche. La ruée de 2008 n\'a pas eu de files d\'attente : elle s\'est jouée dans des chiffres que seuls les trésoriers voyaient (ch. 5).',
    commentaireEn: 'The securities\' value times one minus the haircut: the lender keeps h as a cushion — 100 of securities at a 2% haircut raises 98. The 2008 run was a run ON THIS NUMBER (Gorton): when the haircut on the same portfolio goes from 2% to 25%, funding melts from 98 to 75 — 23 must be found the same day, because repo rolls overnight. How? By selling — and the spiral engages. The 2008 run had no queues: it played out in numbers only treasurers saw (ch. 5).',
  },
  {
    id: 'm11-f-08',
    moduleId: M11,
    nom: 'Levier maximal permis par un haircut',
    nomEn: 'Maximum leverage allowed by a haircut',
    latex: '\\lambda_{\\max} = \\frac{100}{h}',
    commentaire: 'Avec 1 de capital et un haircut h, chaque tour de repo re-nantit le reste : à la limite, les actifs valent capital/h. Haircut 2 % ⇒ levier 50 ; 10 % ⇒ 10 ; 50 % ⇒ 2. C\'est la mécanique qui a permis à LTCM — si courtisé qu\'il négociait des haircuts quasi nuls — de porter plus de 125 Md$ d\'actifs sur moins de 5 Md$ de capital : le prestige des Nobel n\'était pas une image, c\'était une condition de financement. Et c\'est le levier INVISIBLE dans les ratios réglementaires de 2006 : le haircut est une politique de levier qui ne dit pas son nom (ch. 3, 5).',
    commentaireEn: 'With 1 of capital and a haircut h, each repo round re-pledges the remainder: at the limit, assets equal capital/h. Haircut 2% ⇒ leverage 50; 10% ⇒ 10; 50% ⇒ 2. This is the mechanism that let LTCM — so courted it negotiated near-zero haircuts — carry over $125bn of assets on less than $5bn of capital: the Nobel prestige was not an image, it was a funding condition. And it is the leverage INVISIBLE in 2006\'s regulatory ratios: the haircut is a leverage policy that does not speak its name (ch. 3, 5).',
  },
  {
    id: 'm11-f-09',
    moduleId: M11,
    nom: 'Vente forcée sous décote',
    nomEn: 'Forced sale under a liquidation discount',
    latex: '\\text{montant à vendre} = \\frac{\\text{besoin de cash}}{1 - d}',
    commentaire: 'Pour lever un montant de cash sous une décote de liquidation d, il faut vendre PLUS que le besoin : lever 23 sous 5 % de décote oblige à vendre 24,2. C\'est le moteur de la spirale : vendre déprime les prix, la décote s\'élargit, il faut vendre plus — 1987 (assurance de portefeuille), 2008 (haircuts et CDO), 2022 (gilts et LDI). Corollaire de pompier : l\'acheteur en dernier ressort n\'a pas besoin de tout acheter, il lui suffit d\'écraser d pour rouvrir la sortie — treize jours ouvrés et ~19 Md£ ont suffi à la BoE (ch. 1, 5, 7).',
    commentaireEn: 'To raise an amount of cash under a liquidation discount d, you must sell MORE than the need: raising 23 under a 5% discount forces you to sell 24.2. That is the spiral\'s engine: selling depresses prices, the discount widens, you must sell more — 1987 (portfolio insurance), 2008 (haircuts and CDOs), 2022 (gilts and LDI). Firefighter corollary: the buyer of last resort does not need to buy everything, crushing d is enough to reopen the exit — thirteen business days and ~£19bn sufficed for the BoE (ch. 1, 5, 7).',
  },
  {
    id: 'm11-f-10',
    moduleId: M11,
    nom: 'Taille de la vente pour désendetter — et la zone de mort',
    nomEn: 'Sale size to deleverage — and the death zone',
    latex: 'S = \\frac{A - \\lambda E}{1 - \\lambda d}, \\qquad \\text{zone de mort : } \\lambda d \\ge 1',
    commentaire: 'Combien vendre pour ramener le levier à la cible λ, quand chaque vente coûte S·d de fonds propres (la décote est une perte sèche) ? Le numérateur est l\'excès d\'actifs, mais le dénominateur amplifie : au levier cible 25 et 2 % de décote, 1 − λd = 0,5 — il faut vendre le DOUBLE de l\'excès apparent. Et si λd ≥ 1, le dénominateur s\'annule ou change de signe : chaque euro vendu détruit plus de fonds propres qu\'il ne réduit le levier — VENDRE NE DÉSENDETTE PLUS. Il ne reste que le sauvetage ou la faillite : LTCM en septembre 1998, les fonds LDI en septembre 2022 (ch. 1).',
    commentaireEn: 'How much to sell to bring leverage back to the target λ, when each sale costs S·d of equity (the discount is a dead loss)? The numerator is the asset excess, but the denominator amplifies: at target leverage 25 and a 2% discount, 1 − λd = 0.5 — you must sell DOUBLE the apparent excess. And if λd ≥ 1, the denominator vanishes or flips sign: every euro sold destroys more equity than it reduces leverage — SELLING NO LONGER DELEVERAGES. Only rescue or bankruptcy remain: LTCM in September 1998, the LDI funds in September 2022 (ch. 1).',
  },
  {
    id: 'm11-f-11',
    moduleId: M11,
    nom: 'Taux de couverture des dépôts',
    nomEn: 'Deposit coverage ratio',
    latex: '\\text{couverture} = \\frac{\\text{actifs liquides}}{\\text{dépôts exigibles}} \\times 100',
    commentaire: 'La part des dépôts qu\'une banque peut rendre AUJOURD\'HUI : la solvabilité ne protège pas d\'un run. Une banque à 25 % de couverture meurt si plus d\'un quart des dépôts part — et le 9 mars 2023, SVB a vu partir 42 Md$ en UNE journée, environ un quart de ses dépôts, coordonnés par Twitter et les group chats : aucune banque au monde ne couvre cela. Le détail qui tue : plus de 90 % des dépôts de SVB dépassaient le plafond FDIC de 250 k$ — les non-assurés courent les PREMIERS, la garantie n\'ancre que ce qu\'elle couvre (ch. 2, 7).',
    commentaireEn: 'The share of deposits a bank can return TODAY: solvency does not protect against a run. A bank with 25% coverage dies if more than a quarter of deposits leaves — and on 9 March 2023, SVB saw $42bn leave in ONE day, about a quarter of its deposits, coordinated over Twitter and VC group chats: no bank in the world covers that. The killer detail: over 90% of SVB\'s deposits exceeded the $250k FDIC cap — the uninsured run FIRST, the guarantee only anchors what it covers (ch. 2, 7).',
  },
  {
    id: 'm11-f-12',
    moduleId: M11,
    nom: 'Charge d\'intérêts d\'un État',
    nomEn: 'A sovereign\'s interest burden',
    latex: '\\text{charge (\\% du PIB)} = \\frac{\\text{dette/PIB} \\times \\text{taux moyen}}{100}',
    commentaire: 'L\'arithmétique de la doom loop souveraine : à 180 % de dette/PIB (la Grèce de 2011), chaque point de taux coûte 1,8 point de PIB — à 5 % de taux moyen, le service de la dette absorbe 9 % du PIB avant le premier euro d\'école ou d\'hôpital, et le marché en demandait sept fois plus. D\'où la prophétie auto-réalisatrice : taux ↑ ⇒ charge ↑ ⇒ solvabilité ↓ ⇒ taux ↑. Le contrepoint : la même dette à 1,5 % ne coûte que 2,7 % du PIB — une dette n\'est jamais soutenable dans l\'absolu, mais À UN TAUX DONNÉ. C\'est pourquoi l\'OMT, en écrasant le taux, a changé la solvabilité sans toucher au stock (ch. 6).',
    commentaireEn: 'The sovereign doom loop\'s arithmetic: at 180% debt/GDP (Greece 2011), each point of rate costs 1.8 points of GDP — at a 5% average rate, debt service absorbs 9% of GDP before the first euro of schools or hospitals, and the market demanded seven times more. Hence the self-fulfilling prophecy: rates ↑ ⇒ burden ↑ ⇒ solvency ↓ ⇒ rates ↑. The counterpoint: the same debt at 1.5% costs only 2.7% of GDP — a debt is never sustainable in the absolute, but AT A GIVEN RATE. That is why the OMT, by crushing the rate, changed solvency itself without touching the stock (ch. 6).',
  },
  {
    id: 'm11-f-13',
    moduleId: M11,
    nom: 'Spread souverain en points de base',
    nomEn: 'Sovereign spread in basis points',
    latex: '\\text{spread (pb)} = (\\text{taux pays} - \\text{taux de référence}) \\times 100',
    commentaire: 'Le thermomètre de la crise de l\'euro, coté contre le Bund allemand (100 pb = 1 %). Les ordres de grandeur à réciter : l\'OAT française vit entre 30 et 60 pb ; la Grèce franchit 1 000 pb au printemps 2010 ; l\'Italie dépasse 500 pb à l\'automne 2011 — et à 120 % de dette/PIB, ce n\'est pas une nuance, c\'est un changement de régime. Au paroxysme, mars 2012 : 10 ans grec au-delà de 35 % contre un Bund à 1,5 %, soit (35 − 1,5) × 100 = 3 350 pb — à ces niveaux, le taux ne rémunère plus un risque, il EST le défaut anticipé, actualisé dans le prix (ch. 6).',
    commentaireEn: 'The euro crisis\'s thermometer, quoted against the German Bund (100 bps = 1%). The orders of magnitude to recite: the French OAT lives between 30 and 60 bps; Greece crosses 1,000 bps in spring 2010; Italy exceeds 500 bps in autumn 2011 — and at 120% debt/GDP, that is not a nuance, it is a regime change. At the paroxysm, March 2012: the Greek 10-year beyond 35% against a 1.5% Bund, i.e. (35 − 1.5) × 100 = 3,350 bps — at those levels, the rate no longer prices a risk, it IS the anticipated default, discounted into the price (ch. 6).',
  },
];
