import type { Formule } from '../../../engine/types';

const M7 = '07-derives-fermes';

export const formules: Formule[] = [
  {
    id: 'm7-f-01',
    moduleId: M7,
    nom: 'Forward d\'un indice par le coût de portage',
    nomEn: 'Index forward by cost of carry',
    latex: 'F = S \\times \\left(1 + \\frac{r - q}{100}\\,T\\right)',
    commentaire: 'Le terme vaut le spot plus le portage net, en linéaire sur ces horizons : le financement r renchérit, le revenu q (dividendes, taux étranger, convenience yield) réduit. 5 000 × (1 + (4 − 2)/100 × 1) = 5 100 — les 100 points ne sont pas une prévision, c\'est le loyer de l\'argent moins celui de l\'actif (ch. 3).',
    commentaireEn: 'The forward equals spot plus net carry, linear on these horizons: funding r pushes it up, the income q (dividends, foreign rate, convenience yield) pulls it down. 5,000 × (1 + (4 − 2)/100 × 1) = 5,100 — the 100 points are not a forecast, they are the rent of money minus the rent of the asset (ch. 3).',
  },
  {
    id: 'm7-f-02',
    moduleId: M7,
    nom: 'P&L d\'une position futures',
    nomEn: 'Futures position P&L',
    latex: '\\text{P\\&L} = (P_{\\text{sortie}} - P_{\\text{entrée}}) \\times m \\times N \\times \\text{sens}',
    commentaire: 'm le multiplicateur, N le nombre de contrats, sens = +1 long, −1 short. (4 900 − 5 000) × 10 × 2 = −2 000 € pour le long — et exactement +2 000 € pour le short : tout dérivé ferme est un jeu à somme nulle (ch. 2).',
    commentaireEn: 'm the multiplier, N the number of contracts, sign = +1 long, −1 short. (4,900 − 5,000) × 10 × 2 = −€2,000 for the long — and exactly +€2,000 for the short: every forward commitment is a zero-sum game (ch. 2).',
  },
  {
    id: 'm7-f-03',
    moduleId: M7,
    nom: 'Marge de variation (flux quotidien)',
    nomEn: 'Variation margin (daily flow)',
    latex: '\\text{MV} = (P_{\\text{jour}} - P_{\\text{veille}}) \\times m \\times N \\times \\text{sens}',
    commentaire: 'Le flux signé du mark-to-market, réglé en cash chaque soir au cours de compensation — négatif, le compte est débité. Jour 2 du tableau canonique : (4 960 − 5 000) × 10 × 2 = −800 € (ch. 2).',
    commentaireEn: 'The signed mark-to-market flow, settled in cash each evening at the settlement price — negative, the account is debited. Day 2 of the canonical table: (4,960 − 5,000) × 10 × 2 = −€800 (ch. 2).',
  },
  {
    id: 'm7-f-04',
    moduleId: M7,
    nom: 'Appel de marge (convention futures US)',
    nomEn: 'Margin call (US futures convention)',
    latex: '\\text{versement} = \\begin{cases} M_{\\text{initiale}} - \\text{solde} & \\text{si solde} < M_{\\text{maintenance}} \\\\ 0 & \\text{sinon} \\end{cases}',
    commentaire: 'La maintenance est le déclencheur (solde strictement sous le seuil), l\'initiale est la cible : à 8 400 € de solde pour 9 000 € de maintenance et 12 000 € d\'initiale, versement = 12 000 − 8 400 = 3 600 € — pas 600 € (ch. 2).',
    commentaireEn: 'Maintenance is the trigger (balance strictly below the threshold), initial margin is the target: with a balance of 8,400 against 9,000 maintenance and 12,000 initial, the payment is 12,000 − 8,400 = €3,600 — not €600 (ch. 2).',
  },
  {
    id: 'm7-f-05',
    moduleId: M7,
    nom: 'Effet de levier de la marge',
    nomEn: 'Margin leverage',
    latex: '\\Delta_{\\text{mise}} = \\frac{\\Delta_{\\text{sous-jacent}}}{\\text{marge}}',
    commentaire: 'Marge de 10 % ⇒ levier ×10 : +2 % de sous-jacent fait +20 % sur la mise — et −12 % fait −120 % : le dépôt est effacé et il faut remettre au pot. On est engagé sur le notionnel entier, pas sur la mise (ch. 1).',
    commentaireEn: 'A 10% margin ⇒ ×10 leverage: +2% on the underlying makes +20% on the stake — and −12% makes −120%: the deposit is wiped out and fresh cash is owed. You are committed on the full notional, not on your stake (ch. 1).',
  },
  {
    id: 'm7-f-06',
    moduleId: M7,
    nom: 'Taux forward implicite (linéaire)',
    nomEn: 'Implied forward rate (linear)',
    latex: 'f = \\frac{1}{t_2 - t_1}\\left(\\frac{1 + \\frac{r_2}{100}\\,t_2}{1 + \\frac{r_1}{100}\\,t_1} - 1\\right)',
    commentaire: 'Deux chemins sans risque vers t₂ doivent rapporter pareil : 3 % à 6 mois et 3,5 % à 1 an donnent f = (1,035/1,015 − 1)/0,5 = 3,9409 %. Convention linéaire du monétaire (≤ 1 an) : une courbe plate donne un forward légèrement SOUS le taux plat — en composé (module 4), exactement le taux plat (ch. 4).',
    commentaireEn: 'Two riskless paths to t₂ must pay the same: 3% at 6 months and 3.5% at 1 year give f = (1.035/1.015 − 1)/0.5 = 3.9409%. Money-market linear convention (≤ 1 year): a flat curve yields a forward slightly BELOW the flat rate — compounded (module 4), exactly the flat rate (ch. 4).',
  },
  {
    id: 'm7-f-07',
    moduleId: M7,
    nom: 'Règlement différentiel d\'un FRA',
    nomEn: 'FRA cash settlement',
    latex: '\\text{règlement} = \\frac{N \\times \\frac{r_{\\text{constaté}} - r_{\\text{FRA}}}{100} \\times \\delta}{1 + \\frac{r_{\\text{constaté}}}{100}\\,\\delta}',
    commentaire: 'Reçu par le long (payeur du fixe) si les taux ont monté, et actualisé car versé au fixing, en DÉBUT de période d\'intérêt : 10 M€ × 1 % × 0,5/1,02 = 49 019,61 € — replacés 6 mois à 4 %, ils redonnent pile les 50 000 € de surcoût (ch. 4).',
    commentaireEn: 'Received by the long (fixed-rate payer) if rates have risen, and discounted because paid at fixing, at the START of the interest period: €10m × 1% × 0.5/1.02 = €49,019.61 — reinvested 6 months at 4%, it grows back to exactly the €50,000 extra cost (ch. 4).',
  },
  {
    id: 'm7-f-08',
    moduleId: M7,
    nom: 'Facteur d\'actualisation zéro-coupon',
    nomEn: 'Zero-coupon discount factor',
    latex: 'df = \\frac{1}{\\left(1 + \\frac{z}{100}\\right)^{T}}',
    commentaire: 'Composition annuelle au-delà de l\'an, cohérente avec le module 4 : 1/1,04² = 0,924556 pour 4 % à 2 ans. C\'est la brique de toute la valorisation des swaps — la courbe zéro convertie en prix du temps (ch. 5).',
    commentaireEn: 'Annual compounding beyond one year, consistent with module 4: 1/1.04² = 0.924556 for 4% at 2 years. The building block of all swap valuation — the zero curve converted into the price of time (ch. 5).',
  },
  {
    id: 'm7-f-09',
    moduleId: M7,
    nom: 'Taux de swap paritaire',
    nomEn: 'Par swap rate',
    latex: 'C^* = \\frac{1 - df_n}{\\sum_{i=1}^{n} df_i}',
    commentaire: 'Le coupon qui amortit exactement la décote du notionnel actualisé : un swap signé à ce taux vaut zéro. Courbe 3/3,5/4 % : 0,111004/2,793381 = 3,9738 % — une moyenne pondérée de la courbe ; courbe plate à r ⇒ C* = r exactement (ch. 5).',
    commentaireEn: 'The coupon that exactly amortises the discounted notional\'s haircut: a swap signed at this rate is worth zero. Curve 3/3.5/4%: 0.111004/2.793381 = 3.9738% — a weighted average of the curve; flat curve at r ⇒ C* = r exactly (ch. 5).',
  },
  {
    id: 'm7-f-10',
    moduleId: M7,
    nom: 'Valeur de la jambe fixe',
    nomEn: 'Fixed leg value',
    latex: 'V_{\\text{fixe}} = N \\times \\frac{C}{100} \\times \\sum_{i=1}^{n} df_i + N \\times df_n',
    commentaire: 'Le prix d\'une obligation de coupon C sur la courbe zéro : coupons actualisés plus notionnel actualisé. Fixe 5 %, courbe plate 4 %, 3 ans, 100 M€ : 5 × 2,775091 + 88,8996 = 102,7751 M€ ; coupon au taux d\'une courbe plate ⇒ le pair exactement (ch. 5).',
    commentaireEn: 'The price of a bond with coupon C on the zero curve: discounted coupons plus discounted notional. 5% fixed, flat 4% curve, 3 years, €100m: 5 × 2.775091 + 88.8996 = €102.7751m; a coupon at the flat-curve rate ⇒ exactly par (ch. 5).',
  },
  {
    id: 'm7-f-11',
    moduleId: M7,
    nom: 'Valeur du swap pour le payeur fixe',
    nomEn: 'Swap value for the fixed-rate payer',
    latex: 'V_{\\text{payeur}} = N - V_{\\text{fixe}}',
    commentaire: 'La jambe variable vaut le pair juste après fixing : tout tient dans la jambe fixe. Payer 5 % quand le marché ne demande que 4 % : 100 − 102,7751 = −2,7751 M€. Et le réflexe : les taux MONTENT ⇒ le payeur fixe GAGNE — son fixe contractuel est devenu bon marché (ch. 5).',
    commentaireEn: 'The floating leg is worth par right after fixing: everything sits in the fixed leg. Paying 5% when the market asks only 4%: 100 − 102.7751 = −€2.7751m. And the reflex: rates RISE ⇒ the fixed-rate payer WINS — his contractual fixed rate has become cheap (ch. 5).',
  },
  {
    id: 'm7-f-12',
    moduleId: M7,
    nom: 'Nombre de contrats de couverture',
    nomEn: 'Number of hedge contracts',
    latex: 'N = \\frac{\\text{exposition}}{F \\times m}',
    commentaire: 'Arrondi au contrat entier (bêta = 1) : 25 M€/(5 000 × 10 €) = 500 contrats, à la VENTE pour neutraliser un portefeuille. Parfaite seulement si le portefeuille suit l\'indice et si l\'échéance colle — sinon, risque de base : 1 % d\'écart sur 25 M€ = 250 000 € (ch. 7).',
    commentaireEn: 'Rounded to a whole contract (beta = 1): €25m/(5,000 × €10) = 500 contracts, SOLD to neutralise a portfolio. Perfect only if the portfolio tracks the index and the maturity matches — otherwise basis risk: a 1% gap on €25m is €250,000 (ch. 7).',
  },
  {
    id: 'm7-f-13',
    moduleId: M7,
    nom: 'Prix d\'un futures de taux court',
    nomEn: 'Short-term interest rate futures price',
    latex: '\\text{prix} = 100 - \\text{taux}',
    commentaire: 'Taux à 3 % ⇒ le contrat cote 97,00 ; le prix BAISSE quand les taux MONTENT — le réflexe obligataire recréé. Conséquence : l\'emprunteur qui se couvre contre la hausse VEND les contrats, alors qu\'il était long du FRA (ch. 4).',
    commentaireEn: 'A 3% rate ⇒ the contract quotes 97.00; the price FALLS when rates RISE — the bond reflex recreated. Consequence: the borrower hedging against rising rates SELLS the contracts, whereas he was long the FRA (ch. 4).',
  },
  {
    id: 'm7-f-14',
    moduleId: M7,
    nom: 'Valeur du point de base (et du tick)',
    nomEn: 'Value of a basis point (and of the tick)',
    latex: '\\text{valeur du pb} = N \\times 10^{-4} \\times \\delta',
    commentaire: 'Sur l\'Euribor 3 mois (notionnel 1 M€, δ = 0,25) : 1 000 000 × 0,0001 × 0,25 = 25 € par point de base — et le tick de 0,005, échelon minimal de cotation, en vaut 12,50. Une vendeuse de 100 contrats gagne 2 500 € par pb de hausse des taux (ch. 4).',
    commentaireEn: 'On the 3-month Euribor (€1m notional, δ = 0.25): 1,000,000 × 0.0001 × 0.25 = €25 per basis point — and the 0.005 tick, the minimum price increment, is worth 12.50. A seller of 100 contracts earns €2,500 per bp of rate rise (ch. 4).',
  },
  {
    id: 'm7-f-15',
    moduleId: M7,
    nom: 'Somme des marges de variation = P&L',
    nomEn: 'Sum of variation margins = P&L',
    latex: '\\sum_j \\text{MV}_j = (P_{\\text{final}} - P_{\\text{entrée}}) \\times m \\times N \\times \\text{sens}',
    commentaire: 'Le télescopage des flux quotidiens : −800 − 1 600 − 1 200 + 1 600 = −2 000 € = (4 900 − 5 000) × 10 × 2. Le mark-to-market ne change pas le P&L, il en change le CALENDRIER — et la trésorerie exigée en chemin peut tuer avant l\'échéance (ch. 2).',
    commentaireEn: 'The daily flows telescope: −800 − 1,600 − 1,200 + 1,600 = −€2,000 = (4,900 − 5,000) × 10 × 2. Marking to market does not change the P&L, it changes its TIMING — and the cash demanded along the way can kill before maturity (ch. 2).',
  },
  {
    id: 'm7-f-16',
    moduleId: M7,
    nom: 'Dette fixe synthétique',
    nomEn: 'Synthetic fixed-rate debt',
    latex: '\\text{dette variable} + \\text{swap payeur fixe} = \\text{dette fixe}',
    commentaire: 'L\'Euribor payé sur le crédit est remboursé par l\'Euribor reçu du swap : il ne reste que le fixe (plus la marge bancaire du crédit). Le coût se fige sans renégocier la dette — l\'usage corporate canonique du swap (ch. 5).',
    commentaireEn: 'The Euribor paid on the loan is refunded by the Euribor received from the swap: only the fixed rate remains (plus the loan\'s bank margin). The cost is locked without renegotiating the debt — the canonical corporate use of the swap (ch. 5).',
  },
];
