import type { Formule } from '../../../engine/types';

const M12 = '12-gestion-actifs-risques';

export const formules: Formule[] = [
  {
    id: 'm12-f-01',
    moduleId: M12,
    nom: 'Rendement d\'un portefeuille : la moyenne pondérée',
    nomEn: 'Portfolio return: the weighted average',
    latex: 'r_p = w_1\\,r_1 + w_2\\,r_2',
    commentaire: 'La moitié facile de Markowitz : le rendement espéré d\'un portefeuille est la moyenne pondérée des rendements espérés de ses composants — linéaire, sans surprise, sans magie. L\'ancre du métier : le 60/40, 60 % d\'actions à 8 % et 40 % d\'obligations à 3 %, rend 0,6 × 8 + 0,4 × 3 = 6 %. Diversifier ne coûte donc aucun rendement espéré. Tout le module tient dans le contraste avec la formule suivante : le rendement se moyenne, le risque, lui, ne se moyenne pas (ch. 1).',
    commentaireEn: 'The easy half of Markowitz: a portfolio\'s expected return is the weighted average of its components\' expected returns — linear, no surprise, no magic. The trade\'s anchor: the 60/40, 60% equities at 8% and 40% bonds at 3%, returns 0.6 × 8 + 0.4 × 3 = 6%. Diversifying therefore costs no expected return. The whole module sits in the contrast with the next formula: return averages, risk does not (ch. 1).',
  },
  {
    id: 'm12-f-02',
    moduleId: M12,
    nom: 'Volatilité d\'un portefeuille de deux actifs : LA formule',
    nomEn: 'Two-asset portfolio volatility: THE formula',
    latex: '\\sigma_p = \\sqrt{w_1^2\\sigma_1^2 + w_2^2\\sigma_2^2 + 2\\,w_1 w_2\\,\\rho\\,\\sigma_1\\sigma_2}',
    commentaire: 'LA formule du module, à dérouler les yeux fermés : deux termes propres et un terme croisé — le seul où vit la corrélation ρ, donc le seul qui contient toute l\'histoire. L\'ancre : le 60/40 à volatilités 20/10 et ρ = 0,3 donne √(144 + 16 + 28,8) = 13,740451 % — MOINS que la moyenne pondérée 16 % : plus de deux points de risque ont disparu sans sacrifier un centime de rendement, le seul repas gratuit de la finance. À ρ = −1, le même portefeuille tombe à 8 % — la couverture parfaite ; à ρ = 0, deux actifs identiques en 50/50 divisent la volatilité par √2 (20 % devient 14,142136 %). Le défaut de la reine, hérité du m11 : dans les crises, les corrélations montent vers 1 et le repas gratuit s\'évapore au pire moment (ch. 1).',
    commentaireEn: 'THE formula of the module, to unroll with your eyes closed: two own terms and one cross term — the only one where the correlation ρ lives, hence the only one carrying the whole story. The anchor: the 60/40 at 20/10 volatilities and ρ = 0.3 gives √(144 + 16 + 28.8) = 13.740451% — LESS than the 16% weighted average: over two points of risk vanished without sacrificing a cent of return, finance\'s only free lunch. At ρ = −1, the same portfolio drops to 8% — the perfect hedge; at ρ = 0, two identical assets in 50/50 divide volatility by √2 (20% becomes 14.142136%). The queen\'s flaw, inherited from m11: in crises, correlations rise towards 1 and the free lunch evaporates at the worst moment (ch. 1).',
  },
  {
    id: 'm12-f-03',
    moduleId: M12,
    nom: 'Le cas ρ = 1 : la moyenne pondérée, plus aucun repas',
    nomEn: 'The ρ = 1 case: the weighted average, no lunch left',
    latex: '\\rho = 1 \\;\\Rightarrow\\; \\sigma_p = w_1\\sigma_1 + w_2\\sigma_2',
    commentaire: 'Le cas limite à réciter : à corrélation parfaite, le terme croisé complète exactement le carré et la racine se referme en moyenne pondérée — le 60/40 à 20/10 rend 16 %, pas un point de moins. Deux actifs parfaitement corrélés sont UN SEUL actif déguisé : les empiler ne diversifie rien. Le corollaire d\'oral : ce n\'est pas le nombre de lignes qui diversifie, c\'est la corrélation entre elles — mille actifs corrélés à 1 se comportent comme un seul. Et la loi des grands nombres ne fait fondre que le risque SPÉCIFIQUE : le systématique — le marché entier qui baisse — reste, quel que soit le nombre de lignes (ch. 1).',
    commentaireEn: 'The limit case to recite: at perfect correlation, the cross term completes the square exactly and the root closes back into the weighted average — the 60/40 at 20/10 gives 16%, not a point less. Two perfectly correlated assets are ONE asset in disguise: stacking them diversifies nothing. The oral corollary: it is not the number of lines that diversifies, it is the correlation between them — a thousand assets correlated at 1 behave as one. And the law of large numbers only melts SPECIFIC risk: systematic risk — the whole market falling — remains, whatever the number of lines (ch. 1).',
  },
  {
    id: 'm12-f-04',
    moduleId: M12,
    nom: 'Le bêta : corrélation × volatilité relative',
    nomEn: 'Beta: correlation × relative volatility',
    latex: '\\beta = \\rho \\times \\frac{\\sigma_{\\text{actif}}}{\\sigma_{\\text{marché}}}',
    commentaire: 'La mesure de la contribution d\'un actif au risque SYSTÉMATIQUE — la seule que le CAPM rémunère. L\'ancre : un actif à 25 % de volatilité, corrélé à 0,8 avec un marché à 15 %, a un bêta de 0,8 × 25/15 = 1,333333 — il amplifie les mouvements du marché d\'un tiers. Lisez bien les deux ingrédients : le même actif à 25 % de volatilité mais décorrélé (ρ ≈ 0) a un bêta minuscule — son risque, aussi énorme soit-il, est diversifiable, donc gratuit aux yeux du marché. LE piège d\'oral : le bêta n\'est pas la volatilité — on n\'est pas payé pour le risque que l\'on prend, mais pour celui que l\'on ne peut pas éliminer. Usage desk : un book de 120 M à bêta 1,2 s\'expose pour 144 M équivalent-indice — c\'est ce montant que couvre la vente de futures du m7 (ch. 2).',
    commentaireEn: 'The measure of an asset\'s contribution to SYSTEMATIC risk — the only one the CAPM pays for. The anchor: an asset at 25% volatility, correlated 0.8 with a 15% market, has a beta of 0.8 × 25/15 = 1.333333 — it amplifies market moves by a third. Read both ingredients carefully: the same asset at 25% volatility but uncorrelated (ρ ≈ 0) has a tiny beta — its risk, however huge, is diversifiable, hence free in the market\'s eyes. THE oral trap: beta is not volatility — you are not paid for the risk you take, but for the risk you cannot eliminate. Desk usage: a 120M book at beta 1.2 is exposed to 144M index-equivalent — that amount, not the book\'s value, is what m7\'s futures sale hedges (ch. 2).',
  },
  {
    id: 'm12-f-05',
    moduleId: M12,
    nom: 'Le CAPM : le rendement exigé le long de la SML',
    nomEn: 'The CAPM: the required return along the SML',
    latex: 'r = r_f + \\beta \\times (r_m - r_f)',
    commentaire: 'Le modèle central de la finance moderne (Sharpe, 1964) : le rendement exigé d\'un actif ne dépend que de son bêta, le long de la security market line. L\'ancre : taux sans risque 3 %, prime de marché 5 %, bêta 1,2 ⇒ 3 + 1,2 × 5 = 9 %. Le repère empirique à réciter : la prime de risque du marché actions vaut environ 4 à 6 % par an sur longue période. Distinction d\'oral : la SML porte en abscisse le BÊTA et contient tous les actifs ; la CML porte la volatilité TOTALE et ne contient que les portefeuilles efficients. Et la juste place du modèle : il prédit mal (anomalies value, momentum, low-vol), mais son langage bêta/alpha structure tout le métier — un langage plus qu\'une loi (ch. 2).',
    commentaireEn: 'Modern finance\'s central model (Sharpe, 1964): an asset\'s required return depends only on its beta, along the security market line. The anchor: risk-free rate 3%, market premium 5%, beta 1.2 ⇒ 3 + 1.2 × 5 = 9%. The empirical benchmark to recite: the equity market risk premium runs at about 4 to 6% per year over the long run. Oral distinction: the SML has BETA on the x-axis and contains all assets; the CML has TOTAL volatility and contains only efficient portfolios. And the model\'s fair place: it predicts poorly (value, momentum, low-vol anomalies), but its beta/alpha language structures the whole trade — a language more than a law (ch. 2).',
  },
  {
    id: 'm12-f-06',
    moduleId: M12,
    nom: 'L\'alpha de Jensen : ce qui reste quand le bêta est payé',
    nomEn: 'Jensen\'s alpha: what remains once beta is paid',
    latex: '\\alpha = r - \\left[ r_f + \\beta\\,(r_m - r_f) \\right]',
    commentaire: 'Le talent mesuré contre l\'étalon du CAPM : ce que le gérant a livré AU-DELÀ de ce que son bêta exigeait. Le cas d\'école : +12 % avec un bêta de 1,2, marché à 10 %, cash à 3 % — le CAPM exigeait 3 + 1,2 × 7 = 11,4 %, l\'alpha vaut +0,6 %. Le piège démonté : « 12 contre 10, donc 2 points de talent » oublie que le bêta est une amplification ACHETÉE, pas fabriquée — 1,4 des 2 points ne sont que la rémunération du risque. Corollaire : un fonds à bêta 1 qui fait exactement le marché a un alpha nul — un ETF l\'aurait livré pour trois points de base. L\'alpha est la denrée la plus chère et la plus rare du buy-side (ch. 3).',
    commentaireEn: 'Talent measured against the CAPM\'s yardstick: what the manager delivered BEYOND what their beta required. The textbook case: +12% with a beta of 1.2, market at 10%, cash at 3% — the CAPM required 3 + 1.2 × 7 = 11.4%, the alpha is +0.6%. The dismantled trap: "12 versus 10, so 2 points of talent" forgets that beta is amplification BOUGHT, not manufactured — 1.4 of the 2 points are just the price of risk. Corollary: a beta-1 fund that exactly matches the market has zero alpha — an ETF would have delivered it for three basis points. Alpha is the buy-side\'s most expensive and rarest commodity (ch. 3).',
  },
  {
    id: 'm12-f-07',
    moduleId: M12,
    nom: 'Le ratio de Sharpe : l\'excès de rendement par unité de risque',
    nomEn: 'The Sharpe ratio: excess return per unit of risk',
    latex: '\\text{Sharpe} = \\frac{r - r_f}{\\sigma}',
    commentaire: 'Le premier étalon de la performance : valait-il la peine de quitter le cash ? Un nombre SANS UNITÉ — des rendements en % divisés par une volatilité en %. L\'ancre : 8 % de rendement, cash à 3 %, volatilité 10 % ⇒ (8 − 3)/10 = 0,5. Les repères à réciter : 0,3-0,5 pour un portefeuille actions passif sur longue période, > 1 excellent, > 2 SUSPECT — LTCM affichait plus de 4 avant 1998 (m11) et a perdu 4,3 Md$ en quelques semaines. Le mécanisme du soupçon : les stratégies qui vendent de l\'assurance (options du m8, portage) encaissent une prime lisse et portent un risque de queue que la volatilité historique ne voit pas tant qu\'il ne s\'est pas réalisé. Devant un Sharpe spectaculaire, demandez d\'où vient le rendement avant d\'admirer le ratio (ch. 3).',
    commentaireEn: 'Performance\'s first yardstick: was leaving cash worth it? A UNITLESS number — returns in % divided by a volatility in %. The anchor: 8% return, cash at 3%, 10% volatility ⇒ (8 − 3)/10 = 0.5. The benchmarks to recite: 0.3-0.5 for a passive equity portfolio over the long run, above 1 excellent, above 2 SUSPICIOUS — LTCM showed more than 4 before 1998 (m11) and lost $4.3bn in a few weeks. The mechanism behind the suspicion: insurance-selling strategies (m8 options, carry) collect a smooth premium and carry a tail risk that historical volatility cannot see until it happens. Facing a spectacular Sharpe, ask where the return comes from before admiring the ratio (ch. 3).',
  },
  {
    id: 'm12-f-08',
    moduleId: M12,
    nom: 'Tracking error et ratio d\'information : le Sharpe du gérant actif',
    nomEn: 'Tracking error and information ratio: the active manager\'s Sharpe',
    latex: 'IR = \\frac{r_p - r_b}{TE}, \\qquad TE = \\sigma(r_p - r_b)',
    commentaire: 'Le troisième étalon : le mandat. La tracking error est la volatilité de l\'écart au benchmark — et, point capital, elle ne se subit pas, elle se CHOISIT : c\'est le budget de liberté du mandat (~0,5 % pour un fonds indiciel, 2 à 6 % pour un gérant actif). Le ratio d\'information juge l\'usage de ce budget : battre l\'indice de 2 % avec 4 % de TE donne IR = 0,5 — et tenir plus de 0,5 dans la durée est déjà très bon. Même construction que le Sharpe — un excès de rendement divisé par le risque pris pour l\'obtenir — mais l\'étalon est le mandat, pas le cash (ch. 3).',
    commentaireEn: 'The third yardstick: the mandate. Tracking error is the volatility of the gap to the benchmark — and, crucially, it is not endured, it is CHOSEN: the mandate\'s freedom budget (~0.5% for an index fund, 2 to 6% for an active manager). The information ratio judges the use of that budget: beating the index by 2% with 4% of TE gives IR = 0.5 — and holding above 0.5 over time is already very good. Same construction as the Sharpe — an excess return divided by the risk taken to get it — but the yardstick is the mandate, not cash (ch. 3).',
  },
  {
    id: 'm12-f-09',
    moduleId: M12,
    nom: 'La VaR paramétrique : un quantile en une multiplication',
    nomEn: 'Parametric VaR: a quantile in one multiplication',
    latex: '\\text{VaR} = V \\times z \\times \\sigma_{\\text{annuelle}} \\times \\sqrt{h/252}',
    commentaire: 'La réponse de 1994 (RiskMetrics, JPMorgan) à la question du patron : « combien peut-on perdre ? » — un seuil de perte, un niveau de confiance, un horizon. Les z d\'usage à connaître par cœur : 1,65 pour 95 %, 2,33 pour 99 %. L\'ancre : 100 M à 20 % de volatilité, 95 %, 1 jour ⇒ 100 × 1,65 × 0,20 × √(1/252) = 2,078805 M — « on ne devrait pas perdre plus de ~2,1 M en un jour, 19 jours sur 20 » ; en 99 %/10 jours, la combinaison historique de Bâle : 9,282942 M. Le contresens mortel : la VaR n\'est JAMAIS une perte maximale — elle dit où commence la queue, pas ce qu\'il y a dedans. Le 20e jour, la perte peut être de 2,2 M ou de 40 M : le chiffre est muet, par construction (ch. 5).',
    commentaireEn: 'The 1994 answer (RiskMetrics, JPMorgan) to the boss\'s question — "how much can we lose?": a loss threshold, a confidence level, a horizon. The z values to know by heart: 1.65 for 95%, 2.33 for 99%. The anchor: 100M at 20% volatility, 95%, 1 day ⇒ 100 × 1.65 × 0.20 × √(1/252) = 2.078805M — "we should not lose more than ~2.1M in one day, 19 days out of 20"; at 99%/10 days, Basel\'s historical combination: 9.282942M. The deadly misreading: VaR is NEVER a maximum loss — it says where the tail starts, not what is inside it. On the 20th day, the loss can be 2.2M or 40M: the number is silent, by construction (ch. 5).',
  },
  {
    id: 'm12-f-10',
    moduleId: M12,
    nom: 'La racine du temps : un plafond optimiste',
    nomEn: 'The square root of time: an optimistic ceiling',
    latex: '\\text{VaR}_h = \\text{VaR}_{1\\text{j}} \\times \\sqrt{h}',
    commentaire: 'La convention pour étendre une VaR à un horizon plus long : les rendements étant supposés indépendants, les variances s\'additionnent et l\'écart-type croît en √h. L\'ancre : 2 M par jour donnent 2 × √10 = 6,324555 M sur 10 jours — pas 20 M. C\'était la convention réglementaire historique (Bâle exigeait la VaR 10 jours = 1 jour × √10). Le vice caché : l\'hypothèse i.i.d. casse précisément en crise, quand les pertes s\'enchaînent — ventes forcées, appels de marge, les spirales du m11 — et s\'autocorrèlent positivement. Retenez la lecture : un plancher commode par temps calme, un plafond optimiste par gros temps (ch. 5).',
    commentaireEn: 'The convention for extending a VaR to a longer horizon: returns being assumed independent, variances add up and the standard deviation grows as √h. The anchor: 2M per day gives 2 × √10 = 6.324555M over 10 days — not 20M. It was the historical regulatory convention (Basel required the 10-day VaR = 1 day × √10). The hidden flaw: the i.i.d. assumption breaks precisely in crises, when losses chain up — forced sales, margin calls, m11\'s spirals — and become positively autocorrelated. Remember the reading: a handy floor in calm times, an optimistic ceiling in rough ones (ch. 5).',
  },
  {
    id: 'm12-f-11',
    moduleId: M12,
    nom: 'Dépassements attendus : le backtesting de la VaR',
    nomEn: 'Expected exceedances: backtesting the VaR',
    latex: '\\text{dépassements attendus par an} = (1 - c) \\times 252',
    commentaire: 'Le dépassement de VaR n\'est pas un échec du modèle : il est PRÉVU, à la fréquence exacte que le niveau de confiance annonce. À 95 % : 0,05 × 252 ≈ 12,6 jours par an — une douzaine ; à 99 % : environ 2,5. Le backtesting compte les dépassements réalisés et les compare à ce chiffre : trop nombreux, le modèle sous-estime ; JAMAIS dépassé, il surestime et gaspille du capital. Le régulateur en a fait un barème — les feux tricolores de Bâle sur 250 jours à 99 % : vert jusqu\'à 4, orange de 5 à 9 (multiplicateur de capital majoré), rouge à 10 ou plus (modèle présumé faux). La limite, exposée par 2008 : compter les dépassements ne dit rien de leur TAILLE — un modèle peut rester vert et mourir d\'un seul jour (ch. 5).',
    commentaireEn: 'A VaR exceedance is not a model failure: it is EXPECTED, at exactly the frequency the confidence level announces. At 95%: 0.05 × 252 ≈ 12.6 days per year — a dozen; at 99%: about 2.5. Backtesting counts realised exceedances against that number: too many, the model underestimates; NEVER exceeded, it overestimates and wastes capital. The regulator turned the count into a scale — Basel\'s traffic lights over 250 days at 99%: green up to 4, amber from 5 to 9 (higher capital multiplier), red at 10 or more (model presumed wrong). The limit, exposed by 2008: counting exceedances says nothing about their SIZE — a model can stay green and die of a single day (ch. 5).',
  },
  {
    id: 'm12-f-12',
    moduleId: M12,
    nom: 'L\'expected shortfall : et ce jour-là, on perd combien ?',
    nomEn: 'Expected shortfall: and on that day, how much do we lose?',
    latex: 'ES = \\mathbb{E}\\left[\\,\\text{perte} \\mid \\text{perte} > \\text{VaR}\\,\\right]',
    commentaire: 'La réponse à la question qui tue : la MOYENNE des pertes au-delà de la VaR — quand ça dépasse, on perd combien en moyenne ? Deux portefeuilles peuvent avoir la même VaR 99 % de 9,3 M, l\'un perdant 10 M le jour du dépassement, l\'autre 200 M : la VaR est identique, l\'ES ne l\'est pas. C\'est la mesure que Bâle a fini par adopter pour le trading book (FRTB : un ES à 97,5 % remplace la VaR à 99 %) — à distribution normale les deux chiffres sont proches, à queues épaisses l\'ES est nettement plus exigeant, et c\'est le but. Sa limite honnête : une moyenne estimée sur la partie de la distribution qu\'on connaît le plus mal — d\'où le second garde-fou, le stress test (ch. 5, 6).',
    commentaireEn: 'The answer to the killer question: the AVERAGE of losses beyond the VaR — when it exceeds, how much do we lose on average? Two portfolios can share the same 99% VaR of 9.3M, one losing 10M on the exceedance day, the other 200M: the VaR is identical, the ES is not. It is the measure Basel eventually adopted for the trading book (FRTB: a 97.5% ES replaces the 99% VaR) — under a normal distribution the two numbers are close, under fat tails the ES is markedly tougher, and that is the point. Its honest limit: an average estimated on the part of the distribution we know worst — hence the second safeguard, the stress test (ch. 5, 6).',
  },
  {
    id: 'm12-f-13',
    moduleId: M12,
    nom: 'Le stress test « bêta » : pas de probabilité, un scénario',
    nomEn: 'The "beta" stress test: no probability, a scenario',
    latex: '\\text{perte} = V \\times \\text{choc} \\times \\beta',
    commentaire: 'L\'anti-VaR : on renonce à la probabilité et on pose la seule question qui reste quand les lois ont brûlé — « et si ? ». L\'ancre : un portefeuille de 100 M à bêta 1,2 dans un marché à −20 % perd 100 × (−0,20) × 1,2 = −24 M — un chiffre signé, brutal, sans intervalle de confiance. Trois familles de scénarios : historiques (1987, 2008, mars 2020 — personne ne peut dire qu\'ils sont impossibles), hypothétiques (des chocs qui frappent ENSEMBLE, car les crises corrèlent tout), inversés (« qu\'est-ce qui nous tue ? » — le plus fécond). La vertu est dans la question, pas dans le raffinement : LTCM avait des modèles superbes et n\'avait jamais posé la question fruste (ch. 5).',
    commentaireEn: 'The anti-VaR: you give up on probability and ask the only question left when the laws have burned — "what if?". The anchor: a 100M portfolio at beta 1.2 in a −20% market loses 100 × (−0.20) × 1.2 = −24M — a signed, brutal number, with no confidence interval. Three families of scenarios: historical (1987, 2008, March 2020 — nobody can call them impossible), hypothetical (shocks hitting TOGETHER, because crises correlate everything), reverse ("what kills us?" — the most fertile). The virtue is in the question, not the refinement: LTCM had superb models and had never asked the crude question (ch. 5).',
  },
  {
    id: 'm12-f-14',
    moduleId: M12,
    nom: 'RWA : l\'exposition pondérée par son risque',
    nomEn: 'RWA: the exposure weighted by its risk',
    latex: '\\text{RWA} = \\text{exposition} \\times \\text{pondération}',
    commentaire: 'Le dénominateur de tout Bâle III : un euro prêté à l\'État allemand n\'est pas un euro prêté à une PME, donc chaque exposition est multipliée par une pondération qui encode son risque. L\'ancre : 100 M pondérés à 75 % — le standard de la clientèle de détail — donnent 75 M de RWA. L\'échelle à réciter : ~0 % pour le souverain AAA, 20-50 % pour les banques et entreprises bien notées, 75 % pour le détail, 100 % et plus pour le reste — les agences de notation du m5 sont câblées dans le capital bancaire mondial, avec leurs effets de falaise. Le garde-fou contre la pondération elle-même : le ratio de levier, fonds propres / exposition NON pondérée ≥ 3 % — l\'anti-RWA, comme le stress test est l\'anti-VaR (ch. 6).',
    commentaireEn: 'The denominator of all of Basel III: a euro lent to the German state is not a euro lent to an SME, so each exposure is multiplied by a weight encoding its risk. The anchor: 100M weighted at 75% — the retail standard — gives 75M of RWA. The scale to recite: ~0% for AAA sovereigns, 20-50% for well-rated banks and corporates, 75% for retail, 100% and above for the rest — m5\'s rating agencies are wired into global bank capital, cliff effects included. The safeguard against the weighting itself: the leverage ratio, capital / UNWEIGHTED exposure ≥ 3% — the anti-RWA, just as the stress test is the anti-VaR (ch. 6).',
  },
  {
    id: 'm12-f-15',
    moduleId: M12,
    nom: 'Le ratio CET1 : le capital qui absorbe les pertes',
    nomEn: 'The CET1 ratio: the capital that absorbs losses',
    latex: '\\text{CET1} = \\frac{\\text{fonds propres durs}}{\\text{RWA}} \\times 100',
    commentaire: 'LA réponse réglementaire à 2008 : plus de capital, de meilleure qualité. Les fonds propres durs — actions ordinaires et réserves, le capital qui absorbe les pertes sans déclencher de défaut — rapportés aux RWA. L\'ancre : 12 M de fonds propres durs pour 100 M de RWA = 12 %. Les exigences s\'empilent : 4,5 % de minimum, coussin de conservation de 2,5 % (entamable au prix de restrictions sur dividendes et bonus), coussins systémiques de 1 à 3,5 % pour les G-SIB — et les grandes banques européennes vivent à 12-15 %, parce que le marché lui-même exige la marge. Le contre-exemple à réciter : Lehman, levier ~31, soit ~3,2 % de capital sur bilan — 3 % de baisse des actifs suffisaient à tout effacer (m11, ch. 6).',
    commentaireEn: 'THE regulatory answer to 2008: more capital, of better quality. Hard capital — common shares and retained earnings, the capital that absorbs losses without triggering default — over RWA. The anchor: 12M of hard capital for 100M of RWA = 12%. Requirements stack up: a 4.5% minimum, a 2.5% conservation buffer (usable, at the price of dividend and bonus restrictions), systemic buffers of 1 to 3.5% for G-SIBs — and large European banks live at 12-15%, because the market itself demands the margin. The counter-example to recite: Lehman, leverage ~31, i.e. ~3.2% of capital on balance sheet — a 3% fall in assets was enough to wipe everything out (m11, ch. 6).',
  },
  {
    id: 'm12-f-16',
    moduleId: M12,
    nom: 'Le LCR : survivre un mois de run',
    nomEn: 'The LCR: surviving a month-long run',
    latex: '\\text{LCR} = \\frac{\\text{HQLA}}{\\text{sorties nettes à 30 jours}} \\times 100 \\;\\geq\\; 100\\ \\%',
    commentaire: 'La jambe que Bâle II ignorait : 2008 a tué des banques SOLVABLES — Northern Rock, Bear Stearns — mortes de ne plus pouvoir se refinancer. Le LCR exige assez d\'actifs liquides de haute qualité (HQLA : cash, réserves banque centrale, souverains liquides) pour couvrir les sorties nettes de trésorerie sur 30 jours de stress prescrit. L\'ancre : 120 M de HQLA face à 100 M de sorties = 120 % — survivre un mois de run SANS banque centrale. Son complément à un an : le NSFR, les actifs longs financés par des ressources stables, pas par du repo au jour le jour. La leçon SVB (mars 2023, m11) : 42 Md$ de retraits demandés en UNE journée — un run à la vitesse du smartphone peut dépasser le scénario, et le ratio ne protège que ceux qui y sont soumis (ch. 6).',
    commentaireEn: 'The leg Basel II ignored: 2008 killed SOLVENT banks — Northern Rock, Bear Stearns — dead from being unable to refinance. The LCR requires enough high-quality liquid assets (HQLA: cash, central bank reserves, liquid sovereigns) to cover net cash outflows over 30 days of prescribed stress. The anchor: 120M of HQLA against 100M of outflows = 120% — surviving a month-long run WITHOUT the central bank. Its one-year complement: the NSFR, long assets funded by stable resources, not overnight repo. The SVB lesson (March 2023, m11): $42bn of withdrawals requested in ONE day — a smartphone-speed run can outrun the scenario, and the ratio only protects those subject to it (ch. 6).',
  },
  {
    id: 'm12-f-17',
    moduleId: M12,
    nom: 'La valeur nette de frais : l\'argument massue du passif',
    nomEn: 'Value net of fees: the passive camp\'s knockout argument',
    latex: 'V = C \\times \\left(1 + \\frac{r - f}{100}\\right)^{n}',
    commentaire: 'La composition du m4 retournée contre l\'investisseur : le rendement brut r diminué des frais annuels f, composé sur n années. L\'ancre à réciter : 100 investis 30 ans à 7 % brut font 761,225504 ; avec 2 % de frais annuels, 432,194238 — les frais ont coûté 329,031266, plus de trois fois la mise de départ, soit 43 % de la valeur finale, SANS qu\'aucune année isolée ne semble chère. Un ETF à 0,2 % laisse 719,676929 — la quasi-totalité de la performance. L\'arrière-plan : l\'arithmétique de Sharpe (1991) — identité comptable, pas opinion — garantit qu\'avant frais le gérant actif moyen fait exactement le marché, donc moins après ; SPIVA confirme : 85-90 % des fonds actions actifs sous-performent leur indice à 10-15 ans (ch. 4).',
    commentaireEn: 'M4\'s compounding turned against the investor: the gross return r minus annual fees f, compounded over n years. The anchor to recite: 100 invested for 30 years at 7% gross makes 761.225504; with 2% annual fees, 432.194238 — the fees cost 329.031266, more than three times the initial stake, i.e. 43% of the final value, WITHOUT any single year looking expensive. An ETF at 0.2% leaves 719.676929 — nearly all of the performance. The backdrop: Sharpe\'s arithmetic (1991) — an accounting identity, not an opinion — guarantees the average active manager matches the market before fees, hence less after; SPIVA confirms: 85-90% of active equity funds underperform their index over 10-15 years (ch. 4).',
  },
];
