import type { Formule } from '../../../engine/types';

const M10 = '10-macro-banques-centrales';

export const formules: Formule[] = [
  {
    id: 'm10-f-01',
    moduleId: M10,
    nom: 'Règle de Taylor',
    nomEn: 'Taylor rule',
    latex: 'i = r^* + \\pi + a\\,(\\pi - \\pi^*) + b \\cdot \\text{gap}',
    commentaire: 'LA formule du module, écrite en 1993 : taux neutre réel, plus l\'inflation courante (c\'est un taux nominal qu\'on fixe), plus la pénalité d\'écart à la cible, plus la correction conjoncturelle (gap négatif en récession). Coefficients canoniques a = b = 0,5. L\'exemple du cours : (2, 4, 2, −1) donne 2 + 4 + 0,5×2 − 0,5×1 = 6,5 %. Volcker 1980 : prescription 19,5 %, taux réel 20 — la brutalité était la règle. Ce qu\'elle ne dit pas : r* est inobservable, le gap massivement révisé — un étalon de conversation (« la Fed est 300 pb sous sa Taylor »), pas un pilote automatique (ch. 2).',
    commentaireEn: 'THE formula of the module, written in 1993: real neutral rate, plus current inflation (it is a nominal rate being set), plus the penalty for deviating from target, plus the cyclical correction (negative gap in recession). Canonical coefficients a = b = 0.5. The course example: (2, 4, 2, −1) gives 2 + 4 + 0.5×2 − 0.5×1 = 6.5%. Volcker 1980: prescription 19.5%, actual rate 20 — the brutality was the rule. What it does not say: r* is unobservable, the gap heavily revised — a conversation benchmark ("the Fed is 300 bps below its Taylor"), not an autopilot (ch. 2).',
  },
  {
    id: 'm10-f-02',
    moduleId: M10,
    nom: 'Taux réel : équation de Fisher exacte',
    nomEn: 'Real rate: exact Fisher equation',
    latex: 'r = \\frac{1 + i}{1 + \\pi} - 1',
    commentaire: 'Ce qu\'un placement rapporte VRAIMENT une fois l\'inflation déduite — la variable qui dit si une politique est restrictive (réel au-dessus du neutre r*) ou accommodante. Composition discrète, la convention du module. (10 %, 8 %) : 1,10/1,08 − 1 = 1,85 % ; (5 %, 2 %) : 2,9412 %. Peut être négatif — répression financière : un livret à 3 % sous 5 % d\'inflation rend −1,90 %, et l\'été 2022 (nominal 2,5 %, inflation 8 %) affichait −5,09 % — quatre hausses plus tard, encore massivement accommodant (ch. 2, 4).',
    commentaireEn: 'What an investment REALLY returns once inflation is deducted — the variable that says whether a policy is restrictive (real rate above the neutral r*) or accommodative. Discrete compounding, the module\'s convention. (10%, 8%): 1.10/1.08 − 1 = 1.85%; (5%, 2%): 2.9412%. Can be negative — financial repression: a 3% savings account under 5% inflation returns −1.90%, and summer 2022 (nominal 2.5%, inflation 8%) showed −5.09% — four hikes in, still massively accommodative (ch. 2, 4).',
  },
  {
    id: 'm10-f-03',
    moduleId: M10,
    nom: 'Taux réel approché',
    nomEn: 'Approximate real rate',
    latex: 'r \\approx i - \\pi',
    commentaire: 'L\'arithmétique de tête des salles de marché : nominal moins inflation. Elle néglige le terme croisé i×π et SURESTIME donc toujours le réel, d\'autant plus que les niveaux sont élevés — précisément les régimes où l\'on en a besoin : 6 pb d\'écart à (5 %, 2 %) — 3 % contre 2,9412 % —, 15 pb à (10 %, 8 %) — 2 % contre 1,85 %. Le réflexe d\'entretien : donner l\'approximation, PUIS signaler l\'écart et son signe (ch. 2, 4).',
    commentaireEn: 'The trading floor\'s mental arithmetic: nominal minus inflation. It neglects the cross term i×π and therefore always OVERSTATES the real rate, all the more as levels are high — precisely the regimes where you need it: 6 bps of gap at (5%, 2%) — 3% versus 2.9412% —, 15 bps at (10%, 8%) — 2% versus 1.85%. The interview reflex: give the approximation, THEN flag the gap and its sign (ch. 2, 4).',
  },
  {
    id: 'm10-f-04',
    moduleId: M10,
    nom: 'Taux nominal requis (Fisher inversé)',
    nomEn: 'Required nominal rate (inverted Fisher)',
    latex: 'i = (1 + r)(1 + \\pi) - 1',
    commentaire: 'Fisher lu à l\'envers : le nominal qu\'il faut pour servir un réel visé sous une inflation donnée. Viser 3 % de réel sous 2 % d\'inflation exige 1,03 × 1,02 − 1 = 5,06 % — pas 5 : le terme croisé travaille aussi dans ce sens. Vérification de cohérence : l\'aller-retour par Fisher exact retombe exactement sur 3. Cas limite parlant : viser un réel NUL exige un nominal égal à l\'inflation — tout nominal en dessous est une taxe silencieuse sur l\'épargnant (ch. 2, 4).',
    commentaireEn: 'Fisher read backwards: the nominal rate needed to deliver a target real rate under a given inflation. Targeting a 3% real under 2% inflation requires 1.03 × 1.02 − 1 = 5.06% — not 5: the cross term works in this direction too. Consistency check: the round trip through exact Fisher lands exactly back on 3. A telling limit case: targeting a ZERO real rate requires a nominal equal to inflation — any nominal below it is a silent tax on the saver (ch. 2, 4).',
  },
  {
    id: 'm10-f-05',
    moduleId: M10,
    nom: 'Érosion du pouvoir d\'achat',
    nomEn: 'Purchasing-power erosion',
    latex: '\\text{pouvoir d\'achat résiduel} = \\frac{\\text{montant}}{(1 + \\pi)^n}',
    commentaire: 'Les intérêts composés du module 4 joués CONTRE l\'épargnant — techniquement une simple actualisation (la fonction du cours appelle va() sous le capot) au « taux » d\'inflation. 100 € sous 5 % pendant dix ans : 100/1,05^10 = 61,39 € — 38,6 % du billet rongés sans krach ni défaut, et pas 50 % comme le calcul naïf 10 × 5 le suggérerait. À la cible de 2 % : 82,03 € — l\'érosion existe aussi en régime sain, c\'est un choix assumé. À 10 %, sept ans détruisent près de la moitié (51,32 €). Les gagnants symétriques : les débiteurs à taux fixe, l\'État en tête — la taxe d\'inflation (ch. 4).',
    commentaireEn: 'Module 4\'s compound interest played AGAINST the saver — technically a plain discounting (the course function calls va() under the hood) at the inflation "rate". €100 under 5% for ten years: 100/1.05^10 = €61.39 — 38.6% of the banknote gnawed away without a crash or a default, and not 50% as the naive 10 × 5 would suggest. At the 2% target: €82.03 — erosion exists in the healthy regime too, a deliberate choice. At 10%, seven years destroy nearly half (€51.32). The symmetric winners: fixed-rate debtors, the State first — the inflation tax (ch. 4).',
  },
  {
    id: 'm10-f-06',
    moduleId: M10,
    nom: 'Chaînage d\'un indice des prix',
    nomEn: 'Price-index chaining',
    latex: 'I_n = I_0 \\times \\prod_{t=1}^{n} (1 + \\pi_t)',
    commentaire: 'La construction des indices officiels : chaque année, le niveau est multiplié par un plus l\'inflation de l\'année. Trois années à 2 %, 3 % puis 10 % : 100 × 1,02 × 1,03 × 1,10 = 115,57 — et non 115 : la composition mord toujours, dans le sens défavorable au consommateur. L\'asymétrie à avoir manipulée une fois : +10 % puis −10 % ne reviennent pas à 100 mais à 99 — la baisse s\'applique à une base plus haute. Et la distinction qu\'elle porte : désinflation n\'est pas déflation — le rythme ralentit, mais le niveau ne redescend jamais (ch. 4).',
    commentaireEn: 'How official indices are built: each year, the level is multiplied by one plus that year\'s inflation. Three years at 2%, 3% then 10%: 100 × 1.02 × 1.03 × 1.10 = 115.57 — not 115: compounding always bites, in the direction unfavourable to the consumer. The asymmetry to have handled once: +10% then −10% do not return to 100 but to 99 — the fall applies to a higher base. And the distinction it carries: disinflation is not deflation — the pace slows, but the level never comes back down (ch. 4).',
  },
  {
    id: 'm10-f-07',
    moduleId: M10,
    nom: 'Annualisation d\'une inflation mensuelle',
    nomEn: 'Annualising a monthly inflation print',
    latex: '\\pi_{\\text{annualisée}} = (1 + m)^{12} - 1',
    commentaire: 'LE piège des publications CPI : un +0,5 % sur le mois n\'est pas « 6 % en rythme annuel » mais (1,005)^12 − 1 = 6,17 % — les hausses de prix se composent, exactement comme les intérêts du module 4. L\'écart au calcul naïf 12×m grossit avec le chiffre : 1 % par mois fait 12,68 %, pas 12 %. Le réflexe d\'oral : annualiser de tête à 12× pour l\'ordre de grandeur, puis SIGNALER que la composition ajoute quelques dixièmes. Fonctionne aussi en déflation (m négatif). On ne multiplie jamais des taux, on les compose (ch. 4, 6).',
    commentaireEn: 'THE trap of CPI releases: a +0.5% on the month is not "6% annualised" but (1.005)^12 − 1 = 6.17% — price increases compound, exactly like module 4\'s interest. The gap to the naive 12×m grows with the print: 1% per month makes 12.68%, not 12%. The oral reflex: annualise mentally at 12× for the order of magnitude, then FLAG that compounding adds a few tenths. Also works in deflation (negative m). You never multiply rates, you compound them (ch. 4, 6).',
  },
  {
    id: 'm10-f-08',
    moduleId: M10,
    nom: 'Effet de base : le glissement annuel',
    nomEn: 'Base effect: the year-on-year print',
    latex: '\\text{glissement annuel} = \\frac{I_m}{I_{m-12}} - 1',
    commentaire: 'L\'inflation publiée compare l\'indice du mois au même mois de l\'an dernier : le chiffre dépend autant du passé que du présent. L\'exemple chiffré du cours : choc unique de +3 % en mars 2022 puis croisière à +0,2 % par mois — en mars 2023 le glissement inclut encore le choc, 1,03 × 1,002^11 − 1 ≈ 5,29 % ; un mois plus tard le choc SORT de la fenêtre : 1,002^12 − 1 ≈ 2,43 %. L\'inflation affichée chute de 2,9 points sans que le rythme courant change d\'un iota — pure arithmétique de fenêtre glissante, jouée en grandeur réelle au printemps 2023. Réflexe : demander ce qui entre et ce qui sort de la fenêtre (ch. 4).',
    commentaireEn: 'Published inflation compares this month\'s index to the same month last year: the print depends as much on the past as on the present. The course\'s numbered example: a one-off +3% shock in March 2022 then cruising at +0.2% per month — in March 2023 the year-on-year still includes the shock, 1.03 × 1.002^11 − 1 ≈ 5.29%; one month later the shock EXITS the window: 1.002^12 − 1 ≈ 2.43%. Displayed inflation drops 2.9 points while the current pace has not changed one iota — pure rolling-window arithmetic, played out for real in spring 2023. Reflex: ask what enters and what leaves the window (ch. 4).',
  },
  {
    id: 'm10-f-09',
    moduleId: M10,
    nom: 'Surprise standardisée d\'un indicateur',
    nomEn: 'Standardised indicator surprise',
    latex: '\\text{surprise} = \\frac{\\text{publié} - \\text{consensus}}{\\sigma_{\\text{surprises}}}',
    commentaire: 'La lecture professionnelle d\'une publication : le consensus est déjà dans les prix, seul l\'écart bouge les marchés — et cet écart se mesure en écarts-types historiques des surprises, SANS UNITÉ. Le NFP du cours : publié 300 000 contre 180 000 attendus, σ = 60 000 ⇒ +2σ — rare, donc violent ; le même écart brut sur un indicateur plus erratique ne vaudrait qu\'un haussement d\'épaules. La normalisation permet de comparer les chocs entre indicateurs : un CPI à +2σ et un NFP à +2σ sont la même taille de surprise. ±0,5σ est du bruit, ±2σ un événement (ch. 6).',
    commentaireEn: 'The professional reading of a release: the consensus is already in the prices, only the gap moves markets — and that gap is measured in historical standard deviations of surprises, UNITLESS. The course\'s NFP: printed 300,000 versus 180,000 expected, σ = 60,000 ⇒ +2σ — rare, hence violent; the same raw gap on a more erratic indicator would only be worth a shrug. The normalisation lets you compare shocks across indicators: a +2σ CPI and a +2σ NFP are the same size of surprise. ±0.5σ is noise, ±2σ an event (ch. 6).',
  },
  {
    id: 'm10-f-10',
    moduleId: M10,
    nom: 'Probabilité implicite d\'un future sur taux',
    nomEn: 'Implied probability from a rate future',
    latex: '\\text{taux implicite} = 100 - \\text{prix}, \\qquad \\mathbb{P}(\\text{hausse}) = \\frac{\\text{taux implicite} - \\text{taux sans hausse}}{\\text{taux avec hausse} - \\text{taux sans hausse}}',
    commentaire: 'Trois soustractions qui fabriquent les probabilités « selon les marchés » : un future fed funds cote 100 moins le taux moyen attendu — 95,85 implique 4,15 %. Si le taux actuel est 4,00 % et qu\'une hausse de 25 pb est en jeu, 4,15 n\'est ni 4,00 ni 4,25 : c\'est une moyenne pondérée par les probabilités, et l\'interpolation donne P = (4,15 − 4,00)/(4,25 − 4,00) = 60 %. L\'outil FedWatch du CME ne fait rien d\'autre ; en chaînant les futures de mois en mois, on reconstruit tout le sentier anticipé jusqu\'au taux terminal (ch. 6).',
    commentaireEn: 'Three subtractions that manufacture the "market-implied" probabilities: a fed funds future quotes 100 minus the expected average rate — 95.85 implies 4.15%. If the current rate is 4.00% and a 25 bp hike is at stake, 4.15 is neither 4.00 nor 4.25: it is a probability-weighted average, and the interpolation gives P = (4.15 − 4.00)/(4.25 − 4.00) = 60%. The CME\'s FedWatch tool does nothing else; chaining futures month by month reconstructs the whole anticipated path up to the terminal rate (ch. 6).',
  },
  {
    id: 'm10-f-11',
    moduleId: M10,
    nom: 'Taux terminal anticipé',
    nomEn: 'Anticipated terminal rate',
    latex: '\\text{taux terminal} = \\text{taux actuel} + n \\times \\frac{\\text{pas en pb}}{100}',
    commentaire: 'L\'arithmétique des dot plots et des futures : le sommet (ou le plancher) du cycle en cours, en pas de 25 ou 50 pb — la granularité des comités, convertie en % (100 pb = 1 %). Depuis 2,50 %, quatre hausses de 50 pb mènent à 4,50 % ; un pas négatif décrit un cycle de baisse — depuis 4,00 %, trois baisses de 25 pb ramènent à 3,25 %. La sophistication n\'est pas dans la formule mais dans ce que le marché met dans n et dans le pas. L\'échelle des cycles 2022-2023 : BCE +450 pb en quatorze mois, Fed +525 pb en seize — les resserrements les plus violents depuis Volcker (ch. 2, 6).',
    commentaireEn: 'The arithmetic of dot plots and futures: the peak (or floor) of the current cycle, in steps of 25 or 50 bps — the committees\' granularity, converted to % (100 bps = 1%). From 2.50%, four 50 bp hikes lead to 4.50%; a negative step describes an easing cycle — from 4.00%, three 25 bp cuts bring it back to 3.25%. The sophistication is not in the formula but in what the market puts into n and the step. The 2022-2023 scale: ECB +450 bps in fourteen months, Fed +525 bps in sixteen — the most violent tightenings since Volcker (ch. 2, 6).',
  },
  {
    id: 'm10-f-12',
    moduleId: M10,
    nom: 'Variation de prix par la duration',
    nomEn: 'Price change via duration',
    latex: '\\frac{\\Delta P}{P} \\approx -D_{\\text{mod}} \\times \\Delta y',
    commentaire: 'Le canal de transmission le plus mécanique de toute la politique monétaire, hérité du module 4 : duration modifiée fois variation de taux, signe moins, Δy en points de base convertis en %. Duration 7, +100 pb : −7 %. Chiffrez 2022 : +300 pb sur une duration de 7 donnent −21 %, sur une duration de 8, −24 % — la pire année de l\'« actif sans risque » (Global Aggregate ≈ −17 %) ; « sans risque » qualifie le défaut, jamais le prix. Et les gilts de septembre 2022 : +130 pb sur une duration de 20, −26 % en trois séances. L\'approximation est linéaire ; la convexité du m4 adoucit la vraie perte (ch. 3, 7).',
    commentaireEn: 'The most mechanical transmission channel in all of monetary policy, inherited from module 4: modified duration times the rate move, minus sign, Δy in basis points converted to %. Duration 7, +100 bps: −7%. Put numbers on 2022: +300 bps on a duration of 7 gives −21%, on a duration of 8, −24% — the "risk-free asset\'s" worst year (Global Aggregate ≈ −17%); "risk-free" qualifies default, never price. And the September 2022 gilts: +130 bps on a duration of 20, −26% in three sessions. The approximation is linear; module 4\'s convexity softens the true loss (ch. 3, 7).',
  },
  {
    id: 'm10-f-13',
    moduleId: M10,
    nom: 'Ratio de sacrifice',
    nomEn: 'Sacrifice ratio',
    latex: '\\text{ratio de sacrifice} = \\frac{|\\text{écarts de production cumulés}|}{\\text{désinflation}}',
    commentaire: 'La facture de la désinflation : les points de production cumulés perdus PAR point d\'inflation éradiqué. L\'étalon Volcker : environ dix points de désinflation (13 % → 3-4 %) contre une quinzaine de points de PIB de récessions — ratio 15/10 = 1,5, deux récessions et un chômage à 10,8 %. Le contrepoint 2023 : un ratio quasi nul, la « désinflation immaculée » — part du choc d\'offre résorbée d\'elle-même, et surtout anticipations restées ancrées. La leçon : le ratio n\'est pas une constante de la nature, c\'est le prix de la désinflation pour un stock de crédibilité donné (ch. 4).',
    commentaireEn: 'The bill for disinflation: the cumulative output points lost PER point of inflation eradicated. The Volcker benchmark: about ten points of disinflation (13% → 3-4%) against some fifteen GDP points of recessions — ratio 15/10 = 1.5, two recessions and 10.8% unemployment. The 2023 counterpoint: a near-zero ratio, the "immaculate disinflation" — part of the supply shock unwound by itself, and above all expectations that stayed anchored. The lesson: the ratio is not a constant of nature, it is the price of disinflation for a given stock of credibility (ch. 4).',
  },
];
