import type { Formule } from '../../../engine/types';

const M8 = '08-options-volatilite';

export const formules: Formule[] = [
  {
    id: 'm8-f-01',
    moduleId: M8,
    nom: 'Payoff d\'un call à l\'échéance',
    nomEn: 'Call payoff at expiry',
    latex: '\\text{payoff}_{\\text{call}} = \\max(S_T - K,\\ 0)',
    commentaire: 'Le droit d\'acheter à K ne s\'exerce que s\'il rapporte : action à 110 contre un strike de 100, exercer paie 10 ; à 90, le droit s\'abandonne — payoff nul, pas une perte de 10. La demi-droite coudée au strike, la « crosse de hockey », est la signature graphique de l\'option, là où le module 7 ne traçait que des droites (ch. 1).',
    commentaireEn: 'The right to buy at K is exercised only if it pays: stock at 110 against a 100 strike, exercising earns 10; at 90, the right is abandoned — zero payoff, not a loss of 10. The half-line kinked at the strike, the "hockey stick", is the option\'s graphic signature, where module 7 only drew straight lines (ch. 1).',
  },
  {
    id: 'm8-f-02',
    moduleId: M8,
    nom: 'Payoff d\'un put à l\'échéance',
    nomEn: 'Put payoff at expiry',
    latex: '\\text{payoff}_{\\text{put}} = \\max(K - S_T,\\ 0)',
    commentaire: 'Le droit de vendre à K paie la chute : action à 85 contre un strike de 100, le put verse 15 ; au-dessus de 100, il meurt sans valeur. Le gain est massif mais borné — au plus K, l\'action ne descendant pas sous zéro (ch. 1).',
    commentaireEn: 'The right to sell at K pays the fall: stock at 85 against a 100 strike, the put pays 15; above 100, it dies worthless. The gain is large but bounded — at most K, since the stock cannot go below zero (ch. 1).',
  },
  {
    id: 'm8-f-03',
    moduleId: M8,
    nom: 'P&L d\'une position optionnelle',
    nomEn: 'Option position P&L',
    latex: '\\text{P\\&L} = \\text{sens} \\times (\\text{payoff} - \\text{prime})',
    commentaire: 'Sens = +1 acheteur, −1 vendeur : le P&L du vendeur est le miroir exact de celui de l\'acheteur — jeu à somme nulle, comme tout dérivé. Call 100 acheté 4, action à 103 : payoff 3, P&L = −1 — dans la monnaie, exercé, et pourtant perdant : finir ITM ne veut pas dire gagner (ch. 2).',
    commentaireEn: 'Sign = +1 buyer, −1 seller: the seller\'s P&L is the exact mirror of the buyer\'s — a zero-sum game, like any derivative. Call struck at 100 bought for 4, stock at 103: payoff 3, P&L = −1 — in the money, exercised, and yet losing: finishing ITM does not mean making money (ch. 2).',
  },
  {
    id: 'm8-f-04',
    moduleId: M8,
    nom: 'Point mort de l\'acheteur de call',
    nomEn: 'Call buyer\'s break-even',
    latex: '\\text{point mort}_{\\text{call}} = K + \\text{prime}',
    commentaire: 'Le seuil de profit n\'est pas le strike : 100 + 4 = 104. Trois zones : sous 100, perte de la prime entière ; entre 100 et 104, on exerce pour RÉDUIRE la perte ; au-delà de 104 seulement, le profit commence. « J\'exerce donc je gagne » est la faute classique d\'oral (ch. 2).',
    commentaireEn: 'The profit threshold is not the strike: 100 + 4 = 104. Three zones: below 100, the whole premium is lost; between 100 and 104, you exercise to REDUCE the loss; only beyond 104 does profit begin. "I exercise therefore I win" is the classic oral mistake (ch. 2).',
  },
  {
    id: 'm8-f-05',
    moduleId: M8,
    nom: 'Point mort de l\'acheteur de put',
    nomEn: 'Put buyer\'s break-even',
    latex: '\\text{point mort}_{\\text{put}} = K - \\text{prime}',
    commentaire: 'Le miroir baissier : le sous-jacent doit tomber SOUS le strike diminué de la prime pour que le pari paie. Au point mort, personne ne gagne ni ne perd — des deux côtés du contrat, acheteur comme vendeur (ch. 2).',
    commentaireEn: 'The bearish mirror: the underlying must fall BELOW the strike minus the premium for the bet to pay. At the break-even, nobody wins or loses — on either side of the contract, buyer and seller alike (ch. 2).',
  },
  {
    id: 'm8-f-06',
    moduleId: M8,
    nom: 'Points morts d\'un straddle acheté',
    nomEn: 'Long straddle break-evens',
    latex: '\\text{points morts} = K \\pm \\text{coût total}',
    commentaire: 'Call et put achetés au même strike : le pari porte sur l\'amplitude, pas la direction. Strike 100, coût 10 (call 6 + put 4) : points morts 90 et 110 — il faut sortir de la bande pour gagner ; pile au strike, les deux jambes meurent ensemble et la perte est totale : le calme plat est le pire ennemi (ch. 2).',
    commentaireEn: 'Call and put bought at the same strike: the bet is on magnitude, not direction. Strike 100, total cost 10 (call 6 + put 4): break-evens at 90 and 110 — the price must leave the band to win; exactly at the strike, both legs die together and the loss is total: a flat market is the worst enemy (ch. 2).',
  },
  {
    id: 'm8-f-07',
    moduleId: M8,
    nom: 'Parité call-put',
    nomEn: 'Put-call parity',
    latex: 'C - P = S - K\\,e^{-rT}',
    commentaire: 'Relation d\'ARBITRAGE, sans aucun modèle : call + placement de K·e^{−rT} et put + action paient tous deux max(S_T, K) partout, donc cotent pareil (européennes, sans dividende). Canonique : 10,4506 − 5,5735 = 4,8771 = 100 − 95,1229. Donne le put en une ligne, et impose Δcall − Δput = 1, gammas et vegas identiques (ch. 3).',
    commentaireEn: 'A pure ARBITRAGE relation, no model: call + deposit of K·e^{−rT} and put + stock both pay max(S_T, K) in every state, so they trade at the same price (European, no dividend). Canonical: 10.4506 − 5.5735 = 4.8771 = 100 − 95.1229. It delivers the put in one line, and forces Δcall − Δput = 1, identical gammas and vegas (ch. 3).',
  },
  {
    id: 'm8-f-08',
    moduleId: M8,
    nom: 'Probabilité risque-neutre (arbre à une période)',
    nomEn: 'Risk-neutral probability (one-period tree)',
    latex: 'q = \\frac{(1 + rT) - d}{u - d}',
    commentaire: 'Capitalisation linéaire sur la période. u = 1,2, d = 0,8, r = 4 % : q = (1,04 − 0,8)/0,4 = 0,6 — et ce n\'est PAS une prévision : sous q, l\'action actualisée redonne le spot (jeu équitable, martingale). Un poids d\'arbitrage déduit de u, d et r ; la vraie probabilité de hausse est inutile pour pricer (ch. 4).',
    commentaireEn: 'Linear compounding over the period. u = 1.2, d = 0.8, r = 4%: q = (1.04 − 0.8)/0.4 = 0.6 — and this is NOT a forecast: under q, the discounted stock gives back the spot (a fair game, a martingale). An arbitrage weight derived from u, d and r; the true probability of a rise is useless for pricing (ch. 4).',
  },
  {
    id: 'm8-f-09',
    moduleId: M8,
    nom: 'Valeur d\'un dérivé dans l\'arbre à une période',
    nomEn: 'Derivative value in the one-period tree',
    latex: 'V = \\frac{q\\,V_u + (1 - q)\\,V_d}{1 + rT}',
    commentaire: 'L\'espérance risque-neutre du payoff, actualisée — le coût exact de la réplication par Δ actions et un emprunt. Call 100 sur S = 100, u = 1,2, d = 0,8, r = 4 % : (0,6 × 20 + 0,4 × 0)/1,04 = 11,5385. La probabilité réelle de hausse ne figure nulle part : tout autre prix offrirait un arbitrage (ch. 4).',
    commentaireEn: 'The risk-neutral expectation of the payoff, discounted — the exact cost of replication with Δ shares and a loan. Call struck at 100 on S = 100, u = 1.2, d = 0.8, r = 4%: (0.6 × 20 + 0.4 × 0)/1.04 = 11.5385. The real probability of a rise appears nowhere: any other price would offer an arbitrage (ch. 4).',
  },
  {
    id: 'm8-f-10',
    moduleId: M8,
    nom: 'd1 de Black-Scholes',
    nomEn: 'Black-Scholes d1',
    latex: 'd_1 = \\frac{\\ln(S/K) + (r + \\sigma^2/2)\\,T}{\\sigma\\sqrt{T}}',
    commentaire: 'La « distance » du spot au strike en unités d\'écart-type, vue du monde risque-neutre. Canonique (S = 100, K = 100, r = 5 %, σ = 20 %, T = 1) : d1 = (0 + 0,07)/0,2 = 0,35. N(d1) sert deux fois : poids de l\'action dans la formule du prix, et delta du call (ch. 4).',
    commentaireEn: 'The "distance" from spot to strike in standard-deviation units, seen from the risk-neutral world. Canonical (S = 100, K = 100, r = 5%, σ = 20%, T = 1): d1 = (0 + 0.07)/0.2 = 0.35. N(d1) serves twice: the stock\'s weight in the price formula, and the call\'s delta (ch. 4).',
  },
  {
    id: 'm8-f-11',
    moduleId: M8,
    nom: 'd2 de Black-Scholes',
    nomEn: 'Black-Scholes d2',
    latex: 'd_2 = d_1 - \\sigma\\sqrt{T}',
    commentaire: 'Canonique : d2 = 0,35 − 0,2 = 0,15. N(d2) est la probabilité RISQUE-NEUTRE de finir dans la monnaie — 0,5596 ici : le poids q de l\'arbre devenu aire sous la cloche. d2 se lit comme un z-score : l\'avance du sous-jacent porté au taux sans risque sur le strike, en écarts-types σ√T (ch. 4).',
    commentaireEn: 'Canonical: d2 = 0.35 − 0.2 = 0.15. N(d2) is the RISK-NEUTRAL probability of finishing in the money — 0.5596 here: the tree\'s weight q turned into an area under the bell curve. d2 reads like a z-score: the lead of the underlying, grown at the risk-free rate, over the strike, in σ√T standard deviations (ch. 4).',
  },
  {
    id: 'm8-f-12',
    moduleId: M8,
    nom: 'Prix Black-Scholes d\'un call européen',
    nomEn: 'Black-Scholes price of a European call',
    latex: 'C = S\\,N(d_1) - K\\,e^{-rT}\\,N(d_2)',
    commentaire: 'La formule de 1973 se lit comme une facture : l\'action reçue si exercice (S·N(d1), espérance conditionnelle gonflée, d\'où N(d1) > N(d2)), moins le strike actualisé pondéré par la chance de le payer. Canonique : 100 × 0,6368 − 95,1229 × 0,5596 = 10,4506 ; Hull (42, 40, 10 %, 20 %, 0,5) : 4,7594 (ch. 4).',
    commentaireEn: 'The 1973 formula reads like an invoice: the stock received if exercised (S·N(d1), a conditional expectation inflated upward, hence N(d1) > N(d2)), minus the discounted strike weighted by the chance of paying it. Canonical: 100 × 0.6368 − 95.1229 × 0.5596 = 10.4506; Hull (42, 40, 10%, 20%, 0.5): 4.7594 (ch. 4).',
  },
  {
    id: 'm8-f-13',
    moduleId: M8,
    nom: 'Prix Black-Scholes d\'un put européen',
    nomEn: 'Black-Scholes price of a European put',
    latex: 'P = K\\,e^{-rT}\\,N(-d_2) - S\\,N(-d_1)',
    commentaire: 'Équivaut à la parité appliquée au call : P = C − S + K·e^{−rT} = 10,4506 − 100 + 95,1229 = 5,5735 sur le canonique — aucune nouvelle lecture de table. ATM, le put vaut MOINS que le call : le strike actualisé est sous le spot, le portage joue contre le droit de vendre (ch. 4).',
    commentaireEn: 'Equivalent to parity applied to the call: P = C − S + K·e^{−rT} = 10.4506 − 100 + 95.1229 = 5.5735 on the canonical example — no new table lookup. ATM, the put is worth LESS than the call: the discounted strike sits below the spot, carry works against the right to sell (ch. 4).',
  },
  {
    id: 'm8-f-14',
    moduleId: M8,
    nom: 'Delta du call et du put',
    nomEn: 'Call and put delta',
    latex: '\\Delta_{\\text{call}} = N(d_1) \\qquad \\Delta_{\\text{put}} = N(d_1) - 1',
    commentaire: 'La pente du prix, le ratio de couverture — et à peu près une probabilité d\'exercice (la vraie est N(d2), que N(d1) surestime). Canonique : 0,6368 et −0,3632 ; la parité impose Δcall − Δput = 1 exactement. Bornes : OTM profond → 0, ITM profond → ±1 ; ATM, un peu au-dessus de 0,5 pour le call (ch. 5).',
    commentaireEn: 'The price\'s slope, the hedge ratio — and roughly a probability of exercise (the true one is N(d2), which N(d1) overstates). Canonical: 0.6368 and −0.3632; parity forces Δcall − Δput = 1 exactly. Bounds: deep OTM → 0, deep ITM → ±1; ATM, slightly above 0.5 for the call (ch. 5).',
  },
  {
    id: 'm8-f-15',
    moduleId: M8,
    nom: 'Gamma (identique call et put)',
    nomEn: 'Gamma (identical for call and put)',
    latex: '\\Gamma = \\frac{\\varphi(d_1)}{S\\,\\sigma\\sqrt{T}}',
    commentaire: 'La convexité : de combien bouge le delta quand l\'action bouge de 1 — 0,018762 sur le canonique. Maximal à la monnaie et explosif près de l\'échéance (0,019 à un an, 0,20 à quelques jours). Positif pour le détenteur ; le vendeur delta-hedgé paie ≈ ½Γ(ΔS)² par trajet — il achète après la hausse, vend après la baisse (ch. 5).',
    commentaireEn: 'Convexity: how much the delta moves when the stock moves by 1 — 0.018762 on the canonical example. Greatest at the money and explosive near expiry (0.019 at one year, 0.20 with days left). Positive for the holder; the delta-hedged seller pays ≈ ½Γ(ΔS)² per round trip — buying after the rise, selling after the fall (ch. 5).',
  },
  {
    id: 'm8-f-16',
    moduleId: M8,
    nom: 'Vega, par point de volatilité (identique call et put)',
    nomEn: 'Vega, per volatility point (identical for call and put)',
    latex: '\\mathcal{V} = \\frac{S\\,\\varphi(d_1)\\,\\sqrt{T}}{100}',
    commentaire: 'La convention des desks : la variation de prime quand σ gagne UN point. Canonique : 0,3752 — σ passe de 20 % à 21 %, le call passe de 10,4506 à 10,8263. Maximal ATM et croissant avec la maturité : les options courtes sont des affaires de gamma, les longues de vega — et mesurer la sensibilité à un paramètre censé constant est l\'aveu chiffré que le modèle se sait faux (ch. 5).',
    commentaireEn: 'The desk convention: the premium change when σ gains ONE point. Canonical: 0.3752 — σ moves from 20% to 21%, the call goes from 10.4506 to 10.8263. Greatest ATM and increasing with maturity: short-dated options are gamma instruments, long-dated ones vega instruments — and measuring sensitivity to a parameter assumed constant is the model\'s quantified confession that it knows itself wrong (ch. 5).',
  },
  {
    id: 'm8-f-17',
    moduleId: M8,
    nom: 'Annualisation de la volatilité',
    nomEn: 'Annualising volatility',
    latex: '\\sigma_{\\text{an}} = \\sigma_{\\text{jour}} \\times \\sqrt{252}',
    commentaire: 'Les variances s\'additionnent dans le temps, donc l\'écart-type croît comme la racine du temps : 1,2 % par jour × 15,8745 = 19,05 % par an. Multiplier par 252 est l\'erreur d\'unité classique. Règle de tête du desk : √252 ≈ 16, donc 1 % par jour ≈ 16 % par an (ch. 6).',
    commentaireEn: 'Variances add over time, so the standard deviation grows like the square root of time: 1.2% per day × 15.8745 = 19.05% per year. Multiplying by 252 is the classic unit error. Desk rule of thumb: √252 ≈ 16, so 1% per day ≈ 16% per year (ch. 6).',
  },
  {
    id: 'm8-f-18',
    moduleId: M8,
    nom: 'Volatilité implicite (définition)',
    nomEn: 'Implied volatility (definition)',
    latex: '\\sigma_{\\text{imp}} \\ \\text{tel que}\\ C_{BS}(S, K, r, \\sigma_{\\text{imp}}, T) = \\text{prime cotée}',
    commentaire: 'Black-Scholes retourné : puisque le prix s\'observe, on en extrait le σ que le marché y a logé. Unique car le prix croît strictement avec σ (vega > 0) — on encadre par dichotomie : le canonique à 10,4506 rend 20 %. Les desks cotent en vol comme les obligations se cotent en rendement — et l\'implicite dépasse en moyenne la réalisée : le prix de l\'assurance (ch. 6).',
    commentaireEn: 'Black-Scholes turned inside out: since the price is observable, one extracts the σ the market put into it. Unique because the price is strictly increasing in σ (vega > 0) — bracket by bisection: the canonical 10.4506 yields 20%. Desks quote in vol the way bonds are quoted in yield — and implied exceeds subsequently realised on average: the price of insurance (ch. 6).',
  },
];
