import type { Flashcard } from '../../../engine/types';

const M13 = '13-brainteasers-oral';

// 120 cartes : 30 definitions, 30 reflexes jury, 30 calculs mentaux (LE module
// du calcul mental : quota renforce), 20 ordres de grandeur, 10 pieges.
// Couverture : ch1 le calcul mental, ch2 les estimations de Fermi, ch3 les
// probabilites d'entretien, ch4 les brainteasers classiques, ch5 les jeux de
// marche, ch6 defendre son parcours, ch7 le jour J.
export const flashcards: Flashcard[] = [
  // ───────────────────────── Chapitre 1 — Le calcul mental ─────────────────────────
  {
    id: 'm13-fc-001',
    moduleId: M13,
    tags: ['definition', 'calcul-mental'],
    recto: 'La règle de 72 : énoncé, pourquoi 72 et non 69,3, et son domaine de validité ?',
    verso: 'Un capital placé au taux composé annuel de t % double en environ 72/t années. Pourquoi 72 : la constante « exacte » serait 100 × ln 2 ≈ 69,3, mais 72 se divise par 2, 3, 4, 6, 8, 9 et 12 — et l\'écart compense la discrétisation annuelle autour de 8 %, là où la règle a été calibrée. Domaine : quasi exacte vers 8 % (erreur −0,07 %), sous 2 % d\'erreur entre 4 et 12 %, jamais plus de 3,5 % sur la plage 1-15 % ; elle SURESTIME aux taux bas, sous-estime aux taux élevés. L\'ancrage : le modèle réduit de toutes les approximations du cours — un outil, un domaine de validité, une erreur connue (duration m4, delta m8, VaR paramétrique m12 obéissent au même contrat).',
    rectoEn: 'The rule of 72: statement, why 72 and not 69.3, and its domain of validity?',
    versoEn: 'A capital compounding at t% per year doubles in roughly 72/t years. Why 72: the "exact" constant would be 100 × ln 2 ≈ 69.3, but 72 divides by 2, 3, 4, 6, 8, 9 and 12 — and the gap offsets the annual discretisation around 8%, where the rule was calibrated. Domain: near-exact around 8% (error −0.07%), under 2% error between roughly 4 and 12%, never above 3.5% over the 1-15% range; it OVERSTATES at low rates, understates at high rates. The anchor: the scale model of every approximation in this course — one tool, one domain of validity, one known error (m4 duration, m8 delta, m12 parametric VaR obey the same contract).',
  },
  {
    id: 'm13-fc-002',
    moduleId: M13,
    tags: ['definition', 'calcul-mental'],
    recto: 'Les quatre gestes que le jury regarde dans tout calcul mental d\'entretien ?',
    verso: '1) DÉCOMPOSER : ramener le calcul à des briques connues (×25 = ×100 puis ÷4). 2) ARRONDIR proprement : remplacer un nombre hostile par un voisin ami, en retenant le sens de l\'écart. 3) BORNER : encadrer le résultat AVANT de le chercher — l\'assurance anti-énormité. 4) ANNONCER L\'ERREUR : dire de combien l\'approximation se trompe, et dans quel sens. L\'ancrage : personne ne recrute un trader pour sa virtuosité arithmétique — les machines calculent mieux et ne demandent pas de bonus ; le quatrième geste est le plus rare et le plus payant, celui qui transforme « je sais calculer » en « on peut me confier un book ».',
    rectoEn: 'The four moves the panel watches in any interview mental arithmetic?',
    versoEn: '1) DECOMPOSE: reduce the calculation to known bricks (×25 = ×100 then ÷4). 2) ROUND cleanly: replace a hostile number with a friendly neighbour, remembering the direction of the gap. 3) BOUND: bracket the result BEFORE computing it — the insurance against absurdities. 4) STATE THE ERROR: say by how much the approximation is off, and in which direction. The anchor: nobody hires a trader for arithmetic virtuosity — machines compute better and never ask for a bonus; the fourth move is the rarest and best paid, the one that turns "I can calculate" into "this person can run a book".',
  },
  {
    id: 'm13-fc-003',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'De tête : temps de doublement à 8 %, 6 %, 4 % et 2 % — avec le commentaire qui accompagne chaque chiffre ?',
    verso: 'La méthode : diviser 72 par le taux. 8 % ⇒ 9 ans (quasi exact : 9,006, erreur −0,07 %) ; 6 % ⇒ 12 ans ; 4 % ⇒ 18 ans ; 2 % ⇒ 36 ans — contre 35,0 exacts : aux taux bas, la règle SURESTIME d\'environ un an, et le dire fait partie de la réponse. Le geste complet : annoncer le chiffre, puis sa limite. L\'ancrage : à 2 % d\'inflation, les prix doublent « tous les 35 ans environ » — l\'ancre du m10 ; et la zone douce de la règle (vers 8 %) coïncide avec les rendements actions de long terme : « votre portefeuille double en combien de temps ? » se règle en une division.',
    rectoEn: 'From the top of your head: doubling time at 8%, 6%, 4% and 2% — with the comment that goes with each figure?',
    versoEn: 'The method: divide 72 by the rate. 8% ⇒ 9 years (near exact: 9.006, error −0.07%); 6% ⇒ 12 years; 4% ⇒ 18 years; 2% ⇒ 36 years — against 35.0 exact: at low rates the rule OVERSTATES by about a year, and saying so is part of the answer. The full move: state the figure, then its limit. The anchor: at 2% inflation, prices double "roughly every 35 years" — the m10 anchor; and the rule\'s sweet spot (around 8%) coincides with long-run equity returns: "how long for your portfolio to double?" is settled with one division.',
  },
  {
    id: 'm13-fc-004',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: '17 × 24, à la façon du desk : les deux gestes, dans l\'ordre ?',
    verso: 'Geste 1 — BORNER : entre 10 × 20 = 200 et 20 × 25 = 500 ; trois secondes, plus aucune énormité possible. Geste 2 — DÉCOMPOSER vers le voisin ami : 17 × 24 = 17 × 25 − 17 = 425 − 17 = 408 (multiplier par 25, c\'est multiplier par 100 et diviser par 4). Autre chemin, même résultat : 17 × 4 × 6 = 68 × 6 = 408. L\'ancrage : il n\'y a jamais un seul bon chemin, seulement des briques (×25, ×4, ×11, les doublements) qu\'on assemble — et le candidat qui annonce « environ 400, entre 200 et 500 à coup sûr » puis affine vers 408 bat celui qui reste muet dix secondes et lâche 408 sans filet.',
    rectoEn: '17 × 24, desk-style: the two moves, in order?',
    versoEn: 'Move 1 — BOUND: between 10 × 20 = 200 and 20 × 25 = 500; three seconds, and no absurdity is possible any more. Move 2 — DECOMPOSE towards the friendly neighbour: 17 × 24 = 17 × 25 − 17 = 425 − 17 = 408 (multiplying by 25 is multiplying by 100 and dividing by 4). Another path, same result: 17 × 4 × 6 = 68 × 6 = 408. The anchor: there is never one right path, only bricks (×25, ×4, ×11, doublings) to assemble — and the candidate who says "about 400, between 200 and 500 for sure" then refines to 408 beats the one who stays silent for ten seconds and drops 408 without a net.',
  },
  {
    id: 'm13-fc-005',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'De tête, en entretien : 8 % de 25 ?',
    verso: '2 — par COMMUTATIVITÉ : x % de y = y % de x, toujours (les deux s\'écrivent x × y/100). « 8 % de 25 » fige beaucoup de candidats ; « 25 % de 8 » — le quart de 8 — n\'en fige aucun. La méthode : retourner systématiquement le pourcentage dans le sens où l\'un des deux nombres devient une fraction simple (25 % = le quart, 50 % = la moitié, 10 % = le dixième). Même famille : 4 % de 75 = 75 % de 4 = 3. L\'ancrage : le calcul hostile n\'existe presque jamais — il n\'y a que des calculs pas encore retournés.',
    rectoEn: 'From the top of your head, in an interview: 8% of 25?',
    versoEn: '2 — by COMMUTATIVITY: x% of y = y% of x, always (both read x × y/100). "8% of 25" freezes many candidates; "25% of 8" — a quarter of 8 — freezes none. The method: systematically flip the percentage so that one of the two numbers becomes a simple fraction (25% = a quarter, 50% = a half, 10% = a tenth). Same family: 4% of 75 = 75% of 4 = 3. The anchor: the hostile calculation barely exists — there are only calculations not yet flipped.',
  },
  {
    id: 'm13-fc-006',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: '47² et 53² en trois secondes chacun : l\'identité des carrés proches de 50 ?',
    verso: '(50 ± a)² = 2 500 ± 100a + a². Donc 47² se lit « 25 − 3 = 22 centaines, plus 3² » : 2 209 ; et 53² = « 25 + 3 = 28 centaines, plus 9 » : 2 809. Deux gestes : compter les centaines (25 ± a), ajouter le petit carré. L\'ancrage : l\'effet sur un jury est disproportionné par rapport à l\'effort d\'apprentissage — c\'est du rendement pur ; la même logique donne les carrés proches de 100.',
    rectoEn: '47² and 53² in three seconds each: the identity for squares near 50?',
    versoEn: '(50 ± a)² = 2,500 ± 100a + a². So 47² reads "25 − 3 = 22 hundreds, plus 3²": 2,209; and 53² = "25 + 3 = 28 hundreds, plus 9": 2,809. Two moves: count the hundreds (25 ± a), add the small square. The anchor: the effect on a panel is out of all proportion to the learning effort — pure yield; the same logic gives squares near 100.',
  },
  {
    id: 'm13-fc-007',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: '96² de tête : l\'identité des carrés proches de 100 ?',
    verso: '(100 − a)² = 100 × (100 − 2a) + a². Donc 96² = « 100 − 8 = 92 centaines, plus 16 » : 9 216. La méthode en deux gestes : retrancher DEUX fois l\'écart pour les centaines (100 − 2a), puis ajouter le carré de l\'écart. Vérification par la borne : 96² doit vivre juste sous 100² = 10 000 — 9 216 est plausible. L\'ancrage : le miroir de la formule des carrés proches de 50 — deux identités, trois secondes chacune, tout le bestiaire des carrés d\'entretien est couvert.',
    rectoEn: '96² in your head: the identity for squares near 100?',
    versoEn: '(100 − a)² = 100 × (100 − 2a) + a². So 96² = "100 − 8 = 92 hundreds, plus 16": 9,216. The method in two moves: subtract the gap TWICE for the hundreds (100 − 2a), then add the square of the gap. Bound check: 96² must live just under 100² = 10,000 — 9,216 is plausible. The anchor: the mirror of the near-50 formula — two identities, three seconds each, and the whole interview bestiary of squares is covered.',
  },
  {
    id: 'm13-fc-008',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'Retrouver un notionnel avant une décote de 20 % : que vaut 100/0,8 — et la famille de réflexes derrière ?',
    verso: '125 — car diviser par 0,8, c\'est multiplier par 1,25 (1/0,8 = 5/4). La famille complète : diviser par 0,5 = multiplier par 2 ; diviser par 0,25 = multiplier par 4 ; diviser par 0,75 = multiplier par 4/3. La méthode : convertir toute division hostile en multiplication amicale via la fraction inverse. L\'ancrage : « après une décote de 20 %, il reste 80 % — pour remonter au montant initial, ×1,25 » ; c\'est le même réflexe qui rend la LGD maniable (diviser par 0,6 = multiplier par 5/3, m5).',
    rectoEn: 'Recovering a notional before a 20% haircut: what is 100/0.8 — and the family of reflexes behind it?',
    versoEn: '125 — because dividing by 0.8 is multiplying by 1.25 (1/0.8 = 5/4). The full family: dividing by 0.5 = multiplying by 2; by 0.25 = multiplying by 4; by 0.75 = multiplying by 4/3. The method: convert any hostile division into a friendly multiplication via the inverse fraction. The anchor: "after a 20% haircut, 80% remains — to get back to the initial amount, ×1.25"; the same reflex makes LGD tractable (dividing by 0.6 = multiplying by 5/3, m5).',
  },
  {
    id: 'm13-fc-009',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: '+10 % puis −10 % : retour au point de départ ?',
    verso: 'Non : 1,1 × 0,9 = 0,99, soit −1 % — les variations successives se MULTIPLIENT, elles ne s\'additionnent jamais. La méthode : convertir chaque variation en facteur (1 + x) et multiplier les facteurs ; l\'ordre est indifférent, le résultat est toujours sous le point de départ (l\'écart croît comme x²). L\'ancrage : la version douce d\'une leçon que le m11 a payée au prix fort — après −78 % (Nasdaq 2000-2002), il faut +354,5 % et quinze ans pour revenir.',
    rectoEn: '+10% then −10%: back to the starting point?',
    versoEn: 'No: 1.1 × 0.9 = 0.99, i.e. −1% — successive changes MULTIPLY, they never add. The method: turn each change into a factor (1 + x) and multiply the factors; order is irrelevant, and the result always sits below the start (the gap grows like x²). The anchor: the mild version of a lesson m11 paid dearly for — after −78% (Nasdaq 2000-2002), it takes +354.5% and fifteen years to get back.',
  },
  {
    id: 'm13-fc-010',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'Après une perte de 50 %, quel gain faut-il pour revenir au point de départ — et la formule générale ?',
    verso: '+100 % : il faut DOUBLER ce qui reste. Formule générale : après une perte de p, le gain requis est p/(1 − p) — après −20 %, +25 % ; après −50 %, +100 % ; après −90 %, +900 %. La méthode : raisonner sur ce qui RESTE (0,5 doit redevenir 1), jamais sur ce qui a été perdu. L\'ancrage : l\'asymétrie des rendements composés — la raison profonde pour laquelle on ne mise jamais tout (Kelly, ch5) et pour laquelle la gestion du risque du m12 borne les pertes avant de chercher les gains.',
    rectoEn: 'After a 50% loss, what gain brings you back to the start — and the general formula?',
    versoEn: '+100%: you must DOUBLE what remains. General formula: after a loss of p, the required gain is p/(1 − p) — after −20%, +25%; after −50%, +100%; after −90%, +900%. The method: reason on what REMAINS (0.5 must become 1 again), never on what was lost. The anchor: the asymmetry of compounded returns — the deep reason you never bet everything (Kelly, ch5) and why m12 risk management caps losses before chasing gains.',
  },
  {
    id: 'm13-fc-011',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'Le jury lâche « le spread s\'écarte de 50 pb » : conversion immédiate — et 300 pb, et 25 pb ?',
    verso: '100 pb = 1 %, donc 50 pb = 0,5 %, 300 pb = 3 %, 25 pb = 0,25 %. La méthode : décaler la virgule de deux rangs, sans respirer — c\'est une conversion d\'unité, pas un calcul. L\'ancrage : le point de base est la langue maternelle des m4 et m5 ; le jury qui parle en pb attend la conversion instantanée, et le candidat qui hésite sur 50 pb a déjà signalé qu\'il n\'a jamais lu un écran de spreads.',
    rectoEn: 'The panel drops "the spread widens by 50 bp": instant conversion — and 300 bp, and 25 bp?',
    versoEn: '100 bp = 1%, so 50 bp = 0.5%, 300 bp = 3%, 25 bp = 0.25%. The method: shift the decimal point two places, without breathing — it is a unit conversion, not a calculation. The anchor: the basis point is the mother tongue of m4 and m5; a panel speaking in bp expects instant conversion, and the candidate who hesitates on 50 bp has already signalled he has never read a spread screen.',
  },
  {
    id: 'm13-fc-012',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'Enchaînement complet : « une obligation cote 300 pb, recouvrement 40 % — quelle PD le marché price-t-il ? »',
    verso: 'Trois réflexes en dix secondes : 1) CONVERTIR — 300 pb = 3 % ; 2) l\'ANCRE du m5 — PD implicite = spread/LGD, avec LGD = 100 − R = 60 % ; 3) la DIVISION DÉGUISÉE — diviser par 0,6, c\'est multiplier par 5/3 : 3 × 5/3 = 5 % par an. L\'ancrage : c\'est exactement l\'assemblage que le module entraîne — trois briques de calcul, une ancre de cours, zéro calculatrice ; et le garde-fou : une PD à deux chiffres sur de l\'IG signale un facteur perdu en route.',
    rectoEn: 'Full chain: "a bond trades at 300 bp, recovery 40% — what PD is the market pricing?"',
    versoEn: 'Three reflexes in ten seconds: 1) CONVERT — 300 bp = 3%; 2) the m5 ANCHOR — implied PD = spread/LGD, with LGD = 100 − R = 60%; 3) the DISGUISED DIVISION — dividing by 0.6 is multiplying by 5/3: 3 × 5/3 = 5% per year. The anchor: exactly the assembly this module trains — three calculation bricks, one course anchor, zero calculator; and the guardrail: a double-digit PD on IG paper signals a factor lost along the way.',
  },
  {
    id: 'm13-fc-013',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'De tête : la VaR 95 % à un jour d\'un portefeuille de 100 M€ à 20 % de volatilité annuelle ?',
    verso: '≈ 2,1 M€. La méthode en trois gestes : 1) vol annuelle → vol quotidienne : diviser par √252 ≈ 16, soit 20 %/16 = 1,25 % ; 2) multiplier par le quantile 95 % : 1,65 × 1,25 % ≈ 2,1 % ; 3) appliquer au notionnel : 2,1 % de 100 M€ = 2,1 M€. L\'ancrage : l\'ancre du m12 à réciter — « au-delà, on est dans la queue » ; et √252 ≈ 16 est LA constante de conversion à connaître (la racine du temps).',
    rectoEn: 'In your head: the 1-day 95% VaR of a €100m portfolio at 20% annual volatility?',
    versoEn: '≈ €2.1m. The method in three moves: 1) annual vol → daily vol: divide by √252 ≈ 16, so 20%/16 = 1.25%; 2) multiply by the 95% quantile: 1.65 × 1.25% ≈ 2.1%; 3) apply to the notional: 2.1% of €100m = €2.1m. The anchor: the m12 anchor to recite — "beyond that, you are in the tail"; and √252 ≈ 16 is THE conversion constant to know (the square root of time).',
  },
  {
    id: 'm13-fc-014',
    moduleId: M13,
    tags: ['calcul-mental', 'calcul-mental'],
    recto: 'À 8 % par an, combien d\'années pour QUADRUPLER un capital ?',
    verso: '18 ans : quadrupler, c\'est doubler deux fois — la règle de 72 donne 9 ans par doublement, donc 2 × 9 = 18. La méthode : décomposer tout multiple en doublements (×4 = deux doublements, ×8 = trois) et empiler les 72/t. Généralisation : ×8 à 8 % ≈ 27 ans. L\'ancrage : la règle de 72 se COMPOSE — c\'est ce qui la rend plus puissante qu\'elle n\'en a l\'air ; même geste que les intérêts composés du m2 : les facteurs se multiplient, les durées s\'additionnent.',
    rectoEn: 'At 8% per year, how many years to QUADRUPLE a capital?',
    versoEn: '18 years: quadrupling is doubling twice — the rule of 72 gives 9 years per doubling, so 2 × 9 = 18. The method: decompose any multiple into doublings (×4 = two doublings, ×8 = three) and stack the 72/t. Generalisation: ×8 at 8% ≈ 27 years. The anchor: the rule of 72 COMPOUNDS — which makes it more powerful than it looks; same move as m2 compound interest: factors multiply, durations add.',
  },
  {
    id: 'm13-fc-015',
    moduleId: M13,
    tags: ['ordre-de-grandeur', 'calcul-mental'],
    recto: 'ln 2 : la valeur à connaître — et ce qu\'elle explique ?',
    verso: 'ln 2 ≈ 0,693. C\'est elle qui fabrique la règle de 72 : en composition continue, le doublement demande ln 2/taux, soit « 69,3/t » — arrondi à 72 parce que 72 se divise par 2, 3, 4, 6, 8, 9 et 12, et que l\'écart compense la composition annuelle autour de 8 %. L\'ancrage : connaître 0,693 permet la technique du niveau au-dessus (ch7) — le candidat qui a oublié « 72 » mais retrouve « environ 70 divisé par le taux » en le raisonnant vaut PLUS que celui qui récite 72 sans savoir d\'où il vient.',
    rectoEn: 'ln 2: the value to know — and what it explains?',
    versoEn: 'ln 2 ≈ 0.693. It is what manufactures the rule of 72: under continuous compounding, doubling takes ln 2/rate, i.e. "69.3/t" — rounded to 72 because 72 divides by 2, 3, 4, 6, 8, 9 and 12, and the gap offsets annual compounding around 8%. The anchor: knowing 0.693 enables the level-above technique (ch7) — the candidate who forgot "72" but reconstructs "about 70 divided by the rate" by reasoning is worth MORE than the one who recites 72 without knowing where it comes from.',
  },
  {
    id: 'm13-fc-016',
    moduleId: M13,
    tags: ['ordre-de-grandeur', 'calcul-mental'],
    recto: 'Le doublement à 8 % : la valeur exacte derrière le « 9 ans » de la règle de 72 ?',
    verso: '9,006468 ans (ln 2/ln 1,08), contre 9 annoncés : erreur de −0,07 %, indétectable à l\'oral — c\'est LE point de calibrage de la règle. À réciter avec l\'erreur : « 9 ans, quasi exact à ce niveau de taux ; 9,006 si vous voulez la décimale ». L\'ancrage : donner l\'estimation PUIS l\'erreur est le réflexe qui distingue le candidat — montrer qu\'on connaît l\'outil ET sa tolérance, le contrat de toute approximation du cours.',
    rectoEn: 'Doubling at 8%: the exact value behind the rule of 72\'s "9 years"?',
    versoEn: '9.006468 years (ln 2/ln 1.08), against 9 announced: a −0.07% error, undetectable orally — THE calibration point of the rule. Recite it with its error: "9 years, near exact at this rate level; 9.006 if you want the decimal". The anchor: giving the estimate THEN the error is the reflex that sets a candidate apart — showing you know the tool AND its tolerance, the contract of every approximation in the course.',
  },
  {
    id: 'm13-fc-017',
    moduleId: M13,
    tags: ['ordre-de-grandeur', 'calcul-mental'],
    recto: 'Le doublement à 2 % : règle de 72 contre valeur exacte ?',
    verso: '72/2 = 36 ans annoncés, contre 35,002789 exacts (ln 2/ln 1,02) : la règle SURESTIME d\'environ un an aux taux bas (erreur +2,8 %) — et le mentionner fait partie de la réponse. Le domaine complet : quasi exacte vers 8 %, sous 2 % d\'erreur entre 4 et 12 %, jamais plus de 3,5 % sur 1-15 %. L\'ancrage : c\'est l\'ancre croisée du m10 — la promesse des 2 % d\'inflation signifie des prix qui doublent tous les 35 ans environ.',
    rectoEn: 'Doubling at 2%: rule of 72 versus exact value?',
    versoEn: '72/2 = 36 years announced, against 35.002789 exact (ln 2/ln 1.02): the rule OVERSTATES by about a year at low rates (+2.8% error) — and mentioning it is part of the answer. The full domain: near exact around 8%, under 2% error between 4 and 12%, never above 3.5% over 1-15%. The anchor: it is the m10 cross-anchor — the 2% inflation promise means prices that double roughly every 35 years.',
  },
  {
    id: 'm13-fc-018',
    moduleId: M13,
    tags: ['ordre-de-grandeur', 'calcul-mental'],
    recto: 'Le chargeur d\'ancres croisées : les repères des douze modules à réciter en entretien ?',
    verso: 'Changes : ~7 500 Md$ par jour (BRI 2022, m6). Spread corporate IG euro : 80-150 pb, HY 300-500 pb (m5). Recouvrement senior unsecured : R ≈ 40 % — convention, pas une loi (m5). Prime de risque actions : 4-6 % par an sur longue période (m12). VaR 95 % à 1 jour, 100 M€ à 20 % de vol : ≈ 2,1 M€ (m12). Après −50 % : +100 % pour revenir (m11). Doublement : 9 ans à 8 %, 36 ans à 2 %. L\'ancrage : ces repères sont doublement utiles — réponses directes ET garde-fous : si votre calcul sort une PD de 45 % sur de l\'IG, une ancre vous dit qu\'un facteur s\'est perdu ; l\'erreur détectée par vous vaut des points, la même détectée par le jury en coûte le double.',
    rectoEn: 'The cross-anchor magazine: the twelve modules\' reference figures to recite in an interview?',
    versoEn: 'FX: ~$7,500bn a day (BIS 2022, m6). Euro IG corporate spread: 80-150 bp, HY 300-500 bp (m5). Senior unsecured recovery: R ≈ 40% — a convention, not a law (m5). Equity risk premium: 4-6% a year over the long run (m12). 1-day 95% VaR, €100m at 20% vol: ≈ €2.1m (m12). After −50%: +100% to get back (m11). Doubling: 9 years at 8%, 36 years at 2%. The anchor: these anchors are doubly useful — direct answers AND guardrails: if your calculation spits out a 45% PD on IG paper, an anchor tells you a factor got lost; the error you catch earns points, the same error caught by the panel costs double.',
  },
  {
    id: 'm13-fc-019',
    moduleId: M13,
    tags: ['reflexe-jury', 'calcul-mental'],
    recto: 'Le jury lance un calcul : votre tout premier geste, avant même de chercher le résultat ?',
    verso: 'Réflexe : BORNER — encadrer le résultat par un minorant et un majorant grossiers (17 × 24 : entre 10 × 20 = 200 et 20 × 25 = 500). Trois secondes qui achètent deux choses : l\'assurance anti-énormité (aucune réponse absurde ne peut plus sortir) et un premier chiffre à annoncer immédiatement — « entre 200 et 500, je précise ». L\'ancrage : produire un chiffre utilisable MAINTENANT avec une barre d\'erreur, plutôt qu\'un chiffre parfait trop tard — c\'est exactement ce qu\'on fait sur un desk, et c\'est ce que le jury regarde.',
    rectoEn: 'The panel throws you a calculation: your very first move, before even looking for the result?',
    versoEn: 'Reflex: BOUND — bracket the result with a rough floor and ceiling (17 × 24: between 10 × 20 = 200 and 20 × 25 = 500). Three seconds that buy two things: insurance against absurdities (no ridiculous answer can escape any more) and a first figure to announce immediately — "between 200 and 500, refining now". The anchor: produce a usable figure NOW with an error bar, rather than a perfect figure too late — exactly what a desk does, and exactly what the panel watches.',
  },
  {
    id: 'm13-fc-020',
    moduleId: M13,
    tags: ['reflexe-jury', 'calcul-mental'],
    recto: 'Le méta-réflexe de toute estimation devant le jury : dans quel ordre livrer ?',
    verso: 'Réflexe : ANNONCER, puis BORNER, puis RAFFINER. « Environ 9 ans — règle de 72, quasi exacte à ce niveau de taux — 9,006 si vous voulez la décimale. » Trois temps, dix secondes : un outil maîtrisé, une lucidité sur ses limites, une précision disponible à la demande mais jamais imposée. L\'ordre inverse — chercher la décimale d\'abord — est l\'erreur du premier de la classe : elle coûte du temps, du silence, et prouve seulement qu\'on ne hiérarchise pas. L\'ancrage : l\'estimation PUIS l\'erreur — le quatrième geste, celui qui recrute ; et il ne s\'installe qu\'à voix haute, en s\'entraînant à verbaliser borne, décomposition et erreur.',
    rectoEn: 'The meta-reflex of any estimate in front of the panel: in what order to deliver?',
    versoEn: 'Reflex: ANNOUNCE, then BOUND, then REFINE. "About 9 years — rule of 72, near exact at this rate level — 9.006 if you want the decimal." Three beats, ten seconds: a mastered tool, lucidity about its limits, precision available on demand but never imposed. The reverse order — hunting the decimal first — is the top-of-the-class mistake: it costs time, silence, and only proves you cannot prioritise. The anchor: the estimate THEN the error — the fourth move, the one that gets hired; and it only settles by training out loud, verbalising bound, decomposition and error.',
  },
  {
    id: 'm13-fc-021',
    moduleId: M13,
    tags: ['reflexe-jury', 'calcul-mental'],
    recto: 'Votre calcul de PD implicite sort 45 % sur un émetteur investment grade. Que faites-vous ?',
    verso: 'Réflexe : le GARDE-FOU des ancres — avant d\'annoncer, confronter tout résultat aux repères du cours. Une PD IG vit vers 0,1-0,5 % par an (m5) : 45 % signale un facteur perdu en route (pb non convertis, LGD oubliée, division inversée). Corriger à voix haute : « ce chiffre est incompatible avec un spread IG de 80-150 pb — je reprends ». L\'ancrage : l\'erreur détectée par VOUS avant le jury vaut des points ; la même erreur détectée par le jury en coûte le double — les ancres ne servent pas qu\'à répondre, elles servent à se surveiller.',
    rectoEn: 'Your implied-PD calculation spits out 45% on an investment grade issuer. What do you do?',
    versoEn: 'Reflex: the anchor GUARDRAIL — before announcing, check any result against the course\'s reference figures. An IG PD lives around 0.1-0.5% a year (m5): 45% signals a factor lost on the way (bp not converted, LGD forgotten, inverted division). Correct out loud: "this figure is incompatible with an IG spread of 80-150 bp — let me redo it". The anchor: the error YOU catch before the panel earns points; the same error caught by the panel costs double — anchors are not just for answering, they are for self-monitoring.',
  },
  // ───────────────────────── Chapitre 2 — Les estimations de Fermi ─────────────────────────
  {
    id: 'm13-fc-022',
    moduleId: M13,
    tags: ['definition', 'fermi'],
    recto: 'L\'estimation de Fermi : définition et protocole en cinq temps ?',
    verso: 'Produire l\'ORDRE DE GRANDEUR d\'une quantité inconnue en la décomposant en facteurs dont chacun peut être encadré par des bornes sûres. Les cinq temps : 1) reformuler et fixer l\'UNITÉ (par jour ou par an ?) ; 2) DÉCOMPOSER en facteurs ; 3) ENCADRER chaque facteur par deux bornes dont on est sûr ; 4) prendre la moyenne GÉOMÉTRIQUE des bornes, √(b × h) — jamais l\'arithmétique ; 5) ANNONCER l\'ordre de grandeur et le facteur d\'incertitude (« quelques dizaines, à un facteur 3 près »). L\'ancrage : Fermi à Trinity, 1945 — des confettis déplacés de 2,5 m, une puissance estimée à ~10 kilotonnes, la mesure officielle dira ~20 : un facteur 2 sur une bombe atomique, avec trois bouts de papier ; la question ne demande AUCUNE connaissance et rend TOUT le raisonnement visible.',
    rectoEn: 'The Fermi estimate: definition and five-step protocol?',
    versoEn: 'Produce the ORDER OF MAGNITUDE of an unknown quantity by decomposing it into factors each of which can be bracketed by safe bounds. The five steps: 1) rephrase and fix the UNIT (per day or per year?); 2) DECOMPOSE into factors; 3) BRACKET each factor with two bounds you are sure of; 4) take the GEOMETRIC mean of the bounds, √(b × h) — never the arithmetic one; 5) ANNOUNCE the order of magnitude and the uncertainty factor ("a few dozen, to within a factor of 3"). The anchor: Fermi at Trinity, 1945 — confetti displaced 2.5 m, an estimated yield of ~10 kilotons, the official measurement would say ~20: a factor of 2 on an atomic bomb, with three scraps of paper; the question requires NO knowledge and makes ALL the reasoning visible.',
  },
  {
    id: 'm13-fc-023',
    moduleId: M13,
    tags: ['definition', 'fermi'],
    recto: 'La moyenne géométrique : définition, et pourquoi c\'est LE milieu des ordres de grandeur ?',
    verso: '√(b × h) : le milieu MULTIPLICATIF de deux bornes — au même facteur des deux (entre 1 000 et 1 000 000, √ = 31 623, à un facteur ~32 de chaque borne). Pourquoi elle : l\'incertitude d\'ordre de grandeur est multiplicative (« un facteur 10 dans les deux sens ») ; en logarithme, elle devient additive et symétrique, et la moyenne arithmétique des logs, repassée à l\'exponentielle, est précisément la moyenne géométrique. L\'ancrage : la même mathématique fait du produit de facteurs aléatoires une lognormale (m2) et modélise le prix d\'un actif comme produit de ses rendements (m8) — pricer une option et compter des accordeurs de pianos, même outil.',
    rectoEn: 'The geometric mean: definition, and why it is THE midpoint of orders of magnitude?',
    versoEn: '√(b × h): the MULTIPLICATIVE midpoint of two bounds — the same factor away from both (between 1,000 and 1,000,000, √ = 31,623, a factor ~32 from each bound). Why it: order-of-magnitude uncertainty is multiplicative ("a factor of 10 either way"); in logs it becomes additive and symmetric, and the arithmetic mean of the logs, exponentiated back, is precisely the geometric mean. The anchor: the same mathematics turns a product of random factors into a lognormal (m2) and models an asset price as the product of its returns (m8) — pricing an option and counting piano tuners, same tool.',
  },
  {
    id: 'm13-fc-024',
    moduleId: M13,
    tags: ['definition', 'fermi'],
    recto: 'Le squelette de décomposition le plus courant d\'une estimation de Fermi ?',
    verso: 'POPULATION × TAUX × FRÉQUENCE (÷ CAPACITÉ). Les accordeurs de pianos : 2 M d\'habitants → 1 M de foyers × ~3 % d\'équipement (géométrique de 1-10 %) × 1 accord/an ÷ 1 000 accords/an par professionnel = ~30. Chaque facteur se laisse encadrer par du bon sens, aucun n\'exige de savoir quoi que ce soit sur les pianos — et les erreurs, tantôt hautes, tantôt basses, se compensent partiellement. L\'ancrage : le secret statistique de Fermi — mieux vaut six estimations médiocres qu\'une seule devinette héroïque ; en log, l\'estimation est une moyenne de petites erreurs à peu près centrées.',
    rectoEn: 'The most common decomposition skeleton of a Fermi estimate?',
    versoEn: 'POPULATION × RATE × FREQUENCY (÷ CAPACITY). The piano tuners: 2m inhabitants → 1m households × ~3% ownership (geometric mean of 1-10%) × 1 tuning/year ÷ 1,000 tunings/year per professional = ~30. Each factor can be bracketed by common sense, none requires knowing anything about pianos — and the errors, some high, some low, partially offset. The anchor: Fermi\'s statistical secret — six mediocre estimates beat one heroic guess; in logs, the estimate is an average of small, roughly centred errors.',
  },
  {
    id: 'm13-fc-025',
    moduleId: M13,
    tags: ['calcul-mental', 'fermi'],
    recto: 'De tête : le milieu de Fermi entre 1 000 et 1 000 000 ?',
    verso: '√(1 000 × 1 000 000) = √10⁹ = 10^4,5 ≈ 31 623 ≈ 30 000. La méthode en deux gestes : 1) multiplier les puissances de 10 (10³ × 10⁶ = 10⁹) ; 2) prendre la racine = diviser l\'exposant par 2 (10^4,5), et retenir √10 ≈ 3,16 pour la demi-puissance. La moyenne arithmétique dirait 500 500 — un facteur 15 trop haut. L\'ancrage : en exposants, la géométrique est une MOYENNE D\'EXPOSANTS — (3 + 6)/2 = 4,5 — c\'est le calcul mental le plus rapide du chapitre.',
    rectoEn: 'In your head: the Fermi midpoint between 1,000 and 1,000,000?',
    versoEn: '√(1,000 × 1,000,000) = √10⁹ = 10^4.5 ≈ 31,623 ≈ 30,000. The method in two moves: 1) multiply the powers of 10 (10³ × 10⁶ = 10⁹); 2) take the root = halve the exponent (10^4.5), remembering √10 ≈ 3.16 for the half power. The arithmetic mean would say 500,500 — a factor of 15 too high. The anchor: in exponents, the geometric mean is an AVERAGE OF EXPONENTS — (3 + 6)/2 = 4.5 — the fastest mental calculation of the chapter.',
  },
  {
    id: 'm13-fc-026',
    moduleId: M13,
    tags: ['calcul-mental', 'fermi'],
    recto: 'Reconstruire de tête le volume quotidien du marché des changes : la chaîne en trois lignes ?',
    verso: '1) Point de départ réel : commerce mondial ~30 000 Md$ par an ÷ 250 jours ouvrés ≈ 120 Md$ par jour de flux « réels ». 2) Multiplicateur financier (couvertures roulées, spéculation, intermédiation entre teneurs de marché) : sûrement entre 20 et 200 — géométrique √(20 × 200) = √4 000 ≈ 63. 3) Produit : 120 × 63 ≈ 7 500 Md$ par jour — l\'ordre de grandeur de l\'enquête BRI 2022. L\'ancrage : la décomposition montre le raisonnement, l\'ancre du m6 vérifie l\'atterrissage — si la chaîne sort 500 ou 80 000, un facteur s\'est perdu, et c\'est vous qui devez le voir, pas le jury.',
    rectoEn: 'Rebuild the daily FX market volume in your head: the three-line chain?',
    versoEn: '1) Real starting point: world trade ~$30,000bn a year ÷ 250 business days ≈ $120bn a day of "real" flows. 2) Financial multiplier (rolled hedges, speculation, dealer-to-dealer intermediation): surely between 20 and 200 — geometric √(20 × 200) = √4,000 ≈ 63. 3) Product: 120 × 63 ≈ $7,500bn a day — the order of magnitude of the BIS 2022 survey. The anchor: the decomposition shows the reasoning, the m6 anchor checks the landing — if the chain spits out 500 or 80,000, a factor got lost, and YOU must spot it, not the panel.',
  },
  {
    id: 'm13-fc-027',
    moduleId: M13,
    tags: ['ordre-de-grandeur', 'fermi'],
    recto: 'Le volume quotidien du marché des changes : le chiffre à réciter, avec sa source ?',
    verso: '~7 500 Md$ PAR JOUR (enquête triennale de la BRI, 2022) — le plus grand marché du monde, plus de 60 fois le commerce mondial quotidien. À comparer : ~120 Md$ par jour de flux commerciaux « réels » — l\'écrasante majorité du volume est financière (couverture, spéculation, intermédiation). L\'ancrage : l\'ancre du m6, et le garde-fou de toute estimation de Fermi sur les marchés — un candidat qui cite le chiffre AVEC sa source (BRI) parle d\'une voix différente de celui qui répète un titre de presse.',
    rectoEn: 'Daily FX market volume: the figure to recite, with its source?',
    versoEn: '~$7,500bn A DAY (BIS triennial survey, 2022) — the largest market in the world, over 60 times daily world trade. Compare: ~$120bn a day of "real" trade flows — the overwhelming majority of the volume is financial (hedging, speculation, intermediation). The anchor: the m6 anchor, and the guardrail of any market Fermi estimate — a candidate citing the figure WITH its source (BIS) speaks in a different voice from one repeating a headline.',
  },
  {
    id: 'm13-fc-028',
    moduleId: M13,
    tags: ['ordre-de-grandeur', 'fermi'],
    recto: 'Les accordeurs de pianos à Paris : l\'ordre de grandeur et la chaîne qui y mène ?',
    verso: '~30 — « quelques dizaines, à un facteur 2 ou 3 près ». La chaîne : 2 M d\'habitants → 1 M de foyers (2 par foyer) → 3 % ont un piano (géométrique de 1-10 %) = 30 000 pianos → 1 accord par an = 30 000 accords → un accordeur en fait ~1 000 par an (4 par jour, 250 jours) → 30 000/1 000 = 30. Les annuaires en recensent effectivement quelques dizaines. L\'ancrage : la question canonique de Fermi à Chicago — six facteurs, aucun n\'exige de connaître les pianos ; l\'unité tenue de bout en bout (par AN) est ce qui évite le facteur 250.',
    rectoEn: 'Piano tuners in Paris: the order of magnitude and the chain that leads there?',
    versoEn: '~30 — "a few dozen, to within a factor of 2 or 3". The chain: 2m inhabitants → 1m households (2 per household) → 3% own a piano (geometric mean of 1-10%) = 30,000 pianos → 1 tuning a year = 30,000 tunings → one tuner does ~1,000 a year (4 a day, 250 days) → 30,000/1,000 = 30. Professional directories indeed list a few dozen. The anchor: Fermi\'s canonical Chicago question — six factors, none requiring piano knowledge; holding the unit throughout (per YEAR) is what avoids the factor-250 blunder.',
  },
  {
    id: 'm13-fc-029',
    moduleId: M13,
    tags: ['ordre-de-grandeur', 'fermi'],
    recto: 'Les balles de ping-pong dans un Airbus A320 : le chiffre, et le facteur que tout le monde oublie ?',
    verso: '~3,6 millions — « quelques millions ». La chaîne express : cabine ~30 m × ~7 m² ≈ 200 m³ ; une balle de 4 cm ≈ 33,5 cm³ ; et le facteur oublié — des sphères en vrac ne remplissent que ~60 % du volume : 0,6/0,0000335 ≈ 18 000 balles par m³ ; 200 × 18 000 ≈ 3,6 M. Sans le taux de remplissage, l\'estimation gonfle de deux tiers. L\'ancrage : le jury pose la question dix fois par saison et guette précisément ce facteur — la relecture « qui d\'autre ? quoi d\'autre ? » avant d\'annoncer est le geste qui l\'attrape.',
    rectoEn: 'Ping-pong balls in an Airbus A320: the figure, and the factor everyone forgets?',
    versoEn: '~3.6 million — "a few million". The express chain: cabin ~30 m × ~7 m² ≈ 200 m³; a 4 cm ball ≈ 33.5 cm³; and the forgotten factor — loosely packed spheres fill only ~60% of the volume: 0.6/0.0000335 ≈ 18,000 balls per m³; 200 × 18,000 ≈ 3.6m. Without the packing rate, the estimate inflates by two thirds. The anchor: the panel asks this ten times a season and watches for precisely that factor — the "who else? what else?" re-read before announcing is the move that catches it.',
  },
  {
    id: 'm13-fc-030',
    moduleId: M13,
    tags: ['reflexe-jury', 'fermi'],
    recto: 'Question de Fermi : la phrase d\'annonce à réciter jusqu\'à l\'automatisme ?',
    verso: 'Réflexe — le gabarit : « je décompose en A × B × C ; je suis sûr que B est entre tant et tant, je prends le milieu géométrique ; j\'obtiens environ X — retenez l\'ordre de grandeur, à un facteur k près ». Chaque segment montre un geste : la décomposition, les bornes assumées, le bon milieu, l\'incertitude finale. L\'ancrage : c\'est le trois-temps du ch1 — annoncer, borner, raffiner — étendu aux quantités qu\'on ne connaît pas ; la méthode ne vaut que si elle S\'ENTEND, et la structure vaut plus que le résultat.',
    rectoEn: 'Fermi question: the announcement sentence to drill until it is automatic?',
    versoEn: 'Reflex — the template: "I decompose into A × B × C; I am sure B is between so much and so much, I take the geometric midpoint; I get about X — keep the order of magnitude, to within a factor of k". Each segment displays a move: the decomposition, the owned bounds, the right midpoint, the final uncertainty. The anchor: it is ch1\'s three-beat — announce, bound, refine — extended to quantities you do not know; the method only counts if it can be HEARD, and structure outranks the result.',
  },
  {
    id: 'm13-fc-031',
    moduleId: M13,
    tags: ['reflexe-jury', 'fermi'],
    recto: 'Vos bornes de Fermi : étroites pour impressionner, ou larges ?',
    verso: 'Réflexe : LARGES mais ASSUMÉES — « entre 1 % et 10 %, je n\'en sais pas plus, la géométrique dit 3 % » vaut mieux que des bornes étroites bluffées. La largeur avouée est de la rigueur ; la fausse étroitesse est du bluff, et les jurys savent sonder la différence en une question. Le seul impératif : être SÛR de chaque borne — c\'est elle qui porte toute la chaîne. L\'ancrage : atterrir à un facteur 5 avec une chaîne propre bat tomber juste par chance sans décomposition défendable — le jury note la structure, pas le coup de chance.',
    rectoEn: 'Your Fermi bounds: narrow to impress, or wide?',
    versoEn: 'Reflex: WIDE but OWNED — "between 1% and 10%, that is all I know, the geometric mean says 3%" beats bluffed narrow bounds. Admitted width is rigour; fake narrowness is bluff, and panels know how to probe the difference in one question. The single imperative: be SURE of each bound — it carries the whole chain. The anchor: landing within a factor of 5 with a clean chain beats being luckily right without a defensible decomposition — the panel grades the structure, not the fluke.',
  },
  {
    id: 'm13-fc-032',
    moduleId: M13,
    tags: ['reflexe-jury', 'fermi'],
    recto: 'En pleine estimation, vous réalisez avoir oublié un facteur (les pianos des conservatoires…). Que faire ?',
    verso: 'Réflexe : CORRIGER EN ROUTE, à voix haute, sans paniquer — « je réalise que j\'ai oublié les pianos des entreprises : cela ajoute peut-être 20 %, l\'ordre de grandeur tient ». L\'erreur détectée et absorbée à voix haute est un point GAGNÉ : elle montre le contrôle permanent que le desk exige. La prévention : relire sa chaîne de facteurs en se demandant « qui d\'autre ? quoi d\'autre ? » avant d\'annoncer. L\'ancrage : le silence prolongé est éliminatoire là où l\'erreur corrigée ne l\'est pas — l\'exercice simule une salle de marchés, pas une salle d\'examen.',
    rectoEn: 'Mid-estimate, you realise you forgot a factor (conservatory pianos…). What now?',
    versoEn: 'Reflex: CORRECT IN FLIGHT, out loud, without panicking — "I realise I forgot corporate pianos: that adds maybe 20%, the order of magnitude holds". An error caught and absorbed aloud is a point EARNED: it shows the permanent control a desk demands. Prevention: re-read your factor chain asking "who else? what else?" before announcing. The anchor: prolonged silence is eliminatory where a corrected error is not — the exercise simulates a trading floor, not an exam hall.',
  },
  {
    id: 'm13-fc-033',
    moduleId: M13,
    tags: ['reflexe-jury', 'fermi'],
    recto: 'Le jury glisse « certains disent 100 000 » au milieu de votre estimation. Le danger, et la parade ?',
    verso: 'Le danger : l\'ANCRAGE — le premier chiffre entendu aimante votre estimation, même s\'il est faux, même s\'il est lancé exprès. La parade : avoir construit VOS bornes avant d\'écouter les siennes — puis confronter posément : « mon encadrement sort 30 000 ; 100 000 supposerait un taux d\'équipement de 10 %, ma borne haute — possible mais peu probable ». L\'ancrage : le jury teste moins votre chiffre que votre résistance à l\'influence — celui qui lâche ses bornes au premier chiffre adverse lâchera son prix au premier client insistant.',
    rectoEn: 'The panel slips in "some say 100,000" mid-estimate. The danger, and the parry?',
    versoEn: 'The danger: ANCHORING — the first figure heard magnetises your estimate, even if wrong, even if thrown on purpose. The parry: having built YOUR bounds before hearing theirs — then confronting calmly: "my bracket gives 30,000; 100,000 would require a 10% ownership rate, my upper bound — possible but unlikely". The anchor: the panel tests your resistance to influence more than your figure — whoever drops his bounds at the first opposing number will drop his price at the first insistent client.',
  },
  {
    id: 'm13-fc-034',
    moduleId: M13,
    tags: ['piege', 'fermi'],
    recto: '« Entre 1 000 et 1 000 000, je prends le milieu : 500 000 » — le piège ?',
    verso: 'FAUX : c\'est la moyenne ARITHMÉTIQUE, qui écrase la borne basse — 500 000 est à un facteur 500 de 1 000 mais à un facteur 2 seulement de 1 000 000. Sur des ordres de grandeur, l\'incertitude est multiplicative : le seul milieu cohérent est la moyenne GÉOMÉTRIQUE, √(1 000 × 1 000 000) ≈ 31 623 ≈ 30 000, au même facteur ~32 des deux bornes ; l\'arithmétique se trompe d\'un facteur 15. L\'ancrage : « entre mille et un million » signifie « à un facteur 30 près », pas « à ±500 000 près » — la faute la plus fréquente et la plus discriminante de tout l\'exercice de Fermi.',
    rectoEn: '"Between 1,000 and 1,000,000, I take the middle: 500,000" — the trap?',
    versoEn: 'WRONG: that is the ARITHMETIC mean, which crushes the lower bound — 500,000 is a factor 500 from 1,000 but only a factor 2 from 1,000,000. On orders of magnitude, uncertainty is multiplicative: the only coherent midpoint is the GEOMETRIC mean, √(1,000 × 1,000,000) ≈ 31,623 ≈ 30,000, the same factor ~32 from both bounds; the arithmetic mean is off by a factor of 15. The anchor: "between a thousand and a million" means "within a factor of 30", not "within ±500,000" — the most frequent and most discriminating mistake in the whole Fermi exercise.',
  },
  // ───────────────────────── Chapitre 3 — Les probabilités d\'entretien ─────────────────────────
  {
    id: 'm13-fc-035',
    moduleId: M13,
    tags: ['definition', 'probas'],
    recto: 'Le passage par le complémentaire : définition, formule, et les mots qui doivent le déclencher ?',
    verso: 'Pour n essais indépendants de probabilité de succès p, la probabilité d\'AU MOINS UN succès est 1 − (1 − p)ⁿ : on calcule la probabilité que TOUS les essais échouent — un simple produit, grâce à l\'indépendance — et on la retranche de 1. Les mots déclencheurs : « au moins un » ⇒ complémentaire, sans réfléchir. Deux ancres : au moins un 6 en 4 lancers = 51,8 % ; au moins un pile en 3 lancers = 87,5 %. L\'ancrage : le piège additif n × p a exactement la structure du défaut cumulé du m5 — les probabilités de survie se multiplient, les probabilités de défaut ne s\'additionnent jamais.',
    rectoEn: 'The complement trick: definition, formula, and the words that must trigger it?',
    versoEn: 'For n independent trials with success probability p, the probability of AT LEAST ONE success is 1 − (1 − p)ⁿ: compute the probability that ALL trials fail — a simple product, thanks to independence — and subtract it from 1. Trigger words: "at least one" ⇒ complement, no thinking required. Two anchors: at least one 6 in 4 rolls = 51.8%; at least one heads in 3 flips = 87.5%. The anchor: the additive trap n × p has exactly the structure of m5\'s cumulative default — survival probabilities multiply, default probabilities never add.',
  },
  {
    id: 'm13-fc-036',
    moduleId: M13,
    tags: ['definition', 'probas'],
    recto: 'Le paradoxe des anniversaires : énoncé, réponse, et pourquoi l\'intuition rate d\'un facteur huit ?',
    verso: 'Combien de personnes pour que deux partagent leur anniversaire avec plus d\'une chance sur deux ? L\'intuition dit 183 (la moitié de 365) ; la réponse est 23 (probabilité exacte 50,7 %). Pourquoi : les collisions se produisent entre PAIRES, pas entre personnes — 23 personnes forment C(23, 2) = 253 paires, et ce nombre croît en n², pas en n ; le cerveau, câblé linéaire, ne voit pas la croissance quadratique. L\'ancrage : la leçon de desk — les événements joints sont toujours plus probables qu\'on ne le sent : deux défauts « indépendants », deux pannes le même jour ; dès qu\'on compte les paires, le rare devient banal.',
    rectoEn: 'The birthday paradox: statement, answer, and why intuition misses by a factor of eight?',
    versoEn: 'How many people for two of them to share a birthday with better-than-even odds? Intuition says 183 (half of 365); the answer is 23 (exact probability 50.7%). Why: collisions happen between PAIRS, not people — 23 people form C(23, 2) = 253 pairs, and that number grows like n², not n; the brain, wired linear, does not see quadratic growth. The anchor: the desk lesson — joint events are always more likely than they feel: two "independent" defaults, two outages the same day; once you count pairs, the rare becomes routine.',
  },
  {
    id: 'm13-fc-037',
    moduleId: M13,
    tags: ['definition', 'probas'],
    recto: 'Le base rate neglect : définition, et la confusion exacte qu\'il commet ?',
    verso: 'L\'oubli du TAUX DE BASE (la prévalence) : lire « test fiable à 99 % » et répondre 99 % à « suis-je malade sachant test positif ? ». La confusion : prendre P(test⁺ | malade) — la sensibilité — pour P(malade | test⁺) — ce qu\'on cherche. Ce sont deux conditionnelles différentes, et tout Bayes tient dans l\'art de passer de l\'une à l\'autre en réintroduisant la prévalence : quand ce qu\'on cherche est rare, les faux positifs NOIENT les vrais. L\'ancrage : la transposition marché attendue — un indicateur de crise « fiable à 99 % » qui guette un événement à 1 % produit surtout de fausses alertes (m10, m11) ; la force d\'un signal dépend de la rareté de ce qu\'il cherche.',
    rectoEn: 'Base rate neglect: definition, and the exact confusion it commits?',
    versoEn: 'Forgetting the BASE RATE (the prevalence): reading "99% reliable test" and answering 99% to "am I sick given a positive test?". The confusion: taking P(test⁺ | sick) — the sensitivity — for P(sick | test⁺) — what you actually want. They are two different conditionals, and all of Bayes lies in moving from one to the other by reinstating the prevalence: when what you seek is rare, false positives DROWN the true ones. The anchor: the expected market transposition — a "99% reliable" crisis indicator watching a 1% event mostly produces false alarms (m10, m11); a signal\'s strength depends on the rarity of what it hunts.',
  },
  {
    id: 'm13-fc-038',
    moduleId: M13,
    tags: ['definition', 'probas'],
    recto: 'Sensibilité et taux de faux positifs : les deux nombres d\'un test, et pourquoi ils ne suffisent pas ?',
    verso: 'La SENSIBILITÉ : P(test⁺ | malade) — la part des vrais cas que le test détecte (99 %). Le TAUX DE FAUX POSITIFS : P(test⁺ | sain) — la part des sains que le test accuse à tort (5 %). Ils décrivent le TEST, pas votre situation : pour répondre « suis-je malade sachant test⁺ ? », il faut le troisième nombre — la PRÉVALENCE — car le verdict dépend du rapport entre vrais positifs (prévalence × sensibilité) et faux positifs ((1 − prévalence) × taux de FP). L\'ancrage : à 1 % de prévalence, 99 vrais contre 495 faux — un test excellent rend un verdict médiocre sur un événement rare ; les trois curseurs, jamais deux.',
    rectoEn: 'Sensitivity and false positive rate: a test\'s two numbers, and why they are not enough?',
    versoEn: 'SENSITIVITY: P(test⁺ | sick) — the share of true cases the test detects (99%). FALSE POSITIVE RATE: P(test⁺ | healthy) — the share of healthy people wrongly accused (5%). They describe the TEST, not your situation: to answer "am I sick given test⁺?", you need the third number — the PREVALENCE — because the verdict hinges on the ratio of true positives (prevalence × sensitivity) to false positives ((1 − prevalence) × FP rate). The anchor: at 1% prevalence, 99 true against 495 false — an excellent test gives a mediocre verdict on a rare event; three dials, never two.',
  },
  {
    id: 'm13-fc-039',
    moduleId: M13,
    tags: ['definition', 'probas'],
    recto: 'Les combinaisons C(n, k) : définition, et le réflexe de calcul qui distingue à l\'oral ?',
    verso: 'Le nombre de façons de choisir k objets parmi n SANS ORDRE : C(n, k) = n!/(k!(n−k)!). Ancres : C(52, 5) = 2 598 960 mains de poker ; C(10, 3) = 120 ; C(6, 2) = 15 ; C(23, 2) = 253 paires d\'anniversaires. Le réflexe d\'oral : SIMPLIFIER AVANT de multiplier — diviser chaque facteur du dénominateur dans un facteur du numérateur, pour ne jamais manipuler de grands nombres. L\'ancrage : quand l\'ordre ne compte pas, on compte sans énumérer — la brique des anniversaires (paires), des mains de cartes et de la généralisation des deux œufs (ch4).',
    rectoEn: 'Combinations C(n, k): definition, and the calculation reflex that stands out orally?',
    versoEn: 'The number of ways to choose k objects out of n WITHOUT ORDER: C(n, k) = n!/(k!(n−k)!). Anchors: C(52, 5) = 2,598,960 poker hands; C(10, 3) = 120; C(6, 2) = 15; C(23, 2) = 253 birthday pairs. The oral reflex: SIMPLIFY BEFORE multiplying — cancel each denominator factor into a numerator factor, so you never handle big numbers. The anchor: when order does not matter, you count without enumerating — the brick behind birthdays (pairs), card hands and the two-egg generalisation (ch4).',
  },
  {
    id: 'm13-fc-040',
    moduleId: M13,
    tags: ['definition', 'probas'],
    recto: 'Le sophisme du joueur (gambler\'s fallacy) : définition — et le second étage bayésien que l\'oral attend ?',
    verso: 'Croire qu\'après dix piles, un face est « dû » pour rééquilibrer : FAUX — la pièce n\'a pas de mémoire, les lancers sont indépendants, le prochain est à 50 % ; la loi des grands nombres DILUE les écarts dans le long terme, elle ne les compense jamais coup par coup. Le second étage, si le jury insiste : « à condition que la pièce soit équilibrée » — or dix piles n\'arrivent qu\'à ~0,1 % : un esprit bayésien révise sa confiance dans la pièce et parierait plutôt PILE. L\'ancrage : deux erreurs symétriques — supposer une dépendance qui n\'existe pas (la pièce est due) et défendre une indépendance supposée contre l\'évidence (la pièce est peut-être truquée).',
    rectoEn: 'The gambler\'s fallacy: definition — and the second, Bayesian storey the oral expects?',
    versoEn: 'Believing that after ten heads, a tails is "due" to rebalance: WRONG — the coin has no memory, flips are independent, the next one is 50%; the law of large numbers DILUTES deviations over the long run, it never offsets them flip by flip. The second storey, if the panel pushes: "provided the coin is fair" — but ten heads only happen ~0.1% of the time: a Bayesian mind revises its trust in the coin and would rather bet HEADS. The anchor: two symmetric errors — assuming a dependence that does not exist (the coin is due) and defending an assumed independence against the evidence (the coin may be rigged).',
  },
  {
    id: 'm13-fc-041',
    moduleId: M13,
    tags: ['definition', 'probas'],
    recto: 'Monty Hall : l\'énoncé, la réponse, et le test de compréhension que le jury adore ?',
    verso: 'Trois portes, une voiture ; vous en choisissez une ; l\'animateur — qui SAIT où est la voiture — ouvre une des deux autres, toujours sur une chèvre, et propose de changer. CHANGER : de 1/3 à 2/3. Votre porte gardait ses 1/3 (l\'animateur ouvrira une perdante quoi qu\'il arrive) ; les 2/3 restants se concentrent sur la porte qu\'il n\'a PAS ouverte — son geste, contraint par sa connaissance, transporte de l\'information. Le test : si un ami IGNORANT ouvre au hasard et tombe sur une chèvre, changer ne sert à rien — 50/50. L\'ancrage : toute la différence tient dans QUI SAIT QUOI — c\'est du Bayes déguisé (le geste forcé est deux fois plus vraisemblable quand la voiture est derrière l\'autre porte).',
    rectoEn: 'Monty Hall: the setup, the answer, and the comprehension test panels love?',
    versoEn: 'Three doors, one car; you pick one; the host — who KNOWS where the car is — opens one of the other two, always on a goat, and offers a switch. SWITCH: from 1/3 to 2/3. Your door keeps its 1/3 (the host will open a losing door no matter what); the remaining 2/3 concentrate on the door he did NOT open — his move, constrained by his knowledge, carries information. The test: if an IGNORANT friend opens a door at random and happens on a goat, switching is useless — 50/50. The anchor: everything hinges on WHO KNOWS WHAT — it is Bayes in disguise (the forced move is twice as likely when the car is behind the other door).',
  },
  {
    id: 'm13-fc-042',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'De tête : au moins un 6 en quatre lancers de dé ?',
    verso: '51,8 % — jamais 4 × 1/6. La méthode en trois gestes : 1) « au moins un » ⇒ COMPLÉMENTAIRE ; 2) aucun 6 en 4 lancers = (5/6)⁴ ≈ 48,2 % (de tête : 5/6 ≈ 0,833 ; 0,833² ≈ 0,694 ; 0,694² ≈ 0,482) ; 3) retrancher de 1 : 51,8 %. Vérification d\'énormité : six lancers ne donneraient PAS 100 %. L\'ancrage : le pari du chevalier de Méré, favorable de justesse — la question la plus posée de l\'histoire des entretiens, et l\'acte de naissance des probabilités (Pascal-Fermat, 1654).',
    rectoEn: 'In your head: at least one 6 in four dice rolls?',
    versoEn: '51.8% — never 4 × 1/6. The method in three moves: 1) "at least one" ⇒ COMPLEMENT; 2) no 6 in 4 rolls = (5/6)⁴ ≈ 48.2% (mentally: 5/6 ≈ 0.833; 0.833² ≈ 0.694; 0.694² ≈ 0.482); 3) subtract from 1: 51.8%. Absurdity check: six rolls would NOT give 100%. The anchor: the Chevalier de Méré\'s bet, favourable by a whisker — the most asked question in interview history, and the birth certificate of probability theory (Pascal-Fermat, 1654).',
  },
  {
    id: 'm13-fc-043',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'De tête : au moins un pile en trois lancers de pièce ?',
    verso: '87,5 %. La méthode : complémentaire — aucun pile en 3 lancers = (1/2)³ = 1/8 = 12,5 % ; donc au moins un = 1 − 1/8 = 7/8 = 87,5 %. Deux gestes, cinq secondes. Généralisation immédiate : au moins un pile en n lancers = 1 − (1/2)ⁿ — 4 lancers : 93,75 % ; 5 : 96,9 %. L\'ancrage : la deuxième ancre du complémentaire à connaître par cœur avec Méré (51,8 %) — les puissances de 1/2 (1/8, 1/16, 1/32) sont les briques des jeux de pile ou face.',
    rectoEn: 'In your head: at least one heads in three coin flips?',
    versoEn: '87.5%. The method: complement — no heads in 3 flips = (1/2)³ = 1/8 = 12.5%; so at least one = 1 − 1/8 = 7/8 = 87.5%. Two moves, five seconds. Immediate generalisation: at least one heads in n flips = 1 − (1/2)ⁿ — 4 flips: 93.75%; 5: 96.9%. The anchor: the second complement anchor to know by heart alongside Méré (51.8%) — the powers of 1/2 (1/8, 1/16, 1/32) are the bricks of coin-flip games.',
  },
  {
    id: 'm13-fc-044',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'Le second pari de Méré : au moins un double 6 en 24 lancers de deux dés — favorable ou non ?',
    verso: 'DÉFAVORABLE, de justesse : 1 − (35/36)²⁴ = 49,1 %. La méthode : même structure que le premier pari — complémentaire d\'un produit — mais la règle de trois qui le rendait « équivalent » (24/36 = 4/6) est fausse : les probabilités composées ne se transportent pas linéairement. Méré gagnait au premier pari (51,8 %), perdait au second, et son énigme lança Pascal et Fermat en 1654. L\'ancrage : raconter l\'anecdote en trente secondes montre qu\'on sait POURQUOI la règle de trois échoue — même un joueur professionnel se fait piéger par l\'intuition additive.',
    rectoEn: 'Méré\'s second bet: at least one double six in 24 rolls of two dice — favourable or not?',
    versoEn: 'UNFAVOURABLE, by a whisker: 1 − (35/36)²⁴ = 49.1%. The method: same structure as the first bet — complement of a product — but the rule of three that made it "equivalent" (24/36 = 4/6) is false: compound probabilities do not transport linearly. Méré won the first bet (51.8%), lost the second, and his puzzle launched Pascal and Fermat in 1654. The anchor: telling the anecdote in thirty seconds shows you know WHY the rule of three fails — even a professional gambler gets trapped by additive intuition.',
  },
  {
    id: 'm13-fc-045',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'La méthode des 10 000 pour Bayes : dérouler le classique (prévalence 1 %, sensibilité 99 %, faux positifs 5 %) ?',
    verso: 'Trois lignes de calcul mental : 1) sur 10 000 personnes, 1 % sont malades — 100 malades, le test en détecte 99 ; 2) les 9 900 sains subissent 5 % de faux positifs — 495 accusés à tort ; 3) parmi les 99 + 495 = 594 positifs, seuls 99 sont vrais : 99/594 = 1/6 ≈ 16,7 %. Les faux positifs noient les vrais — 495 contre 99, cinq contre un. L\'ancrage : le candidat qui sort la formule a juste ; celui qui déroule les 10 000 MARQUE — la version calcul mental du théorème de Bayes, récitable au tableau en trente secondes.',
    rectoEn: 'The 10,000 method for Bayes: walk through the classic (1% prevalence, 99% sensitivity, 5% false positives)?',
    versoEn: 'Three lines of mental arithmetic: 1) out of 10,000 people, 1% are sick — 100 sick, the test catches 99; 2) the 9,900 healthy suffer 5% false positives — 495 wrongly accused; 3) among the 99 + 495 = 594 positives, only 99 are true: 99/594 = 1/6 ≈ 16.7%. False positives drown the true ones — 495 against 99, five to one. The anchor: the candidate who quotes the formula is right; the one who walks the 10,000 SCORES — the mental-arithmetic version of Bayes\' theorem, recitable at the board in thirty seconds.',
  },
  {
    id: 'm13-fc-046',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'C(52, 5) à la main : le réflexe qui évite les nombres à huit chiffres ?',
    verso: 'SIMPLIFIER AVANT de multiplier : (52 × 51 × 50 × 49 × 48)/(5 × 4 × 3 × 2) s\'apprivoise en divisant d\'abord — 50/5 = 10, 48/4 = 12, 51/3 = 17, 52/2 = 26 — pour finir sur 26 × 17 × 10 × 12 × 49 = 2 598 960 mains de poker. Aucun produit intermédiaire ne dépasse quelques centaines avant l\'assemblage final. L\'ancrage : la version « à la main » de la fonction combinaisons — le geste (annuler le dénominateur d\'abord) compte plus que le résultat, et 2,6 millions est l\'ancre à réciter.',
    rectoEn: 'C(52, 5) by hand: the reflex that avoids eight-digit numbers?',
    versoEn: 'SIMPLIFY BEFORE multiplying: (52 × 51 × 50 × 49 × 48)/(5 × 4 × 3 × 2) is tamed by dividing first — 50/5 = 10, 48/4 = 12, 51/3 = 17, 52/2 = 26 — finishing with 26 × 17 × 10 × 12 × 49 = 2,598,960 poker hands. No intermediate product exceeds a few hundred before the final assembly. The anchor: the "by hand" version of the combinations function — the move (cancel the denominator first) matters more than the result, and 2.6 million is the anchor to recite.',
  },
  {
    id: 'm13-fc-047',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'De tête : deux as d\'affilée en tirant deux cartes sans remise ?',
    verso: '≈ 0,45 % — 1/221. La méthode : 4/52 × 3/51 — et le point NOTÉ est le conditionnement : le second facteur est « sachant le premier as sorti » (il reste 3 as sur 51 cartes). Simplifier : 4/52 = 1/13, 3/51 = 1/17, produit 1/221. L\'ancrage : le mini-classique des cartes — sans remise, les probabilités se CONDITIONNENT ; avec remise, elles seraient indépendantes (1/13 × 1/13 = 1/169) — c\'est la différence que le jury écoute.',
    rectoEn: 'In your head: two aces in a row, drawing two cards without replacement?',
    versoEn: '≈ 0.45% — 1/221. The method: 4/52 × 3/51 — and the GRADED point is the conditioning: the second factor is "given the first ace is out" (3 aces left in 51 cards). Simplify: 4/52 = 1/13, 3/51 = 1/17, product 1/221. The anchor: the card mini-classic — without replacement, probabilities CONDITION; with replacement they would be independent (1/13 × 1/13 = 1/169) — that is the difference the panel listens for.',
  },
  {
    id: 'm13-fc-048',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'De tête : cinq piles d\'affilée — et le piège de direction à ne pas confondre ?',
    verso: '(1/2)⁵ = 1/32 = 3,125 %. La méthode : succès CONSÉCUTIFS ⇒ multiplier les succès, pⁿ (trois 6 d\'affilée : (1/6)³ ≈ 0,46 %). Le miroir exact du « au moins un », où l\'on multiplie les ÉCHECS puis retranche de 1. Confondre les deux directions est la faute classique de fin d\'entretien, quand la fatigue monte. L\'ancrage : avant de calculer, dire à voix haute LAQUELLE des deux structures s\'applique — « série » ⇒ produit des succès ; « au moins un » ⇒ complémentaire.',
    rectoEn: 'In your head: five heads in a row — and the direction trap not to fall into?',
    versoEn: '(1/2)⁵ = 1/32 = 3.125%. The method: CONSECUTIVE successes ⇒ multiply the successes, pⁿ (three 6s in a row: (1/6)³ ≈ 0.46%). The exact mirror of "at least one", where you multiply the FAILURES then subtract from 1. Mixing up the two directions is the classic end-of-interview blunder, when fatigue sets in. The anchor: before computing, say out loud WHICH of the two structures applies — "streak" ⇒ product of successes; "at least one" ⇒ complement.',
  },
  {
    id: 'm13-fc-049',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'C(23, 2) de tête — et pourquoi ce nombre est célèbre ?',
    verso: '253 : C(23, 2) = 23 × 22/2 = 23 × 11 — et ×11, c\'est ×10 + ×1 : 230 + 23 = 253. C\'est le nombre de PAIRES dans une salle de 23 personnes — les 253 occasions de coïncidence qui font basculer le paradoxe des anniversaires au-dessus de 50 %. La méthode générale : C(n, 2) = n(n−1)/2, le nombre de poignées de main. L\'ancrage : deux briques du ch1 (×11, diviser par 2) au service du ch3 — et le chiffre qui répond à « pourquoi 23 suffisent » : on compte les paires, pas les personnes.',
    rectoEn: 'C(23, 2) in your head — and why is that number famous?',
    versoEn: '253: C(23, 2) = 23 × 22/2 = 23 × 11 — and ×11 is ×10 + ×1: 230 + 23 = 253. It is the number of PAIRS in a room of 23 people — the 253 collision opportunities that tip the birthday paradox above 50%. The general method: C(n, 2) = n(n−1)/2, the number of handshakes. The anchor: two ch1 bricks (×11, halving) serving ch3 — and the figure that answers "why 23 is enough": you count pairs, not people.',
  },
  {
    id: 'm13-fc-050',
    moduleId: M13,
    tags: ['calcul-mental', 'probas'],
    recto: 'Le calcul propre du paradoxe des anniversaires : quelle structure, sans calculatrice ?',
    verso: 'Le COMPLÉMENTAIRE, encore : P(tous distincts) = 365/365 × 364/365 × … × 343/365 — chaque nouvel arrivant doit éviter tous les anniversaires déjà pris, et les facteurs s\'érodent un à un jusqu\'à passer sous 50 % au 23e. La méthode d\'oral : poser la structure (produit de survies), citer le résultat (50,7 % à 23), ne PAS dérouler les 23 facteurs. L\'ancrage : même squelette que « au moins un 6 » — produit des non-collisions, retranché de 1 ; la structure récitée vaut le calcul.',
    rectoEn: 'The clean birthday-paradox calculation: what structure, without a calculator?',
    versoEn: 'The COMPLEMENT, again: P(all distinct) = 365/365 × 364/365 × … × 343/365 — each newcomer must dodge every birthday already taken, and the factors erode one by one until dipping below 50% at the 23rd. The oral method: state the structure (product of survivals), quote the result (50.7% at 23), do NOT grind through 23 factors. The anchor: same skeleton as "at least one 6" — product of non-collisions, subtracted from 1; reciting the structure counts as doing the calculation.',
  },
  // __SUITE__
];
