import type { Formule } from '../../../engine/types';

const M13 = '13-brainteasers-oral';

export const formules: Formule[] = [
  {
    id: 'm13-f-01',
    moduleId: M13,
    nom: 'Règle de 72 : le temps de doublement',
    nomEn: 'Rule of 72: the doubling time',
    latex: 't_{\\text{double}} \\approx \\frac{72}{t}',
    commentaire: 'L\'outil de calcul mental le plus rentable de tout l\'entretien : un capital placé au taux composé annuel de t % double en environ 72/t années. Les trois ancres à réciter : 8 % ⇒ 9 ans (exact : 9,006468 — erreur −0,07 %, indétectable) ; 6 % ⇒ 12 ans ; 2 % ⇒ 36 ans contre 35,0 exacts — aux taux bas, la règle SURESTIME d\'environ un an, et le dire fait partie de la réponse. Pourquoi 72 et pas 69,3 (= 100·ln 2) : 72 se divise par 2, 3, 4, 6, 8, 9 et 12, et l\'écart compense la discrétisation annuelle autour de 8 %, là où la règle est calibrée. Domaine de validité : erreur sous 2 % entre 4 et 12 %, jamais plus de 3,5 % sur la plage 1-15 %. C\'est le modèle réduit de toutes les approximations du cours : un outil, un domaine, une erreur connue (ch. 1).',
    commentaireEn: 'The most profitable mental-arithmetic tool of the whole interview: a capital compounding at t% per year doubles in about 72/t years. The three anchors to recite: 8% ⇒ 9 years (exact: 9.006468 — a −0.07% error, undetectable); 6% ⇒ 12 years; 2% ⇒ 36 years against 35.0 exact — at low rates the rule OVERSTATES by about a year, and saying so is part of the answer. Why 72 and not 69.3 (= 100·ln 2): 72 divides by 2, 3, 4, 6, 8, 9 and 12, and the gap offsets the annual discretisation around 8%, where the rule is calibrated. Validity domain: error below 2% between roughly 4 and 12%, never above 3.5% over the 1-15% range. It is the scale model of every approximation in the course: a tool, a domain, a known error (ch. 1).',
  },
  {
    id: 'm13-f-02',
    moduleId: M13,
    nom: 'Doublement exact : ln 2 sur ln(1 + r)',
    nomEn: 'Exact doubling time: ln 2 over ln(1 + r)',
    latex: 't_{\\text{double}} = \\frac{\\ln 2}{\\ln(1 + r)}',
    commentaire: 'La valeur exacte derrière la règle de 72, en composition annuelle discrète : le nombre d\'années tel que (1 + r)^t = 2. Les repères : 8 % ⇒ 9,006468 ans ; 6 % ⇒ 11,895661 ; 2 % ⇒ 35,002789. C\'est aussi la parade au blanc du jour J (ch. 7) : si la constante 72 échappe, remonter d\'un niveau — « le doublement dépend de ln 2 ≈ 0,69, donc l\'ordre de grandeur est 70 divisé par le taux » — et le trou de mémoire devient une démonstration de compréhension. Un candidat qui retrouve 70 en le raisonnant vaut plus qu\'un candidat qui récite 72 sans savoir d\'où il vient.',
    commentaireEn: 'The exact value behind the rule of 72, in discrete annual compounding: the number of years such that (1 + r)^t = 2. The benchmarks: 8% ⇒ 9.006468 years; 6% ⇒ 11.895661; 2% ⇒ 35.002789. It is also the antidote to the interview-day blank (ch. 7): if the constant 72 escapes you, go one level up — "doubling depends on ln 2 ≈ 0.69, so the order of magnitude is 70 divided by the rate" — and the memory lapse becomes a demonstration of understanding. A candidate who rebuilds 70 by reasoning is worth more than one who recites 72 without knowing where it comes from.',
  },
  {
    id: 'm13-f-03',
    moduleId: M13,
    nom: 'Erreur relative d\'une approximation',
    nomEn: 'Relative error of an approximation',
    latex: '\\varepsilon = \\frac{\\text{approx} - \\text{exact}}{\\text{exact}} \\times 100',
    commentaire: 'Le quatrième geste du calcul mental, le plus rare et le plus payant : dire de combien l\'approximation se trompe, et dans quel sens. L\'ancre : la règle de 72 à 8 % donne 9 ans contre 9,006468 exacts, soit ε = −0,071819 % — quasi rien ; à 2 %, 36 contre 35,0, soit +2,85 % — un an de trop. Le signe porte l\'information : négatif, l\'approximation sous-estime ; positif, elle surestime. C\'est ce geste qui transforme « je sais calculer » en « on peut me confier un book » : un chiffre sans barre d\'erreur est une opinion, un chiffre avec sa tolérance est un outil (ch. 1).',
    commentaireEn: 'The fourth mental-arithmetic move, the rarest and the most rewarding: saying by how much the approximation errs, and in which direction. The anchor: the rule of 72 at 8% gives 9 years against 9.006468 exact, i.e. ε = −0.071819% — next to nothing; at 2%, 36 against 35.0, i.e. +2.85% — one year too many. The sign carries the information: negative, the approximation understates; positive, it overstates. This move is what turns "I can compute" into "you can trust me with a book": a number without an error bar is an opinion, a number with its tolerance is a tool (ch. 1).',
  },
  {
    id: 'm13-f-04',
    moduleId: M13,
    nom: 'Au moins un succès : le complémentaire',
    nomEn: 'At least one success: the complement',
    latex: 'P(\\text{au moins un}) = 1 - (1 - p)^n',
    commentaire: 'LE réflexe des probabilités d\'entretien : les mots « au moins un » déclenchent le passage par le complémentaire — la probabilité que TOUS les essais échouent, un simple produit grâce à l\'indépendance, retranchée de 1. Les deux ancres : au moins un 6 en 4 lancers = 1 − (5/6)⁴ = 51,774691 % — le pari du chevalier de Méré, favorable de justesse, dont l\'énigme transmise à Pascal et Fermat fonde le calcul des probabilités en 1654 ; au moins un pile en 3 lancers = 87,5 %. Le piège additif n × p (4 × 1/6 = 66,7 %) est FAUX : à ce compte, six lancers donneraient une certitude. Les succès se composent, ils ne s\'additionnent pas — exactement la leçon du défaut cumulé du m5 (ch. 3).',
    commentaireEn: 'THE interview-probability reflex: the words "at least one" must trigger the complement — the probability that ALL trials fail, a simple product thanks to independence, subtracted from 1. The two anchors: at least one 6 in 4 rolls = 1 − (5/6)⁴ = 51.774691% — the Chevalier de Méré\'s bet, favourable by a whisker, whose puzzle passed to Pascal and Fermat founded probability theory in 1654; at least one heads in 3 flips = 87.5%. The additive trap n × p (4 × 1/6 = 66.7%) is WRONG: at that rate, six rolls would give certainty. Successes compound, they do not add up — exactly m5\'s cumulative-default lesson (ch. 3).',
  },
  {
    id: 'm13-f-05',
    moduleId: M13,
    nom: 'Paradoxe des anniversaires : le produit qui s\'érode',
    nomEn: 'Birthday paradox: the eroding product',
    latex: 'P(\\text{collision}) = 1 - \\prod_{k=0}^{n-1} \\frac{365 - k}{365}',
    commentaire: 'La probabilité qu\'au moins deux personnes sur n partagent leur anniversaire, calculée — encore — par le complémentaire : le produit des probabilités que chaque nouvel arrivant évite tous les jours déjà pris, facteurs qui s\'érodent un à un. Les ancres : n = 23 ⇒ 50,729723 % — la réponse qui défie l\'intuition (qui dit 183, la moitié de 365) ; n = 50 ⇒ 97,0 % ; n = 70 ⇒ 99,9 %. L\'intuition rate d\'un facteur huit parce qu\'elle compte les personnes quand les collisions se produisent entre PAIRES — 253 paires à 23 personnes. La leçon de desk : les événements joints sont toujours plus probables qu\'on ne le sent — deux défauts, deux pannes, deux erreurs le même jour (ch. 3).',
    commentaireEn: 'The probability that at least two people out of n share a birthday, computed — again — through the complement: the product of the probabilities that each newcomer avoids every day already taken, factors eroding one by one. The anchors: n = 23 ⇒ 50.729723% — the answer that defies intuition (which says 183, half of 365); n = 50 ⇒ 97.0%; n = 70 ⇒ 99.9%. Intuition misses by a factor of eight because it counts people while collisions happen between PAIRS — 253 pairs among 23 people. The desk lesson: joint events are always more likely than they feel — two defaults, two failures, two errors on the same day (ch. 3).',
  },
  {
    id: 'm13-f-06',
    moduleId: M13,
    nom: 'Le nombre de paires : C(n, 2)',
    nomEn: 'The number of pairs: C(n, 2)',
    latex: 'C(n, 2) = \\frac{n(n-1)}{2}',
    commentaire: 'La formule qui explique pourquoi le paradoxe des anniversaires n\'en est pas un : 23 personnes forment C(23, 2) = 253 paires — 253 occasions distinctes de coïncidence, chacune de probabilité 1/365. Le nombre de paires croît comme n², pas comme n : c\'est cette croissance quadratique que le cerveau, câblé linéaire, ne voit pas. Autres ancres utiles : 10 personnes ⇒ 45 paires, 100 ⇒ 4 950. À réciter au jury comme l\'explication, pas seulement comme le calcul : « je compte les paires, pas les personnes » est la phrase qui montre qu\'on a compris (ch. 3).',
    commentaireEn: 'The formula that explains why the birthday paradox is no paradox: 23 people form C(23, 2) = 253 pairs — 253 distinct opportunities for a coincidence, each with probability 1/365. The number of pairs grows like n², not like n: this quadratic growth is what the linearly-wired brain fails to see. Other useful anchors: 10 people ⇒ 45 pairs, 100 ⇒ 4,950. To recite to the jury as the explanation, not just the computation: "I count pairs, not people" is the sentence that shows understanding (ch. 3).',
  },
  {
    id: 'm13-f-07',
    moduleId: M13,
    nom: 'Bayes en effectifs : la méthode des 10 000',
    nomEn: 'Bayes with counts: the method of 10,000',
    latex: 'P(\\text{malade} \\mid +) = \\frac{\\text{vrais positifs}}{\\text{vrais positifs} + \\text{faux positifs}}',
    commentaire: 'La forme d\'oral du théorème de Bayes, à dérouler en trois lignes sur une population fictive de 10 000. LE classique absolu : maladie à 1 % de prévalence, test sensible à 99 %, 5 % de faux positifs — 100 malades dont 99 détectés ; 9 900 sains dont 495 positifs à tort ; parmi les 594 positifs, 99 vrais : 99/594 = 1/6 = 16,666667 %, pas 99 %. Les faux positifs NOIENT les vrais quand ce qu\'on cherche est rare : 495 contre 99, cinq contre un. Le candidat qui sort la formule a juste ; celui qui déroule les effectifs marque, parce que la méthode se récite de tête et rend le mécanisme visible (ch. 3).',
    commentaireEn: 'The oral-exam form of Bayes\' theorem, to unroll in three lines over a fictitious population of 10,000. THE absolute classic: disease at 1% prevalence, test 99% sensitive, 5% false positives — 100 sick of whom 99 detected; 9,900 healthy of whom 495 wrongly positive; among the 594 positives, 99 are true: 99/594 = 1/6 = 16.666667%, not 99%. False positives DROWN the true ones when what you seek is rare: 495 against 99, five to one. The candidate who produces the formula is correct; the one who unrolls the counts scores, because the method recites from memory and makes the mechanism visible (ch. 3).',
  },
  {
    id: 'm13-f-08',
    moduleId: M13,
    nom: 'Bayes en ratio : la formule compacte',
    nomEn: 'Bayes as a ratio: the compact formula',
    latex: 'P(\\text{malade} \\mid +) = \\frac{p \\cdot s}{p \\cdot s + (1 - p) \\cdot f}',
    commentaire: 'La même vérité en une fraction : p la prévalence (le taux de base), s la sensibilité du test, f le taux de faux positifs. Avec p = 1 %, s = 99 %, f = 5 % : 0,0099/(0,0099 + 0,0495) = 16,666667 %. L\'erreur d\'intuition porte un nom — le base rate neglect : lire « fiable à 99 % » et confondre P(test⁺ | malade) avec P(malade | test⁺), deux conditionnelles différentes que seule la prévalence relie. La transposition marché attendue par le jury : un indicateur de crise « fiable à 99 % » qui guette un événement à 1 % produit surtout de fausses alertes (m10, m11) ; un signal rare trouvé par mille backtests est probablement un faux positif (m2). La phrase qui résume : la force d\'un signal dépend de la rareté de ce qu\'il cherche (ch. 3).',
    commentaireEn: 'The same truth in one fraction: p the prevalence (the base rate), s the test\'s sensitivity, f the false positive rate. With p = 1%, s = 99%, f = 5%: 0.0099/(0.0099 + 0.0495) = 16.666667%. The intuition error has a name — base rate neglect: reading "99% reliable" and confusing P(test⁺ | sick) with P(sick | test⁺), two different conditionals that only the prevalence connects. The market transposition the jury expects: a "99% reliable" crisis indicator watching a 1% event mostly produces false alarms (m10, m11); a rare signal found by a thousand backtests is probably a false positive (m2). The summary sentence: a signal\'s strength depends on the rarity of what it seeks (ch. 3).',
  },
  {
    id: 'm13-f-09',
    moduleId: M13,
    nom: 'Combinaisons : choisir k parmi n',
    nomEn: 'Combinations: choosing k out of n',
    latex: 'C(n, k) = \\frac{n!}{k!\\,(n-k)!}',
    commentaire: 'Compter sans énumérer, quand l\'ordre ne compte pas. L\'ancre universelle : C(52, 5) = 2 598 960 mains de poker. Le réflexe d\'oral qui distingue : SIMPLIFIER avant de multiplier — (52 × 51 × 50 × 49 × 48)/(5 × 4 × 3 × 2) s\'apprivoise en divisant d\'abord (50/5 = 10, 48/4 = 12, 51/3 = 17, 52/2 = 26) pour finir sur 26 × 17 × 10 × 12 × 49, sans jamais manipuler un nombre à huit chiffres. Mini-classique associé : deux as d\'affilée sans remise = 4/52 × 3/51 = 1/221 ≈ 0,45 % — le point noté est le conditionnement du second tirage. Et les combinaisons reviennent où on ne les attend pas : la généralisation des deux œufs du ch. 4 se referme sur une somme de C(e, i) (ch. 3, 4).',
    commentaireEn: 'Counting without enumerating, when order does not matter. The universal anchor: C(52, 5) = 2,598,960 poker hands. The distinguishing oral reflex: SIMPLIFY before multiplying — (52 × 51 × 50 × 49 × 48)/(5 × 4 × 3 × 2) tames itself by dividing first (50/5 = 10, 48/4 = 12, 51/3 = 17, 52/2 = 26) to finish on 26 × 17 × 10 × 12 × 49, never handling an eight-digit number. The associated mini-classic: two aces in a row without replacement = 4/52 × 3/51 = 1/221 ≈ 0.45% — the graded point is conditioning the second draw. And combinations return where you least expect them: ch. 4\'s two-egg generalisation closes on a sum of C(e, i) (ch. 3, 4).',
  },
  {
    id: 'm13-f-10',
    moduleId: M13,
    nom: 'Série de succès consécutifs',
    nomEn: 'A run of consecutive successes',
    latex: 'P(n \\text{ succès consécutifs}) = p^n',
    commentaire: 'Le miroir exact du « au moins un » : ici on multiplie les SUCCÈS, là-bas on multipliait les échecs — confondre les deux directions est la faute classique de fin d\'entretien, quand la fatigue monte. Les ancres : cinq piles d\'affilée = (1/2)⁵ = 3,125 % ; trois 6 d\'affilée = (1/6)³ = 0,462963 %. Le garde-fou associé est le sophisme du joueur : après dix piles, le prochain lancer reste à 50 % — la pièce n\'a pas de mémoire, la loi des grands nombres dilue les écarts, elle ne les compense jamais coup par coup. Et l\'étage bayésien pour les jurys qui creusent : dix piles n\'arrivent qu\'à 0,1 % — un esprit bayésien commence à douter de la pièce elle-même (ch. 3).',
    commentaireEn: 'The exact mirror of "at least one": here you multiply the SUCCESSES, there you multiplied the failures — mixing up the two directions is the classic end-of-interview mistake, when fatigue sets in. The anchors: five heads in a row = (1/2)⁵ = 3.125%; three 6s in a row = (1/6)³ = 0.462963%. The associated guardrail is the gambler\'s fallacy: after ten heads, the next flip is still 50% — the coin has no memory, the law of large numbers dilutes deviations, it never offsets them flip by flip. And the Bayesian upper floor for juries who dig: ten heads only happen 0.1% of the time — a Bayesian mind starts doubting the coin itself (ch. 3).',
  },
  {
    id: 'm13-f-11',
    moduleId: M13,
    nom: 'Espérance d\'un jeu discret',
    nomEn: 'Expected value of a discrete game',
    latex: 'E = \\sum_i p_i \\, g_i',
    commentaire: 'La moyenne des gains pondérée par leurs probabilités — la VALEUR autour de laquelle tout jeu d\'entretien s\'organise : prix d\'entrée équitable, bid, ask, cote. Le premier réflexe, non négociable : calculer E AVANT d\'ouvrir la bouche — le candidat qui annonce un prix puis calcule a coté au hasard, ce qu\'aucun desk ne pardonne. Les ancres : « vous gagnez la face du dé en euros » vaut 3,50 € ; « 10 € si la carte est rouge » vaut 5 €. Le métier derrière : un market maker qui cote mille fois par jour ne gagne pas sur un coup, il gagne en espérance — le jury vérifie que vous pensez en espérance, pas en anecdote (ch. 5).',
    commentaireEn: 'The probability-weighted average of the payoffs — the VALUE around which every interview game is organised: fair entry price, bid, ask, odds. The first, non-negotiable reflex: compute E BEFORE opening your mouth — the candidate who quotes a price and then computes has quoted at random, which no desk forgives. The anchors: "you win the die\'s face in euros" is worth €3.50; "€10 if the card is red" is worth €5. The trade behind it: a market maker quoting a thousand times a day does not win on one trade, they win in expectation — the jury checks that you think in expectation, not in anecdote (ch. 5).',
  },
  {
    id: 'm13-f-12',
    moduleId: M13,
    nom: 'Espérance d\'un dé à f faces',
    nomEn: 'Expected value of an f-sided die',
    latex: 'E[\\text{dé}] = \\frac{f + 1}{2}',
    commentaire: 'La forme fermée de la brique de tous les jeux de dés : E[d6] = 3,5 ; E[d100] = 50,5. Méfiez-vous du piège du « milieu des faces » : le milieu de 1-6 lu trop vite donne 3 — la vraie espérance est (6 + 1)/2 = 3,5, car les faces vont de 1 à f, pas de 0 à f. C\'est autour de cette valeur que se construit la cotation : bid dessous, ask dessus, fourchette symétrique — 3,3/3,7 est une bonne cote, 1/6 est un refus de coter déguisé. Et sachez défendre la largeur : l\'écart-type d\'un lancer de d6 vaut environ 1,71 — votre marge de 0,2 est minuscule face à ce bruit et ne devient un revenu que répétée : le teneur de marché est une loi des grands nombres (ch. 5, m1).',
    commentaireEn: 'The closed form of the building block of all dice games: E[d6] = 3.5; E[d100] = 50.5. Beware the "middle of the faces" trap: the midpoint of 1-6 read too fast gives 3 — the true expectation is (6 + 1)/2 = 3.5, because faces run from 1 to f, not 0 to f. Around this value the quote is built: bid below, ask above, symmetric spread — 3.3/3.7 is a good quote, 1/6 is a disguised refusal to quote. And know how to defend the width: the standard deviation of one d6 roll is about 1.71 — your 0.2 margin is tiny against that noise and only becomes income through repetition: the market maker is a law of large numbers (ch. 5, m1).',
  },
  {
    id: 'm13-f-13',
    moduleId: M13,
    nom: 'Le dé à relance : l\'option cachée',
    nomEn: 'The die with a re-roll: the hidden option',
    latex: 'E = \\tfrac{1}{2} \\times 5 + \\tfrac{1}{2} \\times 3{,}5 = 4{,}25',
    commentaire: 'La variante favorite des jurys, à résoudre à rebours comme toute option : le second lancer vaut 3,5, donc au premier on garde tout ce qui bat 3,5 — le 4, le 5 ou le 6, de moyenne 5 (probabilité ½) — et on relance le reste. La leçon à énoncer explicitement : le droit de relancer vaut 4,25 − 3,5 = 0,75 — une option, même jamais exercée à perte, a toujours une valeur positive (m8 : le droit sans l\'obligation). Préparez la relance quasi systématique du jury — « et avec deux relances ? » : la valeur de continuation passe à 4,25, donc on ne garde plus que 5 ou 6, et E = 1/3 × 5,5 + 2/3 × 4,25 = 4,666667. Le seuil de conservation MONTE avec le nombre de relances restantes — plus l\'option est riche, plus on est exigeant ; repérer seul ce changement de stratégie est la différence entre une bonne réponse et une embauche (ch. 5).',
    commentaireEn: 'The juries\' favourite variant, solved backwards like any option: the second roll is worth 3.5, so on the first you keep whatever beats 3.5 — the 4, 5 or 6, averaging 5 (probability ½) — and re-roll the rest. The lesson to state explicitly: the right to re-roll is worth 4.25 − 3.5 = 0.75 — an option, even one never exercised at a loss, always has positive value (m8: the right without the obligation). Prepare the jury\'s near-systematic follow-up — "and with two re-rolls?": the continuation value rises to 4.25, so you only keep 5 or 6, and E = 1/3 × 5.5 + 2/3 × 4.25 = 4.666667. The keep threshold RISES with the number of re-rolls left — the richer the option, the pickier you are; spotting that strategy change unprompted is the difference between a good answer and a hire (ch. 5).',
  },
  {
    id: 'm13-f-14',
    moduleId: M13,
    nom: 'Cote équitable d\'un pari',
    nomEn: 'Fair odds of a bet',
    latex: '\\text{cote} = \\frac{100}{p}',
    commentaire: 'En convention « pour 1 » (toucher la cote, mise comprise, pour 1 misé), la cote qui rend le pari d\'espérance nulle pour une probabilité p en % : gagner à 25 % mérite une cote de 4 ; un 6 sur un dé, une cote de 6. Toute cote au-dessus est un edge pour le parieur, en dessous pour la maison. Le point de convention à énoncer AVANT de calculer : « contre 1 » (gain net) donnerait 1/(cote + 1) en lecture inverse — annoncer sa convention est un geste de desk, pas une précaution d\'école. La brique se combine avec l\'espérance : un bookmaker à 7 pour 1 sur un 6 offre 1/6 × 7 = 1,166667 par euro misé, soit +0,17 d\'espérance (ch. 5).',
    commentaireEn: 'In the "for 1" convention (you collect the odds, stake included, per 1 staked), the odds making the bet zero-expectation for a probability p in %: winning at 25% deserves odds of 4; a 6 on a die, odds of 6. Any odds above are an edge for the bettor, below for the house. The convention point to state BEFORE computing: "to 1" (net gain) would give 1/(odds + 1) as the inverse reading — announcing your convention is a desk habit, not a schoolroom precaution. The building block combines with expectation: a bookmaker at 7 for 1 on a 6 offers 1/6 × 7 = 1.166667 per euro staked, i.e. +0.17 of expected value (ch. 5).',
  },
  {
    id: 'm13-f-15',
    moduleId: M13,
    nom: 'Probabilité implicite d\'une cote',
    nomEn: 'Implied probability of odds',
    latex: 'p_{\\text{implicite}} = \\frac{1}{\\text{cote}}',
    commentaire: 'La lecture inverse, la plus utile des deux : tout prix contient une probabilité, il suffit de l\'inverser. Une cote de 5 pour 1 price l\'événement à 1/5 = 20 % ; du 7 pour 1 sur un 6 le price à 14,3 % alors qu\'il arrive à 16,7 % — le pari a une espérance positive, c\'est un edge. À dire au jury : c\'est EXACTEMENT la gymnastique de la PD implicite d\'un spread de crédit au m5 (PD = s/LGD) — extraire la probabilité d\'un prix est le geste commun aux paris, au crédit et aux anticipations de banques centrales. Et repérer l\'edge n\'est que la moitié de la réponse : l\'autre moitié est de dimensionner — « je mise petit, et je répète » est la phrase qui sonne desk (ch. 5).',
    commentaireEn: 'The inverse reading, the more useful of the two: every price contains a probability, you just invert it. Odds of 5 for 1 price the event at 1/5 = 20%; 7 for 1 on a 6 prices it at 14.3% while it happens 16.7% of the time — the bet has positive expectation, that is an edge. To tell the jury: it is EXACTLY the m5 spread-implied PD gymnastics (PD = s/LGD) — extracting a probability from a price is the move common to bets, credit and central bank expectations. And spotting the edge is only half the answer: the other half is sizing — "I bet small, and I repeat" is the sentence that sounds like a desk (ch. 5).',
  },
  {
    id: 'm13-f-16',
    moduleId: M13,
    nom: 'Fermi : la moyenne géométrique des bornes',
    nomEn: 'Fermi: the geometric mean of the bounds',
    latex: '\\hat{x} = \\sqrt{b \\times h}',
    commentaire: 'Le quatrième temps de toute estimation de Fermi : entre deux bornes sûres b et h, le milieu se prend en GÉOMÉTRIQUE, jamais en arithmétique. L\'ancre : entre 1 000 et 1 000 000, la géométrique donne √(10⁹) = 31 622 ≈ 30 000 — au même facteur ~32 des deux bornes — quand l\'arithmétique dit 500 500, à un facteur 500 de la borne basse : elle l\'a écrasée et se trompe d\'un facteur 15. La raison profonde : une incertitude d\'ordre de grandeur est multiplicative, et ne se symétrise qu\'en log — où la moyenne arithmétique des logs redonne exactement la géométrique. C\'est la même mathématique qui fait du produit de facteurs aléatoires une lognormale (m2) et qui modélise le prix d\'un actif au m8 : elle sert à pricer une option comme à compter des accordeurs de pianos (ch. 2).',
    commentaireEn: 'The fourth step of any Fermi estimate: between two safe bounds b and h, the midpoint is taken GEOMETRICALLY, never arithmetically. The anchor: between 1,000 and 1,000,000, the geometric mean gives √(10⁹) = 31,622 ≈ 30,000 — at the same factor ~32 from both bounds — while the arithmetic mean says 500,500, a factor of 500 from the low bound: it crushed it and errs by a factor of 15. The deep reason: order-of-magnitude uncertainty is multiplicative, and only becomes symmetric in logs — where the arithmetic mean of the logs gives back exactly the geometric mean. It is the same mathematics that turns a product of random factors into a lognormal (m2) and models an asset price in m8: it prices an option and counts piano tuners alike (ch. 2).',
  },
  {
    id: 'm13-f-17',
    moduleId: M13,
    nom: 'Critère de Kelly (en survol)',
    nomEn: 'Kelly criterion (overview)',
    latex: 'f^* = \\frac{bp - q}{b}',
    commentaire: 'Combien miser quand on a un edge : la fraction du capital qui maximise la croissance composée à long terme, avec p la probabilité de gain, q = 1 − p, et b le gain NET par unité misée (la cote « pour 1 » moins la mise). L\'ancre du ch. 5 : un pari à 2 pour 1 (b = 1) gagné à 52 % donne f* = (0,52 − 0,48)/1 = 4 % du capital — pas 100 %, pas 20 % : 4. Au-delà de f*, l\'espérance par coup monte encore mais la croissance composée chute jusqu\'à devenir négative : trop miser transforme un jeu gagnant en ruine quasi certaine, à cause de l\'asymétrie des rendements composés (perdre 50 % exige +100 %). En pratique les desks misent « demi-Kelly », car l\'edge est estimé, pas connu. C\'est la version calculable du m12 : la taille de la position est une décision distincte de son sens — et souvent la plus importante des deux (ch. 5).',
    commentaireEn: 'How much to bet when you have an edge: the fraction of capital that maximises long-run compounded growth, with p the win probability, q = 1 − p, and b the NET gain per unit staked (the "for 1" odds minus the stake). Ch. 5\'s anchor: a 2-for-1 bet (b = 1) won 52% of the time gives f* = (0.52 − 0.48)/1 = 4% of capital — not 100%, not 20%: 4. Beyond f*, the per-bet expectation still rises but compounded growth falls until it turns negative: overbetting turns a winning game into near-certain ruin, because of the asymmetry of compounded returns (losing 50% requires +100%). In practice desks bet "half-Kelly", because the edge is estimated, not known. It is the computable version of m12: position size is a decision distinct from direction — and often the more important of the two (ch. 5).',
  },
];
