import type { Flashcard } from '../../../engine/types';

const M2 = '02-methodes-quantitatives';

// 120 cartes : 30 definitions, 20 formules, 10 ordres de grandeur, 24 pieges,
// 22 reflexes jury, 14 calculs mentaux.
// Couverture : ch1 valeur temps, ch2 statistiques descriptives, ch3 probabilites,
// ch4 distributions, ch5 echantillonnage & IC, ch6 tests d'hypotheses, ch7 regression & Monte-Carlo.
export const flashcards: Flashcard[] = [
  // ───────────────────────── Chapitre 1 — La valeur temps de l'argent ─────────────────────────
  {
    id: 'm2-fc-001',
    moduleId: M2,
    tags: ['definition', 'tvm'],
    recto: 'La valeur temps de l\'argent, c\'est quoi ?',
    verso: 'Un euro aujourd\'hui vaut plus qu\'un euro demain : il peut être placé. Capitalisation $VF = VA(1+r)^n$, actualisation $VA = VF/(1+r)^n$, et additivité : la valeur d\'une série de flux = la somme des VA de chaque flux.',
    rectoEn: 'What is the time value of money?',
    versoEn: 'A euro today is worth more than a euro tomorrow: it can be invested. Compounding $FV = PV(1+r)^n$, discounting $PV = FV/(1+r)^n$, and additivity: the value of a cash-flow series = the sum of each flow\'s PV.',
  },
  {
    id: 'm2-fc-002',
    moduleId: M2,
    tags: ['definition', 'tvm'],
    recto: 'Une annuité, c\'est quoi ?',
    verso: 'Série de flux constants F versés à intervalles réguliers pendant n périodes ; convention de fin de période : le premier flux tombe dans une période, pas aujourd\'hui. Le motif des mensualités, des loyers, des coupons.',
    rectoEn: 'What is an annuity?',
    versoEn: 'A series of constant cash flows F paid at regular intervals over n periods; end-of-period convention: the first flow lands one period from now, not today. The pattern of loan payments, rents and coupons.',
  },
  {
    id: 'm2-fc-003',
    moduleId: M2,
    tags: ['formule', 'tvm'],
    recto: 'Formule de la valeur actuelle d\'une annuité ?',
    verso: '$VA = F \\times \\frac{1-(1+r)^{-n}}{r}$. Ex. du cours : 100 € par an pendant 3 ans à 5 % → 100 × 2,723248 = 272,32 € — et non 300 € : chaque flux est rogné par l\'actualisation.',
    rectoEn: 'Present value of an annuity?',
    versoEn: '$PV = F \\times \\frac{1-(1+r)^{-n}}{r}$. Course example: €100 a year for 3 years at 5% → 100 × 2.723248 = €272.32 — not €300: each flow is trimmed by discounting.',
  },
  {
    id: 'm2-fc-005',
    moduleId: M2,
    tags: ['formule', 'tvm'],
    recto: 'Formule de la mensualité d\'un prêt de capital K sur n mois ?',
    verso: '$M = K \\times \\frac{r}{1-(1+r)^{-n}}$ — l\'annuité lue à l\'envers. Ex. : 10 000 € sur 48 mois à 0,4 %/mois → 229,39 € ; 11 010,63 € remboursés, soit 1 010,63 € d\'intérêts. Tout en mensuel : taux ET durée.',
    rectoEn: 'Monthly payment on a loan of principal K over n months?',
    versoEn: '$M = K \\times \\frac{r}{1-(1+r)^{-n}}$ — the annuity read backwards. E.g.: €10,000 over 48 months at 0.4%/month → €229.39; €11,010.63 repaid, i.e. €1,010.63 of interest. Everything monthly: rate AND term.',
  },
  {
    id: 'm2-fc-006',
    moduleId: M2,
    tags: ['piege', 'tvm'],
    recto: '100 € par an pendant 3 ans à 5 % : 272,32 € ou 315,25 € ?',
    verso: 'Les deux — selon la DATE. 272,32 € est la valeur d\'aujourd\'hui (VA), 315,25 € la valeur en fin d\'année 3 (VF). Même nombre vu de deux dates : 272,3248 × 1,05³ = 315,25. Confondre les dates est l\'erreur classique.',
    rectoEn: '€100 a year for 3 years at 5%: €272.32 or €315.25?',
    versoEn: 'Both — depending on the DATE. €272.32 is today\'s value (PV), €315.25 the value at end of year 3 (FV). Same number seen from two dates: 272.3248 × 1.05³ = 315.25. Mixing up dates is the classic mistake.',
  },
  {
    id: 'm2-fc-007',
    moduleId: M2,
    tags: ['definition', 'tvm'],
    recto: 'Une perpétuité, c\'est quoi ?',
    verso: 'Annuité sans fin : un flux constant F versé pour toujours, de valeur pourtant finie, $P = F/r$. Les flux lointains ne pèsent presque rien actualisés : à 4 %, le flux de l\'année 100 vaut 0,99 €, celui de l\'année 200 moins de 2 centimes.',
    rectoEn: 'What is a perpetuity?',
    versoEn: 'An annuity that never ends: a constant flow F paid forever, yet with a finite value, $P = F/r$. Distant flows weigh almost nothing once discounted: at 4%, the year-100 flow is worth €0.99, the year-200 flow under 2 cents.',
  },
  {
    id: 'm2-fc-008',
    moduleId: M2,
    tags: ['formule', 'tvm'],
    recto: 'Formule de la perpétuité, et l\'intuition derrière ?',
    verso: '$P = F/r$ — la limite de l\'annuité quand n → ∞. Ex. : 50 €/an à 4 % → 1 250 €. Intuition : 1 250 € placés à 4 % produisent exactement 50 €/an, éternellement, sans entamer le capital.',
    rectoEn: 'Perpetuity formula, and the intuition behind it?',
    versoEn: '$P = F/r$ — the limit of the annuity as n → ∞. E.g.: €50/yr at 4% → €1,250. Intuition: €1,250 invested at 4% yields exactly €50 a year, forever, without touching the principal.',
  },
  {
    id: 'm2-fc-009',
    moduleId: M2,
    tags: ['piege', 'tvm'],
    recto: 'Perpétuité de 50 € à 4 % : 1 250 €. Et si un flux tombe aussi aujourd\'hui ?',
    verso: 'P = F + F/r = 50 + 1 250 = 1 300 €. La formule F/r suppose le premier flux dans UNE période. Le détail qui tue à l\'oral : toujours vérifier la date du premier flux.',
    rectoEn: '€50 perpetuity at 4%: €1,250. What if a flow is also paid today?',
    versoEn: 'P = F + F/r = 50 + 1,250 = €1,300. The F/r formula assumes the first flow comes in ONE period. The detail that kills at the oral: always check the date of the first flow.',
  },
  {
    id: 'm2-fc-010',
    moduleId: M2,
    tags: ['calcul-mental', 'tvm'],
    recto: 'De tête : que valent 100 € par an pour toujours à 5 % ? Et 50 € à 4 % ?',
    verso: 'F/r : 100/0,05 = 2 000 € ; 50/0,04 = 1 250 €. Routine : diviser le flux par le taux — la formule la plus courte de la finance, à dégainer en une seconde.',
    rectoEn: 'In your head: what is €100 a year forever worth at 5%? And €50 at 4%?',
    versoEn: 'F/r: 100/0.05 = €2,000; 50/0.04 = €1,250. Routine: divide the flow by the rate — the shortest formula in finance, to be drawn in one second.',
  },
  {
    id: 'm2-fc-011',
    moduleId: M2,
    tags: ['definition', 'tvm'],
    recto: 'La VAN (valeur actuelle nette), c\'est quoi ?',
    verso: 'La somme des flux actualisés au coût du capital, investissement initial déduit : $VAN = -I_0 + \\sum F_t/(1+r)^t$. Règle : VAN positive, on accepte ; négative, on refuse. En anglais : NPV.',
    rectoEn: 'What is NPV (net present value)?',
    versoEn: 'The sum of cash flows discounted at the cost of capital, minus the initial outlay: $NPV = -I_0 + \\sum F_t/(1+r)^t$. Rule: positive NPV, accept; negative, reject.',
  },
  {
    id: 'm2-fc-012',
    moduleId: M2,
    tags: ['formule', 'tvm'],
    recto: 'VAN d\'une machine à 1 000 € rapportant 400 €/an pendant 3 ans, coût du capital 10 % ?',
    verso: 'VAN = −1 000 + 400/1,1 + 400/1,1² + 400/1,1³ = −1 000 + 994,74 = −5,26 € → refus. 1 200 € bruts ne valent que 994,74 € d\'aujourd\'hui dès que l\'argent coûte 10 %.',
    rectoEn: 'NPV of a €1,000 machine returning €400/yr for 3 years, 10% cost of capital?',
    versoEn: 'NPV = −1,000 + 400/1.1 + 400/1.1² + 400/1.1³ = −1,000 + 994.74 = −€5.26 → reject. €1,200 gross is only worth €994.74 today once money costs 10%.',
  },
  {
    id: 'm2-fc-013',
    moduleId: M2,
    tags: ['definition', 'tvm'],
    recto: 'Le TRI (taux de rentabilité interne), c\'est quoi ?',
    verso: 'Le taux d\'actualisation qui annule la VAN — le rendement intrinsèque du projet. Décision : accepter si TRI > coût du capital. Jamais le comparer à zéro : c\'est le contresens classique. En anglais : IRR.',
    rectoEn: 'What is the IRR (internal rate of return)?',
    versoEn: 'The discount rate that sets NPV to zero — the project\'s intrinsic return. Decision: accept if IRR > cost of capital. Never compare it to zero: that is the classic misreading.',
  },
  {
    id: 'm2-fc-014',
    moduleId: M2,
    tags: ['formule', 'tvm'],
    recto: 'Comment estimer un TRI sans solveur ? (machine 1 000 €, 400 €/an sur 3 ans)',
    verso: 'Encadrer puis interpoler : VAN(9 %) = +12,52 €, VAN(10 %) = −5,26 €. TRI ≈ 9 + 12,52/(12,52 + 5,26) ≈ 9,70 %. Et 9,70 % < 10 % de coût du capital → refus, cohérent avec la VAN négative.',
    rectoEn: 'How do you estimate an IRR without a solver? (€1,000 machine, €400/yr for 3 years)',
    versoEn: 'Bracket then interpolate: NPV(9%) = +€12.52, NPV(10%) = −€5.26. IRR ≈ 9 + 12.52/(12.52 + 5.26) ≈ 9.70%. And 9.70% < 10% cost of capital → reject, consistent with the negative NPV.',
  },
  {
    id: 'm2-fc-015',
    moduleId: M2,
    tags: ['piege', 'tvm'],
    recto: 'Pourquoi le TRI peut-il dérailler là où la VAN reste fiable ?',
    verso: 'Flux non conventionnels (le signe change plusieurs fois) → plusieurs TRI, ou aucun. Pourcentage aveugle à la taille : 50 % sur 100 € < 15 % sur 100 000 €. Et il suppose le réinvestissement des flux au TRI lui-même. En cas de conflit : la VAN tranche.',
    rectoEn: 'Why can the IRR go off the rails where NPV stays reliable?',
    versoEn: 'Non-conventional flows (sign changes several times) → multiple IRRs, or none. A percentage blind to size: 50% on €100 < 15% on €100,000. And it implicitly assumes flows are reinvested at the IRR itself. In a conflict: NPV decides.',
  },
  {
    id: 'm2-fc-016',
    moduleId: M2,
    tags: ['reflexe-jury', 'tvm'],
    recto: 'Le jury : « VAN et TRI se contredisent sur deux projets. Lequel suivez-vous ? »',
    verso: 'Réflexe : la VAN, toujours — elle mesure la création de valeur en euros. Le TRI est un pourcentage, aveugle à la taille et à la durée : 50 % sur 100 € créent moins de valeur que 15 % sur 100 000 €.',
    rectoEn: 'The panel: "NPV and IRR disagree on two projects. Which one do you follow?"',
    versoEn: 'Reflex: NPV, always — it measures value creation in euros. IRR is a percentage, blind to size and duration: 50% on €100 creates less value than 15% on €100,000.',
  },
  {
    id: 'm2-fc-017',
    moduleId: M2,
    tags: ['formule', 'tvm'],
    recto: 'Formule du taux annuel effectif d\'un taux nominal r composé m fois par an ?',
    verso: '$r_{\\text{eff}} = (1 + r/m)^m - 1$. Ex. : 4,90 % mensuel → (1 + 0,049/12)¹² − 1 = 5,01 %. Deux nominaux à fréquences différentes ne se comparent jamais directement — le service que rend le TAEG.',
    rectoEn: 'Effective annual rate of a nominal rate r compounded m times a year?',
    versoEn: '$r_{\\text{eff}} = (1 + r/m)^m - 1$. E.g.: 4.90% monthly → (1 + 0.049/12)¹² − 1 = 5.01%. Two nominal rates with different compounding frequencies are never directly comparable — exactly what an APR fixes.',
  },
  {
    id: 'm2-fc-018',
    moduleId: M2,
    tags: ['reflexe-jury', 'tvm'],
    recto: 'Le jury : « Banque A : 5,00 % capitalisé annuellement. Banque B : 4,90 % mensuel. Vous placez où ? »',
    verso: 'Réflexe : tout convertir en effectif annuel. B : (1 + 0,049/12)¹² − 1 = 5,01 % > 5,00 %. B gagne — la composition mensuelle fait plus que combler les 10 pb d\'écart facial.',
    rectoEn: 'The panel: "Bank A: 5.00% compounded annually. Bank B: 4.90% monthly. Where do you put the money?"',
    versoEn: 'Reflex: convert everything to an effective annual rate. B: (1 + 0.049/12)¹² − 1 = 5.01% > 5.00%. B wins — monthly compounding more than closes the 10bp headline gap.',
  },
  {
    id: 'm2-fc-019',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'tvm'],
    recto: 'La règle de 72, et son usage ?',
    verso: 'Années pour doubler ≈ 72/taux (en %). À 6 % → 12 ans ; à 8 % → 9 ans. L\'approximation mentale de la capitalisation composée, fiable pour les taux usuels.',
    rectoEn: 'The rule of 72, and how to use it?',
    versoEn: 'Years to double ≈ 72/rate (in %). At 6% → 12 years; at 8% → 9 years. The mental shortcut for compound growth, reliable for usual rates.',
  },
  {
    id: 'm2-fc-020',
    moduleId: M2,
    tags: ['calcul-mental', 'tvm'],
    recto: 'De tête : un placement à 4 % double en combien de temps ? Et à 2 % ?',
    verso: 'Règle de 72 : 72/4 = 18 ans ; 72/2 = 36 ans. Dans l\'autre sens : doubler en 10 ans exige ≈ 7,2 % par an.',
    rectoEn: 'In your head: how long for an investment to double at 4%? And at 2%?',
    versoEn: 'Rule of 72: 72/4 = 18 years; 72/2 = 36 years. The other way round: doubling in 10 years requires ≈ 7.2% a year.',
  },

  // ───────────────────────── Chapitre 2 — Statistiques descriptives ─────────────────────────
  {
    id: 'm2-fc-021',
    moduleId: M2,
    tags: ['definition', 'statistiques'],
    recto: 'Arithmétique, géométrique, harmonique : quelle moyenne pour quelle question ?',
    verso: 'Arithmétique : rendement à attendre sur UNE période. Géométrique : performance composée constatée sur plusieurs périodes. Harmonique : prix moyen d\'achat à montants constants (DCA). Et toujours : arith ≥ géo ≥ harmo.',
    rectoEn: 'Arithmetic, geometric, harmonic: which mean for which question?',
    versoEn: 'Arithmetic: expected return over ONE period. Geometric: realized compounded performance over several periods. Harmonic: average purchase price with constant amounts (DCA). And always: arithmetic ≥ geometric ≥ harmonic.',
  },
  {
    id: 'm2-fc-022',
    moduleId: M2,
    tags: ['formule', 'statistiques'],
    recto: 'Formule de la moyenne géométrique des rendements ?',
    verso: '$r_g = [\\prod (1+r_i)]^{1/n} - 1$. Ex. : +10 % puis −10 % → √(1,10 × 0,90) − 1 = √0,99 − 1 ≈ −0,50 % par an. La seule moyenne qui respecte la composition des rendements.',
    rectoEn: 'Geometric mean of returns?',
    versoEn: '$r_g = [\\prod (1+r_i)]^{1/n} - 1$. E.g.: +10% then −10% → √(1.10 × 0.90) − 1 = √0.99 − 1 ≈ −0.50% a year. The only mean that respects the compounding of returns.',
  },
  {
    id: 'm2-fc-023',
    moduleId: M2,
    tags: ['piege', 'statistiques'],
    recto: '+10 % puis −10 % : le fonds est-il revenu à son point de départ ?',
    verso: 'Non : 100 € → 110 € → 99 €. La perte s\'applique à une base plus haute (110) : elle détruit 11 € contre 10 € créés. Moyenne arithmétique 0 %, géométrique −0,50 %/an. Une « moyenne nulle » peut cacher une perte.',
    rectoEn: '+10% then −10%: is the fund back where it started?',
    versoEn: 'No: €100 → €110 → €99. The loss applies to a higher base (110): it destroys €11 where the gain created only €10. Arithmetic mean 0%, geometric −0.50%/yr. A "zero average" can hide a loss.',
  },
  {
    id: 'm2-fc-024',
    moduleId: M2,
    tags: ['piege', 'statistiques'],
    recto: 'Deux fonds, même moyenne arithmétique. Composent-ils pareil ?',
    verso: 'Non : l\'écart arithmétique − géométrique ≈ σ²/2 — le volatility drag. Ex. : +20 % puis −10 % → arith 5,00 %, géo 3,92 % (1,08 pt d\'écart). À moyenne égale, la volatilité érode la performance composée.',
    rectoEn: 'Two funds, same arithmetic mean. Do they compound the same?',
    versoEn: 'No: the arithmetic − geometric gap ≈ σ²/2 — the volatility drag. E.g.: +20% then −10% → arithmetic 5.00%, geometric 3.92% (a 1.08pt gap). At equal mean, volatility erodes compounded performance.',
  },
  {
    id: 'm2-fc-025',
    moduleId: M2,
    tags: ['reflexe-jury', 'statistiques'],
    recto: 'Le jury : « Votre fonds fait −50 % puis +50 %. Vous êtes revenu à l\'équilibre ? »',
    verso: 'Réflexe : non, −25 %. 100 € → 50 € → 75 € : le +50 % s\'applique à une base divisée par deux. Après −50 %, il faut +100 % pour revenir. La composition n\'est pas une addition.',
    rectoEn: 'The panel: "Your fund does −50% then +50%. Are you back to even?"',
    versoEn: 'Reflex: no, −25%. €100 → €50 → €75: the +50% applies to a halved base. After −50%, you need +100% to get back. Compounding is not addition.',
  },
  {
    id: 'm2-fc-026',
    moduleId: M2,
    tags: ['formule', 'statistiques'],
    recto: 'Formule de la moyenne harmonique, et son terrain d\'usage ?',
    verso: '$H = n / \\sum (1/x_i)$. Ex. : 100 € investis à 10 €/part puis 100 € à 20 € → 15 parts pour 200 €, soit 13,33 €/part = 2/(1/10 + 1/20). Le prix moyen du DCA — et des ratios à numérateur constant (P/E).',
    rectoEn: 'Harmonic mean formula, and where it applies?',
    versoEn: '$H = n / \\sum (1/x_i)$. E.g.: €100 invested at €10/share then €100 at €20 → 15 shares for €200, i.e. €13.33/share = 2/(1/10 + 1/20). The average price of DCA — and of constant-numerator ratios (P/E).',
  },
  {
    id: 'm2-fc-027',
    moduleId: M2,
    tags: ['piege', 'statistiques'],
    recto: 'Vous achetez pour 100 € à 10 €/part, puis pour 100 € à 20 €. Prix moyen : 15 € ?',
    verso: 'Non : 13,33 € — la moyenne harmonique. Le montant fixe achète PLUS de parts quand c\'est bas (10 + 5 = 15 parts pour 200 €). La moyenne arithmétique des prix (15 €) surestime toujours le coût réel du DCA.',
    rectoEn: 'You invest €100 at €10/share, then €100 at €20. Average price: €15?',
    versoEn: 'No: €13.33 — the harmonic mean. The fixed amount buys MORE shares when the price is low (10 + 5 = 15 shares for €200). The arithmetic mean of prices (€15) always overstates the true DCA cost.',
  },
  {
    id: 'm2-fc-028',
    moduleId: M2,
    tags: ['definition', 'statistiques'],
    recto: 'Variance et écart-type d\'échantillon : définition ?',
    verso: '$s^2 = \\frac{1}{n-1}\\sum (r_i - \\bar{r})^2$, et $s = \\sqrt{s^2}$ ramène la dispersion dans l\'unité des données. En finance, l\'écart-type des rendements s\'appelle la volatilité. Diviseur n−1 : la moyenne est estimée sur les mêmes données.',
    rectoEn: 'Sample variance and standard deviation: definition?',
    versoEn: '$s^2 = \\frac{1}{n-1}\\sum (r_i - \\bar{r})^2$, and $s = \\sqrt{s^2}$ brings dispersion back to the data\'s unit. In finance, the standard deviation of returns is called volatility. The n−1 divisor: the mean is estimated on the same data.',
  },
  {
    id: 'm2-fc-029',
    moduleId: M2,
    tags: ['formule', 'statistiques'],
    recto: 'Variance de l\'échantillon {2, 4, 6} ?',
    verso: 'Moyenne 4 ; écarts −2, 0, +2 ; somme des carrés 8 ; variance = 8/(3−1) = 4 ; écart-type 2. Diviser par n donnerait 2,67 : biaisé vers le bas.',
    rectoEn: 'Variance of the sample {2, 4, 6}?',
    versoEn: 'Mean 4; deviations −2, 0, +2; sum of squares 8; variance = 8/(3−1) = 4; standard deviation 2. Dividing by n would give 2.67: biased downwards.',
  },
  {
    id: 'm2-fc-030',
    moduleId: M2,
    tags: ['reflexe-jury', 'statistiques'],
    recto: 'Le jury : « Pourquoi divisez-vous par n − 1 dans la variance ? » — en une phrase.',
    verso: '« Parce que la moyenne est elle-même estimée sur les mêmes données, ce qui sous-estime les écarts. » Bonus : les n écarts somment à zéro → n−1 informations indépendantes (degrés de liberté). Négligeable à 252 observations, décisif à 5.',
    rectoEn: 'The panel: "Why do you divide by n − 1 in the variance?" — in one sentence.',
    versoEn: '"Because the mean is itself estimated on the same data, which understates the deviations." Bonus: the n deviations sum to zero → n−1 independent pieces of information (degrees of freedom). Negligible at 252 observations, decisive at 5.',
  },
  {
    id: 'm2-fc-031',
    moduleId: M2,
    tags: ['formule', 'statistiques'],
    recto: 'Formule d\'annualisation de la volatilité ?',
    verso: '$\\sigma_{\\text{an}} = \\sigma_{\\text{quot}} \\times \\sqrt{252}$ — ce sont les variances qui s\'additionnent, pas les écarts-types. Ex. : 2 % quotidien → 2 × 15,8745 = 31,75 % annualisé. Hebdo ×√52, mensuel ×√12.',
    rectoEn: 'Volatility annualization formula?',
    versoEn: '$\\sigma_{\\text{ann}} = \\sigma_{\\text{daily}} \\times \\sqrt{252}$ — variances add over time, not standard deviations. E.g.: 2% daily → 2 × 15.8745 = 31.75% annualized. Weekly ×√52, monthly ×√12.',
  },
  {
    id: 'm2-fc-032',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'statistiques'],
    recto: '√252, ça vaut combien — et pourquoi le retenir ?',
    verso: '√252 ≈ 15,87 ≈ 16. Règle de tête du desk : 1 % de vol quotidienne ≈ 16 % annualisée. 252 = le nombre de jours de bourse dans l\'année.',
    rectoEn: 'What is √252 — and why memorize it?',
    versoEn: '√252 ≈ 15.87 ≈ 16. Desk rule of thumb: 1% daily vol ≈ 16% annualized. 252 = the number of trading days in a year.',
  },
  {
    id: 'm2-fc-033',
    moduleId: M2,
    tags: ['calcul-mental', 'statistiques'],
    recto: 'De tête : vol quotidienne 1 %, puis 2 % — vol annualisée ?',
    verso: '×16 : 1 % → ≈ 16 % ; 2 % → ≈ 32 % (31,75 % exact). Le raccourci √252 ≈ 16 donne l\'ordre de grandeur en une seconde.',
    rectoEn: 'In your head: 1% daily vol, then 2% — annualized vol?',
    versoEn: '×16: 1% → ≈ 16%; 2% → ≈ 32% (31.75% exact). The √252 ≈ 16 shortcut delivers the order of magnitude in one second.',
  },
  {
    id: 'm2-fc-034',
    moduleId: M2,
    tags: ['piege', 'statistiques'],
    recto: 'Vol quotidienne 2 % : pourquoi pas 2 × 252 = 504 % en annuel ?',
    verso: 'Ce sont les VARIANCES qui s\'additionnent dans le temps, pas les écarts-types. L\'écart-type croît en racine du temps : 2 × √252 = 31,75 %. Multiplier par 252 applique à l\'écart-type la règle de la variance — l\'erreur d\'unité classique.',
    rectoEn: '2% daily vol: why not 2 × 252 = 504% annualized?',
    versoEn: 'VARIANCES add over time, not standard deviations. The standard deviation grows with the square root of time: 2 × √252 = 31.75%. Multiplying by 252 applies the variance rule to a standard deviation — the classic unit error.',
  },
  {
    id: 'm2-fc-035',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'statistiques'],
    recto: 'Ordres de grandeur de la volatilité d\'un indice actions ?',
    verso: '≈ 15 % annualisée par temps calme ; au-delà de 30 %, marché en stress. Et 2 % de vol quotidienne = un indice qui bouge de plus de 2 % environ un jour sur trois (±1σ ≈ deux tiers des jours).',
    rectoEn: 'Orders of magnitude for an equity index\'s volatility?',
    versoEn: '≈ 15% annualized in calm markets; above 30%, the market is in stress. And 2% daily vol = an index moving more than 2% roughly one day in three (±1σ ≈ two thirds of days).',
  },
  {
    id: 'm2-fc-036',
    moduleId: M2,
    tags: ['definition', 'statistiques'],
    recto: 'La covariance, c\'est quoi — et son défaut ?',
    verso: '$s_{AB} = \\frac{1}{n-1}\\sum (r_{A,i}-\\bar{r}_A)(r_{B,i}-\\bar{r}_B)$ : positive si A et B s\'écartent de leurs moyennes du même côté. Défaut : unité illisible (%²) et amplitude dépendante des volatilités — d\'où la corrélation.',
    rectoEn: 'What is covariance — and its flaw?',
    versoEn: '$s_{AB} = \\frac{1}{n-1}\\sum (r_{A,i}-\\bar{r}_A)(r_{B,i}-\\bar{r}_B)$: positive when A and B deviate from their means on the same side. Flaw: an unreadable unit (%²) and a magnitude that depends on volatilities — hence correlation.',
  },
  {
    id: 'm2-fc-037',
    moduleId: M2,
    tags: ['definition', 'statistiques'],
    recto: 'La corrélation, c\'est quoi ?',
    verso: '$\\rho_{AB} = s_{AB}/(s_A s_B)$ : la covariance normalisée, toujours dans [−1, +1]. +1 liaison linéaire parfaite, −1 opposition parfaite, 0 absence de liaison linéaire. Elle ne capte QUE le linéaire.',
    rectoEn: 'What is correlation?',
    versoEn: '$\\rho_{AB} = s_{AB}/(s_A s_B)$: covariance normalized, always within [−1, +1]. +1 perfect linear link, −1 perfect opposition, 0 no linear link. It captures ONLY linear relationships.',
  },
  {
    id: 'm2-fc-038',
    moduleId: M2,
    tags: ['formule', 'statistiques'],
    recto: 'Covariance de A (+2, −1, +3, 0) et B (+1, 0, +4, +3), en % ?',
    verso: 'Moyennes 1 % et 2 % ; produits des écarts : −1, +4, +4, −1, somme 6 ; covariance = 6/(4−1) = 2 %². Positive : les deux actifs évoluent plutôt ensemble (jours 2 et 3).',
    rectoEn: 'Covariance of A (+2, −1, +3, 0) and B (+1, 0, +4, +3), in %?',
    versoEn: 'Means 1% and 2%; products of deviations: −1, +4, +4, −1, summing to 6; covariance = 6/(4−1) = 2%². Positive: the two assets mostly move together (days 2 and 3).',
  },
  {
    id: 'm2-fc-039',
    moduleId: M2,
    tags: ['formule', 'statistiques'],
    recto: 'Corrélation de l\'exemple du cours : covariance 2 %², variances 10/3 %² chacune ?',
    verso: '$s_A = s_B = \\sqrt{10/3} = 1{,}83\\ \\%$ ; ρ = 2/(1,8257 × 1,8257) = 2/3,3333 = 0,60. Ensemble sans être en phase parfaite : les jours de divergence retiennent ρ loin de 1.',
    rectoEn: 'Correlation in the course example: covariance 2%², variances 10/3%² each?',
    versoEn: '$s_A = s_B = \\sqrt{10/3} = 1.83\\%$; ρ = 2/(1.8257 × 1.8257) = 2/3.3333 = 0.60. Moving together without being perfectly in phase: the diverging days keep ρ well below 1.',
  },
  {
    id: 'm2-fc-004',
    moduleId: M2,
    tags: ['formule', 'statistiques'],
    recto: 'Formule de la variance d\'un portefeuille de deux actifs ?',
    verso: '$\\sigma_p^2 = w_A^2\\sigma_A^2 + w_B^2\\sigma_B^2 + 2\\,w_A w_B\\,\\rho_{AB}\\,\\sigma_A\\sigma_B$. Ex. : 50/50, σ = 10 % et 20 %, ρ = 0 → 25 + 100 = 125 %², soit σp = 11,2 % < 15 % de moyenne : le gain de diversification, décidé par ρ.',
    rectoEn: 'Two-asset portfolio variance formula?',
    versoEn: '$\\sigma_p^2 = w_A^2\\sigma_A^2 + w_B^2\\sigma_B^2 + 2\\,w_A w_B\\,\\rho_{AB}\\,\\sigma_A\\sigma_B$. E.g.: 50/50, σ = 10% and 20%, ρ = 0 → 25 + 100 = 125%², i.e. σp = 11.2% < the 15% average: the diversification gain, decided by ρ.',
  },
  {
    id: 'm2-fc-040',
    moduleId: M2,
    tags: ['piege', 'statistiques'],
    recto: 'Ventes de glaces et noyades sont corrélées. Les glaces tuent ?',
    verso: 'Corrélation n\'est pas causalité : la variable cachée est l\'été. Une corrélation élevée peut refléter un facteur commun, une causalité inverse ou une coïncidence d\'échantillon court. Réflexe : chercher le facteur caché avant l\'histoire causale.',
    rectoEn: 'Ice cream sales and drownings are correlated. Does ice cream kill?',
    versoEn: 'Correlation is not causation: the hidden variable is summer. A high correlation can reflect a common factor, reverse causality or a short-sample coincidence. Reflex: look for the hidden factor before telling a causal story.',
  },
  {
    id: 'm2-fc-041',
    moduleId: M2,
    tags: ['piege', 'statistiques'],
    recto: 'Corrélation nulle = indépendance ?',
    verso: 'Non : ρ ne capte que les liaisons LINÉAIRES — une liaison non linéaire parfaite peut donner ρ = 0. L\'implication ne marche que dans un sens : indépendance ⇒ corrélation nulle, jamais l\'inverse.',
    rectoEn: 'Zero correlation = independence?',
    versoEn: 'No: ρ only captures LINEAR relationships — a perfect non-linear link can yield ρ = 0. The implication runs one way only: independence ⇒ zero correlation, never the reverse.',
  },
  {
    id: 'm2-fc-042',
    moduleId: M2,
    tags: ['reflexe-jury', 'statistiques'],
    recto: 'Le jury : « Vos corrélations historiques sont à 0,3. Votre portefeuille est protégé en krach ? »',
    verso: 'Réflexe : non — « en crise, toutes les corrélations vont à 1 ». Estimées par temps calme, elles s\'envolent quand tout le monde vend (2008 : des actifs réputés décorrélés plongent de concert). La diversification s\'évapore au moment où l\'on en a besoin.',
    rectoEn: 'The panel: "Your historical correlations sit at 0.3. Is your portfolio protected in a crash?"',
    versoEn: 'Reflex: no — "in a crisis, all correlations go to 1". Estimated in calm times, they spike when everyone sells at once (2008: supposedly uncorrelated assets plunged together). Diversification evaporates exactly when you need it.',
  },
  {
    id: 'm2-fc-043',
    moduleId: M2,
    tags: ['definition', 'statistiques'],
    recto: 'La skewness, c\'est quoi — et comment lire son signe ?',
    verso: 'Le coefficient d\'asymétrie, nul pour une distribution symétrique. Le signe se lit du côté de la queue LONGUE : négative = petits gains fréquents, rares pertes massives (vendeur d\'options) ; positive = profil loterie (acheteur d\'options).',
    rectoEn: 'What is skewness — and how do you read its sign?',
    versoEn: 'The asymmetry coefficient, zero for a symmetric distribution. The sign reads off the LONG tail side: negative = frequent small gains, rare massive losses (option seller); positive = lottery-ticket profile (option buyer).',
  },
  {
    id: 'm2-fc-044',
    moduleId: M2,
    tags: ['definition', 'statistiques'],
    recto: 'Le kurtosis, c\'est quoi ?',
    verso: 'Le coefficient d\'aplatissement : le poids des queues. Référence : la normale, kurtosis = 3. Au-delà, distribution leptokurtique à queues épaisses — extrêmes plus fréquents que sous la gaussienne. Les rendements quotidiens réels : presque toujours > 3.',
    rectoEn: 'What is kurtosis?',
    versoEn: 'The tail-weight coefficient. Benchmark: the normal distribution, kurtosis = 3. Above that, the distribution is leptokurtic with fat tails — extremes more frequent than under the Gaussian. Real daily returns: almost always > 3.',
  },
  {
    id: 'm2-fc-045',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'statistiques'],
    recto: 'Le kurtosis d\'une loi normale vaut… ?',
    verso: 'Exactement 3 — la référence. Au-dessus : queues épaisses (leptokurtique). Les rendements financiers quotidiens affichent presque toujours nettement plus de 3 : la finance n\'est pas gaussienne.',
    rectoEn: 'The kurtosis of a normal distribution equals…?',
    versoEn: 'Exactly 3 — the benchmark. Above it: fat tails (leptokurtic). Daily financial returns almost always show well above 3: finance is not Gaussian.',
  },
  {
    id: 'm2-fc-046',
    moduleId: M2,
    tags: ['reflexe-jury', 'statistiques'],
    recto: 'Le jury : « 8 % de moyenne, 12 % de vol, skew −0,8, kurtosis 6 — votre lecture ? »',
    verso: 'Réflexe : gains réguliers mais pertes rares et sévères, extrêmes bien plus fréquents que sous la normale — un profil de vendeur d\'assurance, pas un placement tranquille. Traduire les quatre chiffres en une phrase, pas réciter les formules.',
    rectoEn: 'The panel: "8% mean, 12% vol, skew −0.8, kurtosis 6 — your read?"',
    versoEn: 'Reflex: steady gains but rare, severe losses, with extremes far more frequent than under the normal — an insurance-seller profile, not a quiet investment. Translate the four numbers into one sentence, don\'t recite formulas.',
  },

  // ───────────────────────── Chapitre 3 — Probabilités ─────────────────────────
  {
    id: 'm2-fc-047',
    moduleId: M2,
    tags: ['definition', 'probabilites'],
    recto: 'La probabilité conditionnelle P(A|B), c\'est quoi ?',
    verso: '$P(A \\mid B) = P(A \\cap B)/P(B)$ : la probabilité de A quand on restreint l\'univers aux cas où B est vrai. Le sens du conditionnement compte : P(A|B) ≠ P(B|A) en général.',
    rectoEn: 'What is the conditional probability P(A|B)?',
    versoEn: '$P(A \\mid B) = P(A \\cap B)/P(B)$: the probability of A when the universe is restricted to cases where B holds. The direction of conditioning matters: P(A|B) ≠ P(B|A) in general.',
  },
  {
    id: 'm2-fc-048',
    moduleId: M2,
    tags: ['definition', 'probabilites'],
    recto: 'Deux événements indépendants : définition ?',
    verso: '$P(A \\cap B) = P(A) \\times P(B)$ — la réalisation de l\'un ne change pas la probabilité de l\'autre. À ne pas confondre avec incompatibles (qui ne peuvent pas coexister) : ceux-là sont très dépendants.',
    rectoEn: 'Two independent events: definition?',
    versoEn: '$P(A \\cap B) = P(A) \\times P(B)$ — one occurring does not change the other\'s probability. Not to be confused with mutually exclusive events (which cannot coexist): those are highly dependent.',
  },
  {
    id: 'm2-fc-049',
    moduleId: M2,
    tags: ['piege', 'probabilites'],
    recto: 'Indépendants et incompatibles, c\'est pareil ?',
    verso: 'Contresens classique : deux événements incompatibles sont très DÉPENDANTS — savoir que l\'un s\'est réalisé garantit que l\'autre non. Indépendants : P(A∩B) = P(A)P(B) ; incompatibles : P(A∩B) = 0.',
    rectoEn: 'Independent and mutually exclusive — same thing?',
    versoEn: 'Classic misconception: two mutually exclusive events are highly DEPENDENT — knowing one occurred guarantees the other did not. Independent: P(A∩B) = P(A)P(B); mutually exclusive: P(A∩B) = 0.',
  },
  {
    id: 'm2-fc-050',
    moduleId: M2,
    tags: ['calcul-mental', 'probabilites'],
    recto: 'De tête : P(CAC monte) = 60 %, P(DAX monte) = 55 %, P(les deux) = 45 %. P(au moins un) ?',
    verso: 'P(A∪B) = P(A) + P(B) − P(A∩B) = 0,60 + 0,55 − 0,45 = 0,70. Soustraire l\'intersection pour ne pas la compter deux fois — sinon 1,15, absurde.',
    rectoEn: 'In your head: P(CAC up) = 60%, P(DAX up) = 55%, P(both) = 45%. P(at least one)?',
    versoEn: 'P(A∪B) = P(A) + P(B) − P(A∩B) = 0.60 + 0.55 − 0.45 = 0.70. Subtract the intersection so it isn\'t counted twice — otherwise 1.15, absurd.',
  },
  {
    id: 'm2-fc-051',
    moduleId: M2,
    tags: ['definition', 'probabilites'],
    recto: 'Le théorème de Bayes, à quoi sert-il ?',
    verso: 'À retourner le conditionnement : passer de P(B|A) à P(A|B). $P(A \\mid B) = \\frac{P(B \\mid A)P(A)}{P(B \\mid A)P(A) + P(B \\mid \\bar{A})P(\\bar{A})}$ — le dénominateur est la probabilité totale de B.',
    rectoEn: 'What is Bayes\' theorem for?',
    versoEn: 'Flipping the conditioning: going from P(B|A) to P(A|B). $P(A \\mid B) = \\frac{P(B \\mid A)P(A)}{P(B \\mid A)P(A) + P(B \\mid \\bar{A})P(\\bar{A})}$ — the denominator is the total probability of B.',
  },
  {
    id: 'm2-fc-052',
    moduleId: M2,
    tags: ['formule', 'probabilites'],
    recto: 'Bayes sur le test médical : prévalence 1 %, sensibilité 99 %, faux positifs 5 %. P(malade | positif) ?',
    verso: '(0,99 × 0,01)/(0,99 × 0,01 + 0,05 × 0,99) = 0,0099/0,0594 = 16,67 % = 1/6. En effectifs sur 10 000 : 99 vrais positifs contre 495 faux → 99/594.',
    rectoEn: 'Bayes on the medical test: 1% prevalence, 99% sensitivity, 5% false positives. P(sick | positive)?',
    versoEn: '(0.99 × 0.01)/(0.99 × 0.01 + 0.05 × 0.99) = 0.0099/0.0594 = 16.67% = 1/6. In headcounts per 10,000: 99 true positives vs 495 false → 99/594.',
  },
  {
    id: 'm2-fc-053',
    moduleId: M2,
    tags: ['piege', 'probabilites'],
    recto: 'Un test « fiable à 99 % » sonne. Pourquoi n\'êtes-vous probablement PAS malade ?',
    verso: 'La maladie est RARE (1 %) : les 5 % de faux positifs s\'appliquent à 9 900 personnes saines (495 alertes) et noient les 99 vrais malades. P(malade|positif) = 1/6. Ignorer la prévalence est LE piège de Bayes.',
    rectoEn: 'A "99% reliable" test rings. Why are you probably NOT sick?',
    versoEn: 'The disease is RARE (1%): the 5% false positives apply to 9,900 healthy people (495 alerts) and drown out the 99 true patients. P(sick|positive) = 1/6. Ignoring prevalence is THE Bayes trap.',
  },
  {
    id: 'm2-fc-054',
    moduleId: M2,
    tags: ['reflexe-jury', 'probabilites'],
    recto: 'Le jury : « Test positif, fiabilité 99 %, maladie à 1 %. Probabilité d\'être malade — en 30 secondes ? »',
    verso: 'Réflexe : penser en effectifs. « Sur 10 000 personnes : 100 malades → 99 détectés ; 9 900 saines → 495 faux positifs ; 99/594 = 1/6 ≈ 16,67 %. » L\'arbre en effectifs élimine les erreurs sous stress et montre le mécanisme.',
    rectoEn: 'The panel: "Positive test, 99% reliability, 1% prevalence. Probability you are sick — in 30 seconds?"',
    versoEn: 'Reflex: think in headcounts. "Out of 10,000 people: 100 sick → 99 detected; 9,900 healthy → 495 false positives; 99/594 = 1/6 ≈ 16.67%." The headcount tree kills mistakes under stress and shows the mechanism.',
  },
  {
    id: 'm2-fc-055',
    moduleId: M2,
    tags: ['piege', 'probabilites'],
    recto: 'Un signal détecte 70 % des vraies tendances. Quand il sonne, êtes-vous à 70 % sur une tendance ?',
    verso: 'Non : 70 % = P(signal|tendance), pas P(tendance|signal). Sur 100 configs (20 tendances, 30 % de faux signaux sur les 80 autres) : 14 vrais contre 24 faux → 14/38 ≈ 36,8 %. Confondre les deux sens du conditionnement coûte cher.',
    rectoEn: 'A signal catches 70% of true uptrends. When it rings, are you 70% sure of a trend?',
    versoEn: 'No: 70% = P(signal|trend), not P(trend|signal). On 100 setups (20 trends, 30% false alarms on the other 80): 14 true vs 24 false → 14/38 ≈ 36.8%. Confusing the two directions of conditioning is expensive.',
  },
  {
    id: 'm2-fc-056',
    moduleId: M2,
    tags: ['reflexe-jury', 'probabilites'],
    recto: 'Le jury : « L\'ADN correspond, 1 chance sur un million d\'erreur. Coupable à 99,9999 % ? »',
    verso: 'Réflexe : sophisme du procureur — c\'est P(correspondance|innocent), pas P(innocent|correspondance). Sur 60 millions d\'habitants, ≈ 60 correspondances fortuites : sans autre indice, P(coupable) ≈ 1/61. Le test médical, version tribunal.',
    rectoEn: 'The panel: "The DNA matches, a one-in-a-million error rate. Guilty at 99.9999%?"',
    versoEn: 'Reflex: prosecutor\'s fallacy — that is P(match|innocent), not P(innocent|match). Out of 60 million people, ≈ 60 chance matches: with no other evidence, P(guilty) ≈ 1/61. The medical test, courtroom edition.',
  },
  {
    id: 'm2-fc-057',
    moduleId: M2,
    tags: ['calcul-mental', 'probabilites'],
    recto: 'De tête : 10 personnes se serrent toutes la main une fois ; et 3 membres à choisir parmi 10 ?',
    verso: 'C(10,2) = 45 poignées — chaque paire compte une fois. C(10,3) = (10 × 9 × 8)/(3 × 2 × 1) = 120 comités. Réflexe : l\'ordre compte-t-il ? Non → combinaisons.',
    rectoEn: 'In your head: 10 people all shake hands once; and 3 members to pick out of 10?',
    versoEn: 'C(10,2) = 45 handshakes — each pair counts once. C(10,3) = (10 × 9 × 8)/(3 × 2 × 1) = 120 committees. Reflex: does order matter? No → combinations.',
  },
  {
    id: 'm2-fc-058',
    moduleId: M2,
    tags: ['piege', 'probabilites'],
    recto: 'P(au moins un six en 4 lancers) = 4 × 1/6 = 66,7 % ?',
    verso: 'Faux : on compte plusieurs fois les tirages à plusieurs six (et 7 lancers donneraient plus de 100 %). Réflexe « au moins un » → complémentaire : 1 − (5/6)⁴ = 1 − 0,4823 = 51,77 %.',
    rectoEn: 'P(at least one six in 4 rolls) = 4 × 1/6 = 66.7%?',
    versoEn: 'Wrong: multi-six outcomes get counted several times (and 7 rolls would exceed 100%). The "at least one" reflex → complement: 1 − (5/6)⁴ = 1 − 0.4823 = 51.77%.',
  },
  {
    id: 'm2-fc-059',
    moduleId: M2,
    tags: ['calcul-mental', 'probabilites'],
    recto: 'De tête : la routine « au moins un » ?',
    verso: 'P(au moins un) = 1 − P(aucun). Dé : 1 − (5/6)⁴ ≈ 51,8 %. Stratégies : P(au moins un faux positif sur 100 tests à 5 %) = 1 − 0,95¹⁰⁰ ≈ 99,4 %. Toujours passer par le complémentaire.',
    rectoEn: 'In your head: the "at least one" routine?',
    versoEn: 'P(at least one) = 1 − P(none). Dice: 1 − (5/6)⁴ ≈ 51.8%. Strategies: P(at least one false positive across 100 tests at 5%) = 1 − 0.95¹⁰⁰ ≈ 99.4%. Always go through the complement.',
  },
  {
    id: 'm2-fc-060',
    moduleId: M2,
    tags: ['piege', 'probabilites'],
    recto: '« Deux enfants, dont au moins une fille » : P(deux filles) — et pourquoi pas 1/2 ?',
    verso: 'Univers FF, FG, GF, GG ; « au moins une fille » élimine GG → 1/3. Le « 1/2 » oublie que FG et GF sont distincts. Variantes : « l\'aînée est une fille » → 1/2 ; on CROISE une fille au hasard → 1/2. La formulation change tout.',
    rectoEn: '"Two children, at least one is a girl": P(two girls) — and why not 1/2?',
    versoEn: 'Universe GG, GB, BG, BB; "at least one girl" removes BB → 1/3. The "1/2" answer forgets GB and BG are distinct. Variants: "the eldest is a girl" → 1/2; you randomly MEET one child who is a girl → 1/2. Wording changes everything.',
  },
  {
    id: 'm2-fc-061',
    moduleId: M2,
    tags: ['reflexe-jury', 'probabilites'],
    recto: 'Le jury : « Monty Hall — vous changez de porte ? » Déroulez en 30 secondes.',
    verso: 'Réflexe : arbre sur les 3 positions de la voiture. Ma porte : 1/3, changer perd ; les 2 autres cas (2/3) : l\'animateur est FORCÉ d\'ouvrir l\'unique perdante, changer gagne → 2/3. Version choc : 100 portes, il en ouvre 98 — son geste injecte de l\'information.',
    rectoEn: 'The panel: "Monty Hall — do you switch doors?" Walk through it in 30 seconds.',
    versoEn: 'Reflex: tree over the car\'s 3 possible positions. My door: 1/3, switching loses; the other 2 cases (2/3): the host is FORCED to open the only losing door, switching wins → 2/3. Shock version: 100 doors, he opens 98 — his move injects information.',
  },
  {
    id: 'm2-fc-062',
    moduleId: M2,
    tags: ['reflexe-jury', 'probabilites'],
    recto: 'Le jury : « Je lance un dé, je vous paie la face en euros. Vous payez combien pour jouer ? »',
    verso: 'Réflexe : E[X] = (1 + … + 6)/6 = 3,50 € — le prix d\'équilibre d\'un joueur neutre au risque. La nuance qui distingue : en pratique un peu moins, par aversion à la dispersion (σ ≈ 1,71 €) — première apparition de la prime de risque.',
    rectoEn: 'The panel: "I roll a die and pay you the face in euros. How much do you pay to play?"',
    versoEn: 'Reflex: E[X] = (1 + … + 6)/6 = €3.50 — the fair price for a risk-neutral player. The distinguishing nuance: in practice slightly less, out of aversion to dispersion (σ ≈ €1.71) — the first appearance of the risk premium.',
  },
  {
    id: 'm2-fc-063',
    moduleId: M2,
    tags: ['calcul-mental', 'probabilites'],
    recto: 'De tête : espérance d\'un dé ? Et de la somme de deux dés ?',
    verso: 'E = 3,5 — la moyenne de 1 à 6 ; deux dés → 7, l\'espérance est additive. Routine loi uniforme : moyenne des extrêmes, (1 + 6)/2 = 3,5.',
    rectoEn: 'In your head: expected value of one die? And of the sum of two dice?',
    versoEn: 'E = 3.5 — the average of 1 to 6; two dice → 7, expectation is additive. Uniform-law routine: average of the extremes, (1 + 6)/2 = 3.5.',
  },
  {
    id: 'm2-fc-064',
    moduleId: M2,
    tags: ['formule', 'probabilites'],
    recto: 'Formules de l\'espérance et de la variance d\'une variable aléatoire discrète ?',
    verso: '$E[X] = \\sum p_i x_i$ ; $\\text{Var}(X) = E[X^2] - (E[X])^2$. Sur le dé : E = 3,50 ; E[X²] = 91/6 ≈ 15,17 ; Var = 15,17 − 12,25 = 2,92 ; σ ≈ 1,71 €.',
    rectoEn: 'Expectation and variance of a discrete random variable?',
    versoEn: '$E[X] = \\sum p_i x_i$; $\\text{Var}(X) = E[X^2] - (E[X])^2$. On the die: E = 3.50; E[X²] = 91/6 ≈ 15.17; Var = 15.17 − 12.25 = 2.92; σ ≈ €1.71.',
  },

  // ───────────────────────── Chapitre 4 — Distributions ─────────────────────────
  {
    id: 'm2-fc-065',
    moduleId: M2,
    tags: ['definition', 'distributions'],
    recto: 'La loi binomiale B(n, p), c\'est quoi ?',
    verso: 'Le nombre de succès sur n essais indépendants à probabilité p : $P(X=k) = \\binom{n}{k} p^k (1-p)^{n-k}$, espérance np. La structure exacte de l\'arbre binomial du pricing d\'options (module 8).',
    rectoEn: 'What is the binomial distribution B(n, p)?',
    versoEn: 'The number of successes over n independent trials with probability p: $P(X=k) = \\binom{n}{k} p^k (1-p)^{n-k}$, expectation np. The exact structure of the binomial tree used to price options (module 8).',
  },
  {
    id: 'm2-fc-066',
    moduleId: M2,
    tags: ['formule', 'distributions'],
    recto: 'P(exactement 3 hausses sur 10 séances indépendantes, p = 0,5) ?',
    verso: '$\\binom{10}{3} \\times 0{,}5^{10}$ = 120/1 024 ≈ 11,72 %. C(10,3) = 120 compte les chemins à 3 hausses, 0,5¹⁰ est la probabilité de chaque chemin. Espérance : np = 5 hausses.',
    rectoEn: 'P(exactly 3 up-days over 10 independent sessions, p = 0.5)?',
    versoEn: '$\\binom{10}{3} \\times 0.5^{10}$ = 120/1,024 ≈ 11.72%. C(10,3) = 120 counts the paths with 3 up-days, 0.5¹⁰ is each path\'s probability. Expectation: np = 5 up-days.',
  },
  {
    id: 'm2-fc-067',
    moduleId: M2,
    tags: ['calcul-mental', 'distributions'],
    recto: 'De tête : l\'espérance d\'une binomiale ?',
    verso: 'E[X] = np. 10 séances à p = 0,5 → 5 hausses attendues ; 100 tests sans effet au seuil de 5 % → 5 faux positifs attendus. Le réflexe np sort en une seconde.',
    rectoEn: 'In your head: the expectation of a binomial?',
    versoEn: 'E[X] = np. 10 sessions at p = 0.5 → 5 expected up-days; 100 no-effect tests at the 5% level → 5 expected false positives. The np reflex takes one second.',
  },
  {
    id: 'm2-fc-068',
    moduleId: M2,
    tags: ['definition', 'distributions'],
    recto: 'La loi normale, c\'est quoi ?',
    verso: 'Loi continue en cloche, entièrement décrite par μ (centre) et σ (largeur), symétrique. Masse : 68,3 % dans ±1σ, 95,4 % dans ±2σ, 99,7 % dans ±3σ. L\'outil de travail du quotidien — faux dans les queues.',
    rectoEn: 'What is the normal distribution?',
    versoEn: 'A continuous bell-shaped law, fully described by μ (center) and σ (width), symmetric. Mass: 68.3% within ±1σ, 95.4% within ±2σ, 99.7% within ±3σ. The everyday workhorse — wrong in the tails.',
  },
  {
    id: 'm2-fc-069',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'distributions'],
    recto: 'Les règles 68-95-99,7 de la loi normale ?',
    verso: '±1σ : 68,3 % de la masse ; ±2σ : 95,4 % ; ±3σ : 99,7 %. Lecture desk : sous normalité, environ deux tiers des jours dans ±1σ, 19 jours sur 20 dans ±2σ.',
    rectoEn: 'The 68-95-99.7 rules of the normal distribution?',
    versoEn: '±1σ: 68.3% of the mass; ±2σ: 95.4%; ±3σ: 99.7%. Desk reading: under normality, about two thirds of days within ±1σ, 19 days out of 20 within ±2σ.',
  },
  {
    id: 'm2-fc-070',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'distributions'],
    recto: 'Pourquoi 1,96 est-il le nombre fétiche de la statistique ?',
    verso: 'Φ(1,96) = 0,9750 : 97,5 % de la masse sous μ + 1,96σ, donc 95 % dans μ ± 1,96σ. C\'est la frontière des intervalles de confiance à 95 % et du rejet à 5 % bilatéral.',
    rectoEn: 'Why is 1.96 the fetish number of statistics?',
    versoEn: 'Φ(1.96) = 0.9750: 97.5% of the mass below μ + 1.96σ, hence 95% within μ ± 1.96σ. It is the boundary of 95% confidence intervals and of two-sided 5% rejection.',
  },
  {
    id: 'm2-fc-071',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'distributions'],
    recto: '1,645, c\'est quoi ?',
    verso: 'Le quantile à 95 % UNILATÉRAL de la normale : 5 % de la masse au-delà de μ + 1,645σ — ou sous μ − 1,645σ, la queue gauche des calculs de type VaR. À distinguer du 1,96 bilatéral.',
    rectoEn: 'What is 1.645?',
    versoEn: 'The ONE-SIDED 95% quantile of the normal: 5% of the mass beyond μ + 1.645σ — or below μ − 1.645σ, the left tail of VaR-style calculations. Distinct from the two-sided 1.96.',
  },
  {
    id: 'm2-fc-072',
    moduleId: M2,
    tags: ['definition', 'distributions'],
    recto: 'Le z-score, c\'est quoi ?',
    verso: '$z = (x - \\mu)/\\sigma$ : la distance à la moyenne comptée en écarts-types — le passage à la normale centrée réduite. Ex. : rendement −9 %, μ = 6 %, σ = 15 % → z = −1.',
    rectoEn: 'What is a z-score?',
    versoEn: '$z = (x - \\mu)/\\sigma$: the distance to the mean counted in standard deviations — the bridge to the standard normal. E.g.: return −9%, μ = 6%, σ = 15% → z = −1.',
  },
  {
    id: 'm2-fc-073',
    moduleId: M2,
    tags: ['formule', 'distributions'],
    recto: 'Rendement annuel N(6 %, 15 %) : probabilité d\'une année pire que −9 % ?',
    verso: 'z = (−9 − 6)/15 = −1 ; P = Φ(−1) = 1 − Φ(1) = 1 − 0,8413 = 15,87 % — environ une année sur six. Réflexe : convertir en z-score, puis lire la table.',
    rectoEn: 'Annual return N(6%, 15%): probability of a year worse than −9%?',
    versoEn: 'z = (−9 − 6)/15 = −1; P = Φ(−1) = 1 − Φ(1) = 1 − 0.8413 = 15.87% — about one year in six. Reflex: convert to a z-score, then read the table.',
  },
  {
    id: 'm2-fc-074',
    moduleId: M2,
    tags: ['calcul-mental', 'distributions'],
    recto: 'De tête : le seuil que le rendement ne franchit à la baisse que 5 % du temps (loi normale) ?',
    verso: 'μ − 1,645σ ≈ μ − 1,64σ. Ex. : μ = 6 %, σ = 15 % → 6 − 1,645 × 15 ≈ 6 − 24,7 = −18,7 %. La mécanique du quantile 5 % — l\'esprit d\'une VaR.',
    rectoEn: 'In your head: the level a return only breaches downward 5% of the time (normal law)?',
    versoEn: 'μ − 1.645σ ≈ μ − 1.64σ. E.g.: μ = 6%, σ = 15% → 6 − 1.645 × 15 ≈ 6 − 24.7 = −18.7%. The 5% quantile mechanics — the spirit of a VaR.',
  },
  {
    id: 'm2-fc-075',
    moduleId: M2,
    tags: ['definition', 'distributions'],
    recto: 'La loi lognormale, c\'est quoi — et pourquoi pour les prix ?',
    verso: 'X est lognormale si ln X est normale. Support strictement positif (un prix ne peut pas être négatif), queue étirée à droite. Les rendements composés s\'additionnent en log → TCL → ln P_T normal. L\'hypothèse de Black-Scholes.',
    rectoEn: 'What is the lognormal distribution — and why for prices?',
    versoEn: 'X is lognormal if ln X is normal. Strictly positive support (a price cannot go negative), tail stretched to the right. Compounded returns add in logs → CLT → ln P_T normal. The Black-Scholes assumption.',
  },
  {
    id: 'm2-fc-076',
    moduleId: M2,
    tags: ['reflexe-jury', 'distributions'],
    recto: 'Le jury : « Que suppose Black-Scholes sur la dynamique des prix ? »',
    verso: 'Réflexe : prix lognormaux, c\'est-à-dire log-rendements normaux. Justification : les rendements se composent (s\'additionnent en log) et le TCL normalise la somme. La nuance qui paie : le modèle ignore les queues épaisses du réel.',
    rectoEn: 'The panel: "What does Black-Scholes assume about price dynamics?"',
    versoEn: 'Reflex: lognormal prices, i.e. normal log-returns. Rationale: returns compound (add in logs) and the CLT normalizes the sum. The nuance that scores: the model ignores the fat tails of real markets.',
  },
  {
    id: 'm2-fc-077',
    moduleId: M2,
    tags: ['piege', 'distributions'],
    recto: 'Le 19 octobre 1987, le Dow perd 22,6 % — environ 20 écarts-types. La bonne lecture ?',
    verso: 'Pas « malchance cosmique » : sous la normale, un mouvement à 20σ ne devrait jamais s\'observer, même depuis l\'âge de l\'univers. Le modèle normal sous-estime massivement les queues (kurtosis > 3) — 2008, 2010, 2020 l\'ont confirmé.',
    rectoEn: 'On 19 October 1987 the Dow loses 22.6% — about 20 standard deviations. The right read?',
    versoEn: 'Not "cosmic bad luck": under the normal law, a 20σ move should never be observed, even since the age of the universe. The normal model massively understates the tails (kurtosis > 3) — 2008, 2010 and 2020 confirmed it.',
  },
  {
    id: 'm2-fc-078',
    moduleId: M2,
    tags: ['reflexe-jury', 'distributions'],
    recto: 'Le jury : « Votre VaR gaussienne à 99 % borne vos pertes, n\'est-ce pas ? »',
    verso: 'Réflexe : non — elle sous-estime précisément les pertes qu\'elle prétend borner, car les queues réelles sont épaisses. La normale vaut au centre (95 % des journées), pas aux extrêmes. Parades : stress tests, scénarios historiques, lois à queues épaisses.',
    rectoEn: 'The panel: "Your 99% Gaussian VaR caps your losses, doesn\'t it?"',
    versoEn: 'Reflex: no — it understates precisely the losses it claims to bound, because real tails are fat. The normal works at the center (95% of trading days), not at the extremes. Remedies: stress tests, historical scenarios, fat-tailed laws.',
  },

  // ───────────────────────── Chapitre 5 — Échantillonnage & intervalles ─────────────────────────
  {
    id: 'm2-fc-079',
    moduleId: M2,
    tags: ['definition', 'echantillonnage'],
    recto: 'Le théorème central limite, énoncé exact ?',
    verso: '$\\bar{x} \\approx N(\\mu, \\sigma/\\sqrt{n})$ pour n assez grand, QUELLE QUE SOIT la loi de départ (tirages indépendants de même loi, variance finie). Deux miracles : la forme est universelle, la vitesse de resserrement est connue — en √n.',
    rectoEn: 'The central limit theorem, exact statement?',
    versoEn: '$\\bar{x} \\approx N(\\mu, \\sigma/\\sqrt{n})$ for large enough n, WHATEVER the starting distribution (i.i.d. draws, finite variance). Two miracles in one: the shape is universal, and the tightening speed is known — √n.',
  },
  {
    id: 'm2-fc-080',
    moduleId: M2,
    tags: ['reflexe-jury', 'echantillonnage'],
    recto: 'Le jury : « Le TCL dit qu\'avec assez de données, les rendements deviennent normaux ? »',
    verso: 'Réflexe : non — il porte sur la MOYENNE d\'échantillon, pas sur les données. Les rendements gardent leurs queues épaisses, même avec un million d\'observations ; c\'est x̄ qui se distribue en cloche autour de μ, à la vitesse σ/√n.',
    rectoEn: 'The panel: "The CLT says that with enough data, returns become normal?"',
    versoEn: 'Reflex: no — it applies to the sample MEAN, not the data. Returns keep their fat tails even with a million observations; it is x̄ that distributes as a bell around μ, at speed σ/√n.',
  },
  {
    id: 'm2-fc-081',
    moduleId: M2,
    tags: ['definition', 'echantillonnage'],
    recto: 'L\'erreur standard, c\'est quoi ?',
    verso: 'L\'écart-type d\'un ESTIMATEUR : pour la moyenne, $\\sigma/\\sqrt{n}$ — de combien x̄ bougerait d\'un échantillon à l\'autre. À ne pas confondre avec σ, la dispersion des données elles-mêmes.',
    rectoEn: 'What is the standard error?',
    versoEn: 'The standard deviation of an ESTIMATOR: for the mean, $\\sigma/\\sqrt{n}$ — how much x̄ would move from one sample to the next. Not to be confused with σ, the dispersion of the data themselves.',
  },
  {
    id: 'm2-fc-082',
    moduleId: M2,
    tags: ['calcul-mental', 'echantillonnage'],
    recto: 'De tête : vol mensuelle 2 %, 25 observations. Erreur standard de la moyenne ?',
    verso: 'σ/√n = 2/√25 = 2/5 = 0,4 %. Routine : racine de n, pas n — et √25 = 5 sort tout seul.',
    rectoEn: 'In your head: 2% monthly vol, 25 observations. Standard error of the mean?',
    versoEn: 'σ/√n = 2/√25 = 2/5 = 0.4%. Routine: square root of n, not n — and √25 = 5 comes for free.',
  },
  {
    id: 'm2-fc-083',
    moduleId: M2,
    tags: ['piege', 'echantillonnage'],
    recto: 'Erreur standard : σ/n ou σ/√n ?',
    verso: 'σ/√n : c\'est la VARIANCE qui se divise par n, donc l\'écart-type par √n. Avec σ = 2 % et n = 25 : 0,4 %, pas 0,08 %. Et multiplier par √n est la règle d\'annualisation de la vol — l\'autre sens : agréger pour cumuler, pas pour moyenner.',
    rectoEn: 'Standard error: σ/n or σ/√n?',
    versoEn: 'σ/√n: the VARIANCE divides by n, so the standard deviation divides by √n. With σ = 2% and n = 25: 0.4%, not 0.08%. And multiplying by √n is the vol annualization rule — the other direction: aggregating to cumulate, not to average.',
  },
  {
    id: 'm2-fc-084',
    moduleId: M2,
    tags: ['definition', 'echantillonnage'],
    recto: 'L\'intervalle de confiance à 95 %, c\'est quoi ?',
    verso: '$\\bar{x} \\pm 1{,}96\\,\\sigma/\\sqrt{n}$ : un intervalle construit pour attraper μ dans 95 % des échantillons. La confiance qualifie la MÉTHODE — la machine à fabriquer des intervalles —, pas l\'intervalle calculé.',
    rectoEn: 'What is a 95% confidence interval?',
    versoEn: '$\\bar{x} \\pm 1.96\\,\\sigma/\\sqrt{n}$: an interval built to capture μ in 95% of samples. The confidence qualifies the METHOD — the interval-making machine — not the computed interval.',
  },
  {
    id: 'm2-fc-085',
    moduleId: M2,
    tags: ['formule', 'echantillonnage'],
    recto: 'IC à 95 % : x̄ = 0,08 %/jour, s = 1,2 %, n = 252. Déroulez.',
    verso: 'SE = 1,2/√252 = 0,0756 % ; marge = 1,96 × 0,0756 = 0,148 pt ; IC = [−0,07 % ; +0,23 %]. Il contient zéro : un an de données quotidiennes ne prouve même pas que la moyenne est positive.',
    rectoEn: '95% CI: x̄ = 0.08%/day, s = 1.2%, n = 252. Walk through it.',
    versoEn: 'SE = 1.2/√252 = 0.0756%; margin = 1.96 × 0.0756 = 0.148pt; CI = [−0.07%; +0.23%]. It contains zero: a full year of daily data cannot even establish that the mean is positive.',
  },
  {
    id: 'm2-fc-086',
    moduleId: M2,
    tags: ['piege', 'echantillonnage'],
    recto: '« Il y a 95 % de chances que μ soit dans mon intervalle » : où est la faute ?',
    verso: 'μ est un nombre FIXE inconnu ; c\'est l\'intervalle qui est aléatoire. Une fois calculé, il contient μ ou non — plus de probabilité, juste de l\'ignorance. Correct : « 95 % des intervalles ainsi construits contiendraient μ ». La phrase qui élimine à l\'oral.',
    rectoEn: '"There is a 95% chance that μ is inside my interval": where is the mistake?',
    versoEn: 'μ is a FIXED unknown number; the interval is what is random. Once computed, it either contains μ or not — no probability left, only ignorance. Correct: "95% of intervals built this way would contain μ". The sentence that gets you eliminated at the oral.',
  },
  {
    id: 'm2-fc-087',
    moduleId: M2,
    tags: ['calcul-mental', 'echantillonnage'],
    recto: 'De tête : moyenne 2 %, erreur standard 1 %. L\'IC à 95 % approximatif ?',
    verso: 'x̄ ± 2 SE ≈ [0 % ; 4 %] — zéro au bord : significativité limite. Le réflexe ±2SE (1,96 ≈ 2) donne le verdict avant toute table.',
    rectoEn: 'In your head: mean 2%, standard error 1%. The approximate 95% CI?',
    versoEn: 'x̄ ± 2 SE ≈ [0%; 4%] — zero right at the edge: borderline significance. The ±2SE reflex (1.96 ≈ 2) gives the verdict before any table.',
  },
  {
    id: 'm2-fc-088',
    moduleId: M2,
    tags: ['reflexe-jury', 'echantillonnage'],
    recto: 'Le jury : « 0,08 % par jour, soit 20 % annualisé. Spectaculaire, non ? »',
    verso: 'Réflexe : l\'IC à 95 % vaut [−0,07 % ; +0,23 %] — il contient zéro. La vol quotidienne (1,2 %) écrase la moyenne (0,08 %). Annualiser (0,08 × 252 = 20,16 %) n\'ajoute aucune information : le signal se noie dans le bruit.',
    rectoEn: 'The panel: "0.08% a day, i.e. 20% annualized. Spectacular, right?"',
    versoEn: 'Reflex: the 95% CI is [−0.07%; +0.23%] — it contains zero. Daily vol (1.2%) crushes the daily mean (0.08%). Annualizing (0.08 × 252 = 20.16%) adds no information: the signal drowns in the noise.',
  },
  {
    id: 'm2-fc-089',
    moduleId: M2,
    tags: ['reflexe-jury', 'echantillonnage'],
    recto: 'Le jury : « Sharpe de 2 sur 6 mois de backtest. Votre avis ? »',
    verso: 'Réflexe : six mois, l\'erreur standard de la moyenne est énorme — le résultat est compatible avec une stratégie sans aucun talent. Diviser σ par √n et regarder si la moyenne survit à ses barres d\'erreur avant de s\'enthousiasmer.',
    rectoEn: 'The panel: "A Sharpe of 2 over a 6-month backtest. Your view?"',
    versoEn: 'Reflex: six months — the standard error of the mean is huge; the result is consistent with a strategy that has no skill at all. Divide σ by √n and check whether the mean survives its own error bars before getting excited.',
  },
  {
    id: 'm2-fc-090',
    moduleId: M2,
    tags: ['reflexe-jury', 'echantillonnage'],
    recto: 'Le jury : « Moyenne ou volatilité : laquelle s\'estime bien ? »',
    verso: 'Réflexe : la vol s\'estime vite et bien, la moyenne lentement et mal — sur un an de quotidien, σ̂ est solide quand l\'IC de la moyenne contient encore zéro. Estimer une moyenne de rendements est l\'un des problèmes les plus ingrats de la finance.',
    rectoEn: 'The panel: "Mean or volatility: which one estimates well?"',
    versoEn: 'Reflex: volatility estimates fast and well, the mean slowly and badly — on a year of daily data, σ̂ is solid while the mean\'s CI still contains zero. Estimating a mean return is one of the most thankless problems in finance.',
  },
  {
    id: 'm2-fc-091',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'echantillonnage'],
    recto: 'Pour diviser l\'erreur d\'estimation par 2, il faut combien de données en plus ?',
    verso: '4 fois plus : l\'erreur décroît en 1/√n. 252 jours → 1 008 jours (quatre ans) pour doubler la précision. La malédiction de la racine carrée : la précision coûte quadratiquement cher.',
    rectoEn: 'To halve the estimation error, how much more data do you need?',
    versoEn: '4 times more: the error shrinks as 1/√n. 252 days → 1,008 days (four years) to double precision. The square-root curse: precision is quadratically expensive.',
  },
  {
    id: 'm2-fc-092',
    moduleId: M2,
    tags: ['calcul-mental', 'echantillonnage'],
    recto: 'De tête : 0,08 % par jour, ça fait combien par an ?',
    verso: '× 252 : 0,08 × 252 = 20,16 ≈ 20 %/an. Attention à l\'asymétrie des règles : le rendement moyen s\'annualise en ×252, la volatilité en ×√252.',
    rectoEn: 'In your head: 0.08% a day — how much per year?',
    versoEn: '× 252: 0.08 × 252 = 20.16 ≈ 20%/yr. Mind the asymmetry of the rules: the mean return annualizes by ×252, volatility by ×√252.',
  },

  // ───────────────────────── Chapitre 6 — Tests d'hypothèses ─────────────────────────
  {
    id: 'm2-fc-093',
    moduleId: M2,
    tags: ['definition', 'tests'],
    recto: 'Hypothèse nulle et hypothèse alternative : qui joue quel rôle ?',
    verso: 'H₀ = absence d\'effet (le fonds n\'a pas de talent), présumée vraie ; H₁ = l\'effet existe. Présomption d\'innocence : la charge de la preuve pèse sur H₁, on ne rejette H₀ que sur preuve forte. Seuil α = 5 % par convention (héritage de Fisher).',
    rectoEn: 'Null and alternative hypotheses: who plays which role?',
    versoEn: 'H₀ = no effect (the fund has no skill), presumed true; H₁ = the effect is real. Presumption of innocence: the burden of proof lies on H₁, and H₀ is only rejected on strong evidence. Threshold α = 5% by convention (a Fisher legacy).',
  },
  {
    id: 'm2-fc-094',
    moduleId: M2,
    tags: ['piege', 'tests'],
    recto: 'Le test ne rejette pas H₀ : le fonds est donc sans talent ?',
    verso: 'Non — on ne prouve jamais H₀. Ne pas rejeter signifie « les données ne suffisent pas à affirmer l\'effet », pas « l\'effet n\'existe pas ». Acquitté ne veut pas dire innocent.',
    rectoEn: 'The test fails to reject H₀: so the fund has no skill?',
    versoEn: 'No — H₀ is never proven. Failing to reject means "the data are not enough to assert the effect", not "the effect does not exist". Acquitted does not mean innocent.',
  },
  {
    id: 'm2-fc-095',
    moduleId: M2,
    tags: ['formule', 'tests'],
    recto: 'Formule de la statistique de test, et le fonds du cours (2 %/an, s = 5 %, 25 ans) ?',
    verso: '$t = (\\bar{x} - \\mu_0)/(s/\\sqrt{n})$. SE = 5/√25 = 1 % → t = (2 − 0)/1 = 2,0 ; p = 2 × (1 − Φ(2)) = 4,55 % < 5 % : significatif… d\'un cheveu (frontière à 1,96).',
    rectoEn: 'Test statistic formula, and the course fund (2%/yr, s = 5%, 25 years)?',
    versoEn: '$t = (\\bar{x} - \\mu_0)/(s/\\sqrt{n})$. SE = 5/√25 = 1% → t = (2 − 0)/1 = 2.0; p = 2 × (1 − Φ(2)) = 4.55% < 5%: significant… by a hair (boundary at 1.96).',
  },
  {
    id: 'm2-fc-096',
    moduleId: M2,
    tags: ['reflexe-jury', 'tests'],
    recto: 'Le jury : « Un fonds bat son indice de 2 % par an depuis 25 ans. Talent ou chance ? »',
    verso: 'Réflexe : t = 2/(5/√25) = 2,0, p ≈ 4,6 % — significatif d\'un cheveu. La précision qui fait mouche : en Student à 24 ddl, seuil 2,06, p ≈ 5,7 % → le cheveu casse. Vingt-cinq ans pour une conclusion fragile : calibrez l\'humilité.',
    rectoEn: 'The panel: "A fund beats its index by 2% a year for 25 years. Skill or luck?"',
    versoEn: 'Reflex: t = 2/(5/√25) = 2.0, p ≈ 4.6% — significant by a hair. The precision that scores: under Student with 24 df, threshold 2.06, p ≈ 5.7% → the hair snaps. Twenty-five years for such a fragile conclusion: calibrate your humility.',
  },
  {
    id: 'm2-fc-097',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'tests'],
    recto: 'Le seuil critique d\'un test t à 24 degrés de liberté (5 % bilatéral) ?',
    verso: '2,06 — contre 1,96 pour la normale. À petit n, la Student a des queues plus épaisses : σ estimé par s ajoute de l\'incertitude. La frontière 1,96 suppose n grand.',
    rectoEn: 'The critical threshold of a t-test with 24 degrees of freedom (two-sided 5%)?',
    versoEn: '2.06 — versus 1.96 for the normal. At small n, the Student has fatter tails: estimating σ with s adds uncertainty. The 1.96 boundary assumes large n.',
  },
  {
    id: 'm2-fc-098',
    moduleId: M2,
    tags: ['piege', 'tests'],
    recto: 't = 2,0 sur 25 observations : significatif à 5 % ?',
    verso: 'Non, de justesse : avec σ estimé sur n = 25, le test exact est un Student à 24 ddl — seuil 2,06, p ≈ 5,7 %. Le réflexe 1,96 vaut pour n grand ; à petit n, l\'honnêteté statistique conclut « non significatif ».',
    rectoEn: 't = 2.0 on 25 observations: significant at 5%?',
    versoEn: 'No, just barely: with σ estimated on n = 25, the exact test is a Student with 24 df — threshold 2.06, p ≈ 5.7%. The 1.96 reflex holds for large n; at small n, statistical honesty concludes "not significant".',
  },
  {
    id: 'm2-fc-099',
    moduleId: M2,
    tags: ['calcul-mental', 'tests'],
    recto: 'De tête : l\'arrondi de salle pour 1,96 — et ce qu\'il permet ?',
    verso: '1,96 ≈ 2 : IC ≈ x̄ ± 2 SE, rejet si |t| > 2. Sur le fonds du cours, t = 2,0 pile sur la frontière → réflexe immédiat « limite, à challenger », sans aucune table.',
    rectoEn: 'In your head: the trading-floor rounding for 1.96 — and what it buys you?',
    versoEn: '1.96 ≈ 2: CI ≈ x̄ ± 2 SE, reject if |t| > 2. On the course fund, t = 2.0 sits right on the boundary → instant reflex "borderline, challenge it", with no table at all.',
  },
  {
    id: 'm2-fc-100',
    moduleId: M2,
    tags: ['definition', 'tests'],
    recto: 'La p-value : définition exacte ?',
    verso: 'La probabilité, SI H₀ est vraie, d\'observer un écart au moins aussi extrême que celui constaté : P(données | H₀). Ex. : t = 2,0 → p = 2 × (1 − 0,97725) = 4,55 % en bilatéral. Décision : p < α → rejet.',
    rectoEn: 'The p-value: exact definition?',
    versoEn: 'The probability, IF H₀ is true, of observing a gap at least as extreme as the one seen: P(data | H₀). E.g.: t = 2.0 → p = 2 × (1 − 0.97725) = 4.55% two-sided. Decision: p < α → reject.',
  },
  {
    id: 'm2-fc-101',
    moduleId: M2,
    tags: ['piege', 'tests'],
    recto: '« p = 4,6 %, donc 95,4 % de chances que le fonds ait du talent » : la faute ?',
    verso: 'Inversion du conditionnement : p = P(données|H₀), pas P(H₀|données) — le sophisme du procureur version desk. Pour P(talent|données), il faudrait Bayes et un a priori : les vrais talents étant rares, la plupart des « positifs » à 5 % restent des faux.',
    rectoEn: '"p = 4.6%, so a 95.4% chance the fund has skill": the mistake?',
    versoEn: 'Conditioning flipped: p = P(data|H₀), not P(H₀|data) — the prosecutor\'s fallacy, desk edition. For P(skill|data) you would need Bayes and a prior: true skill being rare, most 5% "positives" remain false ones.',
  },
  {
    id: 'm2-fc-102',
    moduleId: M2,
    tags: ['definition', 'tests'],
    recto: 'Erreurs de type I et de type II ?',
    verso: 'Type I : rejeter H₀ vraie — fausse alerte, probabilité α. Type II : rater un effet réel — probabilité β. Le radar antiaérien : trop sensible → vols d\'oiseaux (type I) ; trop sourd → avions ratés (type II). α est le bouton de sensibilité.',
    rectoEn: 'Type I and type II errors?',
    versoEn: 'Type I: rejecting a true H₀ — false alarm, probability α. Type II: missing a real effect — probability β. The air-defense radar: too sensitive → bird flights (type I); too deaf → missed aircraft (type II). α is the sensitivity knob.',
  },
  {
    id: 'm2-fc-103',
    moduleId: M2,
    tags: ['definition', 'tests'],
    recto: 'La puissance d\'un test, c\'est quoi ?',
    verso: '1 − β : la probabilité de détecter un effet qui existe réellement. Durcir α la fait chuter ; le seul moyen d\'améliorer α ET β à la fois est d\'augmenter n — l\'erreur standard σ/√n rétrécit et sépare mieux signal et bruit.',
    rectoEn: 'What is the power of a test?',
    versoEn: '1 − β: the probability of detecting an effect that really exists. Tightening α makes it drop; the only way to improve both α AND β is to raise n — the standard error σ/√n shrinks and better separates signal from noise.',
  },
  {
    id: 'm2-fc-104',
    moduleId: M2,
    tags: ['reflexe-jury', 'tests'],
    recto: 'Le jury : « Vous passez α de 5 % à 1 %. Conséquences ? »',
    verso: 'Réflexe : moins de fausses alertes (type I), mais radar plus sourd — β monte, la puissance chute. On ne gagne pas sur les deux tableaux à n fixé ; seul n ↑ améliore les deux. Le curseur dépend du coût relatif des deux erreurs.',
    rectoEn: 'The panel: "You move α from 5% to 1%. Consequences?"',
    versoEn: 'Reflex: fewer false alarms (type I), but a deafer radar — β rises, power falls. You cannot win on both fronts at fixed n; only raising n improves both. Where to set the knob depends on the relative cost of the two errors.',
  },
  {
    id: 'm2-fc-105',
    moduleId: M2,
    tags: ['definition', 'tests'],
    recto: 'Le data snooping, c\'est quoi ?',
    verso: 'La fouille de données : tester des dizaines de stratégies et ne montrer que celles qui « marchent ». Au seuil de 5 %, 100 stratégies nulles produisent ≈ 5 « découvertes » par construction. Parades : hypothèses déclarées avant, seuils durcis, out-of-sample.',
    rectoEn: 'What is data snooping?',
    versoEn: 'Data mining gone wrong: testing dozens of strategies and only showing the ones that "work". At the 5% level, 100 worthless strategies produce ≈ 5 "discoveries" by construction. Remedies: pre-declared hypotheses, tightened thresholds, out-of-sample validation.',
  },
  {
    id: 'm2-fc-106',
    moduleId: M2,
    tags: ['reflexe-jury', 'tests'],
    recto: 'Le jury : « Sur 100 backtests, un sort significatif à 5 %. Vous allouez ? »',
    verso: 'Réflexe : P(au moins un faux positif) = 1 − 0,95¹⁰⁰ ≈ 99,4 % — la découverte était garantie d\'avance (64 % dès 20 tests). La question à poser : combien d\'essais avant celui qu\'on me montre ? Exiger l\'out-of-sample.',
    rectoEn: 'The panel: "Out of 100 backtests, one comes out significant at 5%. Do you allocate?"',
    versoEn: 'Reflex: P(at least one false positive) = 1 − 0.95¹⁰⁰ ≈ 99.4% — the discovery was guaranteed in advance (64% with just 20 tests). The question to ask: how many trials before the one I am being shown? Demand out-of-sample.',
  },
  {
    id: 'm2-fc-107',
    moduleId: M2,
    tags: ['piege', 'tests'],
    recto: 'La performance moyenne des fonds existants reflète-t-elle le marché ?',
    verso: 'Non : biais du survivant — les fonds morts disparaissent des bases de données, on moyenne les gagnants en oubliant les disparus. Tout track record impressionne moins quand on rappelle que les contemporains défunts ne témoignent plus.',
    rectoEn: 'Does the average performance of existing funds reflect the market?',
    versoEn: 'No: survivorship bias — dead funds vanish from databases, so you average the winners while forgetting the departed. Any track record impresses less once you recall that its deceased contemporaries are no longer there to testify.',
  },
  {
    id: 'm2-fc-108',
    moduleId: M2,
    tags: ['reflexe-jury', 'tests'],
    recto: 'Le jury : « Significatif à 5 %, donc ça vaut de l\'argent ? »',
    verso: 'Réflexe : significatif ≠ important. Avec un million d\'observations, +0,01 %/an devient significatif — et économiquement invisible, dévoré par le moindre coût de transaction. La significativité dit « pas du bruit », jamais « rentable ». L\'une est affaire de √n, l\'autre de centimes.',
    rectoEn: 'The panel: "Significant at 5%, so it makes money?"',
    versoEn: 'Reflex: significant ≠ important. With a million observations, +0.01%/yr becomes significant — and economically invisible, eaten by the slightest transaction cost. Significance says "probably not noise", never "worth money". One is a matter of √n, the other of cents.',
  },

  // ───────────────────────── Chapitre 7 — Régression & Monte-Carlo ─────────────────────────
  {
    id: 'm2-fc-109',
    moduleId: M2,
    tags: ['definition', 'regression'],
    recto: 'Le beta d\'un titre, c\'est quoi ?',
    verso: 'La pente de la régression des rendements du titre sur ceux du marché : b = cov(x,y)/var(x) — sa sensibilité moyenne. β = 1,35 : le titre amplifie le marché de 35 % ; β = 0,5 : il amortit. L\'ordonnée a préfigure l\'alpha.',
    rectoEn: 'What is a stock\'s beta?',
    versoEn: 'The slope of the regression of the stock\'s returns on the market\'s: b = cov(x,y)/var(x) — its average sensitivity. β = 1.35: the stock amplifies the market by 35%; β = 0.5: it dampens. The intercept a prefigures alpha.',
  },
  {
    id: 'm2-fc-110',
    moduleId: M2,
    tags: ['formule', 'regression'],
    recto: 'Formules des moindres carrés, et l\'exemple du cours (5 semaines) ?',
    verso: '$b = \\text{cov}(x,y)/\\text{var}(x)$, $a = \\bar{y} - b\\bar{x}$. Sommes du cours : 35 et 26 → b = 35/26 = 1,35 ; a = 1,2 − 1,3462 = −0,15. La droite passe toujours par le point moyen (x̄, ȳ).',
    rectoEn: 'Least-squares formulas, and the course example (5 weeks)?',
    versoEn: '$b = \\text{cov}(x,y)/\\text{var}(x)$, $a = \\bar{y} - b\\bar{x}$. Course sums: 35 and 26 → b = 35/26 = 1.35; a = 1.2 − 1.3462 = −0.15. The line always passes through the mean point (x̄, ȳ).',
  },
  {
    id: 'm2-fc-111',
    moduleId: M2,
    tags: ['calcul-mental', 'regression'],
    recto: 'De tête : cov(x, y) = 3, var(x) = 2. Beta ? Et si la covariance est négative ?',
    verso: 'β = cov/var = 3/2 = 1,5 — amplificateur. Cov < 0 → β < 0 : le titre bouge contre le marché. Routine : le signe de β est celui de la covariance ; var(x) > 0 toujours.',
    rectoEn: 'In your head: cov(x, y) = 3, var(x) = 2. Beta? And if the covariance is negative?',
    versoEn: 'β = cov/var = 3/2 = 1.5 — an amplifier. Cov < 0 → β < 0: the stock moves against the market. Routine: β takes the sign of the covariance; var(x) > 0 always.',
  },
  {
    id: 'm2-fc-112',
    moduleId: M2,
    tags: ['definition', 'regression'],
    recto: 'Le R², c\'est quoi ?',
    verso: 'La part de la variance de y expliquée par la droite ; en régression simple, R² = ρ². Ex. du cours : ρ = 0,9631 → R² = 0,9275 : 93 % des variations expliqués par le marché, 7 % de risque spécifique. R² = 1 sur données réelles : méfiance.',
    rectoEn: 'What is R-squared?',
    versoEn: 'The share of y\'s variance explained by the line; in simple regression, R² = ρ². Course example: ρ = 0.9631 → R² = 0.9275: 93% of the moves explained by the market, 7% specific risk. R² = 1 on real data: be suspicious.',
  },
  {
    id: 'm2-fc-113',
    moduleId: M2,
    tags: ['definition', 'regression'],
    recto: 'Le résidu d\'une régression, c\'est quoi — et pourquoi le regarder ?',
    verso: 'e = y − ŷ : ce que le modèle ne voit pas. Somme nulle par construction, mais la STRUCTURE diagnostique : courbe, tendance, paquets de volatilité = la droite rate quelque chose. Jamais livrer une régression sans le graphique des résidus.',
    rectoEn: 'What is a regression residual — and why look at it?',
    versoEn: 'e = y − ŷ: what the model does not see. Zero-sum by construction, but the STRUCTURE is the diagnostic: a curve, a trend, volatility clusters = the line is missing something. Never deliver a regression without the residual plot.',
  },
  {
    id: 'm2-fc-114',
    moduleId: M2,
    tags: ['piege', 'regression'],
    recto: 'R² = 0,95 entre le prix de l\'or et l\'immobilier parisien : du solide ?',
    verso: 'Non : régression fallacieuse — deux séries qui montent avec le temps sont mécaniquement corrélées (la dérive commune, facteur caché). Règle absolue du desk : régresser des RENDEMENTS, jamais des prix. En rendements, ce R² s\'effondrerait.',
    rectoEn: 'R² = 0.95 between gold prices and Paris property prices: solid?',
    versoEn: 'No: spurious regression — two series trending up over time are mechanically correlated (the shared drift, a hidden factor). The desk\'s absolute rule: regress RETURNS, never prices. In returns, that R² would collapse.',
  },
  {
    id: 'm2-fc-115',
    moduleId: M2,
    tags: ['piege', 'regression'],
    recto: 'Votre β = 1,35 estimé sur des semaines à ±4 % : valable dans un krach à −20 % ?',
    verso: 'Non : la droite n\'existe que sur la plage du nuage — extrapoler hors échantillon est illégitime, et c\'est précisément en crise que les relations se déforment (« toutes les corrélations vont à 1 »).',
    rectoEn: 'Your β = 1.35 estimated on ±4% weeks: valid in a −20% crash?',
    versoEn: 'No: the line only exists over the range of the cloud — extrapolating beyond the sample is illegitimate, and it is precisely in a crisis that relationships warp ("all correlations go to 1").',
  },
  {
    id: 'm2-fc-116',
    moduleId: M2,
    tags: ['piege', 'regression'],
    recto: 'Pourquoi un seul point peut-il faire basculer une pente de moindres carrés ?',
    verso: 'Les carrés donnent un poids énorme aux points extrêmes. Ex. du cours : retirez la semaine 5, la pente saute de 1,35 à 1,66. Réflexe : inspecter les outliers avant de croire un β.',
    rectoEn: 'Why can a single point flip a least-squares slope?',
    versoEn: 'Squares give extreme points enormous weight. Course example: remove week 5 and the slope jumps from 1.35 to 1.66. Reflex: inspect the outliers before trusting a β.',
  },
  {
    id: 'm2-fc-117',
    moduleId: M2,
    tags: ['reflexe-jury', 'regression'],
    recto: 'Le jury : « β = 1,35 calculé sur 5 semaines. Vous le mettez dans le pricer ? »',
    verso: 'Réflexe : une pente estimée porte une erreur standard — cinq points, c\'est un sondage à cinq personnes. Et un seul outlier déplace la pente (1,35 → 1,66 sans la semaine 5). Demander l\'historique long et l\'IC du β.',
    rectoEn: 'The panel: "β = 1.35 computed over 5 weeks. Do you feed it to the pricer?"',
    versoEn: 'Reflex: an estimated slope carries a standard error — five points is a five-person poll. And a single outlier moves the slope (1.35 → 1.66 without week 5). Ask for the long history and the β\'s CI.',
  },
  {
    id: 'm2-fc-118',
    moduleId: M2,
    tags: ['reflexe-jury', 'monte-carlo'],
    recto: 'Le jury : « Un million de trajectoires Monte-Carlo : le risque extrême est cerné ? »',
    verso: 'Réflexe : la simulation reproduit VOTRE modèle, pas le monde — un million de trajectoires lognormales n\'inventeront jamais les queues épaisses que la lognormale ignore. Monte-Carlo résout le problème du calcul, jamais celui du modèle.',
    rectoEn: 'The panel: "A million Monte Carlo paths: is the tail risk nailed down?"',
    versoEn: 'Reflex: the simulation reproduces YOUR model, not the world — a million lognormal paths will never invent the fat tails the lognormal ignores. Monte Carlo solves the computation problem, never the model problem.',
  },
  {
    id: 'm2-fc-119',
    moduleId: M2,
    tags: ['definition', 'monte-carlo'],
    recto: 'La méthode de Monte-Carlo, c\'est quoi ?',
    verso: 'Estimer une grandeur sans formule fermée en simulant N scénarios aléatoires et en moyennant : modéliser l\'aléa, simuler, compter. Un estimateur MC est une moyenne d\'échantillon → erreur standard $\\sqrt{p(1-p)/N}$, décroissance en 1/√N. Usages : exotiques, VaR.',
    rectoEn: 'What is the Monte Carlo method?',
    versoEn: 'Estimating a quantity with no closed-form formula by simulating N random scenarios and averaging: model the randomness, simulate, count. An MC estimator is a sample mean → standard error $\\sqrt{p(1-p)/N}$, decaying as 1/√N. Uses: exotics, VaR.',
  },
  {
    id: 'm2-fc-120',
    moduleId: M2,
    tags: ['ordre-de-grandeur', 'monte-carlo'],
    recto: 'Vitesse de convergence d\'un pricer Monte-Carlo ?',
    verso: 'Erreur en 1/√N : à N = 1 000, ≈ ±1,5 pt sur une probabilité ; une décimale de mieux coûte ×100 simulations (N = 100 000 pour 0,15 pt). Quadrupler N ne divise l\'erreur que par 2 — et changer la graine ne gagne rien.',
    rectoEn: 'Convergence speed of a Monte Carlo pricer?',
    versoEn: 'Error in 1/√N: at N = 1,000, ≈ ±1.5pt on a probability; one more decimal costs ×100 simulations (N = 100,000 for 0.15pt). Quadrupling N only halves the error — and changing the seed gains nothing.',
  },
];
