import type { Formule } from '../../../engine/types';

const M2 = '02-methodes-quantitatives';

export const formules: Formule[] = [
  {
    id: 'm2-f-01',
    moduleId: M2,
    nom: 'Valeur actuelle et valeur future',
    nomEn: 'Present and future value',
    latex: 'VF = VA \\times (1+r)^n \\qquad VA = \\frac{VF}{(1+r)^n}',
    commentaire: 'Pour transporter un flux unique dans le temps : capitaliser vers le futur, actualiser vers aujourd\'hui.',
    commentaireEn: 'To move a single cash flow through time: compound toward the future, discount back to today.',
  },
  {
    id: 'm2-f-02',
    moduleId: M2,
    nom: 'Valeur actuelle d\'une annuité',
    nomEn: 'Present value of an annuity',
    latex: 'VA = F \\times \\frac{1-(1+r)^{-n}}{r}',
    commentaire: 'Pour valoriser une série de flux constants versés en fin de période — mensualités, loyers, coupons.',
    commentaireEn: 'To value a stream of constant end-of-period cash flows — loan payments, rents, coupons.',
  },
  {
    id: 'm2-f-03',
    moduleId: M2,
    nom: 'Valeur future d\'une annuité',
    nomEn: 'Future value of an annuity',
    latex: 'VF = F \\times \\frac{(1+r)^{n}-1}{r}',
    commentaire: 'Pour la richesse accumulée par une épargne régulière à la fin des n périodes.',
    commentaireEn: 'For the wealth accumulated by regular savings at the end of the n periods.',
  },
  {
    id: 'm2-f-04',
    moduleId: M2,
    nom: 'Mensualité d\'un prêt',
    nomEn: 'Loan payment',
    latex: 'M = K \\times \\frac{r}{1-(1+r)^{-n}}',
    commentaire: 'Pour la mensualité qui rembourse un capital K en n périodes — l\'annuité lue à l\'envers ; avec des mensualités, tout passe en mensuel.',
    commentaireEn: 'For the payment that repays a principal K over n periods — the annuity read in reverse; with monthly payments, everything switches to monthly units.',
  },
  {
    id: 'm2-f-05',
    moduleId: M2,
    nom: 'Perpétuité',
    nomEn: 'Perpetuity',
    latex: 'P = \\frac{F}{r}',
    commentaire: 'Pour valoriser un flux constant sans fin (premier flux dans une période) — la première brique des modèles de dividendes.',
    commentaireEn: 'To value a constant flow that never ends (first flow one period away) — the first building block of dividend models.',
  },
  {
    id: 'm2-f-06',
    moduleId: M2,
    nom: 'Valeur actuelle nette (VAN)',
    nomEn: 'Net present value (NPV)',
    latex: 'VAN = -I_0 + \\sum_{t=1}^{n} \\frac{F_t}{(1+r)^t}',
    commentaire: 'Pour décider d\'investir : VAN positive, on accepte — et en cas de conflit avec le TRI, c\'est la VAN qui tranche.',
    commentaireEn: 'To decide whether to invest: positive NPV, accept — and when NPV and IRR conflict, NPV decides.',
  },
  {
    id: 'm2-f-07',
    moduleId: M2,
    nom: 'Moyenne géométrique',
    nomEn: 'Geometric mean',
    latex: 'r_g = \\left[\\prod_{i=1}^{n}(1+r_i)\\right]^{1/n} - 1',
    commentaire: 'Pour la performance composée réellement obtenue ; l\'arithmétique, toujours supérieure ou égale, estime l\'espérance d\'une période.',
    commentaireEn: 'For the compound performance actually achieved; the arithmetic mean, always greater or equal, estimates the expectation for one period.',
  },
  {
    id: 'm2-f-08',
    moduleId: M2,
    nom: 'Moyenne harmonique',
    nomEn: 'Harmonic mean',
    latex: 'H = \\frac{n}{\\sum_{i=1}^{n} \\frac{1}{x_i}}',
    commentaire: 'Pour le prix moyen d\'achat à montants investis constants (investissement programmé) et les moyennes de ratios type P/E.',
    commentaireEn: 'For the average purchase price when investing constant amounts (dollar cost averaging) and for averaging ratios such as P/Es.',
  },
  {
    id: 'm2-f-09',
    moduleId: M2,
    nom: 'Variance d\'échantillon',
    nomEn: 'Sample variance',
    latex: 's^2 = \\frac{1}{n-1}\\sum_{i=1}^{n}\\left(r_i - \\bar{r}\\right)^2',
    commentaire: 'Pour mesurer la dispersion : dénominateur n − 1, car la moyenne est elle-même estimée sur les mêmes données.',
    commentaireEn: 'To measure dispersion: denominator n − 1, because the mean is itself estimated on the same data.',
  },
  {
    id: 'm2-f-10',
    moduleId: M2,
    nom: 'Volatilité annualisée',
    nomEn: 'Annualised volatility',
    latex: '\\sigma_{\\text{an}} = \\sigma_{\\text{quot}} \\times \\sqrt{252}',
    commentaire: 'Pour annualiser : les variances s\'additionnent dans le temps, l\'écart-type croît en racine du temps — √252 ≈ 16.',
    commentaireEn: 'To annualise: variances add over time, the standard deviation grows with the square root of time — √252 ≈ 16.',
  },
  {
    id: 'm2-f-11',
    moduleId: M2,
    nom: 'Covariance d\'échantillon',
    nomEn: 'Sample covariance',
    latex: 's_{AB} = \\frac{1}{n-1}\\sum_{i=1}^{n}\\left(r_{A,i}-\\bar{r}_A\\right)\\left(r_{B,i}-\\bar{r}_B\\right)',
    commentaire: 'Pour mesurer si deux séries bougent ensemble — unité illisible (%²), à normaliser en corrélation.',
    commentaireEn: 'To measure whether two series move together — unreadable unit (%²), to be normalised into a correlation.',
  },
  {
    id: 'm2-f-12',
    moduleId: M2,
    nom: 'Corrélation',
    nomEn: 'Correlation',
    latex: '\\rho_{AB} = \\frac{s_{AB}}{s_A\\,s_B}',
    commentaire: 'Pour normaliser la covariance dans [−1, 1] — liaisons linéaires uniquement, et corrélation n\'est pas causalité.',
    commentaireEn: 'To normalise the covariance into [−1, 1] — linear relationships only, and correlation is not causation.',
  },
  {
    id: 'm2-f-13',
    moduleId: M2,
    nom: 'Théorème de Bayes',
    nomEn: 'Bayes\' theorem',
    latex: 'P(A \\mid B) = \\frac{P(B \\mid A)\\,P(A)}{P(B \\mid A)\\,P(A) + P(B \\mid \\bar{A})\\,P(\\bar{A})}',
    commentaire: 'Pour retourner un conditionnement — et en pratique, penser en effectifs : « sur 10 000 personnes… ».',
    commentaireEn: 'To reverse a conditioning — and in practice, think in headcounts: "out of 10,000 people…".',
  },
  {
    id: 'm2-f-14',
    moduleId: M2,
    nom: 'Loi binomiale',
    nomEn: 'Binomial distribution',
    latex: 'P(X = k) = \\binom{n}{k}\\,p^k\\,(1-p)^{n-k}',
    commentaire: 'Pour compter k succès sur n tirages indépendants — espérance np ; la structure de l\'arbre binomial du pricing d\'options.',
    commentaireEn: 'To count k successes out of n independent trials — expectation np; the structure of the binomial tree used to price options.',
  },
  {
    id: 'm2-f-15',
    moduleId: M2,
    nom: 'Espérance et variance d\'une variable discrète',
    nomEn: 'Mean and variance of a discrete random variable',
    latex: 'E[X] = \\sum_i p_i\\,x_i \\qquad \\text{Var}(X) = E[X^2] - \\big(E[X]\\big)^2',
    commentaire: 'Pour pricer un pari : moyenne pondérée par les probabilités, et dispersion autour d\'elle — la prime de risque naît de cette variance.',
    commentaireEn: 'To price a bet: probability-weighted average, and dispersion around it — the risk premium is born from this variance.',
  },
  {
    id: 'm2-f-16',
    moduleId: M2,
    nom: 'Z-score',
    nomEn: 'Z-score',
    latex: 'z = \\frac{x - \\mu}{\\sigma}',
    commentaire: 'Pour compter une distance à la moyenne en écarts-types et lire la probabilité dans la table de la normale (Φ).',
    commentaireEn: 'To count a distance to the mean in standard deviations and read the probability off the normal table (Φ).',
  },
  {
    id: 'm2-f-17',
    moduleId: M2,
    nom: 'Erreur standard de la moyenne',
    nomEn: 'Standard error of the mean',
    latex: 'SE = \\frac{\\sigma}{\\sqrt{n}}',
    commentaire: 'Pour mesurer de combien une moyenne d\'échantillon bouge d\'un tirage à l\'autre — diviser l\'erreur par 2 exige de quadrupler n.',
    commentaireEn: 'To measure how much a sample mean moves from one draw to the next — halving the error requires quadrupling n.',
  },
  {
    id: 'm2-f-18',
    moduleId: M2,
    nom: 'Intervalle de confiance à 95 %',
    nomEn: '95% confidence interval',
    latex: 'IC_{95\\,\\%} = \\bar{x} \\pm 1{,}96\\,\\frac{\\sigma}{\\sqrt{n}}',
    commentaire: 'Pour encadrer μ : la méthode attrape la vraie moyenne dans 95 % des échantillons — la confiance qualifie la méthode, pas l\'intervalle calculé.',
    commentaireEn: 'To bracket μ: the method catches the true mean in 95% of samples — the confidence qualifies the method, not the computed interval.',
  },
  {
    id: 'm2-f-19',
    moduleId: M2,
    nom: 'Statistique de test t',
    nomEn: 't-statistic',
    latex: 't = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}',
    commentaire: 'Pour tester H₀ : l\'écart observé compté en erreurs standards — significatif à 5 % bilatéral au-delà de 1,96 (grand n) ou 2,06 (Student, 24 ddl).',
    commentaireEn: 'To test H₀: the observed gap counted in standard errors — significant at 5% two-sided beyond 1.96 (large n) or 2.06 (Student, 24 df).',
  },
  {
    id: 'm2-f-20',
    moduleId: M2,
    nom: 'Régression linéaire : pente et ordonnée',
    nomEn: 'Linear regression: slope and intercept',
    latex: 'b = \\frac{\\text{cov}(x,y)}{\\text{var}(x)} \\qquad a = \\bar{y} - b\\,\\bar{x}',
    commentaire: 'Pour estimer la droite des moindres carrés : régresser un titre sur le marché donne son beta, et R² = ρ² la part expliquée.',
    commentaireEn: 'To estimate the least-squares line: regressing a stock on the market gives its beta, and R² = ρ² the share explained.',
  },
  {
    id: 'm2-f-21',
    moduleId: M2,
    nom: 'Variance d\'un portefeuille de deux actifs',
    nomEn: 'Two-asset portfolio variance',
    latex: '\\sigma_p^2 = w_A^2\\,\\sigma_A^2 + w_B^2\\,\\sigma_B^2 + 2\\,w_A w_B\\,\\rho_{AB}\\,\\sigma_A\\sigma_B',
    commentaire: 'Pour agréger le risque de deux actifs : c\'est la corrélation qui décide du gain de diversification — le pont vers le module 12.',
    commentaireEn: 'To aggregate the risk of two assets: the correlation decides the diversification gain — the bridge to module 12.',
  },
  {
    id: 'm2-f-22',
    moduleId: M2,
    nom: 'Erreur type d\'une estimation Monte-Carlo',
    nomEn: 'Monte Carlo standard error',
    latex: 'SE_{MC} = \\sqrt{\\frac{p\\,(1-p)}{N}}',
    commentaire: 'Pour calibrer une simulation : un estimateur Monte-Carlo est une moyenne, son erreur décroît en 1/√N — une décimale de précision coûte cent fois plus de tirages.',
    commentaireEn: 'To calibrate a simulation: a Monte Carlo estimator is a mean, its error shrinks as 1/√N — one extra decimal of precision costs a hundred times more draws.',
  },
];
