import type { Langue } from './types';

/**
 * Dictionnaire des textes d'interface (chrome UI uniquement — le contenu
 * pédagogique vit dans les modules avec ses champs *En).
 * Le français est la source de vérité ; chaque clé DOIT avoir fr + en.
 * Convention de nommage : namespace.cleCamelCase.
 */
export const TEXTES = {
  /* ── Navigation (AppShell) ─────────────────────────────────────── */
  'nav.tableau': { fr: 'Tableau de bord', en: 'Dashboard' },
  'nav.tableauCourt': { fr: 'Tableau', en: 'Home' },
  'nav.cours': { fr: 'Cours', en: 'Course' },
  'nav.entrainement': { fr: 'Entraînement', en: 'Practice' },
  'nav.examen': { fr: 'Examen blanc', en: 'Mock exam' },
  'nav.examenCourt': { fr: 'Examen', en: 'Exam' },
  'nav.glossaire': { fr: 'Glossaire', en: 'Glossary' },
  'nav.reglages': { fr: 'Réglages', en: 'Settings' },
  'nav.principale': { fr: 'Navigation principale', en: 'Main navigation' },
  'nav.sousTitre': { fr: 'Finance de marché', en: 'Financial markets' },
  'nav.accueilAria': { fr: 'Le Desk — Tableau de bord', en: 'Le Desk — Dashboard' },

  /* ── Commun (boutons, verdicts, libellés partagés) ─────────────── */
  'commun.retour': { fr: 'Retour', en: 'Back' },
  'commun.retourListe': { fr: 'Retour à la liste', en: 'Back to list' },
  'commun.valider': { fr: 'Valider', en: 'Submit' },
  'commun.suivant': { fr: 'Suivant', en: 'Next' },
  'commun.commencer': { fr: 'Commencer', en: 'Start' },
  'commun.terminer': { fr: 'Terminer', en: 'Finish' },
  'commun.annuler': { fr: 'Annuler', en: 'Cancel' },
  'commun.fermer': { fr: 'Fermer', en: 'Close' },
  'commun.questionSuivante': { fr: 'Question suivante', en: 'Next question' },
  'commun.question': { fr: 'Question', en: 'Question' },
  'commun.reponse': { fr: 'Réponse', en: 'Answer' },
  'commun.bonneReponse': { fr: 'Bonne réponse !', en: 'Correct!' },
  'commun.reponseIncorrecte': { fr: 'Réponse incorrecte.', en: 'Incorrect.' },
  'commun.reponseExacte': { fr: 'Réponse exacte', en: 'Exact answer' },
  'commun.votreReponse': { fr: 'Votre réponse', en: 'Your answer' },
  'commun.reponseNumerique': { fr: 'Réponse numérique', en: 'Numeric answer' },
  'commun.modules': { fr: 'Modules', en: 'Modules' },
  'commun.difficulte': { fr: 'Difficulté', en: 'Difficulty' },
  'commun.aucunModuleContenu': { fr: 'Aucun module avec contenu disponible.', en: 'No module with available content.' },
  'commun.aucuneQuestionDisponible': { fr: 'Aucune question disponible', en: 'No questions available' },
  'commun.filAriane': { fr: "Fil d'Ariane", en: 'Breadcrumb' },
  'commun.correct': { fr: 'Correct.', en: 'Correct.' },
  'commun.incorrect': { fr: 'Incorrect.', en: 'Incorrect.' },

  /* ── Tableau de bord ───────────────────────────────────────────── */
  'tableau.revisionsDuJour': { fr: 'Révisions du jour', en: "Today's reviews" },
  'tableau.rienAReviser': { fr: "Rien à réviser aujourd'hui.", en: 'Nothing to review today.' },
  'tableau.revenezDemain': { fr: 'Revenez demain pour de nouvelles cartes.', en: 'Come back tomorrow for new cards.' },
  'tableau.aReviser': { fr: 'à réviser', en: 'due' },
  'tableau.nouvelles': { fr: 'nouvelles', en: 'new' },
  'tableau.reviserMaintenant': { fr: 'Réviser maintenant', en: 'Review now' },
  'tableau.serieEnCours': { fr: 'Série en cours', en: 'Current streak' },
  'tableau.serieZero': { fr: 'Commencez une session pour démarrer votre série.', en: 'Start a session to begin your streak.' },
  'tableau.jourConsecutif': { fr: 'jour consécutif', en: 'consecutive day' },
  'tableau.joursConsecutifs': { fr: 'jours consécutifs', en: 'consecutive days' },
  'tableau.reprendre': { fr: 'Reprendre', en: 'Resume' },
  'tableau.progressionCours': { fr: 'Progression du cours', en: 'Course progress' },
  'tableau.aucunModule': { fr: 'Aucun module disponible.', en: 'No modules available.' },
  'tableau.pointsFaibles': { fr: 'Points faibles', en: 'Weak areas' },
  'tableau.pasAssezDonnees': { fr: 'Pas assez de données.', en: 'Not enough data yet.' },
  'tableau.faitesQcm': { fr: 'Faites quelques QCM pour révéler vos points faibles.', en: 'Take a few quizzes to reveal your weak areas.' },
  'tableau.retravailler': { fr: 'Retravailler', en: 'Practice again' },
  'tableau.dernieresSessions': { fr: 'Dernières sessions', en: 'Recent sessions' },
  'tableau.typeQcm': { fr: 'QCM', en: 'MCQ' },
  'tableau.typeExercice': { fr: 'Exercice', en: 'Exercise' },
  'tableau.typeProbleme': { fr: 'Problème', en: 'Problem' },
  'tableau.typeJury': { fr: 'Jury', en: 'Interview' },
  'tableau.typeExamen': { fr: 'Examen blanc', en: 'Mock exam' },

  /* ── Cours (liste, module, chapitre, MDX chrome) ───────────────── */
  'cours.bientotDisponible': { fr: 'Bientôt disponible', en: 'Coming soon' },
  'cours.chapitre': { fr: 'chapitre', en: 'chapter' },
  'cours.chapitres': { fr: 'chapitres', en: 'chapters' },
  'cours.chapitresAcquisSuffixe': { fr: 'acquis', en: 'completed' },
  'cours.acquis': { fr: 'Acquis', en: 'Completed' },
  'cours.lu': { fr: 'Lu', en: 'Read' },
  'cours.nonLu': { fr: 'Non lu', en: 'Unread' },
  'cours.moduleIntrouvable': { fr: 'Module introuvable', en: 'Module not found' },
  'cours.moduleIntrouvableIndice': { fr: "Ce module n'existe pas ou n'est pas encore disponible.", en: 'This module does not exist or is not yet available.' },
  'cours.retourCours': { fr: 'Retour aux cours', en: 'Back to course' },
  'cours.aucunChapitre': { fr: 'Aucun chapitre disponible', en: 'No chapters available' },
  'cours.enRedaction': { fr: 'Le contenu de ce module est en cours de rédaction.', en: 'The content of this module is being written.' },
  'cours.chapitreIntrouvable': { fr: 'Chapitre introuvable', en: 'Chapter not found' },
  'cours.chapitreIntrouvableIndice': { fr: "Ce chapitre n'existe pas ou n'est pas encore disponible.", en: 'This chapter does not exist or is not yet available.' },
  'cours.chapitrePrecedent': { fr: 'Chapitre précédent', en: 'Previous chapter' },
  'cours.chapitreSuivant': { fr: 'Chapitre suivant', en: 'Next chapter' },
  'cours.navigationChapitres': { fr: 'Navigation entre chapitres', en: 'Chapter navigation' },
  'cours.checkpointTitre': { fr: 'Checkpoint — vérifiez votre compréhension', en: 'Checkpoint — test your understanding' },
  'cours.checkpointValide': { fr: 'Checkpoint validé', en: 'Checkpoint passed' },
  'cours.toutesReussies': { fr: 'Toutes les questions ont été réussies.', en: 'All questions answered correctly.' },
  'cours.refaire': { fr: 'Refaire', en: 'Redo' },
  'cours.reessayer': { fr: 'Réessayer', en: 'Try again' },
  'cours.pourAllerPlusLoin': { fr: 'Pour aller plus loin', en: 'Going further' },
  'cours.calloutDefinition': { fr: 'Définition', en: 'Definition' },
  'cours.calloutExemple': { fr: 'Exemple', en: 'Example' },
  'cours.calloutPiege': { fr: 'Piège', en: 'Pitfall' },
  'cours.calloutImportant': { fr: 'Important', en: 'Key point' },

  /* ── Entraînement (hub + exercices & problèmes) ────────────────── */
  'exo.titre': { fr: 'Exercices & problèmes', en: 'Exercises & problems' },
  'exo.modesExercicesDesc': { fr: 'Calculs paramétrés avec corrigé pas à pas, progressifs par palier.', en: 'Parameterised calculations with step-by-step solutions, tiered by difficulty.' },
  'exo.modesQcmDesc': { fr: 'Questions à choix multiples, pièges expliqués.', en: 'Multiple-choice questions with explained pitfalls.' },
  'exo.modesJury': { fr: 'Questions de jury', en: 'Interview questions' },
  'exo.modesJuryDesc': { fr: 'Questions ouvertes type entretien ou grand oral.', en: 'Open-ended questions, interview or oral-exam style.' },
  'exo.modesFlashDesc': { fr: 'Révision espacée des notions et formules clés.', en: 'Spaced repetition of key concepts and formulas.' },
  'exo.palier1': { fr: 'Échauffement — N1', en: 'Warm-up — N1' },
  'exo.palier2': { fr: 'Classiques — N2', en: 'Core — N2' },
  'exo.palier3': { fr: 'Avancés — N3', en: 'Advanced — N3' },
  'exo.palier4': { fr: 'Boss — N4', en: 'Boss — N4' },
  'exo.reussi': { fr: 'Réussi', en: 'Passed' },
  'exo.nonReussi': { fr: 'Non réussi', en: 'Not passed' },
  'exo.parcours': { fr: 'Parcours', en: 'Learning path' },
  'exo.libre': { fr: 'Libre', en: 'Free practice' },
  'exo.modeEntrainement': { fr: "Mode d'entraînement", en: 'Practice mode' },
  'exo.moduleSansExercices': { fr: "Ce module n'a pas encore d'exercices.", en: 'This module has no exercises yet.' },
  'exo.revenezBientot': { fr: 'Revenez bientôt, le contenu est en préparation.', en: 'Check back soon — content is in preparation.' },
  'exo.parcoursTermine': { fr: 'Parcours terminé — rejouez ce que vous voulez', en: 'Learning path complete — replay anything you like' },
  'exo.continuerParcours': { fr: 'Continuer le parcours', en: 'Continue the path' },
  'exo.exercicesApplication': { fr: "Exercices d'application", en: 'Application exercises' },
  'exo.aucunExercice': { fr: 'Aucun exercice correspondant.', en: 'No matching exercises.' },
  'exo.modifiezFiltres': { fr: 'Modifiez les filtres pour élargir la sélection.', en: 'Adjust the filters to broaden the selection.' },
  'exo.problemesDeCas': { fr: 'Problèmes de cas', en: 'Case problems' },
  'exo.aucunProbleme': { fr: 'Aucun problème correspondant.', en: 'No matching problems.' },
  'exo.enonce': { fr: 'Énoncé', en: 'Problem statement' },
  'exo.miseEnSituation': { fr: 'Mise en situation', en: 'Scenario' },
  'exo.corrigePasAPas': { fr: 'Corrigé pas à pas', en: 'Step-by-step solution' },
  'exo.etape': { fr: 'Étape', en: 'Step' },
  'exo.rejouer': { fr: "Rejouer avec d'autres valeurs", en: 'Replay with new values' },
  'exo.rejouerCourt': { fr: 'Rejouer (autres valeurs)', en: 'Replay (new values)' },
  'exo.score': { fr: 'Score', en: 'Score' },

  /* ── QCM ───────────────────────────────────────────────────────── */
  'qcm.titre': { fr: 'QCM', en: 'MCQ' },
  'qcm.nombreQuestions': { fr: 'Nombre de questions', en: 'Number of questions' },
  'qcm.chronoParQuestion': { fr: 'Chrono par question', en: 'Time per question' },
  'qcm.aucunChrono': { fr: 'Aucun', en: 'None' },
  'qcm.questionDisponible': { fr: 'question disponible', en: 'question available' },
  'qcm.questionsDisponibles': { fr: 'questions disponibles', en: 'questions available' },
  'qcm.juste': { fr: 'Juste', en: 'Correct' },
  'qcm.faux': { fr: 'Faux', en: 'Wrong' },
  'qcm.tempsEcoule': { fr: 'Temps écoulé — la question est comptée fausse.', en: "Time's up — the question is marked wrong." },
  'qcm.voirResultats': { fr: 'Voir les résultats', en: 'View results' },
  'qcm.resultats': { fr: 'Résultats', en: 'Results' },
  'qcm.tempsMoyen': { fr: 'Temps moyen par question', en: 'Average time per question' },
  'qcm.parTheme': { fr: 'Par thème', en: 'By topic' },
  'qcm.questionsManquees': { fr: 'Questions manquées', en: 'Missed questions' },
  'qcm.tempsEcouleSansReponse': { fr: 'Temps écoulé — sans réponse.', en: "Time's up — no answer." },
  'qcm.refaireSession': { fr: 'Refaire une session', en: 'Start another session' },

  /* ── Mode jury ─────────────────────────────────────────────────── */
  'jury.titre': { fr: 'Mode jury', en: 'Interview mode' },
  'jury.preparation': { fr: 'Préparation', en: 'Preparation' },
  'jury.aucune': { fr: 'Aucune', en: 'None' },
  'jury.tirerQuestion': { fr: 'Tirer une question', en: 'Draw a question' },
  'jury.reponseVoixHaute': { fr: 'Réponse à voix haute', en: 'Answer out loud' },
  'jury.repondezVoixHaute': { fr: 'Répondez à voix haute, comme devant le jury.', en: 'Answer out loud, as if facing the panel.' },
  'jury.passerReponse': { fr: 'Passer à la réponse', en: 'Move on to the answer' },
  'jury.jaiTermine': { fr: "J'ai terminé", en: "I'm done" },
  'jury.grilleCorrection': { fr: 'Grille de correction', en: 'Marking grid' },
  'jury.planAttendu': { fr: 'Plan attendu', en: 'Expected outline' },
  'jury.pointsAttendus': { fr: 'Points attendus', en: 'Expected points' },
  'jury.pourImpressionner': { fr: 'Pour impressionner', en: 'To impress' },
  'jury.bonus': { fr: 'bonus', en: 'bonus' },
  'jury.reponseModele': { fr: 'Réponse modèle rédigée', en: 'Written model answer' },
  'jury.autoEvaluer': { fr: "S'auto-évaluer", en: 'Self-assess' },
  'jury.autoEvaluation': { fr: 'Auto-évaluation', en: 'Self-assessment' },
  'jury.commentEvaluez': { fr: 'Comment évaluez-vous votre réponse ?', en: 'How would you rate your answer?' },
  'jury.rate': { fr: 'Raté', en: 'Missed' },
  'jury.moyen': { fr: 'Moyen', en: 'Average' },
  'jury.bon': { fr: 'Bon', en: 'Good' },
  'jury.reponseEnregistree': { fr: 'Réponse enregistrée.', en: 'Answer recorded.' },

  /* ── Flashcards ────────────────────────────────────────────────── */
  'flash.titre': { fr: 'Flashcards', en: 'Flashcards' },
  'flash.sessionDuJour': { fr: 'Session du jour', en: "Today's session" },
  'flash.aReviser': { fr: 'à réviser', en: 'due' },
  'flash.nouvelles': { fr: 'nouvelles', en: 'new' },
  'flash.nouvellesParJour': { fr: 'Nouvelles cartes par jour', en: 'New cards per day' },
  'flash.modifiableReglages': { fr: '(modifiable dans Réglages)', en: '(adjustable in Settings)' },
  'flash.aucuneCarte': { fr: "Aucune carte pour aujourd'hui.", en: 'No cards for today.' },
  'flash.toutAJour': { fr: 'Toutes les révisions sont à jour, ou aucun module ne contient de flashcards.', en: 'All reviews are up to date, or no module contains flashcards.' },
  'flash.carteRestante': { fr: 'carte restante', en: 'card left' },
  'flash.cartesRestantes': { fr: 'cartes restantes', en: 'cards left' },
  'flash.appuyezRetourner': { fr: 'Appuyez pour retourner (Espace / Entrée)', en: 'Tap to flip (Space / Enter)' },
  'flash.encore': { fr: 'Encore', en: 'Again' },
  'flash.difficile': { fr: 'Difficile', en: 'Hard' },
  'flash.bien': { fr: 'Bien', en: 'Good' },
  'flash.facile': { fr: 'Facile', en: 'Easy' },
  'flash.aujourdhui': { fr: "aujourd'hui", en: 'today' },
  'flash.sessionTerminee': { fr: 'Session terminée', en: 'Session complete' },
  'flash.carteRevisee': { fr: 'carte révisée', en: 'card reviewed' },
  'flash.cartesRevisees': { fr: 'cartes révisées', en: 'cards reviewed' },

  /* ── Examen blanc ──────────────────────────────────────────────── */
  'examen.titre': { fr: 'Examen blanc', en: 'Mock exam' },
  'examen.enCours': { fr: 'Examen blanc en cours', en: 'Mock exam in progress' },
  'examen.contenuInsuffisant': { fr: 'Contenu insuffisant pour composer un examen.', en: 'Not enough content to build an exam.' },
  'examen.contenuInsuffisantIndice': { fr: "Ajoutez des QCM, problèmes et questions jury dans les modules pour débloquer l'examen blanc.", en: 'Add MCQs, problems and interview questions to the modules to unlock the mock exam.' },
  'examen.format': { fr: "Format de l'examen", en: 'Exam format' },
  'examen.sectionA': { fr: 'Section A', en: 'Section A' },
  'examen.sectionB': { fr: 'Section B', en: 'Section B' },
  'examen.sectionC': { fr: 'Section C', en: 'Section C' },
  'examen.sectionATitre': { fr: 'Section A — QCM', en: 'Section A — MCQ' },
  'examen.sectionBTitre': { fr: 'Section B — Problèmes', en: 'Section B — Problems' },
  'examen.sectionCTitre': { fr: 'Section C — Jury', en: 'Section C — Interview' },
  'examen.qcmChronometres': { fr: 'QCM chronométrés — 30 secondes par question', en: 'timed MCQs — 30 seconds per question' },
  'examen.problemeQuantitatif': { fr: 'problème quantitatif — sous-questions enchaînées', en: 'quantitative problem — chained sub-questions' },
  'examen.problemesQuantitatifs': { fr: 'problèmes quantitatifs — sous-questions enchaînées', en: 'quantitative problems — chained sub-questions' },
  'examen.questionJury': { fr: 'question jury — préparation 30 s + réponse 2 min', en: 'interview question — 30 s preparation + 2 min answer' },
  'examen.questionsJury': { fr: 'questions jury — préparation 30 s + réponse 2 min', en: 'interview questions — 30 s preparation + 2 min answer' },
  'examen.perimetreDuree': { fr: 'Périmètre : tout le contenu disponible. Durée estimée : 45 à 60 minutes.', en: 'Scope: all available content. Estimated duration: 45 to 60 minutes.' },
  'examen.commencerExamen': { fr: "Commencer l'examen", en: 'Start the exam' },
  'examen.historique': { fr: 'Historique', en: 'History' },
  'examen.abandonner': { fr: 'Abandonner', en: 'Quit' },
  'examen.abandonnerTitre': { fr: "Abandonner l'examen", en: 'Quit the exam' },
  'examen.abandonMessage': { fr: "L'examen sera interrompu et aucun résultat ne sera enregistré.", en: 'The exam will be stopped and no result will be recorded.' },
  'examen.continuerExamen': { fr: "Continuer l'examen", en: 'Continue the exam' },
  'examen.organisezMentalement': { fr: 'Organisez mentalement votre réponse. Le chrono de préparation tourne.', en: 'Organise your answer mentally. The preparation clock is running.' },
  'examen.tempsReponse': { fr: 'Temps de réponse', en: 'Answer time' },
  'examen.commencerReponse': { fr: 'Commencer la réponse', en: 'Start answering' },
  'examen.terminerEvaluer': { fr: 'Terminer et évaluer', en: 'Finish and assess' },
  'examen.autoEvalSubjective': { fr: 'Auto-évaluation subjective :', en: 'Subjective self-assessment:' },
  'examen.reponseModeleRapport': { fr: 'La réponse modèle sera visible dans le rapport final.', en: 'The model answer will be available in the final report.' },
  'examen.rapportTitre': { fr: "Rapport d'examen", en: 'Exam report' },
  'examen.scoreGlobal': { fr: 'Score global pondéré', en: 'Weighted overall score' },
  'examen.resultatsQcmTheme': { fr: 'Résultats QCM par thème', en: 'MCQ results by topic' },
  'examen.corrigeA': { fr: 'Corrigé — Section A (QCM)', en: 'Solutions — Section A (MCQ)' },
  'examen.corrigeB': { fr: 'Corrigé — Section B (Problèmes)', en: 'Solutions — Section B (Problems)' },
  'examen.corrigeC': { fr: 'Corrigé — Section C (Jury)', en: 'Solutions — Section C (Interview)' },
  'examen.sansReponse': { fr: 'Sans réponse', en: 'No answer' },
  'examen.probleme': { fr: 'Problème', en: 'Problem' },
  'examen.juryLabel': { fr: 'Jury', en: 'Interview' },
  'examen.plan': { fr: 'Plan', en: 'Outline' },
  'examen.bonusTitre': { fr: 'Bonus', en: 'Bonus' },
  'examen.reponseModele': { fr: 'Réponse modèle', en: 'Model answer' },
  'examen.retourAccueil': { fr: "Retour à l'accueil", en: 'Back to home' },
  'examen.votreReponseLabel': { fr: 'Votre réponse :', en: 'Your answer:' },
  'examen.reponseExacteLabel': { fr: 'Réponse exacte :', en: 'Exact answer:' },

  /* ── Glossaire & formulaire ────────────────────────────────────── */
  'glossaire.titre': { fr: 'Glossaire & formulaire', en: 'Glossary & formula sheet' },
  'glossaire.onglet': { fr: 'Glossaire', en: 'Glossary' },
  'glossaire.formulaire': { fr: 'Formulaire', en: 'Formula sheet' },
  'glossaire.section': { fr: 'Section', en: 'Section' },
  'glossaire.rechercher': { fr: 'Rechercher', en: 'Search' },
  'glossaire.chercherTerme': { fr: 'Chercher un terme…', en: 'Search for a term…' },
  'glossaire.chercherFormule': { fr: 'Chercher une formule…', en: 'Search for a formula…' },
  'glossaire.vide': { fr: "Le glossaire est vide pour l'instant.", en: 'The glossary is empty for now.' },
  'glossaire.videIndice': { fr: 'Les définitions seront ajoutées au fur et à mesure de la construction du cours.', en: 'Definitions will be added as the course is built.' },
  'glossaire.aucunResultat': { fr: 'Aucun résultat.', en: 'No results.' },
  'glossaire.essayezAutreTerme': { fr: 'Essayez un autre terme ou simplifiez votre recherche.', en: 'Try another term or simplify your search.' },
  'glossaire.formulaireVide': { fr: "Le formulaire est vide pour l'instant.", en: 'The formula sheet is empty for now.' },
  'glossaire.formulesAjoutees': { fr: 'Les formules seront ajoutées au fur et à mesure de la construction du cours.', en: 'Formulas will be added as the course is built.' },
  'glossaire.essayezAutreFormule': { fr: 'Essayez un autre nom de formule.', en: 'Try another formula name.' },
  'glossaire.equivalentEn': { fr: 'EN :', en: 'FR:' },

  /* ── Réglages ──────────────────────────────────────────────────── */
  'reglages.titre': { fr: 'Réglages', en: 'Settings' },
  'reglages.apparence': { fr: 'Apparence', en: 'Appearance' },
  'reglages.themeInterface': { fr: "Thème de l'interface", en: 'Interface theme' },
  'reglages.sombre': { fr: 'Sombre', en: 'Dark' },
  'reglages.clair': { fr: 'Clair', en: 'Light' },
  'reglages.langueDescription': { fr: "Langue de l'interface et du contenu", en: 'Interface and content language' },
  'reglages.langueFallback': { fr: 'Le contenu non encore traduit reste affiché en français.', en: 'Content not yet translated is shown in French.' },
  'reglages.flashcards': { fr: 'Flashcards', en: 'Flashcards' },
  'reglages.nouvellesCartesParJour': { fr: 'Nouvelles cartes par jour', en: 'New cards per day' },
  'reglages.entre5et50': { fr: 'Entre 5 et 50 cartes.', en: 'Between 5 and 50 cards.' },
  'reglages.sauvegarde': { fr: 'Sauvegarde', en: 'Backup' },
  'reglages.exportDescription': { fr: 'Téléchargez une copie de votre progression au format JSON.', en: 'Download a copy of your progress as a JSON file.' },
  'reglages.exporter': { fr: 'Exporter ma progression', en: 'Export my progress' },
  'reglages.importDescription': { fr: 'Restaurez une sauvegarde précédemment exportée.', en: 'Restore a previously exported backup.' },
  'reglages.importer': { fr: 'Importer une sauvegarde', en: 'Import a backup' },
  'reglages.resetDescription': { fr: 'Supprimez toute votre progression et repartez de zéro.', en: 'Delete all your progress and start from scratch.' },
  'reglages.reinitialiser': { fr: 'Réinitialiser la progression', en: 'Reset progress' },
  'reglages.importReussi': { fr: 'Progression importée avec succès.', en: 'Progress imported successfully.' },
  'reglages.importErreur': { fr: "Erreur lors de l'import.", en: 'Import failed.' },
  'reglages.fichierInvalide': { fr: 'Fichier invalide.', en: 'Invalid file.' },
  'reglages.resetReussi': { fr: 'Progression réinitialisée.', en: 'Progress has been reset.' },
  'reglages.importModalMessage': { fr: 'Cette opération remplace votre progression actuelle par la sauvegarde importée. Cette action est irréversible.', en: 'This operation replaces your current progress with the imported backup. This action cannot be undone.' },
  'reglages.confirmerImport': { fr: "Confirmer l'import", en: 'Confirm import' },
  'reglages.resetModalMessage': { fr: 'Toute votre progression sera définitivement supprimée : tentatives, flashcards, série, chapitres lus. Cette action est irréversible.', en: 'All your progress will be permanently deleted: attempts, flashcards, streak, read chapters. This action cannot be undone.' },
  'reglages.ouiReinitialiser': { fr: 'Oui, réinitialiser', en: 'Yes, reset' },
  'reglages.derniereConfirmation': { fr: 'Dernière confirmation : êtes-vous certain de vouloir tout effacer ?', en: 'Final confirmation: are you sure you want to erase everything?' },
  'reglages.effacerDefinitivement': { fr: 'Effacer définitivement', en: 'Erase permanently' },

  /* ── Chapitre bilingue ─────────────────────────────────────────────── */
  'cours.enAnglaisIndisponible': { fr: 'Version anglaise non encore disponible — affichage en français.', en: 'English version not yet available — showing French.' },

  /* ── Entraînement (hub) ────────────────────────────────────────────── */
  'exo.titreHub': { fr: 'Entraînement', en: 'Practice' },
  'exo.modesExercicesTitre': { fr: 'Exercices & problèmes', en: 'Exercises & problems' },
  'exo.modesQcmTitre': { fr: 'QCM', en: 'MCQ' },
  'exo.modesFlashTitre': { fr: 'Flashcards', en: 'Flashcards' },
} as const satisfies Record<string, Record<Langue, string>>;

export type CleTexte = keyof typeof TEXTES;

/** Traduit une clé d'interface. Le français est toujours présent (source de vérité). */
export function t(langue: Langue, cle: CleTexte): string {
  return TEXTES[cle][langue];
}
