import type { Flashcard } from '../../../engine/types';

const M4 = '04-taux-obligations';

// 80 cartes : 30 definitions, 20 formules, 12 ordres de grandeur, 18 pieges & reflexes.
// Couverture : ch1 taux & conventions, ch2 obligation, ch3 pricing, ch4 rendement,
// ch5 courbe, ch6 duration & convexite, ch7 marche en pratique.
export const flashcards: Flashcard[] = [
  // ───────────────────────── Chapitre 1 — Taux & conventions ─────────────────────────
  {
    id: 'm4-fc-01',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Formule de l\'actualisation d\'un flux unique ?',
    verso: '$VA = \\frac{VF}{(1+r)^n}$. Ex. : 10 000 € dans 5 ans à 3 % → 10 000/1,03⁵ = 8 626,09 €.',
    rectoEn: 'Formula for discounting a single future cash flow?',
    versoEn: '$PV = \\frac{FV}{(1+r)^n}$. E.g.: €10,000 due in 5 years at 3% → 10,000/1.03⁵ = €8,626.09.',
  },
  {
    id: 'm4-fc-02',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Formule de la capitalisation composée ?',
    verso: '$VF = VA \\times (1+r)^n$. Ex. : 10 000 € à 3 % sur 5 ans → 11 592,74 € (contre 11 500 € en intérêts simples).',
    rectoEn: 'Compound interest (future value) formula?',
    versoEn: '$FV = PV \\times (1+r)^n$. E.g.: €10,000 at 3% for 5 years → €11,592.74 (vs €11,500 with simple interest).',
  },
  {
    id: 'm4-fc-03',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Relation de Fisher entre taux nominal, taux réel et inflation anticipée ?',
    verso: '$(1+i) = (1+r_{\\text{réel}})(1+\\pi^{e})$, soit i ≈ r + πᵉ pour des taux faibles — auxquels s\'ajoutent les primes de risque propres à chaque emprunteur.',
    rectoEn: 'Fisher relation linking nominal rate, real rate and expected inflation?',
    versoEn: '$(1+i) = (1+r_{\\text{real}})(1+\\pi^{e})$, i.e. i ≈ r + πᵉ for low rates — plus the risk premia specific to each borrower.',
  },
  {
    id: 'm4-fc-04',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Taux annuel effectif d\'un taux nominal r composé m fois par an ?',
    verso: '$r_{\\text{eff}} = (1 + \\frac{r}{m})^m - 1$. Ex. : 4 % à composition semestrielle → 1,02² − 1 = 4,04 %.',
    rectoEn: 'Effective annual rate of a nominal rate r compounded m times a year?',
    versoEn: '$r_{\\text{eff}} = (1 + \\frac{r}{m})^m - 1$. E.g.: 4% compounded semi-annually → 1.02² − 1 = 4.04%.',
  },
  {
    id: 'm4-fc-05',
    moduleId: M4,
    tags: ['formule', 'conventions'],
    recto: 'Intérêt d\'une opération de marché monétaire euro ?',
    verso: '$I = N \\times r \\times \\frac{\\text{jours}}{360}$ (Exact/360, intérêts simples). Ex. : 1 M€ à 3 % sur 91 jours → 7 583,33 €.',
    rectoEn: 'Interest on a euro money-market transaction?',
    versoEn: '$I = N \\times r \\times \\frac{\\text{days}}{360}$ (Act/360, simple interest). E.g.: €1m at 3% for 91 days → €7,583.33.',
  },
  {
    id: 'm4-fc-06',
    moduleId: M4,
    tags: ['piege', 'conventions'],
    recto: 'Peut-on comparer directement un taux Exact/360 à un taux en base 365 ?',
    verso: 'Non : à taux affiché égal, la base 360 verse ~1,4 % d\'intérêts de plus en relatif. 3 % Exact/360 ≈ 3,04 % en base 365. Réflexe : toujours demander la base.',
    rectoEn: 'Can you compare an Act/360 rate directly with a 365-day-basis rate?',
    versoEn: 'No: at the same quoted rate, the 360 basis pays about 1.4% more interest in relative terms. 3% Act/360 ≈ 3.04% on a 365 basis. Reflex: always ask for the day count.',
  },
  {
    id: 'm4-fc-07',
    moduleId: M4,
    tags: ['piege', 'conventions'],
    recto: 'Placement du 15 février au 17 mai (91 jours réels) compté en 30/360 : combien de jours retenus ?',
    verso: '92 jours : chaque mois est forfaitisé à 30 jours, février « compte » donc 30. Les jours comptés ne sont pas les jours réels — le piège classique des bases.',
    rectoEn: 'Deposit from 15 February to 17 May (91 actual days) counted under 30/360: how many days?',
    versoEn: '92 days: every month is standardized to 30 days, so February "counts" 30. Counted days are not actual days — the classic day-count trap.',
  },
  {
    id: 'm4-fc-08',
    moduleId: M4,
    tags: ['definition', 'marche-monetaire'],
    recto: 'L\'€STR, c\'est quoi ?',
    verso: 'Taux au jour le jour de la zone euro, calculé chaque jour par la BCE sur les transactions réelles d\'emprunt en blanc des banques. La référence « sans risque » overnight en euro.',
    rectoEn: 'What is €STR?',
    versoEn: 'The euro-area overnight rate, computed daily by the ECB from banks\' actual unsecured borrowing transactions. The euro overnight risk-free benchmark.',
  },
  {
    id: 'm4-fc-09',
    moduleId: M4,
    tags: ['definition', 'marche-monetaire'],
    recto: 'L\'Euribor, c\'est quoi, et en quoi diffère-t-il de l\'€STR ?',
    verso: 'Taux interbancaire offert en euro (1 semaine à 12 mois), issu des contributions d\'un panel de banques. Taux à terme avec risque de crédit — l\'€STR est overnight, sur transactions réelles.',
    rectoEn: 'What is Euribor, and how does it differ from €STR?',
    versoEn: 'The euro interbank offered rate (1 week to 12 months), built from a panel of banks\' contributions. A term rate carrying credit risk — €STR is overnight and transaction-based.',
  },
  {
    id: 'm4-fc-10',
    moduleId: M4,
    tags: ['definition', 'marche-monetaire'],
    recto: 'Un BTF, c\'est quoi ?',
    verso: 'Bon du Trésor français à taux fixe < 1 an, zéro-coupon, émis chaque semaine par adjudication (base Exact/360). L\'équivalent du T-bill américain.',
    rectoEn: 'What is a BTF?',
    versoEn: 'A French Treasury bill: fixed-rate paper under 1 year, zero-coupon, auctioned weekly (Act/360 basis). The French equivalent of a US T-bill.',
  },
  {
    id: 'm4-fc-11',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'marche-monetaire'],
    recto: 'Niveau de l\'€STR début 2026 ?',
    verso: 'Environ 2 % : le prix de l\'argent au jour le jour en zone euro, calé sur les taux directeurs de la BCE.',
    rectoEn: 'Level of €STR in early 2026?',
    versoEn: 'Around 2%: the price of overnight money in the euro area, anchored to the ECB\'s policy rates.',
  },
  {
    id: 'm4-fc-12',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'marche-monetaire'],
    recto: 'Niveau de l\'Euribor 3 mois début 2026 ?',
    verso: 'Environ 2 à 2,5 % — légèrement au-dessus de l\'€STR (~2 %) : l\'écart rémunère le terme et le risque de crédit interbancaire, et sert de baromètre de confiance (envolé en 2008).',
    rectoEn: 'Level of 3-month Euribor in early 2026?',
    versoEn: 'About 2 to 2.5% — slightly above €STR (~2%): the gap pays for term and interbank credit risk, and doubles as a confidence barometer (it blew out in 2008).',
  },

  // ───────────────────────── Chapitre 2 — L'obligation ─────────────────────────
  {
    id: 'm4-fc-13',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Une obligation, c\'est quoi ?',
    verso: 'Titre de créance négociable : l\'émetteur emprunte un nominal, verse un coupon périodique et rembourse à maturité. Contrairement à un prêt bancaire, le titre s\'échange librement sur un marché.',
    rectoEn: 'What is a bond?',
    versoEn: 'A tradable debt security: the issuer borrows a face value, pays a periodic coupon and repays at maturity. Unlike a bank loan, the security trades freely in a market.',
  },
  {
    id: 'm4-fc-14',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Un zéro-coupon, c\'est quoi, et ses deux propriétés remarquables ?',
    verso: 'Obligation à flux unique (le nominal à l\'échéance), vendue sous le pair. Seul titre dont le rendement est verrouillé à l\'achat et dont la duration égale exactement la maturité.',
    rectoEn: 'What is a zero-coupon bond, and its two remarkable properties?',
    versoEn: 'A single-cash-flow bond (face value at maturity), sold below par. The only bond whose return is locked in at purchase and whose duration exactly equals its maturity.',
  },
  {
    id: 'm4-fc-15',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Une obligation à taux variable (FRN), c\'est quoi ?',
    verso: 'Titre dont le coupon est réindexé à chaque fixing sur un taux monétaire (ex. Euribor 3M + 0,60 %). Son prix reste proche du pair tant que la qualité de crédit de l\'émetteur est stable.',
    rectoEn: 'What is a floating rate note (FRN)?',
    versoEn: 'A bond whose coupon resets at each fixing off a money-market rate (e.g. 3-month Euribor + 0.60%). Its price stays near par as long as the issuer\'s credit quality is stable.',
  },
  {
    id: 'm4-fc-16',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Une OATi, c\'est quoi ?',
    verso: 'OAT indexée sur l\'inflation française hors tabac : nominal multiplié par un coefficient d\'indexation, coupon = taux réel fixe appliqué à ce nominal indexé. L\'OAT€i suit l\'inflation zone euro.',
    rectoEn: 'What is an OATi?',
    versoEn: 'A French government bond indexed to French ex-tobacco inflation: the principal is scaled by an index ratio and the coupon — a fixed real rate — applies to that indexed principal. The OAT€i tracks euro-area inflation.',
  },
  {
    id: 'm4-fc-17',
    moduleId: M4,
    tags: ['definition', 'dette'],
    recto: 'Une OAT, c\'est quoi ?',
    verso: 'Obligation assimilable du Trésor : dette à moyen-long terme de l\'État français, émise par adjudication mensuelle par l\'AFT. La souche 10 ans la plus récente est la référence du marché français.',
    rectoEn: 'What is an OAT?',
    versoEn: 'The French government\'s medium- to long-term bond, auctioned monthly by Agence France Trésor. The most recent 10-year line is the French market benchmark.',
  },
  {
    id: 'm4-fc-18',
    moduleId: M4,
    tags: ['definition', 'primaire'],
    recto: 'Comment fonctionne une adjudication « à prix multiples » ?',
    verso: 'Les ordres des SVT sont servis du prix le plus élevé au plus bas jusqu\'au montant visé, et chaque ordre servi paie le prix qu\'il a demandé. Format AFT : BTF chaque semaine, OAT chaque mois.',
    rectoEn: 'How does a multiple-price auction work?',
    versoEn: 'Primary dealers\' bids are filled from the highest price down to the target amount, and each filled bid pays its own price. The AFT format: weekly BTF, monthly OAT auctions.',
  },
  {
    id: 'm4-fc-19',
    moduleId: M4,
    tags: ['definition', 'primaire'],
    recto: 'La syndication, c\'est quoi ?',
    verso: 'Émission via un syndicat de banques qui sonde les investisseurs, construit le livre d\'ordres, cale le prix et alloue les titres. Voie normale des entreprises — et des États pour les souches nouvelles ou très longues.',
    rectoEn: 'What is a syndicated issue?',
    versoEn: 'An issue placed by a bank syndicate that sounds out investors, builds the order book, sets the price and allocates the bonds. The standard route for corporates — and for sovereigns on new or very long lines.',
  },
  {
    id: 'm4-fc-20',
    moduleId: M4,
    tags: ['definition', 'primaire'],
    recto: 'Un SVT, c\'est quoi ?',
    verso: 'Spécialiste en valeurs du Trésor (primary dealer) : banque agréée par l\'AFT — elles sont une quinzaine — qui s\'engage à soumissionner aux adjudications et à coter la dette française en continu au secondaire.',
    rectoEn: 'What is an SVT?',
    versoEn: 'A French primary dealer: a bank approved by the AFT — about fifteen of them — committed to bidding at auctions and quoting French debt continuously in the secondary market.',
  },
  {
    id: 'm4-fc-21',
    moduleId: M4,
    tags: ['piege', 'obligation'],
    recto: 'Les taux montent brutalement de 1 point : que fait le prix d\'un FRN ?',
    verso: 'Il reste proche du pair : le coupon se recale sur l\'Euribor au prochain fixing — la hausse passe dans les coupons futurs, pas dans le prix. Il ne décroche que si la marge de crédit exigée change.',
    rectoEn: 'Rates jump 1 point: what happens to an FRN\'s price?',
    versoEn: 'It stays near par: the coupon resets to Euribor at the next fixing — the rise flows into future coupons, not the price. It only drifts from par if the required credit margin changes.',
  },
  {
    id: 'm4-fc-22',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'marche'],
    recto: 'Taille du marché obligataire mondial ?',
    verso: '≈ 140 000 Md USD d\'encours — du même ordre que la capitalisation boursière mondiale des actions. C\'est sur les courbes souveraines que se pricent quasiment tous les autres actifs.',
    rectoEn: 'Size of the global bond market?',
    versoEn: 'About $140 trillion outstanding — on a par with global equity market capitalization. Nearly every other asset is priced off sovereign yield curves.',
  },

  // ───────────────────────── Chapitre 3 — Pricer une obligation ─────────────────────────
  {
    id: 'm4-fc-23',
    moduleId: M4,
    tags: ['formule', 'pricing'],
    recto: 'Formule du prix d\'une obligation à taux fixe ?',
    verso: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+r)^t}$ : somme des flux actualisés au taux exigé. Ex. : 1 000 €, coupon 5 %, 3 ans, taux 4 % → 1 027,75 €.',
    rectoEn: 'Price formula for a fixed-rate bond?',
    versoEn: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+r)^t}$: the sum of cash flows discounted at the required rate. E.g.: €1,000 face, 5% coupon, 3 years, 4% market rate → €1,027.75.',
  },
  {
    id: 'm4-fc-24',
    moduleId: M4,
    tags: ['formule', 'pricing'],
    recto: 'Formule du prix d\'un zéro-coupon ?',
    verso: '$P = \\frac{N}{(1+r)^n}$ : le nominal actualisé depuis l\'échéance. Ex. : 1 000 € dans 10 ans à 4 % → 675,56 €.',
    rectoEn: 'Price formula for a zero-coupon bond?',
    versoEn: '$P = \\frac{N}{(1+r)^n}$: the face value discounted from maturity. E.g.: €1,000 due in 10 years at 4% → €675.56.',
  },
  {
    id: 'm4-fc-25',
    moduleId: M4,
    tags: ['formule', 'pricing'],
    recto: 'Formule du coupon couru ?',
    verso: '$\\text{couru} = C \\times \\frac{\\text{jours courus}}{\\text{jours de la période}}$ (Exact/Exact pour les OAT). Ex. : coupon 30 €, 146 jours sur 365 → 12,00 €.',
    rectoEn: 'Accrued interest formula?',
    versoEn: '$\\text{accrued} = C \\times \\frac{\\text{days accrued}}{\\text{days in period}}$ (Act/Act for OATs). E.g.: €30 coupon, 146 of 365 days → €12.00.',
  },
  {
    id: 'm4-fc-26',
    moduleId: M4,
    tags: ['definition', 'pricing'],
    recto: 'Prix propre vs prix sale ?',
    verso: 'Propre (clean) : prix coté sur les écrans, hors couru. Sale (dirty) : montant réglé = propre + coupon couru. On cote propre pour neutraliser les dents de scie calendaires du couru.',
    rectoEn: 'Clean price versus dirty price?',
    versoEn: 'Clean: the quoted screen price, excluding accrued interest. Dirty: the amount settled = clean + accrued. Quoting clean strips out the calendar sawtooth of accruals.',
  },
  {
    id: 'm4-fc-27',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Une OAT cote 98,45 %. Est-ce le montant que règle l\'acheteur ?',
    verso: 'Non : le prix coté est un prix propre. On règle prix propre + coupon couru. Ex. : 984,50 € + 12,00 € de couru = 996,50 €. Le couru s\'ajoute, jamais ne se déduit.',
    rectoEn: 'An OAT quotes 98.45%. Is that what the buyer pays?',
    versoEn: 'No: the quoted price is a clean price. You settle clean price + accrued interest. E.g.: €984.50 + €12.00 accrued = €996.50. Accrued is added, never deducted.',
  },
  {
    id: 'm4-fc-28',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Le prix sale chute du montant du coupon au lendemain du détachement. Mauvais signe ?',
    verso: 'Non, pure mécanique : le couru retombe à zéro une fois le coupon versé ; le prix propre n\'a presque pas bougé. C\'est pour neutraliser ces dents de scie que le marché cote en prix propre.',
    rectoEn: 'The dirty price drops by the coupon amount the day after payment. Bad news?',
    versoEn: 'No — pure mechanics: accrued interest resets to zero once the coupon is paid; the clean price has barely moved. That sawtooth is exactly why the market quotes clean prices.',
  },
  {
    id: 'm4-fc-29',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Pourquoi le prix d\'une obligation baisse-t-il quand les taux montent ? Les deux réponses attendues ?',
    verso: 'Mécanique : flux contractuels fixes actualisés à un taux plus élevé → somme plus faible. Marché : les émissions neuves servent plus, l\'ancien titre doit décoter pour rester compétitif.',
    rectoEn: 'Why does a bond\'s price fall when rates rise? The two expected answers?',
    versoEn: 'Mechanical: fixed contractual cash flows discounted at a higher rate → a smaller sum. Market: new issues pay more, so the old bond must trade at a discount to stay competitive.',
  },
  {
    id: 'm4-fc-30',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Coupon 2 %, taux de marché 4 % : où est le prix ? Et la règle générale ?',
    verso: 'Sous le pair (décote). Coupon > taux → surcote ; égal → pair ; inférieur → décote. La décote n\'est pas une punition : c\'est le mécanisme qui égalise les rendements entre l\'ancien et le neuf.',
    rectoEn: '2% coupon, 4% market rate: where is the price? And the general rule?',
    versoEn: 'Below par (discount). Coupon > market rate → premium; equal → par; lower → discount. The discount is no punishment: it is the mechanism that equalizes returns between old and new bonds.',
  },

  // ───────────────────────── Chapitre 4 — Le rendement ─────────────────────────
  {
    id: 'm4-fc-31',
    moduleId: M4,
    tags: ['formule', 'rendement'],
    recto: 'Formule du rendement courant ?',
    verso: '$r_{\\text{courant}} = \\frac{C}{P}$. Ex. : coupon 50 €, prix 1 027,75 € → 4,86 %. Ordre de grandeur du loyer annuel — ignore remboursement et calendrier.',
    rectoEn: 'Current yield formula?',
    versoEn: '$r_{\\text{current}} = \\frac{C}{P}$. E.g.: €50 coupon, €1,027.75 price → 4.86%. A quick gauge of annual income — ignores redemption and timing.',
  },
  {
    id: 'm4-fc-32',
    moduleId: M4,
    tags: ['formule', 'rendement'],
    recto: 'Équation de définition du rendement actuariel (YTM) ?',
    verso: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+y)^t}$ : y égalise prix observé et flux actualisés. Pas de formule fermée — essais encadrants. Ex. : 2 ans, coupon 4 %, P = 990 € → y ≈ 4,53 %.',
    rectoEn: 'Defining equation of yield to maturity (YTM)?',
    versoEn: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+y)^t}$: y equates the observed price and the discounted flows. No closed form — solved by bracketing trials. E.g.: 2 years, 4% coupon, P = €990 → y ≈ 4.53%.',
  },
  {
    id: 'm4-fc-33',
    moduleId: M4,
    tags: ['definition', 'rendement'],
    recto: 'Le rendement actuariel (YTM), c\'est quoi ?',
    verso: 'Le taux unique qui égalise prix observé et flux actualisés : le TRI de l\'investissement obligataire. Rendement promis sous conditions (détention à maturité, réinvestissement à y), pas garanti.',
    rectoEn: 'What is yield to maturity (YTM)?',
    versoEn: 'The single rate that equates the observed price with the discounted cash flows: the IRR of the bond investment. A promised return under conditions (hold to maturity, reinvest at y), not a guaranteed one.',
  },
  {
    id: 'm4-fc-34',
    moduleId: M4,
    tags: ['definition', 'rendement'],
    recto: 'Le rendement courant, c\'est quoi, et que rate-t-il ?',
    verso: 'Coupon annuel rapporté au prix payé : le loyer instantané du titre. Il ignore le remboursement (gain ou perte en capital certain) et le calendrier des flux — myope en surcote comme en décote.',
    rectoEn: 'What is current yield, and what does it miss?',
    versoEn: 'The annual coupon over the price paid: the bond\'s instant income measure. It ignores redemption (the certain capital gain or loss) and cash-flow timing — misleading on premium and discount bonds alike.',
  },
  {
    id: 'm4-fc-35',
    moduleId: M4,
    tags: ['piege', 'rendement'],
    recto: 'Titre en surcote : classer YTM, rendement courant et taux de coupon.',
    verso: 'YTM < rendement courant < taux de coupon. Ex. fil rouge : 4 % < 4,86 % < 5 %. L\'ordre s\'inverse en décote. Le rendement courant ne voit pas la perte en capital.',
    rectoEn: 'Premium bond: rank YTM, current yield and coupon rate.',
    versoEn: 'YTM < current yield < coupon rate. Running example: 4% < 4.86% < 5%. The order flips for a discount bond. Current yield is blind to the capital loss.',
  },
  {
    id: 'm4-fc-36',
    moduleId: M4,
    tags: ['piege', 'rendement'],
    recto: 'J\'achète à un YTM de 4 % et je garde jusqu\'au bout : mon rendement réalisé est-il garanti à 4 % ?',
    verso: 'Non : la détention fige les flux, pas leur réinvestissement. Si les taux baissent, les coupons se replacent moins bien → rendement réalisé < 4 %. Seul le zéro-coupon verrouille son rendement.',
    rectoEn: 'I buy at a 4% YTM and hold to maturity: is my realized return locked at 4%?',
    versoEn: 'No: holding fixes the cash flows, not their reinvestment. If rates fall, coupons reinvest at lower rates → realized return below 4%. Only a zero-coupon locks in its return at purchase.',
  },
  {
    id: 'm4-fc-37',
    moduleId: M4,
    tags: ['piege', 'rendement'],
    recto: '« L\'OAT 10 ans est passée de 3,2 % à 3,5 %. » Que s\'est-il passé concrètement ?',
    verso: 'Les souverains se cotent en taux : le YTM de la souche de référence a monté, donc son prix a baissé. « Les taux montent » et « les prix obligataires baissent » sont la même phrase.',
    rectoEn: '"The 10-year OAT moved from 3.2% to 3.5%." What actually happened?',
    versoEn: 'Sovereigns are quoted in yield: the benchmark\'s YTM rose, so its price fell. "Yields up" and "bond prices down" are the same sentence in two different units.',
  },
  {
    id: 'm4-fc-38',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'rendement'],
    recto: 'Niveau du taux OAT 10 ans début 2026 ?',
    verso: 'Environ 3 à 3,5 % — contre ~2 % pour l\'argent au jour le jour (€STR) : l\'écart rémunère le temps long (prime de terme, incertitude sur l\'inflation et les taux futurs).',
    rectoEn: 'Level of the 10-year OAT yield in early 2026?',
    versoEn: 'About 3 to 3.5% — versus ~2% for overnight money (€STR): the gap pays for the long horizon (term premium, uncertainty on inflation and future rates).',
  },

  // ───────────────────────── Chapitre 5 — La courbe des taux ─────────────────────────
  {
    id: 'm4-fc-39',
    moduleId: M4,
    tags: ['formule', 'courbe'],
    recto: 'Formule du bootstrap du taux zéro-coupon 2 ans ?',
    verso: '$(1+z_2)^2 = \\frac{C+N}{P - \\frac{C}{1+z_1}}$ : on retire du prix le coupon de l\'an 1 actualisé à z₁, le flux final donne z₂. Ex. du cours : z₂ = 3,01 % pour un YTM de 3,00 %.',
    rectoEn: 'Bootstrap formula for the 2-year zero-coupon rate?',
    versoEn: '$(1+z_2)^2 = \\frac{C+N}{P - \\frac{C}{1+z_1}}$: strip the year-1 coupon discounted at z₁ from the price; the final flow yields z₂. Course example: z₂ = 3.01% versus a 3.00% YTM.',
  },
  {
    id: 'm4-fc-40',
    moduleId: M4,
    tags: ['formule', 'courbe'],
    recto: 'Formule du taux forward implicite f₁,₂ ?',
    verso: '$(1+z_2)^2 = (1+z_1)(1+f_{1,2})$ — imposée par l\'absence d\'arbitrage. Ex. : z₁ = 2 %, z₂ = 3 % → f₁,₂ = 1,03²/1,02 − 1 ≈ 4,01 %.',
    rectoEn: 'Implied forward rate formula f₁,₂?',
    versoEn: '$(1+z_2)^2 = (1+z_1)(1+f_{1,2})$ — imposed by no-arbitrage. E.g.: z₁ = 2%, z₂ = 3% → f₁,₂ = 1.03²/1.02 − 1 ≈ 4.01%.',
  },
  {
    id: 'm4-fc-41',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'La courbe des taux, c\'est quoi ?',
    verso: 'Les rendements actuariels d\'un même émetteur classés par maturité, à un instant donné. La courbe souveraine de chaque devise est l\'étalon de pricing de tous les autres actifs.',
    rectoEn: 'What is the yield curve?',
    versoEn: 'One issuer\'s yields to maturity arranged by maturity at a point in time. Each currency\'s sovereign curve is the pricing benchmark for every other asset.',
  },
  {
    id: 'm4-fc-42',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Une courbe des taux inversée, c\'est quoi et qu\'annonce-t-elle ?',
    verso: 'Taux courts > taux longs : le marché anticipe des baisses de taux directeurs, scénario de ralentissement. Signal historiquement sérieux (1980, 1990, 2001, 2008), pas un oracle (2022-2024).',
    rectoEn: 'What is an inverted yield curve and what does it signal?',
    versoEn: 'Short rates above long rates: the market prices in policy-rate cuts, the typical slowdown scenario. A historically serious signal (1980, 1990, 2001, 2008), not an oracle (2022-2024).',
  },
  {
    id: 'm4-fc-43',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Le bootstrapping, c\'est quoi et pourquoi en a-t-on besoin ?',
    verso: 'Extraction de proche en proche des taux zéro-coupon depuis les prix d\'obligations couponnées (z₁ → z₂ → z₃…). Nécessaire car le YTM d\'un titre couponné est une moyenne déformée par l\'effet coupon.',
    rectoEn: 'What is bootstrapping and why is it needed?',
    versoEn: 'The step-by-step extraction of zero-coupon rates from coupon-bond prices (z₁ → z₂ → z₃…). Needed because a coupon bond\'s YTM is an average distorted by the coupon effect.',
  },
  {
    id: 'm4-fc-44',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Un taux forward, c\'est quoi ?',
    verso: 'Le taux à terme implicite de la courbe : celui qui rend équivalents placer long d\'un bloc et rouler du court. Un fait arithmétique d\'absence d\'arbitrage — pas une prévision.',
    rectoEn: 'What is a forward rate?',
    versoEn: 'The term rate implied by the curve: the rate that makes one long placement equivalent to rolling shorter ones. An arithmetic no-arbitrage fact — not a forecast.',
  },
  {
    id: 'm4-fc-45',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Le 2s10s, c\'est quoi ?',
    verso: 'Le spread de courbe le plus suivi : taux 10 ans moins taux 2 ans, en points de base. Il s\'élargit (pentification) ou se resserre (aplatissement) ; négatif = courbe inversée.',
    rectoEn: 'What is the 2s10s?',
    versoEn: 'The most watched curve spread: the 10-year minus the 2-year yield, in basis points. It widens (steepening) or narrows (flattening); negative = inverted curve.',
  },
  {
    id: 'm4-fc-46',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Vocabulaire bull/bear appliqué aux mouvements de courbe ?',
    verso: 'Bull = les taux baissent (prix montent), bear = les taux montent. Combiné à steepening/flattening : ex. bear flattening = les taux courts montent plus vite que les longs — type resserrement 2022-2023.',
    rectoEn: 'Bull/bear vocabulary applied to curve moves?',
    versoEn: 'Bull = yields fall (prices rise), bear = yields rise. Combined with steepening/flattening: e.g. bear flattening = short rates rise faster than long ones — the 2022-2023 tightening pattern.',
  },
  {
    id: 'm4-fc-47',
    moduleId: M4,
    tags: ['piege', 'courbe'],
    recto: 'z₁ = 2 %, z₂ = 3 % → forward 1 an dans 1 an ≈ 4,01 %. Le marché « prévoit »-il 4,01 % ?',
    verso: 'Non : 4,01 % est le taux d\'indifférence entre placer 2 ans d\'un bloc et rouler du 1 an. La prime de terme se loge dans le forward, qui surestime historiquement les taux réalisés.',
    rectoEn: 'z₁ = 2%, z₂ = 3% → 1-year forward, 1 year ahead ≈ 4.01%. Does the market "forecast" 4.01%?',
    versoEn: 'No: 4.01% is the indifference rate between a 2-year block and rolling 1-year placements. The term premium sits inside the forward, which has historically overshot realized rates.',
  },
  {
    id: 'm4-fc-48',
    moduleId: M4,
    tags: ['piege', 'courbe'],
    recto: 'Deux obligations, même signature, même maturité, coupons différents : même YTM ?',
    verso: 'Non sur une courbe pentue : c\'est l\'effet coupon — le gros coupon pèse plus sur les taux courts. Ex. du cours : titre 2 ans au pair, YTM 3,00 %, mais z₂ = 3,01 %. D\'où le bootstrap.',
    rectoEn: 'Two bonds, same issuer, same maturity, different coupons: same YTM?',
    versoEn: 'Not on a sloped curve: that is the coupon effect — the high coupon weights short rates more. Course example: 2-year bond at par, YTM 3.00%, but z₂ = 3.01%. Hence bootstrapping.',
  },

  // ───────────────────────── Chapitre 6 — Duration & convexité ─────────────────────────
  {
    id: 'm4-fc-49',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule de la duration de Macaulay ?',
    verso: '$D_{Mac} = \\frac{\\sum_t t \\cdot VA(F_t)}{P}$ — barycentre temporel des flux actualisés, en années. Ex. : 1 000 €, coupon 5 %, 3 ans, taux 4 % → 2,86 ans.',
    rectoEn: 'Macaulay duration formula?',
    versoEn: '$D_{Mac} = \\frac{\\sum_t t \\cdot PV(F_t)}{P}$ — the time barycentre of discounted cash flows, in years. E.g.: €1,000, 5% coupon, 3 years, 4% rate → 2.86 years.',
  },
  {
    id: 'm4-fc-50',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule de la duration modifiée ?',
    verso: '$D_{mod} = \\frac{D_{Mac}}{1+y}$ — sans unité. Ex. : 2,8615/1,04 = 2,75 : une hausse de 1 point du taux coûte ≈ 2,75 % du prix.',
    rectoEn: 'Modified duration formula?',
    versoEn: '$D_{mod} = \\frac{D_{Mac}}{1+y}$ — unitless. E.g.: 2.8615/1.04 = 2.75: a 1-point rise in yield costs about 2.75% of the price.',
  },
  {
    id: 'm4-fc-51',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule de la variation de prix par la duration ?',
    verso: '$\\Delta P \\approx -D_{mod} \\times \\Delta y \\times P$. Ex. : $D_{mod}$ 5, +100 pb, 1 000 € → −50 €.',
    rectoEn: 'Duration approximation of the price change?',
    versoEn: '$\\Delta P \\approx -D_{mod} \\times \\Delta y \\times P$. E.g.: $D_{mod}$ 5, +100bp, €1,000 → −€50.',
  },
  {
    id: 'm4-fc-52',
    moduleId: M4,
    tags: ['formule', 'convexite'],
    recto: 'Formule de la variation de prix avec correction de convexité ?',
    verso: '$\\frac{\\Delta P}{P} \\approx -D_{mod}\\,\\Delta y + \\frac{1}{2}\\,C\\,(\\Delta y)^2$. Le terme en (Δy)², positif dans les deux sens, corrige la tangente pour les chocs larges.',
    rectoEn: 'Price change formula with the convexity correction?',
    versoEn: '$\\frac{\\Delta P}{P} \\approx -D_{mod}\\,\\Delta y + \\frac{1}{2}\\,C\\,(\\Delta y)^2$. The (Δy)² term, positive in both directions, fixes the tangent error for large shocks.',
  },
  {
    id: 'm4-fc-53',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule du DV01 ?',
    verso: '$DV01 = D_{mod} \\times P \\times 0{,}0001$ — en euros par point de base. Ex. : D_mod 2,75, position 1 027,75 € → 0,28 €/pb.',
    rectoEn: 'DV01 formula?',
    versoEn: '$DV01 = D_{mod} \\times P \\times 0.0001$ — in euros per basis point. E.g.: D_mod 2.75, €1,027.75 position → €0.28 per bp.',
  },
  {
    id: 'm4-fc-54',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Duration d\'un portefeuille obligataire ?',
    verso: '$D_{ptf} = \\sum_i w_i \\, D_i$ : moyenne des durations pondérée par les poids en valeur de marché. Ex. : 60 % à 2,5 + 40 % à 7 → 4,3.',
    rectoEn: 'Duration of a bond portfolio?',
    versoEn: '$D_{ptf} = \\sum_i w_i \\, D_i$: the market-value-weighted average of the holdings\' durations. E.g.: 60% at 2.5 + 40% at 7 → 4.3.',
  },
  {
    id: 'm4-fc-55',
    moduleId: M4,
    tags: ['formule', 'couverture'],
    recto: 'Nombre de contrats pour couvrir un portefeuille en DV01 ?',
    verso: '$n = \\frac{DV01_{\\text{portefeuille}}}{DV01_{\\text{contrat}}}$. Ex. : 4 000 €/pb à couvrir, contrat à 80 €/pb → vendre 50 contrats. Position insensible au premier ordre.',
    rectoEn: 'Number of futures contracts to hedge a portfolio in DV01 terms?',
    versoEn: '$n = \\frac{DV01_{\\text{portfolio}}}{DV01_{\\text{futures}}}$. E.g.: €4,000/bp to hedge, €80/bp per contract → sell 50 contracts. First-order rate-neutral position.',
  },
  {
    id: 'm4-fc-56',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Prix et duration d\'une perpétuité ?',
    verso: '$P = \\frac{c}{y}$ et $D_{Mac} = \\frac{1+y}{y}$. À 4 % : duration de 26 ans — maturité infinie, duration finie.',
    rectoEn: 'Price and duration of a perpetuity?',
    versoEn: '$P = \\frac{c}{y}$ and $D_{Mac} = \\frac{1+y}{y}$. At 4%: a 26-year duration — infinite maturity, finite duration.',
  },
  {
    id: 'm4-fc-57',
    moduleId: M4,
    tags: ['definition', 'duration'],
    recto: 'La duration de Macaulay, c\'est quoi ?',
    verso: 'La moyenne des dates des flux pondérée par leur poids actualisé dans le prix : le barycentre temporel, en années. Celle d\'un zéro-coupon égale exactement sa maturité.',
    rectoEn: 'What is Macaulay duration?',
    versoEn: 'The average of the cash-flow dates weighted by each flow\'s discounted share of the price: the time centre of gravity, in years. A zero-coupon\'s equals its maturity exactly.',
  },
  {
    id: 'm4-fc-58',
    moduleId: M4,
    tags: ['definition', 'duration'],
    recto: 'La duration modifiée, c\'est quoi ?',
    verso: 'Le facteur de sensibilité du prix au taux : D_Mac/(1+y), sans unité. D_mod = 6 → ≈ 6 % de perte pour +1 point de taux. Géométriquement : la pente de la tangente prix-taux.',
    rectoEn: 'What is modified duration?',
    versoEn: 'The price sensitivity factor to yield: D_Mac/(1+y), unitless. D_mod = 6 → about a 6% price loss for a 1-point rise. Geometrically: the slope of the price-yield tangent.',
  },
  {
    id: 'm4-fc-59',
    moduleId: M4,
    tags: ['definition', 'duration'],
    recto: 'Le DV01, c\'est quoi ?',
    verso: 'La variation en monnaie d\'une position pour 1 pb de taux : D_mod × valeur × 0,0001. L\'unité de risque quotidienne des desks — « si les taux prennent 1 pb, je perds combien ? »',
    rectoEn: 'What is DV01?',
    versoEn: 'The money change in a position for a 1bp move in yields: D_mod × market value × 0.0001. The desk\'s daily unit of risk — "rates up 1bp, how much do I lose?"',
  },
  {
    id: 'm4-fc-60',
    moduleId: M4,
    tags: ['definition', 'convexite'],
    recto: 'La convexité, c\'est quoi, et pourquoi est-ce une qualité ?',
    verso: 'La courbure de la relation prix-taux. Le terme ½C(Δy)² est positif dans les deux sens : il amortit les pertes en hausse et amplifie les gains en baisse. À duration égale, elle se paie.',
    rectoEn: 'What is convexity, and why is it a quality?',
    versoEn: 'The curvature of the price-yield relationship. The ½C(Δy)² term is positive either way: it cushions losses when rates rise and amplifies gains when they fall. At equal duration, it commands a price.',
  },
  {
    id: 'm4-fc-61',
    moduleId: M4,
    tags: ['definition', 'gestion'],
    recto: 'L\'immunisation d\'un portefeuille, c\'est quoi ?',
    verso: 'Égaliser duration de l\'actif et du passif (à valeurs actuelles égales) : effet prix et effet réinvestissement se compensent à l\'horizon de la duration. Le cœur de la gestion actif-passif.',
    rectoEn: 'What is portfolio immunization?',
    versoEn: 'Matching asset and liability durations (at equal present values): the price effect and the reinvestment effect offset at the duration horizon. The heart of asset-liability management.',
  },
  {
    id: 'm4-fc-62',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Coupon ↑ ⇒ duration ?',
    verso: 'Duration ↓ : les flux sont rapatriés plus tôt, le barycentre temporel se rapproche. Sur 3 ans à 4 % : 3,00 ans à coupon nul, 2,86 ans à 5 %, 2,79 ans à 8 %.',
    rectoEn: 'Coupon up ⇒ duration?',
    versoEn: 'Duration down: more value is paid back early, pulling the time barycentre toward the present. Over 3 years at 4%: 3.00 years at zero coupon, 2.86 at 5%, 2.79 at 8%.',
  },
  {
    id: 'm4-fc-63',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Même maturité 10 ans, même choc de +1 point : zéro-coupon et coupon 8 % perdent-ils autant ?',
    verso: 'Non : −9,13 % pour le zéro-coupon, −7,01 % pour le coupon 8 %. La maturité ne date que le dernier flux ; la sensibilité dépend du calendrier complet — c\'est la duration.',
    rectoEn: 'Same 10-year maturity, same +1-point shock: do a zero-coupon and an 8% coupon bond lose the same?',
    versoEn: 'No: −9.13% for the zero-coupon, −7.01% for the 8% coupon. Maturity only dates the last flow; sensitivity depends on the full cash-flow schedule — that is duration.',
  },
  {
    id: 'm4-fc-64',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: '« La duration de ce portefeuille est de 7. » — 7 quoi ? Les trois unités à ne pas confondre ?',
    verso: 'Macaulay en années ; modifiée sans unité (% de prix par point de taux) ; DV01 en euros par pb. Toujours nommer l\'unité — le lapsus trahit la récitation.',
    rectoEn: '"This portfolio\'s duration is 7." — 7 what? The three units never to mix up?',
    versoEn: 'Macaulay in years; modified duration unitless (% of price per point of yield); DV01 in euros per bp. Always name the unit — the slip betrays rote learning.',
  },
  {
    id: 'm4-fc-65',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Dans ΔP ≈ −D_mod × Δy × P, comment entrer un choc de 50 pb ?',
    verso: 'En décimal : 50 pb = 0,005. Ex. : D_mod 6, P 1 000 € → −30 €. Erreur classique : prendre 0,5 ou 0,05 et se tromper d\'un facteur 10 ou 100.',
    rectoEn: 'In ΔP ≈ −D_mod × Δy × P, how do you enter a 50bp shock?',
    versoEn: 'As a decimal: 50bp = 0.005. E.g.: D_mod 6, P €1,000 → −€30. Classic error: using 0.5 or 0.05 and ending up off by a factor of 10 or 100.',
  },
  {
    id: 'm4-fc-66',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Deux portefeuilles de même DV01, l\'un concentré sur le 2 ans, l\'autre sur le 30 ans : même risque ?',
    verso: 'Non : la duration couvre un choc parallèle — le niveau, pas la pente. Un bear steepening les traite très différemment. D\'où durations partielles et stratégies de courbe.',
    rectoEn: 'Two portfolios with the same DV01, one in 2-year paper, the other in 30-year: same risk?',
    versoEn: 'No: duration covers a parallel shock — the level, not the slope. A bear steepening treats them very differently. Hence partial durations and curve strategies.',
  },
  {
    id: 'm4-fc-67',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'duration'],
    recto: 'Duration modifiée d\'une OAT 10 ans ?',
    verso: '≈ 8 à 8,5 : une hausse de 100 pb coûte environ 8 % du prix ; 1 pb ≈ 0,08 % de la valeur (DV01).',
    rectoEn: 'Modified duration of a 10-year OAT?',
    versoEn: 'About 8 to 8.5: a 100bp rise costs roughly 8% of the price; 1bp ≈ 0.08% of value (DV01).',
  },

  // ───────────────────────── Chapitre 7 — Le marché en pratique ─────────────────────────
  {
    id: 'm4-fc-68',
    moduleId: M4,
    tags: ['definition', 'repo'],
    recto: 'Le repo, c\'est quoi ?',
    verso: 'Pension livrée : vente de titres avec engagement de rachat à date et prix convenus — un prêt de cash garanti par titres. Finance les desks, permet la vente à découvert, transmet la politique monétaire.',
    rectoEn: 'What is a repo?',
    versoEn: 'A repurchase agreement: selling securities while committing to buy them back at an agreed date and price — a cash loan secured by securities. Funds desks, enables short selling, transmits monetary policy.',
  },
  {
    id: 'm4-fc-69',
    moduleId: M4,
    tags: ['definition', 'repo'],
    recto: 'Le haircut d\'un repo, c\'est quoi ?',
    verso: 'La décote sur la valeur du collatéral : avec 2 % de haircut, 10 M€ de titres ne lèvent que 9,8 M€ de cash. Protège le prêteur contre une baisse des titres pendant l\'opération.',
    rectoEn: 'What is a repo haircut?',
    versoEn: 'The discount applied to the collateral\'s value: with a 2% haircut, €10m of securities raises only €9.8m of cash. It protects the lender against a fall in the collateral during the trade.',
  },
  {
    id: 'm4-fc-70',
    moduleId: M4,
    tags: ['definition', 'repo'],
    recto: 'GC vs « spécial » au repo ?',
    verso: 'GC : n\'importe quel titre d\'un panier de qualité convient, le taux colle aux taux directeurs — le prix du cash. Spécial : un titre précis est recherché (vente à découvert), son taux repo passe sous le GC.',
    rectoEn: 'GC versus "special" in the repo market?',
    versoEn: 'GC: any security from a quality basket will do; the rate tracks policy rates — the price of cash. Special: a specific bond is in demand (short sellers), so its repo rate drops below GC.',
  },
  {
    id: 'm4-fc-71',
    moduleId: M4,
    tags: ['definition', 'spreads'],
    recto: 'Le spread OAT-Bund, c\'est quoi ?',
    verso: 'Écart de rendement actuariel entre OAT 10 ans et Bund 10 ans, en pb : la prime exigée pour prêter à la France plutôt qu\'à l\'Allemagne (budget, politique, liquidité). Des rendements, jamais des prix.',
    rectoEn: 'What is the OAT-Bund spread?',
    versoEn: 'The yield gap between the 10-year OAT and the 10-year Bund, in bp: the premium demanded to lend to France rather than Germany (fiscal, political, liquidity). Always yields, never prices.',
  },
  {
    id: 'm4-fc-72',
    moduleId: M4,
    tags: ['definition', 'marche'],
    recto: 'Le démembrement (stripping), c\'est quoi ?',
    verso: 'Séparer coupons et principal d\'une OAT en zéro-coupons négociables indépendamment (strips). Idéal pour adosser un engagement à date fixe : duration = maturité, exactement.',
    rectoEn: 'What is stripping?',
    versoEn: 'Splitting an OAT\'s coupons and principal into independently traded zero-coupons (strips). Ideal for matching a fixed-date liability: duration equals maturity, exactly.',
  },
  {
    id: 'm4-fc-73',
    moduleId: M4,
    tags: ['piege', 'spreads'],
    recto: 'L\'OAT-Bund s\'écarte de 75 à 90 pb. Peut-on conclure que le marché sanctionne la France ?',
    verso: 'Non : un spread a deux jambes. Si le Bund baisse (fuite vers la qualité), l\'écart se creuse sans que la France ait démérité. Réflexe : décomposer les deux jambes avant d\'interpréter.',
    rectoEn: 'The OAT-Bund widens from 75 to 90bp. Can you conclude the market is punishing France?',
    versoEn: 'No: a spread has two legs. If the Bund rallies (flight to quality), the gap widens with no French fault. Reflex: decompose both legs before interpreting.',
  },
  {
    id: 'm4-fc-74',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'dette'],
    recto: 'Dette publique française début 2026 ?',
    verso: '≈ 3 500 Md€, dont ≈ 2 800 Md€ de dette négociable de l\'État — l\'essentiel en OAT, le court terme en BTF.',
    rectoEn: 'French public debt in early 2026?',
    versoEn: 'About €3,500bn, of which about €2,800bn of negotiable central-government debt — mostly OATs, with BTFs covering the short end.',
  },
  {
    id: 'm4-fc-75',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'spreads'],
    recto: 'Niveau du spread OAT-Bund début 2026 ? Et avant 2022 ?',
    verso: '≈ 70-80 pb, contre 30-40 pb avant 2022 : changement de régime avec la remontée des taux et l\'instabilité politique française (pics > 80 pb en 2024-2025).',
    rectoEn: 'OAT-Bund spread in early 2026? And before 2022?',
    versoEn: 'About 70-80bp, versus 30-40bp before 2022: a regime change driven by rising rates and French political instability (peaks above 80bp in 2024-2025).',
  },
  {
    id: 'm4-fc-76',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'dette'],
    recto: 'Programme annuel d\'émissions à moyen-long terme de l\'AFT ?',
    verso: 'De l\'ordre de 300 Md€ ces dernières années, déroulé par adjudications régulières (BTF chaque semaine, OAT chaque mois). La prévisibilité fait emprunter moins cher.',
    rectoEn: 'AFT\'s annual medium- and long-term issuance program?',
    versoEn: 'On the order of €300bn in recent years, run through regular auctions (weekly BTFs, monthly OATs). Predictability lowers the cost of borrowing.',
  },
  {
    id: 'm4-fc-77',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'dette'],
    recto: 'Quelle part de la dette française est détenue par des non-résidents ?',
    verso: 'Environ la moitié — signe de confiance autant que source de vulnérabilité : ces porteurs comparent en permanence l\'OAT à ses concurrentes.',
    rectoEn: 'What share of French debt is held by non-residents?',
    versoEn: 'About half — a sign of confidence as much as a source of vulnerability: those holders constantly benchmark the OAT against its competitors.',
  },
  {
    id: 'm4-fc-78',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'spreads'],
    recto: 'Jusqu\'où est monté le BTP-Bund au pic de la crise de la zone euro (2011-2012) ?',
    verso: 'Au-delà de 500 pb — les marchés testaient la réversibilité de l\'euro. Il a fallu le « whatever it takes » de Draghi (juillet 2012) pour casser la spirale.',
    rectoEn: 'How wide did the BTP-Bund spread get at the peak of the euro crisis (2011-2012)?',
    versoEn: 'Beyond 500bp — markets were openly testing the euro\'s reversibility. It took Draghi\'s "whatever it takes" (July 2012) to break the spiral.',
  },
  {
    id: 'm4-fc-79',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'credit'],
    recto: 'Spread de crédit typique d\'un émetteur investment grade ?',
    verso: '≈ 80 à 150 pb au-dessus du souverain de même maturité (IG : AAA à BBB−). Très variable selon le cycle : compression en période calme, explosion en crise.',
    rectoEn: 'Typical credit spread for an investment-grade issuer?',
    versoEn: 'About 80 to 150bp over the same-maturity sovereign (IG: AAA to BBB−). Highly cycle-dependent: compressed in calm markets, exploding in crises.',
  },
  {
    id: 'm4-fc-80',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'credit'],
    recto: 'Spread de crédit typique d\'un émetteur high yield ?',
    verso: '≈ 300 à 500 pb au-dessus du souverain (notes sous BBB−). L\'écart avec l\'IG rémunère une probabilité de défaut nettement plus élevée — mécanique détaillée au module 5.',
    rectoEn: 'Typical credit spread for a high-yield issuer?',
    versoEn: 'About 300 to 500bp over the sovereign (ratings below BBB−). The gap versus IG pays for a much higher default probability — mechanics covered in module 5.',
  },
];
