import type { Flashcard } from '../../../engine/types';

const M4 = '04-taux-obligations';

// 120 cartes : 30 definitions, 20 formules, 12 ordres de grandeur, 26 pieges,
// 20 reflexes jury, 12 calculs mentaux.
// Couverture : ch1 taux & conventions, ch2 obligation, ch3 pricing, ch4 rendement,
// ch5 courbe, ch6 duration & convexite, ch7 marche en pratique.
export const flashcards: Flashcard[] = [
  // ───────────────────────── Chapitre 1 — Taux & conventions ─────────────────────────
  {
    id: 'm4-fc-01',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Formule de l\'actualisation d\'un flux unique ?',
    verso: '$VA = \\frac{VF}{(1+r)^n}$. Ex. : 10 000 € dans 5 ans à 3 % → 10 000/1,03⁵ = 8 626,09 €.',
    rectoEn: 'Formula for discounting a single future cash flow?',
    versoEn: '$PV = \\frac{FV}{(1+r)^n}$. E.g.: €10,000 due in 5 years at 3% → 10,000/1.03⁵ = €8,626.09.',
  },
  {
    id: 'm4-fc-02',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Formule de la capitalisation composée ?',
    verso: '$VF = VA \\times (1+r)^n$. Ex. : 10 000 € à 3 % sur 5 ans → 11 592,74 € (contre 11 500 € en intérêts simples).',
    rectoEn: 'Compound interest (future value) formula?',
    versoEn: '$FV = PV \\times (1+r)^n$. E.g.: €10,000 at 3% for 5 years → €11,592.74 (vs €11,500 with simple interest).',
  },
  {
    id: 'm4-fc-03',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Relation de Fisher entre taux nominal, taux réel et inflation anticipée ?',
    verso: '$(1+i) = (1+r_{\\text{réel}})(1+\\pi^{e})$, soit i ≈ r + πᵉ pour des taux faibles — auxquels s\'ajoutent les primes de risque propres à chaque emprunteur.',
    rectoEn: 'Fisher relation linking nominal rate, real rate and expected inflation?',
    versoEn: '$(1+i) = (1+r_{\\text{real}})(1+\\pi^{e})$, i.e. i ≈ r + πᵉ for low rates — plus the risk premia specific to each borrower.',
  },
  {
    id: 'm4-fc-04',
    moduleId: M4,
    tags: ['formule', 'taux'],
    recto: 'Taux annuel effectif d\'un taux nominal r composé m fois par an ?',
    verso: '$r_{\\text{eff}} = (1 + \\frac{r}{m})^m - 1$. Ex. : 4 % à composition semestrielle → 1,02² − 1 = 4,04 %.',
    rectoEn: 'Effective annual rate of a nominal rate r compounded m times a year?',
    versoEn: '$r_{\\text{eff}} = (1 + \\frac{r}{m})^m - 1$. E.g.: 4% compounded semi-annually → 1.02² − 1 = 4.04%.',
  },
  {
    id: 'm4-fc-05',
    moduleId: M4,
    tags: ['formule', 'conventions'],
    recto: 'Intérêt d\'une opération de marché monétaire euro ?',
    verso: '$I = N \\times r \\times \\frac{\\text{jours}}{360}$ (Exact/360, intérêts simples). Ex. : 1 M€ à 3 % sur 91 jours → 7 583,33 €.',
    rectoEn: 'Interest on a euro money-market transaction?',
    versoEn: '$I = N \\times r \\times \\frac{\\text{days}}{360}$ (Act/360, simple interest). E.g.: €1m at 3% for 91 days → €7,583.33.',
  },
  {
    id: 'm4-fc-06',
    moduleId: M4,
    tags: ['piege', 'conventions'],
    recto: 'Peut-on comparer directement un taux Exact/360 à un taux en base 365 ?',
    verso: 'Non : à taux affiché égal, la base 360 verse ~1,4 % d\'intérêts de plus en relatif. 3 % Exact/360 ≈ 3,04 % en base 365. Réflexe : toujours demander la base.',
    rectoEn: 'Can you compare an Act/360 rate directly with a 365-day-basis rate?',
    versoEn: 'No: at the same quoted rate, the 360 basis pays about 1.4% more interest in relative terms. 3% Act/360 ≈ 3.04% on a 365 basis. Reflex: always ask for the day count.',
  },
  {
    id: 'm4-fc-07',
    moduleId: M4,
    tags: ['piege', 'conventions'],
    recto: 'Placement du 15 février au 17 mai (91 jours réels) compté en 30/360 : combien de jours retenus ?',
    verso: '92 jours : chaque mois est forfaitisé à 30 jours, février « compte » donc 30. Les jours comptés ne sont pas les jours réels — le piège classique des bases.',
    rectoEn: 'Deposit from 15 February to 17 May (91 actual days) counted under 30/360: how many days?',
    versoEn: '92 days: every month is standardized to 30 days, so February "counts" 30. Counted days are not actual days — the classic day-count trap.',
  },
  {
    id: 'm4-fc-08',
    moduleId: M4,
    tags: ['definition', 'marche-monetaire'],
    recto: 'L\'€STR, c\'est quoi ?',
    verso: 'Taux au jour le jour de la zone euro, calculé chaque jour par la BCE sur les transactions réelles d\'emprunt en blanc des banques. La référence « sans risque » overnight en euro.',
    rectoEn: 'What is €STR?',
    versoEn: 'The euro-area overnight rate, computed daily by the ECB from banks\' actual unsecured borrowing transactions. The euro overnight risk-free benchmark.',
  },
  {
    id: 'm4-fc-09',
    moduleId: M4,
    tags: ['definition', 'marche-monetaire'],
    recto: 'L\'Euribor, c\'est quoi, et en quoi diffère-t-il de l\'€STR ?',
    verso: 'Taux interbancaire offert en euro (1 semaine à 12 mois), issu des contributions d\'un panel de banques. Taux à terme avec risque de crédit — l\'€STR est overnight, sur transactions réelles.',
    rectoEn: 'What is Euribor, and how does it differ from €STR?',
    versoEn: 'The euro interbank offered rate (1 week to 12 months), built from a panel of banks\' contributions. A term rate carrying credit risk — €STR is overnight and transaction-based.',
  },
  {
    id: 'm4-fc-10',
    moduleId: M4,
    tags: ['definition', 'marche-monetaire'],
    recto: 'Un BTF, c\'est quoi ?',
    verso: 'Bon du Trésor français à taux fixe < 1 an, zéro-coupon, émis chaque semaine par adjudication (base Exact/360). L\'équivalent du T-bill américain.',
    rectoEn: 'What is a BTF?',
    versoEn: 'A French Treasury bill: fixed-rate paper under 1 year, zero-coupon, auctioned weekly (Act/360 basis). The French equivalent of a US T-bill.',
  },
  {
    id: 'm4-fc-11',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'marche-monetaire'],
    recto: 'Niveau de l\'€STR début 2026 ?',
    verso: 'Environ 2 % : le prix de l\'argent au jour le jour en zone euro, calé sur les taux directeurs de la BCE.',
    rectoEn: 'Level of €STR in early 2026?',
    versoEn: 'Around 2%: the price of overnight money in the euro area, anchored to the ECB\'s policy rates.',
  },
  {
    id: 'm4-fc-12',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'marche-monetaire'],
    recto: 'Niveau de l\'Euribor 3 mois début 2026 ?',
    verso: 'Environ 2 à 2,5 % — légèrement au-dessus de l\'€STR (~2 %) : l\'écart rémunère le terme et le risque de crédit interbancaire, et sert de baromètre de confiance (envolé en 2008).',
    rectoEn: 'Level of 3-month Euribor in early 2026?',
    versoEn: 'About 2 to 2.5% — slightly above €STR (~2%): the gap pays for term and interbank credit risk, and doubles as a confidence barometer (it blew out in 2008).',
  },

  // ───────────────────────── Chapitre 2 — L'obligation ─────────────────────────
  {
    id: 'm4-fc-13',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Une obligation, c\'est quoi ?',
    verso: 'Titre de créance négociable : l\'émetteur emprunte un nominal, verse un coupon périodique et rembourse à maturité. Contrairement à un prêt bancaire, le titre s\'échange librement sur un marché.',
    rectoEn: 'What is a bond?',
    versoEn: 'A tradable debt security: the issuer borrows a face value, pays a periodic coupon and repays at maturity. Unlike a bank loan, the security trades freely in a market.',
  },
  {
    id: 'm4-fc-14',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Un zéro-coupon, c\'est quoi, et ses deux propriétés remarquables ?',
    verso: 'Obligation à flux unique (le nominal à l\'échéance), vendue sous le pair. Seul titre dont le rendement est verrouillé à l\'achat et dont la duration égale exactement la maturité.',
    rectoEn: 'What is a zero-coupon bond, and its two remarkable properties?',
    versoEn: 'A single-cash-flow bond (face value at maturity), sold below par. The only bond whose return is locked in at purchase and whose duration exactly equals its maturity.',
  },
  {
    id: 'm4-fc-15',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Une obligation à taux variable (FRN), c\'est quoi ?',
    verso: 'Titre dont le coupon est réindexé à chaque fixing sur un taux monétaire (ex. Euribor 3M + 0,60 %). Son prix reste proche du pair tant que la qualité de crédit de l\'émetteur est stable.',
    rectoEn: 'What is a floating rate note (FRN)?',
    versoEn: 'A bond whose coupon resets at each fixing off a money-market rate (e.g. 3-month Euribor + 0.60%). Its price stays near par as long as the issuer\'s credit quality is stable.',
  },
  {
    id: 'm4-fc-16',
    moduleId: M4,
    tags: ['definition', 'obligation'],
    recto: 'Une OATi, c\'est quoi ?',
    verso: 'OAT indexée sur l\'inflation française hors tabac : nominal multiplié par un coefficient d\'indexation, coupon = taux réel fixe appliqué à ce nominal indexé. L\'OAT€i suit l\'inflation zone euro.',
    rectoEn: 'What is an OATi?',
    versoEn: 'A French government bond indexed to French ex-tobacco inflation: the principal is scaled by an index ratio and the coupon — a fixed real rate — applies to that indexed principal. The OAT€i tracks euro-area inflation.',
  },
  {
    id: 'm4-fc-17',
    moduleId: M4,
    tags: ['definition', 'dette'],
    recto: 'Une OAT, c\'est quoi ?',
    verso: 'Obligation assimilable du Trésor : dette à moyen-long terme de l\'État français, émise par adjudication mensuelle par l\'AFT. La souche 10 ans la plus récente est la référence du marché français.',
    rectoEn: 'What is an OAT?',
    versoEn: 'The French government\'s medium- to long-term bond, auctioned monthly by Agence France Trésor. The most recent 10-year line is the French market benchmark.',
  },
  {
    id: 'm4-fc-18',
    moduleId: M4,
    tags: ['definition', 'primaire'],
    recto: 'Comment fonctionne une adjudication « à prix multiples » ?',
    verso: 'Les ordres des SVT sont servis du prix le plus élevé au plus bas jusqu\'au montant visé, et chaque ordre servi paie le prix qu\'il a demandé. Format AFT : BTF chaque semaine, OAT chaque mois.',
    rectoEn: 'How does a multiple-price auction work?',
    versoEn: 'Primary dealers\' bids are filled from the highest price down to the target amount, and each filled bid pays its own price. The AFT format: weekly BTF, monthly OAT auctions.',
  },
  {
    id: 'm4-fc-19',
    moduleId: M4,
    tags: ['definition', 'primaire'],
    recto: 'La syndication, c\'est quoi ?',
    verso: 'Émission via un syndicat de banques qui sonde les investisseurs, construit le livre d\'ordres, cale le prix et alloue les titres. Voie normale des entreprises — et des États pour les souches nouvelles ou très longues.',
    rectoEn: 'What is a syndicated issue?',
    versoEn: 'An issue placed by a bank syndicate that sounds out investors, builds the order book, sets the price and allocates the bonds. The standard route for corporates — and for sovereigns on new or very long lines.',
  },
  {
    id: 'm4-fc-20',
    moduleId: M4,
    tags: ['definition', 'primaire'],
    recto: 'Un SVT, c\'est quoi ?',
    verso: 'Spécialiste en valeurs du Trésor (primary dealer) : banque agréée par l\'AFT — elles sont une quinzaine — qui s\'engage à soumissionner aux adjudications et à coter la dette française en continu au secondaire.',
    rectoEn: 'What is an SVT?',
    versoEn: 'A French primary dealer: a bank approved by the AFT — about fifteen of them — committed to bidding at auctions and quoting French debt continuously in the secondary market.',
  },
  {
    id: 'm4-fc-21',
    moduleId: M4,
    tags: ['piege', 'obligation'],
    recto: 'Les taux montent brutalement de 1 point : que fait le prix d\'un FRN ?',
    verso: 'Il reste proche du pair : le coupon se recale sur l\'Euribor au prochain fixing — la hausse passe dans les coupons futurs, pas dans le prix. Il ne décroche que si la marge de crédit exigée change.',
    rectoEn: 'Rates jump 1 point: what happens to an FRN\'s price?',
    versoEn: 'It stays near par: the coupon resets to Euribor at the next fixing — the rise flows into future coupons, not the price. It only drifts from par if the required credit margin changes.',
  },
  {
    id: 'm4-fc-22',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'marche'],
    recto: 'Taille du marché obligataire mondial ?',
    verso: '≈ 140 000 Md USD d\'encours — du même ordre que la capitalisation boursière mondiale des actions. C\'est sur les courbes souveraines que se pricent quasiment tous les autres actifs.',
    rectoEn: 'Size of the global bond market?',
    versoEn: 'About $140 trillion outstanding — on a par with global equity market capitalization. Nearly every other asset is priced off sovereign yield curves.',
  },

  // ───────────────────────── Chapitre 3 — Pricer une obligation ─────────────────────────
  {
    id: 'm4-fc-23',
    moduleId: M4,
    tags: ['formule', 'pricing'],
    recto: 'Formule du prix d\'une obligation à taux fixe ?',
    verso: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+r)^t}$ : somme des flux actualisés au taux exigé. Ex. : 1 000 €, coupon 5 %, 3 ans, taux 4 % → 1 027,75 €.',
    rectoEn: 'Price formula for a fixed-rate bond?',
    versoEn: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+r)^t}$: the sum of cash flows discounted at the required rate. E.g.: €1,000 face, 5% coupon, 3 years, 4% market rate → €1,027.75.',
  },
  {
    id: 'm4-fc-24',
    moduleId: M4,
    tags: ['formule', 'pricing'],
    recto: 'Formule du prix d\'un zéro-coupon ?',
    verso: '$P = \\frac{N}{(1+r)^n}$ : le nominal actualisé depuis l\'échéance. Ex. : 1 000 € dans 10 ans à 4 % → 675,56 €.',
    rectoEn: 'Price formula for a zero-coupon bond?',
    versoEn: '$P = \\frac{N}{(1+r)^n}$: the face value discounted from maturity. E.g.: €1,000 due in 10 years at 4% → €675.56.',
  },
  {
    id: 'm4-fc-25',
    moduleId: M4,
    tags: ['formule', 'pricing'],
    recto: 'Formule du coupon couru ?',
    verso: '$\\text{couru} = C \\times \\frac{\\text{jours courus}}{\\text{jours de la période}}$ (Exact/Exact pour les OAT). Ex. : coupon 30 €, 146 jours sur 365 → 12,00 €.',
    rectoEn: 'Accrued interest formula?',
    versoEn: '$\\text{accrued} = C \\times \\frac{\\text{days accrued}}{\\text{days in period}}$ (Act/Act for OATs). E.g.: €30 coupon, 146 of 365 days → €12.00.',
  },
  {
    id: 'm4-fc-26',
    moduleId: M4,
    tags: ['definition', 'pricing'],
    recto: 'Prix propre vs prix sale ?',
    verso: 'Propre (clean) : prix coté sur les écrans, hors couru. Sale (dirty) : montant réglé = propre + coupon couru. On cote propre pour neutraliser les dents de scie calendaires du couru.',
    rectoEn: 'Clean price versus dirty price?',
    versoEn: 'Clean: the quoted screen price, excluding accrued interest. Dirty: the amount settled = clean + accrued. Quoting clean strips out the calendar sawtooth of accruals.',
  },
  {
    id: 'm4-fc-27',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Une OAT cote 98,45 %. Est-ce le montant que règle l\'acheteur ?',
    verso: 'Non : le prix coté est un prix propre. On règle prix propre + coupon couru. Ex. : 984,50 € + 12,00 € de couru = 996,50 €. Le couru s\'ajoute, jamais ne se déduit.',
    rectoEn: 'An OAT quotes 98.45%. Is that what the buyer pays?',
    versoEn: 'No: the quoted price is a clean price. You settle clean price + accrued interest. E.g.: €984.50 + €12.00 accrued = €996.50. Accrued is added, never deducted.',
  },
  {
    id: 'm4-fc-28',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Le prix sale chute du montant du coupon au lendemain du détachement. Mauvais signe ?',
    verso: 'Non, pure mécanique : le couru retombe à zéro une fois le coupon versé ; le prix propre n\'a presque pas bougé. C\'est pour neutraliser ces dents de scie que le marché cote en prix propre.',
    rectoEn: 'The dirty price drops by the coupon amount the day after payment. Bad news?',
    versoEn: 'No — pure mechanics: accrued interest resets to zero once the coupon is paid; the clean price has barely moved. That sawtooth is exactly why the market quotes clean prices.',
  },
  {
    id: 'm4-fc-29',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Pourquoi le prix d\'une obligation baisse-t-il quand les taux montent ? Les deux réponses attendues ?',
    verso: 'Mécanique : flux contractuels fixes actualisés à un taux plus élevé → somme plus faible. Marché : les émissions neuves servent plus, l\'ancien titre doit décoter pour rester compétitif.',
    rectoEn: 'Why does a bond\'s price fall when rates rise? The two expected answers?',
    versoEn: 'Mechanical: fixed contractual cash flows discounted at a higher rate → a smaller sum. Market: new issues pay more, so the old bond must trade at a discount to stay competitive.',
  },
  {
    id: 'm4-fc-30',
    moduleId: M4,
    tags: ['piege', 'pricing'],
    recto: 'Coupon 2 %, taux de marché 4 % : où est le prix ? Et la règle générale ?',
    verso: 'Sous le pair (décote). Coupon > taux → surcote ; égal → pair ; inférieur → décote. La décote n\'est pas une punition : c\'est le mécanisme qui égalise les rendements entre l\'ancien et le neuf.',
    rectoEn: '2% coupon, 4% market rate: where is the price? And the general rule?',
    versoEn: 'Below par (discount). Coupon > market rate → premium; equal → par; lower → discount. The discount is no punishment: it is the mechanism that equalizes returns between old and new bonds.',
  },

  // ───────────────────────── Chapitre 4 — Le rendement ─────────────────────────
  {
    id: 'm4-fc-31',
    moduleId: M4,
    tags: ['formule', 'rendement'],
    recto: 'Formule du rendement courant ?',
    verso: '$r_{\\text{courant}} = \\frac{C}{P}$. Ex. : coupon 50 €, prix 1 027,75 € → 4,86 %. Ordre de grandeur du loyer annuel — ignore remboursement et calendrier.',
    rectoEn: 'Current yield formula?',
    versoEn: '$r_{\\text{current}} = \\frac{C}{P}$. E.g.: €50 coupon, €1,027.75 price → 4.86%. A quick gauge of annual income — ignores redemption and timing.',
  },
  {
    id: 'm4-fc-32',
    moduleId: M4,
    tags: ['formule', 'rendement'],
    recto: 'Équation de définition du rendement actuariel (YTM) ?',
    verso: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+y)^t}$ : y égalise prix observé et flux actualisés. Pas de formule fermée — essais encadrants. Ex. : 2 ans, coupon 4 %, P = 990 € → y ≈ 4,53 %.',
    rectoEn: 'Defining equation of yield to maturity (YTM)?',
    versoEn: '$P = \\sum_{t=1}^{n} \\frac{F_t}{(1+y)^t}$: y equates the observed price and the discounted flows. No closed form — solved by bracketing trials. E.g.: 2 years, 4% coupon, P = €990 → y ≈ 4.53%.',
  },
  {
    id: 'm4-fc-33',
    moduleId: M4,
    tags: ['definition', 'rendement'],
    recto: 'Le rendement actuariel (YTM), c\'est quoi ?',
    verso: 'Le taux unique qui égalise prix observé et flux actualisés : le TRI de l\'investissement obligataire. Rendement promis sous conditions (détention à maturité, réinvestissement à y), pas garanti.',
    rectoEn: 'What is yield to maturity (YTM)?',
    versoEn: 'The single rate that equates the observed price with the discounted cash flows: the IRR of the bond investment. A promised return under conditions (hold to maturity, reinvest at y), not a guaranteed one.',
  },
  {
    id: 'm4-fc-34',
    moduleId: M4,
    tags: ['definition', 'rendement'],
    recto: 'Le rendement courant, c\'est quoi, et que rate-t-il ?',
    verso: 'Coupon annuel rapporté au prix payé : le loyer instantané du titre. Il ignore le remboursement (gain ou perte en capital certain) et le calendrier des flux — myope en surcote comme en décote.',
    rectoEn: 'What is current yield, and what does it miss?',
    versoEn: 'The annual coupon over the price paid: the bond\'s instant income measure. It ignores redemption (the certain capital gain or loss) and cash-flow timing — misleading on premium and discount bonds alike.',
  },
  {
    id: 'm4-fc-35',
    moduleId: M4,
    tags: ['piege', 'rendement'],
    recto: 'Titre en surcote : classer YTM, rendement courant et taux de coupon.',
    verso: 'YTM < rendement courant < taux de coupon. Ex. fil rouge : 4 % < 4,86 % < 5 %. L\'ordre s\'inverse en décote. Le rendement courant ne voit pas la perte en capital.',
    rectoEn: 'Premium bond: rank YTM, current yield and coupon rate.',
    versoEn: 'YTM < current yield < coupon rate. Running example: 4% < 4.86% < 5%. The order flips for a discount bond. Current yield is blind to the capital loss.',
  },
  {
    id: 'm4-fc-36',
    moduleId: M4,
    tags: ['piege', 'rendement'],
    recto: 'J\'achète à un YTM de 4 % et je garde jusqu\'au bout : mon rendement réalisé est-il garanti à 4 % ?',
    verso: 'Non : la détention fige les flux, pas leur réinvestissement. Si les taux baissent, les coupons se replacent moins bien → rendement réalisé < 4 %. Seul le zéro-coupon verrouille son rendement.',
    rectoEn: 'I buy at a 4% YTM and hold to maturity: is my realized return locked at 4%?',
    versoEn: 'No: holding fixes the cash flows, not their reinvestment. If rates fall, coupons reinvest at lower rates → realized return below 4%. Only a zero-coupon locks in its return at purchase.',
  },
  {
    id: 'm4-fc-37',
    moduleId: M4,
    tags: ['piege', 'rendement'],
    recto: '« L\'OAT 10 ans est passée de 3,2 % à 3,5 %. » Que s\'est-il passé concrètement ?',
    verso: 'Les souverains se cotent en taux : le YTM de la souche de référence a monté, donc son prix a baissé. « Les taux montent » et « les prix obligataires baissent » sont la même phrase.',
    rectoEn: '"The 10-year OAT moved from 3.2% to 3.5%." What actually happened?',
    versoEn: 'Sovereigns are quoted in yield: the benchmark\'s YTM rose, so its price fell. "Yields up" and "bond prices down" are the same sentence in two different units.',
  },
  {
    id: 'm4-fc-38',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'rendement'],
    recto: 'Niveau du taux OAT 10 ans début 2026 ?',
    verso: 'Environ 3 à 3,5 % — contre ~2 % pour l\'argent au jour le jour (€STR) : l\'écart rémunère le temps long (prime de terme, incertitude sur l\'inflation et les taux futurs).',
    rectoEn: 'Level of the 10-year OAT yield in early 2026?',
    versoEn: 'About 3 to 3.5% — versus ~2% for overnight money (€STR): the gap pays for the long horizon (term premium, uncertainty on inflation and future rates).',
  },

  // ───────────────────────── Chapitre 5 — La courbe des taux ─────────────────────────
  {
    id: 'm4-fc-39',
    moduleId: M4,
    tags: ['formule', 'courbe'],
    recto: 'Formule du bootstrap du taux zéro-coupon 2 ans ?',
    verso: '$(1+z_2)^2 = \\frac{C+N}{P - \\frac{C}{1+z_1}}$ : on retire du prix le coupon de l\'an 1 actualisé à z₁, le flux final donne z₂. Ex. du cours : z₂ = 3,01 % pour un YTM de 3,00 %.',
    rectoEn: 'Bootstrap formula for the 2-year zero-coupon rate?',
    versoEn: '$(1+z_2)^2 = \\frac{C+N}{P - \\frac{C}{1+z_1}}$: strip the year-1 coupon discounted at z₁ from the price; the final flow yields z₂. Course example: z₂ = 3.01% versus a 3.00% YTM.',
  },
  {
    id: 'm4-fc-40',
    moduleId: M4,
    tags: ['formule', 'courbe'],
    recto: 'Formule du taux forward implicite f₁,₂ ?',
    verso: '$(1+z_2)^2 = (1+z_1)(1+f_{1,2})$ — imposée par l\'absence d\'arbitrage. Ex. : z₁ = 2 %, z₂ = 3 % → f₁,₂ = 1,03²/1,02 − 1 ≈ 4,01 %.',
    rectoEn: 'Implied forward rate formula f₁,₂?',
    versoEn: '$(1+z_2)^2 = (1+z_1)(1+f_{1,2})$ — imposed by no-arbitrage. E.g.: z₁ = 2%, z₂ = 3% → f₁,₂ = 1.03²/1.02 − 1 ≈ 4.01%.',
  },
  {
    id: 'm4-fc-41',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'La courbe des taux, c\'est quoi ?',
    verso: 'Les rendements actuariels d\'un même émetteur classés par maturité, à un instant donné. La courbe souveraine de chaque devise est l\'étalon de pricing de tous les autres actifs.',
    rectoEn: 'What is the yield curve?',
    versoEn: 'One issuer\'s yields to maturity arranged by maturity at a point in time. Each currency\'s sovereign curve is the pricing benchmark for every other asset.',
  },
  {
    id: 'm4-fc-42',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Une courbe des taux inversée, c\'est quoi et qu\'annonce-t-elle ?',
    verso: 'Taux courts > taux longs : le marché anticipe des baisses de taux directeurs, scénario de ralentissement. Signal historiquement sérieux (1980, 1990, 2001, 2008), pas un oracle (2022-2024).',
    rectoEn: 'What is an inverted yield curve and what does it signal?',
    versoEn: 'Short rates above long rates: the market prices in policy-rate cuts, the typical slowdown scenario. A historically serious signal (1980, 1990, 2001, 2008), not an oracle (2022-2024).',
  },
  {
    id: 'm4-fc-43',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Le bootstrapping, c\'est quoi et pourquoi en a-t-on besoin ?',
    verso: 'Extraction de proche en proche des taux zéro-coupon depuis les prix d\'obligations couponnées (z₁ → z₂ → z₃…). Nécessaire car le YTM d\'un titre couponné est une moyenne déformée par l\'effet coupon.',
    rectoEn: 'What is bootstrapping and why is it needed?',
    versoEn: 'The step-by-step extraction of zero-coupon rates from coupon-bond prices (z₁ → z₂ → z₃…). Needed because a coupon bond\'s YTM is an average distorted by the coupon effect.',
  },
  {
    id: 'm4-fc-44',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Un taux forward, c\'est quoi ?',
    verso: 'Le taux à terme implicite de la courbe : celui qui rend équivalents placer long d\'un bloc et rouler du court. Un fait arithmétique d\'absence d\'arbitrage — pas une prévision.',
    rectoEn: 'What is a forward rate?',
    versoEn: 'The term rate implied by the curve: the rate that makes one long placement equivalent to rolling shorter ones. An arithmetic no-arbitrage fact — not a forecast.',
  },
  {
    id: 'm4-fc-45',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Le 2s10s, c\'est quoi ?',
    verso: 'Le spread de courbe le plus suivi : taux 10 ans moins taux 2 ans, en points de base. Il s\'élargit (pentification) ou se resserre (aplatissement) ; négatif = courbe inversée.',
    rectoEn: 'What is the 2s10s?',
    versoEn: 'The most watched curve spread: the 10-year minus the 2-year yield, in basis points. It widens (steepening) or narrows (flattening); negative = inverted curve.',
  },
  {
    id: 'm4-fc-46',
    moduleId: M4,
    tags: ['definition', 'courbe'],
    recto: 'Vocabulaire bull/bear appliqué aux mouvements de courbe ?',
    verso: 'Bull = les taux baissent (prix montent), bear = les taux montent. Combiné à steepening/flattening : ex. bear flattening = les taux courts montent plus vite que les longs — type resserrement 2022-2023.',
    rectoEn: 'Bull/bear vocabulary applied to curve moves?',
    versoEn: 'Bull = yields fall (prices rise), bear = yields rise. Combined with steepening/flattening: e.g. bear flattening = short rates rise faster than long ones — the 2022-2023 tightening pattern.',
  },
  {
    id: 'm4-fc-47',
    moduleId: M4,
    tags: ['piege', 'courbe'],
    recto: 'z₁ = 2 %, z₂ = 3 % → forward 1 an dans 1 an ≈ 4,01 %. Le marché « prévoit »-il 4,01 % ?',
    verso: 'Non : 4,01 % est le taux d\'indifférence entre placer 2 ans d\'un bloc et rouler du 1 an. La prime de terme se loge dans le forward, qui surestime historiquement les taux réalisés.',
    rectoEn: 'z₁ = 2%, z₂ = 3% → 1-year forward, 1 year ahead ≈ 4.01%. Does the market "forecast" 4.01%?',
    versoEn: 'No: 4.01% is the indifference rate between a 2-year block and rolling 1-year placements. The term premium sits inside the forward, which has historically overshot realized rates.',
  },
  {
    id: 'm4-fc-48',
    moduleId: M4,
    tags: ['piege', 'courbe'],
    recto: 'Deux obligations, même signature, même maturité, coupons différents : même YTM ?',
    verso: 'Non sur une courbe pentue : c\'est l\'effet coupon — le gros coupon pèse plus sur les taux courts. Ex. du cours : titre 2 ans au pair, YTM 3,00 %, mais z₂ = 3,01 %. D\'où le bootstrap.',
    rectoEn: 'Two bonds, same issuer, same maturity, different coupons: same YTM?',
    versoEn: 'Not on a sloped curve: that is the coupon effect — the high coupon weights short rates more. Course example: 2-year bond at par, YTM 3.00%, but z₂ = 3.01%. Hence bootstrapping.',
  },

  // ───────────────────────── Chapitre 6 — Duration & convexité ─────────────────────────
  {
    id: 'm4-fc-49',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule de la duration de Macaulay ?',
    verso: '$D_{Mac} = \\frac{\\sum_t t \\cdot VA(F_t)}{P}$ — barycentre temporel des flux actualisés, en années. Ex. : 1 000 €, coupon 5 %, 3 ans, taux 4 % → 2,86 ans.',
    rectoEn: 'Macaulay duration formula?',
    versoEn: '$D_{Mac} = \\frac{\\sum_t t \\cdot PV(F_t)}{P}$ — the time barycentre of discounted cash flows, in years. E.g.: €1,000, 5% coupon, 3 years, 4% rate → 2.86 years.',
  },
  {
    id: 'm4-fc-50',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule de la duration modifiée ?',
    verso: '$D_{mod} = \\frac{D_{Mac}}{1+y}$ — sans unité. Ex. : 2,8615/1,04 = 2,75 : une hausse de 1 point du taux coûte ≈ 2,75 % du prix.',
    rectoEn: 'Modified duration formula?',
    versoEn: '$D_{mod} = \\frac{D_{Mac}}{1+y}$ — unitless. E.g.: 2.8615/1.04 = 2.75: a 1-point rise in yield costs about 2.75% of the price.',
  },
  {
    id: 'm4-fc-51',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule de la variation de prix par la duration ?',
    verso: '$\\Delta P \\approx -D_{mod} \\times \\Delta y \\times P$. Ex. : $D_{mod}$ 5, +100 pb, 1 000 € → −50 €.',
    rectoEn: 'Duration approximation of the price change?',
    versoEn: '$\\Delta P \\approx -D_{mod} \\times \\Delta y \\times P$. E.g.: $D_{mod}$ 5, +100bp, €1,000 → −€50.',
  },
  {
    id: 'm4-fc-52',
    moduleId: M4,
    tags: ['formule', 'convexite'],
    recto: 'Formule de la variation de prix avec correction de convexité ?',
    verso: '$\\frac{\\Delta P}{P} \\approx -D_{mod}\\,\\Delta y + \\frac{1}{2}\\,C\\,(\\Delta y)^2$. Le terme en (Δy)², positif dans les deux sens, corrige la tangente pour les chocs larges.',
    rectoEn: 'Price change formula with the convexity correction?',
    versoEn: '$\\frac{\\Delta P}{P} \\approx -D_{mod}\\,\\Delta y + \\frac{1}{2}\\,C\\,(\\Delta y)^2$. The (Δy)² term, positive in both directions, fixes the tangent error for large shocks.',
  },
  {
    id: 'm4-fc-53',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Formule du DV01 ?',
    verso: '$DV01 = D_{mod} \\times P \\times 0{,}0001$ — en euros par point de base. Ex. : D_mod 2,75, position 1 027,75 € → 0,28 €/pb.',
    rectoEn: 'DV01 formula?',
    versoEn: '$DV01 = D_{mod} \\times P \\times 0.0001$ — in euros per basis point. E.g.: D_mod 2.75, €1,027.75 position → €0.28 per bp.',
  },
  {
    id: 'm4-fc-54',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Duration d\'un portefeuille obligataire ?',
    verso: '$D_{ptf} = \\sum_i w_i \\, D_i$ : moyenne des durations pondérée par les poids en valeur de marché. Ex. : 60 % à 2,5 + 40 % à 7 → 4,3.',
    rectoEn: 'Duration of a bond portfolio?',
    versoEn: '$D_{ptf} = \\sum_i w_i \\, D_i$: the market-value-weighted average of the holdings\' durations. E.g.: 60% at 2.5 + 40% at 7 → 4.3.',
  },
  {
    id: 'm4-fc-55',
    moduleId: M4,
    tags: ['formule', 'couverture'],
    recto: 'Nombre de contrats pour couvrir un portefeuille en DV01 ?',
    verso: '$n = \\frac{DV01_{\\text{portefeuille}}}{DV01_{\\text{contrat}}}$. Ex. : 4 000 €/pb à couvrir, contrat à 80 €/pb → vendre 50 contrats. Position insensible au premier ordre.',
    rectoEn: 'Number of futures contracts to hedge a portfolio in DV01 terms?',
    versoEn: '$n = \\frac{DV01_{\\text{portfolio}}}{DV01_{\\text{futures}}}$. E.g.: €4,000/bp to hedge, €80/bp per contract → sell 50 contracts. First-order rate-neutral position.',
  },
  {
    id: 'm4-fc-56',
    moduleId: M4,
    tags: ['formule', 'duration'],
    recto: 'Prix et duration d\'une perpétuité ?',
    verso: '$P = \\frac{c}{y}$ et $D_{Mac} = \\frac{1+y}{y}$. À 4 % : duration de 26 ans — maturité infinie, duration finie.',
    rectoEn: 'Price and duration of a perpetuity?',
    versoEn: '$P = \\frac{c}{y}$ and $D_{Mac} = \\frac{1+y}{y}$. At 4%: a 26-year duration — infinite maturity, finite duration.',
  },
  {
    id: 'm4-fc-57',
    moduleId: M4,
    tags: ['definition', 'duration'],
    recto: 'La duration de Macaulay, c\'est quoi ?',
    verso: 'La moyenne des dates des flux pondérée par leur poids actualisé dans le prix : le barycentre temporel, en années. Celle d\'un zéro-coupon égale exactement sa maturité.',
    rectoEn: 'What is Macaulay duration?',
    versoEn: 'The average of the cash-flow dates weighted by each flow\'s discounted share of the price: the time centre of gravity, in years. A zero-coupon\'s equals its maturity exactly.',
  },
  {
    id: 'm4-fc-58',
    moduleId: M4,
    tags: ['definition', 'duration'],
    recto: 'La duration modifiée, c\'est quoi ?',
    verso: 'Le facteur de sensibilité du prix au taux : D_Mac/(1+y), sans unité. D_mod = 6 → ≈ 6 % de perte pour +1 point de taux. Géométriquement : la pente de la tangente prix-taux.',
    rectoEn: 'What is modified duration?',
    versoEn: 'The price sensitivity factor to yield: D_Mac/(1+y), unitless. D_mod = 6 → about a 6% price loss for a 1-point rise. Geometrically: the slope of the price-yield tangent.',
  },
  {
    id: 'm4-fc-59',
    moduleId: M4,
    tags: ['definition', 'duration'],
    recto: 'Le DV01, c\'est quoi ?',
    verso: 'La variation en monnaie d\'une position pour 1 pb de taux : D_mod × valeur × 0,0001. L\'unité de risque quotidienne des desks — « si les taux prennent 1 pb, je perds combien ? »',
    rectoEn: 'What is DV01?',
    versoEn: 'The money change in a position for a 1bp move in yields: D_mod × market value × 0.0001. The desk\'s daily unit of risk — "rates up 1bp, how much do I lose?"',
  },
  {
    id: 'm4-fc-60',
    moduleId: M4,
    tags: ['definition', 'convexite'],
    recto: 'La convexité, c\'est quoi, et pourquoi est-ce une qualité ?',
    verso: 'La courbure de la relation prix-taux. Le terme ½C(Δy)² est positif dans les deux sens : il amortit les pertes en hausse et amplifie les gains en baisse. À duration égale, elle se paie.',
    rectoEn: 'What is convexity, and why is it a quality?',
    versoEn: 'The curvature of the price-yield relationship. The ½C(Δy)² term is positive either way: it cushions losses when rates rise and amplifies gains when they fall. At equal duration, it commands a price.',
  },
  {
    id: 'm4-fc-61',
    moduleId: M4,
    tags: ['definition', 'gestion'],
    recto: 'L\'immunisation d\'un portefeuille, c\'est quoi ?',
    verso: 'Égaliser duration de l\'actif et du passif (à valeurs actuelles égales) : effet prix et effet réinvestissement se compensent à l\'horizon de la duration. Le cœur de la gestion actif-passif.',
    rectoEn: 'What is portfolio immunization?',
    versoEn: 'Matching asset and liability durations (at equal present values): the price effect and the reinvestment effect offset at the duration horizon. The heart of asset-liability management.',
  },
  {
    id: 'm4-fc-62',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Coupon ↑ ⇒ duration ?',
    verso: 'Duration ↓ : les flux sont rapatriés plus tôt, le barycentre temporel se rapproche. Sur 3 ans à 4 % : 3,00 ans à coupon nul, 2,86 ans à 5 %, 2,79 ans à 8 %.',
    rectoEn: 'Coupon up ⇒ duration?',
    versoEn: 'Duration down: more value is paid back early, pulling the time barycentre toward the present. Over 3 years at 4%: 3.00 years at zero coupon, 2.86 at 5%, 2.79 at 8%.',
  },
  {
    id: 'm4-fc-63',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Même maturité 10 ans, même choc de +1 point : zéro-coupon et coupon 8 % perdent-ils autant ?',
    verso: 'Non : −9,13 % pour le zéro-coupon, −7,01 % pour le coupon 8 %. La maturité ne date que le dernier flux ; la sensibilité dépend du calendrier complet — c\'est la duration.',
    rectoEn: 'Same 10-year maturity, same +1-point shock: do a zero-coupon and an 8% coupon bond lose the same?',
    versoEn: 'No: −9.13% for the zero-coupon, −7.01% for the 8% coupon. Maturity only dates the last flow; sensitivity depends on the full cash-flow schedule — that is duration.',
  },
  {
    id: 'm4-fc-64',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: '« La duration de ce portefeuille est de 7. » — 7 quoi ? Les trois unités à ne pas confondre ?',
    verso: 'Macaulay en années ; modifiée sans unité (% de prix par point de taux) ; DV01 en euros par pb. Toujours nommer l\'unité — le lapsus trahit la récitation.',
    rectoEn: '"This portfolio\'s duration is 7." — 7 what? The three units never to mix up?',
    versoEn: 'Macaulay in years; modified duration unitless (% of price per point of yield); DV01 in euros per bp. Always name the unit — the slip betrays rote learning.',
  },
  {
    id: 'm4-fc-65',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Dans ΔP ≈ −D_mod × Δy × P, comment entrer un choc de 50 pb ?',
    verso: 'En décimal : 50 pb = 0,005. Ex. : D_mod 6, P 1 000 € → −30 €. Erreur classique : prendre 0,5 ou 0,05 et se tromper d\'un facteur 10 ou 100.',
    rectoEn: 'In ΔP ≈ −D_mod × Δy × P, how do you enter a 50bp shock?',
    versoEn: 'As a decimal: 50bp = 0.005. E.g.: D_mod 6, P €1,000 → −€30. Classic error: using 0.5 or 0.05 and ending up off by a factor of 10 or 100.',
  },
  {
    id: 'm4-fc-66',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Deux portefeuilles de même DV01, l\'un concentré sur le 2 ans, l\'autre sur le 30 ans : même risque ?',
    verso: 'Non : la duration couvre un choc parallèle — le niveau, pas la pente. Un bear steepening les traite très différemment. D\'où durations partielles et stratégies de courbe.',
    rectoEn: 'Two portfolios with the same DV01, one in 2-year paper, the other in 30-year: same risk?',
    versoEn: 'No: duration covers a parallel shock — the level, not the slope. A bear steepening treats them very differently. Hence partial durations and curve strategies.',
  },
  {
    id: 'm4-fc-67',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'duration'],
    recto: 'Duration modifiée d\'une OAT 10 ans ?',
    verso: '≈ 8 à 8,5 : une hausse de 100 pb coûte environ 8 % du prix ; 1 pb ≈ 0,08 % de la valeur (DV01).',
    rectoEn: 'Modified duration of a 10-year OAT?',
    versoEn: 'About 8 to 8.5: a 100bp rise costs roughly 8% of the price; 1bp ≈ 0.08% of value (DV01).',
  },

  // ───────────────────────── Chapitre 7 — Le marché en pratique ─────────────────────────
  {
    id: 'm4-fc-68',
    moduleId: M4,
    tags: ['definition', 'repo'],
    recto: 'Le repo, c\'est quoi ?',
    verso: 'Pension livrée : vente de titres avec engagement de rachat à date et prix convenus — un prêt de cash garanti par titres. Finance les desks, permet la vente à découvert, transmet la politique monétaire.',
    rectoEn: 'What is a repo?',
    versoEn: 'A repurchase agreement: selling securities while committing to buy them back at an agreed date and price — a cash loan secured by securities. Funds desks, enables short selling, transmits monetary policy.',
  },
  {
    id: 'm4-fc-69',
    moduleId: M4,
    tags: ['definition', 'repo'],
    recto: 'Le haircut d\'un repo, c\'est quoi ?',
    verso: 'La décote sur la valeur du collatéral : avec 2 % de haircut, 10 M€ de titres ne lèvent que 9,8 M€ de cash. Protège le prêteur contre une baisse des titres pendant l\'opération.',
    rectoEn: 'What is a repo haircut?',
    versoEn: 'The discount applied to the collateral\'s value: with a 2% haircut, €10m of securities raises only €9.8m of cash. It protects the lender against a fall in the collateral during the trade.',
  },
  {
    id: 'm4-fc-70',
    moduleId: M4,
    tags: ['definition', 'repo'],
    recto: 'GC vs « spécial » au repo ?',
    verso: 'GC : n\'importe quel titre d\'un panier de qualité convient, le taux colle aux taux directeurs — le prix du cash. Spécial : un titre précis est recherché (vente à découvert), son taux repo passe sous le GC.',
    rectoEn: 'GC versus "special" in the repo market?',
    versoEn: 'GC: any security from a quality basket will do; the rate tracks policy rates — the price of cash. Special: a specific bond is in demand (short sellers), so its repo rate drops below GC.',
  },
  {
    id: 'm4-fc-71',
    moduleId: M4,
    tags: ['definition', 'spreads'],
    recto: 'Le spread OAT-Bund, c\'est quoi ?',
    verso: 'Écart de rendement actuariel entre OAT 10 ans et Bund 10 ans, en pb : la prime exigée pour prêter à la France plutôt qu\'à l\'Allemagne (budget, politique, liquidité). Des rendements, jamais des prix.',
    rectoEn: 'What is the OAT-Bund spread?',
    versoEn: 'The yield gap between the 10-year OAT and the 10-year Bund, in bp: the premium demanded to lend to France rather than Germany (fiscal, political, liquidity). Always yields, never prices.',
  },
  {
    id: 'm4-fc-72',
    moduleId: M4,
    tags: ['definition', 'marche'],
    recto: 'Le démembrement (stripping), c\'est quoi ?',
    verso: 'Séparer coupons et principal d\'une OAT en zéro-coupons négociables indépendamment (strips). Idéal pour adosser un engagement à date fixe : duration = maturité, exactement.',
    rectoEn: 'What is stripping?',
    versoEn: 'Splitting an OAT\'s coupons and principal into independently traded zero-coupons (strips). Ideal for matching a fixed-date liability: duration equals maturity, exactly.',
  },
  {
    id: 'm4-fc-73',
    moduleId: M4,
    tags: ['piege', 'spreads'],
    recto: 'L\'OAT-Bund s\'écarte de 75 à 90 pb. Peut-on conclure que le marché sanctionne la France ?',
    verso: 'Non : un spread a deux jambes. Si le Bund baisse (fuite vers la qualité), l\'écart se creuse sans que la France ait démérité. Réflexe : décomposer les deux jambes avant d\'interpréter.',
    rectoEn: 'The OAT-Bund widens from 75 to 90bp. Can you conclude the market is punishing France?',
    versoEn: 'No: a spread has two legs. If the Bund rallies (flight to quality), the gap widens with no French fault. Reflex: decompose both legs before interpreting.',
  },
  {
    id: 'm4-fc-74',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'dette'],
    recto: 'Dette publique française début 2026 ?',
    verso: '≈ 3 500 Md€, dont ≈ 2 800 Md€ de dette négociable de l\'État — l\'essentiel en OAT, le court terme en BTF.',
    rectoEn: 'French public debt in early 2026?',
    versoEn: 'About €3,500bn, of which about €2,800bn of negotiable central-government debt — mostly OATs, with BTFs covering the short end.',
  },
  {
    id: 'm4-fc-75',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'spreads'],
    recto: 'Niveau du spread OAT-Bund début 2026 ? Et avant 2022 ?',
    verso: '≈ 70-80 pb, contre 30-40 pb avant 2022 : changement de régime avec la remontée des taux et l\'instabilité politique française (pics > 80 pb en 2024-2025).',
    rectoEn: 'OAT-Bund spread in early 2026? And before 2022?',
    versoEn: 'About 70-80bp, versus 30-40bp before 2022: a regime change driven by rising rates and French political instability (peaks above 80bp in 2024-2025).',
  },
  {
    id: 'm4-fc-76',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'dette'],
    recto: 'Programme annuel d\'émissions à moyen-long terme de l\'AFT ?',
    verso: 'De l\'ordre de 300 Md€ ces dernières années, déroulé par adjudications régulières (BTF chaque semaine, OAT chaque mois). La prévisibilité fait emprunter moins cher.',
    rectoEn: 'AFT\'s annual medium- and long-term issuance program?',
    versoEn: 'On the order of €300bn in recent years, run through regular auctions (weekly BTFs, monthly OATs). Predictability lowers the cost of borrowing.',
  },
  {
    id: 'm4-fc-77',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'dette'],
    recto: 'Quelle part de la dette française est détenue par des non-résidents ?',
    verso: 'Environ la moitié — signe de confiance autant que source de vulnérabilité : ces porteurs comparent en permanence l\'OAT à ses concurrentes.',
    rectoEn: 'What share of French debt is held by non-residents?',
    versoEn: 'About half — a sign of confidence as much as a source of vulnerability: those holders constantly benchmark the OAT against its competitors.',
  },
  {
    id: 'm4-fc-78',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'spreads'],
    recto: 'Jusqu\'où est monté le BTP-Bund au pic de la crise de la zone euro (2011-2012) ?',
    verso: 'Au-delà de 500 pb — les marchés testaient la réversibilité de l\'euro. Il a fallu le « whatever it takes » de Draghi (juillet 2012) pour casser la spirale.',
    rectoEn: 'How wide did the BTP-Bund spread get at the peak of the euro crisis (2011-2012)?',
    versoEn: 'Beyond 500bp — markets were openly testing the euro\'s reversibility. It took Draghi\'s "whatever it takes" (July 2012) to break the spiral.',
  },
  {
    id: 'm4-fc-79',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'credit'],
    recto: 'Spread de crédit typique d\'un émetteur investment grade ?',
    verso: '≈ 80 à 150 pb au-dessus du souverain de même maturité (IG : AAA à BBB−). Très variable selon le cycle : compression en période calme, explosion en crise.',
    rectoEn: 'Typical credit spread for an investment-grade issuer?',
    versoEn: 'About 80 to 150bp over the same-maturity sovereign (IG: AAA to BBB−). Highly cycle-dependent: compressed in calm markets, exploding in crises.',
  },
  {
    id: 'm4-fc-80',
    moduleId: M4,
    tags: ['ordre-de-grandeur', 'credit'],
    recto: 'Spread de crédit typique d\'un émetteur high yield ?',
    verso: '≈ 300 à 500 pb au-dessus du souverain (notes sous BBB−). L\'écart avec l\'IG rémunère une probabilité de défaut nettement plus élevée — mécanique détaillée au module 5.',
    rectoEn: 'Typical credit spread for a high-yield issuer?',
    versoEn: 'About 300 to 500bp over the sovereign (ratings below BBB−). The gap versus IG pays for a much higher default probability — mechanics covered in module 5.',
  },

  // ───────────────────────── Cartes 81-100 — Réflexes jury ─────────────────────────
  {
    id: 'm4-fc-81',
    moduleId: M4,
    tags: ['reflexe-jury', 'pricing'],
    recto: 'Le jury : « Pourquoi votre obligation perd-elle de la valeur quand les taux montent ? »',
    verso: 'Réflexe : flux fixes, le prix est la seule variable d\'ajustement — donner les deux lectures : actualisation au dénominateur + concurrence des émissions neuves. Flash : coupon 5 %, 3 ans → 1 027,75 € à 4 %, 1 000 € à 5 %.',
    rectoEn: 'The panel: "Why does your bond lose value when rates rise?"',
    versoEn: 'Reflex: cash flows are fixed, the price is the only adjusting variable — give both readings: discounting in the denominator + competition from new issues. Flash: 5% coupon, 3 years → €1,027.75 at 4%, €1,000 at 5%.',
  },
  {
    id: 'm4-fc-82',
    moduleId: M4,
    tags: ['reflexe-jury', 'duration'],
    recto: 'Le jury : « Votre fonds a une duration de 8, les taux montent de 50 pb — combien perdez-vous ? »',
    verso: 'Réflexe : répondre en une seconde, sans brouillon : ΔP/P ≈ −D × Δy. Flash : −8 × 0,5 % = −4 % ; sur 100 M€, −4 M€. Toute hésitation ici coûte plus cher que la perte.',
    rectoEn: 'The panel: "Your fund runs a duration of 8, rates rise 50bp — how much do you lose?"',
    versoEn: 'Reflex: answer in one second, no scratch paper: ΔP/P ≈ −D × Δy. Flash: −8 × 0.5% = −4%; on €100m, −€4m. Hesitating here costs more than the loss itself.',
  },
  {
    id: 'm4-fc-83',
    moduleId: M4,
    tags: ['reflexe-jury', 'courbe'],
    recto: 'Le jury : « La courbe s\'inverse demain matin. Votre lecture en une phrase ? »',
    verso: 'Réflexe : le marché price des baisses de taux directeurs — scénario de ralentissement. Ajouter la nuance qui paie : signal sérieux (1980, 1990, 2001, 2008), pas un oracle — deux ans d\'inversion 2022-2024 sans récession.',
    rectoEn: 'The panel: "The curve inverts tomorrow morning. Your one-sentence read?"',
    versoEn: 'Reflex: the market is pricing policy-rate cuts — a slowdown scenario. Add the nuance that scores: a serious signal (1980, 1990, 2001, 2008), not an oracle — two years inverted in 2022-2024 with no recession.',
  },
  {
    id: 'm4-fc-84',
    moduleId: M4,
    tags: ['reflexe-jury', 'courbe'],
    recto: 'Le jury : « Le forward 1 an dans 1 an est à 4 %. C\'est donc la prévision du marché ? »',
    verso: 'Réflexe : non — taux d\'indifférence d\'arbitrage entre placer 2 ans d\'un bloc et rouler du 1 an, prime de terme incluse. Flash : z₁ 2 %, z₂ 3 % → f = 1,03²/1,02 − 1 ≈ 4,01 %.',
    rectoEn: 'The panel: "The 1-year forward, 1 year ahead, sits at 4%. So that is the market\'s forecast?"',
    versoEn: 'Reflex: no — the no-arbitrage indifference rate between a 2-year block and rolling 1-year paper, term premium included. Flash: z₁ 2%, z₂ 3% → f = 1.03²/1.02 − 1 ≈ 4.01%.',
  },
  {
    id: 'm4-fc-85',
    moduleId: M4,
    tags: ['reflexe-jury', 'rendement'],
    recto: 'Le jury : « Vous achetez à un YTM de 4 %. C\'est du 4 % garanti ? »',
    verso: 'Réflexe : promesse conditionnelle — détention à maturité ET réinvestissement des coupons à 4 %. Seul le zéro-coupon verrouille. Flash : coupons replacés à 2 %, le réalisé tombe sous les 4 %.',
    rectoEn: 'The panel: "You buy at a 4% YTM. Is that a guaranteed 4%?"',
    versoEn: 'Reflex: a conditional promise — hold to maturity AND reinvest coupons at 4%. Only a zero-coupon locks it in. Flash: coupons reinvested at 2% drag the realized return below 4%.',
  },
  {
    id: 'm4-fc-86',
    moduleId: M4,
    tags: ['reflexe-jury', 'convexite'],
    recto: 'Le jury : « Deux fonds, même duration. Pourquoi payer plus cher le plus convexe ? »',
    verso: 'Réflexe : le terme ½C(Δy)² est positif dans les deux sens — il amortit la hausse des taux et amplifie la baisse. Flash : le 3 ans du cours à 4 %, ±1 pt : +28,82 € contre −27,75 €. L\'asymétrie, c\'est la convexité.',
    rectoEn: 'The panel: "Two funds, same duration. Why pay up for the more convex one?"',
    versoEn: 'Reflex: the ½C(Δy)² term is positive both ways — it cushions the sell-off and amplifies the rally. Flash: the course 3-year at 4%, ±1pt: +€28.82 vs −€27.75. That asymmetry is convexity.',
  },
  {
    id: 'm4-fc-87',
    moduleId: M4,
    tags: ['reflexe-jury', 'repo'],
    recto: 'Le jury : « Le repo, en une phrase — et pourquoi tout casse quand il se grippe ? »',
    verso: 'Réflexe : prêt de cash garanti par titres — il finance les desks, fournit les titres aux vendeurs à découvert, transmet les taux directeurs. Flash : sept. 2019, repo US à 10 % en séance → la Fed réinjecte, une première depuis 2008.',
    rectoEn: 'The panel: "Repo in one sentence — and why does everything break when it seizes up?"',
    versoEn: 'Reflex: a cash loan secured by securities — it funds desks, sources bonds for short sellers, transmits policy rates. Flash: Sept 2019, US repo at 10% intraday → the Fed injected cash, a first since 2008.',
  },
  {
    id: 'm4-fc-88',
    moduleId: M4,
    tags: ['reflexe-jury', 'spreads'],
    recto: 'Le jury : « L\'OAT-Bund passe de 75 à 90 pb : la France est sanctionnée, n\'est-ce pas ? »',
    verso: 'Réflexe : décomposer les deux jambes avant de conclure — une OAT qui monte ou un Bund qui baisse (fuite vers la qualité) écartent autant. Flash : Bund −15 pb à OAT inchangée = même spread, lecture opposée.',
    rectoEn: 'The panel: "The OAT-Bund moves from 75 to 90bp: the market is punishing France, right?"',
    versoEn: 'Reflex: decompose both legs before concluding — an OAT rising or a Bund rallying (flight to quality) widens it just as much. Flash: Bund −15bp with the OAT unchanged = same spread, opposite reading.',
  },
  {
    id: 'm4-fc-89',
    moduleId: M4,
    tags: ['reflexe-jury', 'gestion'],
    recto: 'Le jury : « Vous devez payer 100 M€ dans 7 ans. Comment dormez-vous tranquille ? »',
    verso: 'Réflexe : immuniser — duration de l\'actif = 7 ans, à valeurs actuelles égales : effet prix et effet réinvestissement se compensent à l\'horizon. Le plus propre : un zéro-coupon 7 ans, adossement exact.',
    rectoEn: 'The panel: "You owe €100m in 7 years. How do you sleep at night?"',
    versoEn: 'Reflex: immunize — set asset duration = 7 years at equal present values: the price effect and the reinvestment effect offset at the horizon. Cleanest: a 7-year zero-coupon, an exact match.',
  },
  {
    id: 'm4-fc-90',
    moduleId: M4,
    tags: ['reflexe-jury', 'pricing'],
    recto: 'Le jury : « L\'écran affiche 98,45 %. Vous payez donc 984,50 € pour 1 000 € de nominal ? »',
    verso: 'Réflexe : non — l\'écran cote propre, on règle propre + coupon couru, et le couru s\'ajoute toujours. Flash : 984,50 € + 12,00 € de couru = 996,50 €.',
    rectoEn: 'The panel: "The screen shows 98.45%. So you pay €984.50 per €1,000 face?"',
    versoEn: 'Reflex: no — screens quote clean, you settle clean + accrued interest, and accrued is always added. Flash: €984.50 + €12.00 accrued = €996.50.',
  },
  {
    id: 'm4-fc-91',
    moduleId: M4,
    tags: ['reflexe-jury', 'primaire'],
    recto: 'Le jury : « Comment la France emprunte-t-elle, concrètement, mardi prochain ? »',
    verso: 'Réflexe : adjudication AFT à prix multiples — les SVT enchérissent, servis du prix le plus haut au plus bas, chacun paie son prix. Cadence : BTF chaque semaine, OAT chaque mois, ≈ 300 Md€ par an.',
    rectoEn: 'The panel: "How does France actually borrow next Tuesday?"',
    versoEn: 'Reflex: an AFT multiple-price auction — primary dealers bid, filled from the highest price down, each paying its own price. Rhythm: weekly BTFs, monthly OATs, about €300bn a year.',
  },
  {
    id: 'm4-fc-92',
    moduleId: M4,
    tags: ['reflexe-jury', 'obligation'],
    recto: 'Le jury : « Hausse surprise de 100 pb : que fait le prix de votre FRN ? »',
    verso: 'Réflexe : quasi rien — le coupon se recale au prochain fixing, la hausse passe dans les coupons futurs. Flash : duration ≈ temps au fixing (≤ 3 mois) → −0,25 % au pire pour +100 pb.',
    rectoEn: 'The panel: "A surprise 100bp hike: what happens to your FRN\'s price?"',
    versoEn: 'Reflex: almost nothing — the coupon resets at the next fixing, the hike flows into future coupons. Flash: duration ≈ time to the fixing (≤ 3 months) → −0.25% at worst for +100bp.',
  },
  {
    id: 'm4-fc-93',
    moduleId: M4,
    tags: ['reflexe-jury', 'obligation'],
    recto: 'Le jury : « L\'inflation surprend à la hausse. Pourquoi votre OATi protège-t-elle — et contre quoi pas ? »',
    verso: 'Réflexe : nominal × coefficient d\'indexation, coupon réel fixe sur nominal indexé — protège de l\'inflation réalisée, pas d\'une hausse des taux réels. Flash : inflation 3 % → nominal ×1,03, le coupon suit.',
    rectoEn: 'The panel: "Inflation surprises to the upside. Why does your OATi protect you — and against what does it not?"',
    versoEn: 'Reflex: principal × index ratio, fixed real coupon on the indexed principal — protects against realized inflation, not against rising real rates. Flash: 3% inflation → principal ×1.03, the coupon follows.',
  },
  {
    id: 'm4-fc-94',
    moduleId: M4,
    tags: ['reflexe-jury', 'courbe'],
    recto: 'Le jury : « Pourquoi vos pricers ne travaillent-ils pas directement sur les YTM cotés ? »',
    verso: 'Réflexe : le YTM d\'un titre couponné est une moyenne déformée par l\'effet coupon — on bootstrappe les taux zéro-coupon de proche en proche. Flash : 2 ans au pair, YTM 3,00 % mais z₂ = 3,01 %.',
    rectoEn: 'The panel: "Why don\'t your pricers run directly on quoted YTMs?"',
    versoEn: 'Reflex: a coupon bond\'s YTM is an average distorted by the coupon effect — you bootstrap zero-coupon rates step by step. Flash: 2-year at par, 3.00% YTM yet z₂ = 3.01%.',
  },
  {
    id: 'm4-fc-95',
    moduleId: M4,
    tags: ['reflexe-jury', 'duration'],
    recto: 'Le jury : « Votre risque de taux, là, maintenant ? Répondez comme un trader. »',
    verso: 'Réflexe : donner le DV01, en euros par pb — pas un discours. Flash : 50 M€ à D_mod 8 → 40 000 €/pb. « Je perds 40 k€ par point de base de hausse » : c\'est la réponse attendue.',
    rectoEn: 'The panel: "Your rate risk, right now? Answer like a trader."',
    versoEn: 'Reflex: give the DV01, in euros per bp — not a speech. Flash: €50m at D_mod 8 → €40,000/bp. "I lose €40k per basis point of rise" is the expected answer.',
  },
  {
    id: 'm4-fc-96',
    moduleId: M4,
    tags: ['reflexe-jury', 'courbe'],
    recto: 'Le jury : « Vous anticipez une pentification. Montez-moi le trade. »',
    verso: 'Réflexe : steepener 2s10s duration-neutre — acheter le 2 ans, vendre le 10 ans, DV01 égalisés (nominal du 2 ans ≈ 4-5× celui du 10 ans). P&L ≈ DV01 d\'une patte × Δ2s10s en pb.',
    rectoEn: 'The panel: "You expect a steepening. Put the trade on for me."',
    versoEn: 'Reflex: a duration-neutral 2s10s steepener — buy the 2-year, sell the 10-year, DV01s matched (2-year notional ≈ 4-5× the 10-year\'s). P&L ≈ one leg\'s DV01 × Δ2s10s in bp.',
  },
  {
    id: 'm4-fc-97',
    moduleId: M4,
    tags: ['reflexe-jury', 'courbe'],
    recto: 'Le jury : « La banque centrale lance un QE : effet sur la courbe ? Et le QT ? »',
    verso: 'Réflexe : QE = achats concentrés sur le long → prime de terme comprimée, courbe aplatie, signal brouillé. QT = extinction du portefeuille → le marché absorbe plus de papier, primes regonflées, repentification.',
    rectoEn: 'The panel: "The central bank launches QE: effect on the curve? And QT?"',
    versoEn: 'Reflex: QE = purchases concentrated at the long end → term premium compressed, curve flattened, signal blurred. QT = portfolio run-off → the market absorbs more paper, premia rebuild, the curve re-steepens.',
  },
  {
    id: 'm4-fc-98',
    moduleId: M4,
    tags: ['reflexe-jury', 'gestion'],
    recto: 'Le jury : « Les taux ne bougent pas d\'un an. Votre position longue rapporte quoi ? »',
    verso: 'Réflexe : le carry — rendement du titre moins coût de financement repo — plus le roll-down sur courbe pentue. Flash : OAT à 3,3 % financée à 2 % → portage ≈ 130 pb sur l\'année.',
    rectoEn: 'The panel: "Rates go nowhere for a year. What does your long position earn?"',
    versoEn: 'Reflex: the carry — the bond\'s yield minus the repo funding cost — plus roll-down on a steep curve. Flash: an OAT at 3.3% funded at 2% → about 130bp of carry over the year.',
  },
  {
    id: 'm4-fc-99',
    moduleId: M4,
    tags: ['reflexe-jury', 'repo'],
    recto: 'Le jury : « À quoi sert le haircut, et qui protège-t-il ? »',
    verso: 'Réflexe : il protège le prêteur de cash contre une baisse du collatéral pendant l\'opération — et calibre le levier de tout le système. Flash : 10 M€ d\'OAT, haircut 2 % → 9,8 M€ levés.',
    rectoEn: 'The panel: "What is the haircut for, and whom does it protect?"',
    versoEn: 'Reflex: it protects the cash lender against the collateral falling during the trade — and calibrates leverage across the system. Flash: €10m of OATs, 2% haircut → €9.8m raised.',
  },
  {
    id: 'm4-fc-100',
    moduleId: M4,
    tags: ['reflexe-jury', 'credit'],
    recto: 'Le jury : « L\'émetteur fait défaut. Qui est payé avant vous ? »',
    verso: 'Réflexe : dérouler l\'échelle — senior sécurisée > senior non sécurisée (la masse des obligations) > subordonnée > hybrides AT1 > actions. Marquer : Credit Suisse 2023, ≈ 16 Md CHF d\'AT1 effacés.',
    rectoEn: 'The panel: "The issuer defaults. Who gets paid before you?"',
    versoEn: 'Reflex: run the ladder — senior secured > senior unsecured (the bulk of bonds) > subordinated > AT1 hybrids > equity. Land the point: Credit Suisse 2023, about CHF 16bn of AT1s wiped out.',
  },

  // ───────────────────────── Cartes 101-112 — Calcul mental ─────────────────────────
  {
    id: 'm4-fc-101',
    moduleId: M4,
    tags: ['calcul-mental', 'duration'],
    recto: 'De tête : position 20 M€, duration modifiée 6, taux +25 pb. ΔP ?',
    verso: 'ΔP ≈ −D × Δy × P = −6 × 0,0025 × 20 M€ = −300 k€. Routine : duration × pb ÷ 100 = % de prix (6 × 25/100 = 1,5 %), puis appliquer à la position.',
    rectoEn: 'In your head: €20m position, modified duration 6, rates +25bp. ΔP?',
    versoEn: 'ΔP ≈ −D × Δy × P = −6 × 0.0025 × €20m = −€300k. Routine: duration × bp ÷ 100 = % of price (6 × 25/100 = 1.5%), then apply it to the position.',
  },
  {
    id: 'm4-fc-102',
    moduleId: M4,
    tags: ['calcul-mental', 'duration'],
    recto: 'De tête : le prix d\'un point de base sur 10 M€ de duration modifiée 8 ?',
    verso: 'DV01 = D × valeur × 0,0001 = 8 × 10 M€ × 0,0001 = 8 000 €/pb. Raccourci de desk : valeur en M€ × duration × 100 € (10 × 8 × 100 = 8 000 €).',
    rectoEn: 'In your head: the price of one basis point on €10m with modified duration 8?',
    versoEn: 'DV01 = D × value × 0.0001 = 8 × €10m × 0.0001 = €8,000/bp. Desk shortcut: value in €m × duration × €100 (10 × 8 × 100 = €8,000).',
  },
  {
    id: 'm4-fc-103',
    moduleId: M4,
    tags: ['calcul-mental', 'duration'],
    recto: 'La règle d\'or du desk : +1 point de taux = combien sur le prix ?',
    verso: '≈ −D % : duration 5 → −5 %, duration 19 (30 ans) → −19 %. Vaut dans les deux sens, au correctif de convexité près — l\'estimation linéaire suffit pour l\'ordre de grandeur.',
    rectoEn: 'The desk\'s golden rule: a 1-point rise in yields = how much on the price?',
    versoEn: '≈ −D%: duration 5 → −5%, duration 19 (30-year) → −19%. Works both ways, up to the convexity correction — the linear estimate is enough for the order of magnitude.',
  },
  {
    id: 'm4-fc-104',
    moduleId: M4,
    tags: ['calcul-mental', 'pricing'],
    recto: 'De tête : coupon annuel 3 %, dernier détachement il y a 5 mois. Couru sur 1 000 € ?',
    verso: 'Couru ≈ coupon × mois/12 = 30 € × 5/12 = 12,50 €. Approximation de desk — l\'exact dépend de la base (Exact/Exact pour les OAT), mais l\'ordre de grandeur sort en deux secondes.',
    rectoEn: 'In your head: 3% annual coupon, last payment 5 months ago. Accrued on €1,000?',
    versoEn: 'Accrued ≈ coupon × months/12 = €30 × 5/12 = €12.50. Desk approximation — the exact figure depends on the day count (Act/Act for OATs), but the ballpark takes two seconds.',
  },
  {
    id: 'm4-fc-105',
    moduleId: M4,
    tags: ['calcul-mental', 'conventions'],
    recto: 'Conversions réflexes : 1 pb en %, 0,25 % en pb, et 50 pb en décimal pour la formule de duration ?',
    verso: '1 pb = 0,01 % = 0,0001. 0,25 % = 25 pb. 50 pb = 0,005 en décimal. Facteur 100 entre % et pb, facteur 10 000 entre pb et décimal — l\'erreur d\'un facteur 10 est éliminatoire.',
    rectoEn: 'Reflex conversions: 1bp in %, 0.25% in bp, and 50bp as a decimal for the duration formula?',
    versoEn: '1bp = 0.01% = 0.0001. 0.25% = 25bp. 50bp = 0.005 as a decimal. Factor 100 between % and bp, factor 10,000 between bp and decimal — a factor-of-10 slip is disqualifying.',
  },
  {
    id: 'm4-fc-106',
    moduleId: M4,
    tags: ['calcul-mental', 'repo'],
    recto: 'De tête : OAT 10 ans à 3,3 % financée en repo à 2 %. Quelle hausse de taux efface un an de portage ?',
    verso: 'Carry ≈ 130 pb/an. Point mort : Δy = carry/duration ≈ 130/8 ≈ 16 pb. Une hausse de 16 pb dans l\'année mange tout le portage — le carry se juge toujours rapporté à la duration.',
    rectoEn: 'In your head: a 10-year OAT at 3.3% funded in repo at 2%. What rate rise wipes out a year of carry?',
    versoEn: 'Carry ≈ 130bp a year. Break-even: Δy = carry/duration ≈ 130/8 ≈ 16bp. A 16bp rise within the year eats the whole carry — carry is always judged against duration.',
  },
  {
    id: 'm4-fc-107',
    moduleId: M4,
    tags: ['calcul-mental', 'spreads'],
    recto: 'De tête : 25 M€ d\'OAT 10 ans, l\'OAT-Bund s\'écarte de 12 pb par la jambe OAT. Impact en euros ?',
    verso: 'Perte ≈ DV01 × Δspread = (8,5 × 25 M€ × 0,0001) × 12 ≈ 21 250 € × 12 ≈ −255 k€. Un mouvement de spread se monétise comme un mouvement de taux : par le DV01.',
    rectoEn: 'In your head: €25m of 10-year OATs, the OAT-Bund widens 12bp through the OAT leg. Euro impact?',
    versoEn: 'Loss ≈ DV01 × Δspread = (8.5 × €25m × 0.0001) × 12 ≈ €21,250 × 12 ≈ −€255k. A spread move is monetized like a rate move: through the DV01.',
  },
  {
    id: 'm4-fc-108',
    moduleId: M4,
    tags: ['calcul-mental', 'duration'],
    recto: 'Les durations à connaître par cœur, coupons moyens : 2 ans, 5 ans, 10 ans, 30 ans ?',
    verso: '≈ 1,9 ; 4,5 ; 8,5 ; 19. Repère : la duration fait ~85-90 % de la maturité sur le court et décroche sur le long (les coupons pèsent). De quoi chiffrer n\'importe quel choc en deux secondes.',
    rectoEn: 'The durations to know cold, average coupons: 2-year, 5-year, 10-year, 30-year?',
    versoEn: '≈ 1.9; 4.5; 8.5; 19. Rule of thumb: duration runs ~85-90% of maturity at the short end and falls away at the long end (coupons weigh in). Enough to size any shock in two seconds.',
  },
  {
    id: 'm4-fc-109',
    moduleId: M4,
    tags: ['calcul-mental', 'taux'],
    recto: 'De tête : à 4 %, combien d\'années pour doubler un capital ? Et à 2 % ?',
    verso: 'Règle des 72 : doublement ≈ 72/taux. À 4 % → 18 ans ; à 2 % → 36 ans. Vérification : 1,04¹⁸ ≈ 2,03. L\'arme idéale pour donner de la chair aux intérêts composés à l\'oral.',
    rectoEn: 'In your head: at 4%, how many years to double your money? And at 2%?',
    versoEn: 'Rule of 72: doubling time ≈ 72/rate. At 4% → 18 years; at 2% → 36 years. Check: 1.04¹⁸ ≈ 2.03. The ideal weapon for making compounding concrete in an interview.',
  },
  {
    id: 'm4-fc-110',
    moduleId: M4,
    tags: ['calcul-mental', 'rendement'],
    recto: 'En une seconde : le titre cote 104 %. Rendement courant au-dessus ou en dessous du YTM ?',
    verso: 'Surcote → coupon > YTM, et le courant ignore la perte en capital au pair : YTM < courant < coupon. En décote, l\'ordre s\'inverse. Flash : prix 104, coupon 5 % → courant 4,81 %, YTM plus bas encore.',
    rectoEn: 'In one second: the bond quotes 104%. Is current yield above or below the YTM?',
    versoEn: 'Premium → coupon > YTM, and current yield ignores the pull-to-par loss: YTM < current < coupon. The order flips at a discount. Flash: price 104, 5% coupon → current 4.81%, YTM lower still.',
  },
  {
    id: 'm4-fc-111',
    moduleId: M4,
    tags: ['calcul-mental', 'courbe'],
    recto: 'De tête : z₁ = 2 %, z₂ = 3 %. Le forward 1 an dans 1 an, sans calculatrice ?',
    verso: 'f₁,₂ ≈ 2×z₂ − z₁ = 6 − 2 = 4 % (exact : 4,01 %). Le 2 ans est la moyenne des deux années : la deuxième doit rattraper. Généralisation : f ≈ (n₂z₂ − n₁z₁)/(n₂ − n₁).',
    rectoEn: 'In your head: z₁ = 2%, z₂ = 3%. The 1-year forward, 1 year ahead, without a calculator?',
    versoEn: 'f₁,₂ ≈ 2×z₂ − z₁ = 6 − 2 = 4% (exact: 4.01%). The 2-year rate averages the two years, so year two must catch up. General form: f ≈ (n₂z₂ − n₁z₁)/(n₂ − n₁).',
  },
  {
    id: 'm4-fc-112',
    moduleId: M4,
    tags: ['calcul-mental', 'convexite'],
    recto: 'En une seconde : la duration prédit −8 %. Le vrai chiffre est-il au-dessus ou en dessous ?',
    verso: 'Au-dessus (moins négatif) : le correctif ½C(Δy)² est toujours positif pour une obligation classique. La tangente surestime les pertes et sous-estime les gains. Flash : −8 % devient ≈ −7,7 % avec la convexité.',
    rectoEn: 'In one second: duration predicts −8%. Is the true number above or below that?',
    versoEn: 'Above (less negative): the ½C(Δy)² correction is always positive for a plain bond. The tangent overstates losses and understates gains. Flash: −8% becomes ≈ −7.7% with convexity.',
  },

  // ───────────────────────── Cartes 113-120 — Pièges niveau 4 ─────────────────────────
  {
    id: 'm4-fc-113',
    moduleId: M4,
    tags: ['piege', 'duration'],
    recto: 'Piège : maturité infinie, donc duration infinie ?',
    verso: 'Non : la duration de Macaulay d\'une perpétuité vaut (1+y)/y — finie. À 4 % → 26 ans ; à 2 % → 51 ans. Les flux lointains pèsent de moins en moins une fois actualisés : le barycentre converge.',
    rectoEn: 'Trap: infinite maturity, therefore infinite duration?',
    versoEn: 'No: a perpetuity\'s Macaulay duration is (1+y)/y — finite. At 4% → 26 years; at 2% → 51 years. Distant flows weigh less and less once discounted: the barycentre converges.',
  },
  {
    id: 'm4-fc-114',
    moduleId: M4,
    tags: ['piege', 'duration', 'obligation'],
    recto: 'Piège : un FRN 10 ans a-t-il une duration de taux proche de 8, comme une OAT 10 ans ?',
    verso: 'Non : ≈ le temps jusqu\'au prochain fixing (0 à 3 mois sur Euribor 3M) — le coupon se recale et le titre revient au pair. Reste en revanche une vraie sensibilité au spread de crédit sur les 10 ans.',
    rectoEn: 'Trap: does a 10-year FRN carry a rate duration near 8, like a 10-year OAT?',
    versoEn: 'No: ≈ the time to the next fixing (0 to 3 months on 3-month Euribor) — the coupon resets and the note pulls back to par. What remains is genuine credit-spread duration over the full 10 years.',
  },
  {
    id: 'm4-fc-115',
    moduleId: M4,
    tags: ['piege', 'convexite', 'gestion'],
    recto: 'Piège : barbell (2 ans + 30 ans) et bullet (10 ans), même duration : comportement identique ?',
    verso: 'Non : même sensibilité au choc parallèle seulement. Le barbell est plus convexe — il gagne sur les gros chocs — mais souffre si la courbe se pentifie ou se déforme au milieu. Même duration ≠ même exposition à la courbe.',
    rectoEn: 'Trap: a barbell (2-year + 30-year) and a bullet (10-year), same duration: identical behavior?',
    versoEn: 'No: same sensitivity to a parallel shock only. The barbell is more convex — it wins on large moves — but suffers if the curve steepens or kinks in the belly. Equal duration ≠ equal curve exposure.',
  },
  {
    id: 'm4-fc-116',
    moduleId: M4,
    tags: ['piege', 'gestion'],
    recto: 'Piège : portefeuille immunisé en janvier — tranquille jusqu\'à l\'échéance ?',
    verso: 'Non : la duration de l\'actif dérive avec le temps et chaque mouvement de taux, celle du passif aussi — et pas au même rythme. L\'immunisation est un cap à tenir : on re-balance régulièrement, ce n\'est pas un réglage unique.',
    rectoEn: 'Trap: portfolio immunized in January — safe until maturity?',
    versoEn: 'No: asset duration drifts with time and with every rate move, liability duration too — and not at the same pace. Immunization is a heading to hold: you rebalance regularly, it is not a one-off setting.',
  },
  {
    id: 'm4-fc-117',
    moduleId: M4,
    tags: ['piege', 'courbe'],
    recto: 'Piège : votre steepener 2s10s est duration-neutre, donc sans risque si les taux montent ?',
    verso: 'Non : neutre au choc parallèle seulement. En bear flattening — le 2 ans monte plus vite, type 2022-2023 —, la pente se resserre et le steepener perd : DV01 d\'une patte × pb de resserrement.',
    rectoEn: 'Trap: your 2s10s steepener is duration-neutral, hence riskless if rates rise?',
    versoEn: 'No: neutral to a parallel shock only. In a bear flattening — the 2-year rising faster, 2022-2023 style — the slope narrows and the steepener loses: one leg\'s DV01 × bp of narrowing.',
  },
  {
    id: 'm4-fc-118',
    moduleId: M4,
    tags: ['piege', 'conventions'],
    recto: 'Piège : du 15 février au 15 mars en base 30/360 : 28 jours de calendrier, donc 28 jours comptés ?',
    verso: 'Non : 30 jours — chaque mois est forfaitisé à 30, février compris. En 30/360, on compte mois × 30, pas les jours réels. C\'est en Exact/360 ou Exact/Exact que le calendrier compte.',
    rectoEn: 'Trap: 15 February to 15 March under 30/360: 28 calendar days, so 28 days counted?',
    versoEn: 'No: 30 days — every month is standardized to 30, February included. Under 30/360 you count months × 30, not actual days. Act/360 or Act/Act is where the calendar matters.',
  },
  {
    id: 'm4-fc-119',
    moduleId: M4,
    tags: ['piege', 'rendement'],
    recto: 'Piège : détenu jusqu\'au remboursement, le titre acheté à YTM 4 % a forcément rapporté 4 % ?',
    verso: 'Non : le réalisé dépend du taux de replacement des coupons. Flash : 3 ans, coupon 5 %, coupons replacés à 2 % au lieu de 4 % → réalisé ≈ 3,9 %. YTM = réalisé : pour le zéro-coupon uniquement.',
    rectoEn: 'Trap: held to redemption, a bond bought at a 4% YTM has necessarily returned 4%?',
    versoEn: 'No: the realized return depends on the coupon reinvestment rate. Flash: 3 years, 5% coupon, coupons reinvested at 2% instead of 4% → realized ≈ 3.9%. YTM = realized: for the zero-coupon only.',
  },
  {
    id: 'm4-fc-120',
    moduleId: M4,
    tags: ['piege', 'courbe'],
    recto: 'Piège : le forward annonçait 4 %, le taux réalisé un an plus tard est 4 % : preuve que le forward prévoit ?',
    verso: 'Non : coïncidence ne vaut pas causalité — le forward est un taux d\'arbitrage, prime de terme incluse, qui surestime historiquement les taux réalisés. Un tir réussi ne fait pas un viseur.',
    rectoEn: 'Trap: the forward said 4%, the realized rate a year later is 4%: proof that forwards forecast?',
    versoEn: 'No: coincidence is not causation — the forward is an arbitrage rate, term premium included, and it has historically overshot realized rates. One lucky hit does not make a gunsight.',
  },
];
