import type { Formule } from '../../../engine/types';

const M4 = '04-taux-obligations';

export const formules: Formule[] = [
  {
    id: 'm4-f-01',
    moduleId: M4,
    nom: 'Valeur actuelle (actualisation)',
    nomEn: 'Present value (discounting)',
    latex: 'VA = \\frac{VF}{(1+r)^n}',
    commentaire: 'Pour ramener un flux futur unique à sa valeur d\'aujourd\'hui — la brique de base de tout pricing.',
    commentaireEn: 'To bring a single future cash flow back to today\'s value — the basic building block of all pricing.',
  },
  {
    id: 'm4-f-02',
    moduleId: M4,
    nom: 'Valeur future (capitalisation composée)',
    nomEn: 'Future value (compound interest)',
    latex: 'VF = VA \\times (1+r)^n',
    commentaire: 'Pour capitaliser un placement à intérêts composés sur n années.',
    commentaireEn: 'To compound an investment at compound interest over n years.',
  },
  {
    id: 'm4-f-03',
    moduleId: M4,
    nom: 'Taux annuel effectif',
    nomEn: 'Effective annual rate',
    latex: 'r_{\\text{eff}} = \\left(1 + \\frac{r}{m}\\right)^{m} - 1',
    commentaire: 'Pour comparer des taux nominaux à fréquences de composition différentes (m compositions par an).',
    commentaireEn: 'To compare nominal rates with different compounding frequencies (m compounding periods per year).',
  },
  {
    id: 'm4-f-04',
    moduleId: M4,
    nom: 'Intérêt monétaire (Exact/360)',
    nomEn: 'Money-market interest (Act/360)',
    latex: 'I = N \\times r \\times \\frac{\\text{jours}}{360}',
    commentaire: 'Pour calculer l\'intérêt d\'une opération de marché monétaire euro : jours calendaires réels, base 360.',
    commentaireEn: 'To compute interest on a euro money-market transaction: actual calendar days over a 360-day year.',
  },
  {
    id: 'm4-f-05',
    moduleId: M4,
    nom: 'Prix d\'une obligation',
    nomEn: 'Bond price',
    latex: 'P = \\sum_{t=1}^{n} \\frac{F_t}{(1+r)^t}',
    commentaire: 'Pour pricer une obligation à taux fixe : somme des flux actualisés au taux exigé par le marché.',
    commentaireEn: 'To price a fixed-rate bond: the sum of cash flows discounted at the market-required rate.',
  },
  {
    id: 'm4-f-06',
    moduleId: M4,
    nom: 'Prix d\'un zéro-coupon',
    nomEn: 'Zero-coupon price',
    latex: 'P = \\frac{N}{(1+r)^n}',
    commentaire: 'Pour pricer un titre à flux unique : le nominal actualisé depuis l\'échéance.',
    commentaireEn: 'To price a single-cash-flow security: the face value discounted back from maturity.',
  },
  {
    id: 'm4-f-07',
    moduleId: M4,
    nom: 'Coupon couru',
    nomEn: 'Accrued interest',
    latex: '\\text{couru} = C \\times \\frac{\\text{jours courus}}{\\text{jours de la période}}',
    commentaire: 'Pour passer du prix propre coté au prix sale réglé (base Exact/Exact pour les OAT).',
    commentaireEn: 'To go from the quoted clean price to the settled dirty price (Act/Act basis for OATs).',
  },
  {
    id: 'm4-f-08',
    moduleId: M4,
    nom: 'Rendement courant',
    nomEn: 'Current yield',
    latex: 'r_{\\text{courant}} = \\frac{C}{P}',
    commentaire: 'Pour un ordre de grandeur instantané du loyer annuel — ignore le remboursement et le calendrier des flux.',
    commentaireEn: 'For an instant gauge of annual income — ignores redemption and the timing of cash flows.',
  },
  {
    id: 'm4-f-09',
    moduleId: M4,
    nom: 'Rendement actuariel (YTM) — équation de définition',
    nomEn: 'Yield to maturity (YTM) — defining equation',
    latex: 'P = \\sum_{t=1}^{n} \\frac{F_t}{(1+y)^t}',
    commentaire: 'Pour définir le taux y qui égalise prix observé et flux actualisés — se résout numériquement par essais encadrants.',
    commentaireEn: 'To define the rate y that equates the observed price with the discounted cash flows — solved numerically by bracketing trials.',
  },
  {
    id: 'm4-f-10',
    moduleId: M4,
    nom: 'Bootstrap du taux zéro-coupon 2 ans',
    nomEn: 'Bootstrapping the 2-year zero-coupon rate',
    latex: '(1+z_2)^2 = \\frac{C+N}{P - \\dfrac{C}{1+z_1}}',
    commentaire: 'Pour extraire le taux zéro-coupon 2 ans du prix d\'une obligation couponnée, z₁ étant déjà connu.',
    commentaireEn: 'To extract the 2-year zero-coupon rate from a coupon bond\'s price, z₁ being already known.',
  },
  {
    id: 'm4-f-11',
    moduleId: M4,
    nom: 'Taux forward implicite',
    nomEn: 'Implied forward rate',
    latex: '(1+z_2)^2 = (1+z_1)(1+f_{1,2})',
    commentaire: 'Pour calculer le taux à terme entre l\'an 1 et l\'an 2, imposé par l\'absence d\'arbitrage — pas une prévision.',
    commentaireEn: 'To compute the term rate between year 1 and year 2, imposed by no-arbitrage — not a forecast.',
  },
  {
    id: 'm4-f-12',
    moduleId: M4,
    nom: 'Duration de Macaulay',
    nomEn: 'Macaulay duration',
    latex: 'D_{Mac} = \\frac{\\sum_{t=1}^{n} t \\cdot VA(F_t)}{P}',
    commentaire: 'Pour mesurer le barycentre temporel des flux actualisés — en années.',
    commentaireEn: 'To measure the time barycentre of the discounted cash flows — in years.',
  },
  {
    id: 'm4-f-13',
    moduleId: M4,
    nom: 'Duration modifiée',
    nomEn: 'Modified duration',
    latex: 'D_{mod} = \\frac{D_{Mac}}{1+y}',
    commentaire: 'Pour convertir la duration en facteur de sensibilité du prix au taux — sans unité.',
    commentaireEn: 'To convert duration into a price sensitivity factor to yield — unitless.',
  },
  {
    id: 'm4-f-14',
    moduleId: M4,
    nom: 'Variation de prix par la duration',
    nomEn: 'Duration approximation of price change',
    latex: '\\Delta P \\approx -D_{mod} \\times \\Delta y \\times P',
    commentaire: 'Pour estimer de tête l\'effet d\'un petit choc de taux (Δy en décimal : 50 pb = 0,005).',
    commentaireEn: 'To estimate in your head the effect of a small rate shock (Δy as a decimal: 50bp = 0.005).',
  },
  {
    id: 'm4-f-15',
    moduleId: M4,
    nom: 'Correction de convexité',
    nomEn: 'Convexity correction',
    latex: '\\frac{\\Delta P}{P} \\approx -D_{mod}\\,\\Delta y + \\tfrac{1}{2}\\,C\\,(\\Delta y)^2',
    commentaire: 'Pour les chocs larges : le terme en (Δy)², positif dans les deux sens, corrige l\'approximation de la tangente.',
    commentaireEn: 'For large shocks: the (Δy)² term, positive in both directions, corrects the tangent approximation.',
  },
  {
    id: 'm4-f-16',
    moduleId: M4,
    nom: 'DV01',
    nomEn: 'DV01',
    latex: 'DV01 = D_{mod} \\times P \\times 0{,}0001',
    commentaire: 'Pour chiffrer en euros l\'impact d\'un point de base sur une position — l\'unité de risque quotidienne des desks.',
    commentaireEn: 'To put a euro figure on a one-basis-point move for a position — the desks\' daily unit of risk.',
  },
  {
    id: 'm4-f-17',
    moduleId: M4,
    nom: 'Duration d\'un portefeuille',
    nomEn: 'Portfolio duration',
    latex: 'D_{ptf} = \\sum_{i} w_i \\, D_i',
    commentaire: 'Pour agréger le risque de taux : moyenne des durations pondérée par les poids en valeur de marché.',
    commentaireEn: 'To aggregate rate risk: the average of durations weighted by market-value weights.',
  },
  {
    id: 'm4-f-18',
    moduleId: M4,
    nom: 'Ratio de couverture en DV01',
    nomEn: 'DV01 hedge ratio',
    latex: 'n_{\\text{contrats}} = \\frac{DV01_{\\text{portefeuille}}}{DV01_{\\text{contrat}}}',
    commentaire: 'Pour neutraliser le risque de taux d\'un portefeuille avec des contrats à terme, en égalisant les DV01.',
    commentaireEn: 'To neutralize a portfolio\'s rate risk with futures contracts by equalizing DV01s.',
  },
  {
    id: 'm4-f-19',
    moduleId: M4,
    nom: 'Perpétuité : prix et duration',
    nomEn: 'Perpetuity: price and duration',
    latex: 'P = \\frac{c}{y} \\qquad D_{Mac} = \\frac{1+y}{y}',
    commentaire: 'Pour pricer un coupon perpétuel — et retenir qu\'une maturité infinie n\'implique pas une duration infinie.',
    commentaireEn: 'To price a perpetual coupon — and to remember that infinite maturity does not imply infinite duration.',
  },
];
