import type { Formule } from '../../../engine/types';

const M4 = '04-taux-obligations';

export const formules: Formule[] = [
  {
    id: 'm4-f-01',
    moduleId: M4,
    nom: 'Valeur actuelle (actualisation)',
    latex: 'VA = \\frac{VF}{(1+r)^n}',
    commentaire: 'Pour ramener un flux futur unique à sa valeur d\'aujourd\'hui — la brique de base de tout pricing.',
  },
  {
    id: 'm4-f-02',
    moduleId: M4,
    nom: 'Valeur future (capitalisation composée)',
    latex: 'VF = VA \\times (1+r)^n',
    commentaire: 'Pour capitaliser un placement à intérêts composés sur n années.',
  },
  {
    id: 'm4-f-03',
    moduleId: M4,
    nom: 'Taux annuel effectif',
    latex: 'r_{\\text{eff}} = \\left(1 + \\frac{r}{m}\\right)^{m} - 1',
    commentaire: 'Pour comparer des taux nominaux à fréquences de composition différentes (m compositions par an).',
  },
  {
    id: 'm4-f-04',
    moduleId: M4,
    nom: 'Intérêt monétaire (Exact/360)',
    latex: 'I = N \\times r \\times \\frac{\\text{jours}}{360}',
    commentaire: 'Pour calculer l\'intérêt d\'une opération de marché monétaire euro : jours calendaires réels, base 360.',
  },
  {
    id: 'm4-f-05',
    moduleId: M4,
    nom: 'Prix d\'une obligation',
    latex: 'P = \\sum_{t=1}^{n} \\frac{F_t}{(1+r)^t}',
    commentaire: 'Pour pricer une obligation à taux fixe : somme des flux actualisés au taux exigé par le marché.',
  },
  {
    id: 'm4-f-06',
    moduleId: M4,
    nom: 'Prix d\'un zéro-coupon',
    latex: 'P = \\frac{N}{(1+r)^n}',
    commentaire: 'Pour pricer un titre à flux unique : le nominal actualisé depuis l\'échéance.',
  },
  {
    id: 'm4-f-07',
    moduleId: M4,
    nom: 'Coupon couru',
    latex: '\\text{couru} = C \\times \\frac{\\text{jours courus}}{\\text{jours de la période}}',
    commentaire: 'Pour passer du prix propre coté au prix sale réglé (base Exact/Exact pour les OAT).',
  },
  {
    id: 'm4-f-08',
    moduleId: M4,
    nom: 'Rendement courant',
    latex: 'r_{\\text{courant}} = \\frac{C}{P}',
    commentaire: 'Pour un ordre de grandeur instantané du loyer annuel — ignore le remboursement et le calendrier des flux.',
  },
  {
    id: 'm4-f-09',
    moduleId: M4,
    nom: 'Rendement actuariel (YTM) — équation de définition',
    latex: 'P = \\sum_{t=1}^{n} \\frac{F_t}{(1+y)^t}',
    commentaire: 'Pour définir le taux y qui égalise prix observé et flux actualisés — se résout numériquement par essais encadrants.',
  },
  {
    id: 'm4-f-10',
    moduleId: M4,
    nom: 'Bootstrap du taux zéro-coupon 2 ans',
    latex: '(1+z_2)^2 = \\frac{C+N}{P - \\dfrac{C}{1+z_1}}',
    commentaire: 'Pour extraire le taux zéro-coupon 2 ans du prix d\'une obligation couponnée, z₁ étant déjà connu.',
  },
  {
    id: 'm4-f-11',
    moduleId: M4,
    nom: 'Taux forward implicite',
    latex: '(1+z_2)^2 = (1+z_1)(1+f_{1,2})',
    commentaire: 'Pour calculer le taux à terme entre l\'an 1 et l\'an 2, imposé par l\'absence d\'arbitrage — pas une prévision.',
  },
  {
    id: 'm4-f-12',
    moduleId: M4,
    nom: 'Duration de Macaulay',
    latex: 'D_{Mac} = \\frac{\\sum_{t=1}^{n} t \\cdot VA(F_t)}{P}',
    commentaire: 'Pour mesurer le barycentre temporel des flux actualisés — en années.',
  },
  {
    id: 'm4-f-13',
    moduleId: M4,
    nom: 'Duration modifiée',
    latex: 'D_{mod} = \\frac{D_{Mac}}{1+y}',
    commentaire: 'Pour convertir la duration en facteur de sensibilité du prix au taux — sans unité.',
  },
  {
    id: 'm4-f-14',
    moduleId: M4,
    nom: 'Variation de prix par la duration',
    latex: '\\Delta P \\approx -D_{mod} \\times \\Delta y \\times P',
    commentaire: 'Pour estimer de tête l\'effet d\'un petit choc de taux (Δy en décimal : 50 pb = 0,005).',
  },
  {
    id: 'm4-f-15',
    moduleId: M4,
    nom: 'Correction de convexité',
    latex: '\\frac{\\Delta P}{P} \\approx -D_{mod}\\,\\Delta y + \\tfrac{1}{2}\\,C\\,(\\Delta y)^2',
    commentaire: 'Pour les chocs larges : le terme en (Δy)², positif dans les deux sens, corrige l\'approximation de la tangente.',
  },
  {
    id: 'm4-f-16',
    moduleId: M4,
    nom: 'DV01',
    latex: 'DV01 = D_{mod} \\times P \\times 0{,}0001',
    commentaire: 'Pour chiffrer en euros l\'impact d\'un point de base sur une position — l\'unité de risque quotidienne des desks.',
  },
  {
    id: 'm4-f-17',
    moduleId: M4,
    nom: 'Duration d\'un portefeuille',
    latex: 'D_{ptf} = \\sum_{i} w_i \\, D_i',
    commentaire: 'Pour agréger le risque de taux : moyenne des durations pondérée par les poids en valeur de marché.',
  },
  {
    id: 'm4-f-18',
    moduleId: M4,
    nom: 'Ratio de couverture en DV01',
    latex: 'n_{\\text{contrats}} = \\frac{DV01_{\\text{portefeuille}}}{DV01_{\\text{contrat}}}',
    commentaire: 'Pour neutraliser le risque de taux d\'un portefeuille avec des contrats à terme, en égalisant les DV01.',
  },
  {
    id: 'm4-f-19',
    moduleId: M4,
    nom: 'Perpétuité : prix et duration',
    latex: 'P = \\frac{c}{y} \\qquad D_{Mac} = \\frac{1+y}{y}',
    commentaire: 'Pour pricer un coupon perpétuel — et retenir qu\'une maturité infinie n\'implique pas une duration infinie.',
  },
];
