import type { Formule } from '../../../engine/types';

const M6 = '06-change-commos-crypto';

export const formules: Formule[] = [
  {
    id: 'm6-f-01',
    moduleId: M6,
    nom: 'Parité des taux d\'intérêt couverte (CIP)',
    nomEn: 'Covered interest rate parity (CIP)',
    latex: 'F = S \\times \\frac{1 + r_{\\text{cotée}}\\,T}{1 + r_{\\text{base}}\\,T}',
    commentaire: 'Le forward de change par absence d\'arbitrage : S le spot, r les taux en linéaire simple, T en années — taux de la devise cotée au numérateur, base au dénominateur. Exemple canonique : 1,10 × 1,05/1,03 = 1,1214 (ch. 2).',
    commentaireEn: 'The FX forward by absence of arbitrage: S the spot, r the simple linear rates, T in years — the quote currency\'s rate on top, the base\'s below. Canonical example: 1.10 × 1.05/1.03 = 1.1214 (ch. 2).',
  },
  {
    id: 'm6-f-02',
    moduleId: M6,
    nom: 'Points de terme (points de swap)',
    nomEn: 'Forward points (swap points)',
    latex: '\\text{points} = (F - S) \\times 10\\,000',
    commentaire: 'L\'écart forward-spot en pips, ce que cotent réellement les cambistes : positifs, la base est en report ; négatifs, en déport. (1,121359 − 1,10) × 10 000 = +213,6 pips (ch. 2).',
    commentaireEn: 'The forward-spot gap in pips, what dealers actually quote: positive, the base trades at a premium; negative, at a discount. (1.121359 − 1.10) × 10,000 = +213.6 pips (ch. 2).',
  },
  {
    id: 'm6-f-03',
    moduleId: M6,
    nom: 'Forward approché par le différentiel de taux',
    nomEn: 'Forward approximated by the rate differential',
    latex: 'F \\approx S \\times \\left(1 + (r_{\\text{cotée}} - r_{\\text{base}})\\,T\\right)',
    commentaire: 'L\'approximation de tête, valable pour des différentiels modérés et des horizons courts : 1,10 × (1 + 0,02) = 1,1220 contre 1,1214 exact — bonne pour l\'ordre de grandeur, jamais pour le pricing (ch. 2).',
    commentaireEn: 'The mental-math shortcut, valid for moderate differentials and short horizons: 1.10 × (1 + 0.02) = 1.1220 against the exact 1.1214 — good for the order of magnitude, never for pricing (ch. 2).',
  },
  {
    id: 'm6-f-04',
    moduleId: M6,
    nom: 'PPA absolue (taux de change d\'équilibre)',
    nomEn: 'Absolute PPP (equilibrium exchange rate)',
    latex: 'S_{\\text{PPA}} = \\frac{P_{\\text{cotée}}}{P_{\\text{base}}}',
    commentaire: 'La loi du prix unique agrégée : le panier coûte P en chaque devise, et le taux qui égalise les pouvoirs d\'achat est leur rapport, homogène au cours BASE/COTÉE. Big Mac à 5,80 $ et 5,00 € : PPA EUR/USD = 1,16 (ch. 3).',
    commentaireEn: 'The law of one price aggregated: the basket costs P in each currency, and the rate equalising purchasing powers is their ratio, consistent with the BASE/QUOTE convention. Big Mac at $5.80 and €5.00: EUR/USD PPP = 1.16 (ch. 3).',
  },
  {
    id: 'm6-f-05',
    moduleId: M6,
    nom: 'Sur/sous-évaluation par rapport à la PPA',
    nomEn: 'Over/undervaluation relative to PPP',
    latex: '\\text{écart} = \\left(\\frac{S}{S_{\\text{PPA}}} - 1\\right) \\times 100',
    commentaire: 'L\'écart mesure la valorisation de la devise de BASE : spot 1,10 contre PPA 1,16 donne −5,17 % — l\'euro est sous-évalué (il achète moins de dollars que le panier ne le justifie), le dollar symétriquement surévalué (ch. 3).',
    commentaireEn: 'The gap measures the BASE currency\'s valuation: spot 1.10 against a 1.16 PPP gives −5.17% — the euro is undervalued (it buys fewer dollars than the basket warrants), the dollar symmetrically overvalued (ch. 3).',
  },
  {
    id: 'm6-f-06',
    moduleId: M6,
    nom: 'PPA relative (différentiel d\'inflation)',
    nomEn: 'Relative PPP (inflation differential)',
    latex: '\\frac{\\Delta S}{S} \\approx \\pi_{\\text{cotée}} - \\pi_{\\text{base}}',
    commentaire: 'La version dynamique de la PPA : la devise du pays à forte inflation (π) se déprécie d\'environ le différentiel d\'inflation. Boussole de très long terme — un écart à la parité met de l\'ordre de trois à cinq ans à se résorber de moitié (ch. 3).',
    commentaireEn: 'The dynamic version of PPP: the high-inflation country\'s currency (π) depreciates by roughly the inflation differential. A very-long-run compass — a gap to parity takes about three to five years to close by half (ch. 3).',
  },
  {
    id: 'm6-f-07',
    moduleId: M6,
    nom: 'P&L d\'un carry trade',
    nomEn: 'Carry trade P&L',
    latex: '\\text{P\\&L} = N \\times \\left(\\frac{r_{\\text{cible}} - r_{\\text{fin}}}{100} + \\frac{\\Delta}{100}\\right)',
    commentaire: 'Sur un notionnel N : portage (placement r_cible moins financement r_fin, en %) plus variation Δ de la devise cible (positive si elle s\'apprécie). 1 M$, 8 %, 2 %, Δ = −10 % : −40 000 $ — le crash mange le portage et au-delà (ch. 3).',
    commentaireEn: 'On a notional N: carry (investment rate r_target minus funding r_fund, in %) plus the target currency\'s move Δ (positive if it appreciates). $1m, 8%, 2%, Δ = −10%: −$40,000 — the crash eats the carry and more (ch. 3).',
  },
  {
    id: 'm6-f-08',
    moduleId: M6,
    nom: 'Forward d\'une matière première (cash and carry)',
    nomEn: 'Commodity forward (cash and carry)',
    latex: 'F = S \\times \\left(1 + \\frac{c}{100}\\,T\\right)',
    commentaire: 'Le terme vaut le spot S plus le coût complet de porter la matière jusqu\'à l\'échéance, au portage net c (en % par an). Spot 80 $, portage net 5 %, 1 an : F = 80 × 1,05 = 84 $ — la courbe monte, c\'est le contango (ch. 6).',
    commentaireEn: 'The forward equals the spot S plus the full cost of carrying the commodity to maturity, at the net carry c (in % per year). Spot $80, net carry 5%, 1 year: F = 80 × 1.05 = $84 — an upward curve, that is contango (ch. 6).',
  },
  {
    id: 'm6-f-09',
    moduleId: M6,
    nom: 'Coût de portage net',
    nomEn: 'Net cost of carry',
    latex: 'c = \\text{financement} + \\text{stockage} - \\text{convenience yield}',
    commentaire: 'Financement et stockage renchérissent le terme ; le convenience yield — le dividende de disponibilité du détenteur du physique — le réduit. 4 + 2 − 1 = +5 % : contango (F = 84) ; 2 + 1 − 6 = −3 % : backwardation (F = 77,60) (ch. 6).',
    commentaireEn: 'Funding and storage push the forward up; the convenience yield — the availability dividend of holding the physical — pulls it down. 4 + 2 − 1 = +5%: contango (F = 84); 2 + 1 − 6 = −3%: backwardation (F = 77.60) (ch. 6).',
  },
  {
    id: 'm6-f-10',
    moduleId: M6,
    nom: 'Roll yield annualisé',
    nomEn: 'Annualised roll yield',
    latex: '\\text{roll yield} = \\left(\\frac{F_{\\text{proche}}}{F_{\\text{lointain}}} - 1\\right) \\times \\frac{1}{T}',
    commentaire: 'Le coût (ou gain) de rester exposé : au roll, on vend le contrat proche et on rachète le lointain, T étant l\'écart entre échéances en années. Contango 80/84 : −4,76 % par an — l\'érosion des trackers ; backwardation 80/77,60 : +3,09 % (ch. 6).',
    commentaireEn: 'The cost (or gain) of staying exposed: at the roll, you sell the near contract and buy the far one, T being the gap between maturities in years. Contango 80/84: −4.76% a year — the tracker erosion; backwardation 80/77.60: +3.09% (ch. 6).',
  },
  {
    id: 'm6-f-11',
    moduleId: M6,
    nom: 'Base (spot moins futures)',
    nomEn: 'Basis (spot minus futures)',
    latex: '\\text{base} = S - F',
    commentaire: 'Négative en contango, positive en backwardation — et elle converge mécaniquement vers zéro à l\'échéance, le futures qui expire devenant du spot. Sa pente courte se lit comme un indicateur de stocks en temps réel (ch. 6).',
    commentaireEn: 'Negative in contango, positive in backwardation — and it mechanically converges to zero at expiry, the dying futures becoming spot. Its front slope reads as a real-time inventory gauge (ch. 6).',
  },
  {
    id: 'm6-f-12',
    moduleId: M6,
    nom: 'Coût d\'un aller-retour au spread bid/ask',
    nomEn: 'Round-trip cost of the bid/ask spread',
    latex: '\\text{coût} = M \\times \\frac{\\text{ask} - \\text{bid}}{\\text{milieu}} \\qquad \\text{milieu} = \\frac{\\text{bid} + \\text{ask}}{2}',
    commentaire: 'Le spread relatif appliqué au montant M traité. 1 M€ sur 1,0998/1,1002 : 1 M × 0,0004/1,1000 = 363,64 € — et non 400 € : les pips s\'encaissent en devise cotée et se reconvertissent au cours milieu (ch. 1).',
    commentaireEn: 'The relative spread applied to the amount M traded. €1m on 1.0998/1.1002: 1m × 0.0004/1.1000 = €363.64 — not €400: the pips accrue in the quote currency and must be converted back at the mid rate (ch. 1).',
  },
  {
    id: 'm6-f-13',
    moduleId: M6,
    nom: 'Rendement annualisé d\'un actif sans flux (composé)',
    nomEn: 'Annualised return of a no-cash-flow asset (CAGR)',
    latex: 'r = \\left(\\left(\\frac{V_T}{V_0}\\right)^{1/T} - 1\\right) \\times 100',
    commentaire: 'Pour or, devises ou crypto — les actifs sans flux du module — le rendement se mesure en composé, jamais en moyenne arithmétique : 100 → 121 en 2 ans fait 10 % par an exactement, pas 10,5 % (ch. 5 et 7).',
    commentaireEn: 'For gold, currencies or crypto — the module\'s no-cash-flow assets — returns are measured compounded, never as an arithmetic average: 100 → 121 over 2 years is exactly 10% a year, not 10.5% (ch. 5 and 7).',
  },
  {
    id: 'm6-f-14',
    moduleId: M6,
    nom: 'Cours croisé',
    nomEn: 'Cross rate',
    latex: '\\text{EUR/GBP} = \\frac{\\text{EUR/USD}}{\\text{GBP/USD}}',
    commentaire: 'Une paire sans dollar se déduit des deux paires en dollar : EUR/USD 1,10 et GBP/USD 1,25 donnent EUR/GBP = 0,88. Les desks arbitrent en continu la cross cotée contre cette valeur implicite (ch. 1).',
    commentaireEn: 'A non-dollar pair derives from the two dollar pairs: EUR/USD 1.10 and GBP/USD 1.25 give EUR/GBP = 0.88. Desks continuously arbitrage the quoted cross against this implied value (ch. 1).',
  },
  {
    id: 'm6-f-15',
    moduleId: M6,
    nom: 'Variation en pips',
    nomEn: 'Move in pips',
    latex: '\\Delta_{\\text{pips}} = (S_1 - S_0) \\times 10\\,000',
    commentaire: 'Sur les paires cotées à 4 décimales, le pip est la 4ᵉ décimale (0,0001) : de 1,1000 à 1,1025, +25 pips. Exception : les paires en yen cotent à 2 décimales — le pip y vaut 0,01, et le facteur devient 100 (ch. 1).',
    commentaireEn: 'On pairs quoted to 4 decimals, the pip is the 4th decimal (0.0001): from 1.1000 to 1.1025, +25 pips. Exception: yen pairs quote to 2 decimals — the pip is 0.01 and the factor becomes 100 (ch. 1).',
  },
  {
    id: 'm6-f-16',
    moduleId: M6,
    nom: 'Décomposition du rendement d\'une position futures',
    nomEn: 'Futures position return decomposition',
    latex: '\\text{rendement total} \\approx \\text{spot return} + \\text{roll yield} + \\text{collateral yield}',
    commentaire: 'Trois briques additives : variation du spot, pente de la courbe payée ou encaissée au roll, intérêts du cash en garantie. Spot +5 %, roll −4,76 %, collatéral 3 % : ≈ +3,2 % — presque rien ne vient du pétrole lui-même (ch. 6).',
    commentaireEn: 'Three additive building blocks: the spot move, the curve slope paid or earned at the roll, the interest on the collateral cash. Spot +5%, roll −4.76%, collateral 3%: ≈ +3.2% — almost none of it comes from oil itself (ch. 6).',
  },
];
