import type { Flashcard } from '../../../engine/types';

const M1 = '01-panorama-marches';

// 120 cartes : 32 definitions, 12 formules, 16 ordres de grandeur, 22 pieges,
// 24 reflexes jury, 14 calculs mentaux.
// Couverture : ch1 fonctions des marches, ch2 acteurs, ch3 salle des marches,
// ch4 ordres & execution, ch5 microstructure, ch6 regulation, ch7 post-marche.
export const flashcards: Flashcard[] = [
  // ───────────────────────── Chapitre 1 — À quoi servent les marchés ─────────────────────────
  {
    id: 'm1-fc-001',
    moduleId: M1,
    tags: ['definition', 'fonctions-marches'],
    recto: 'Marché primaire vs marché secondaire : quelle différence ?',
    verso: 'Primaire : des titres neufs contre de l\'argent frais — le seul moment où l\'argent va à l\'émetteur (IPO, augmentation de capital, émission obligataire). Secondaire : les investisseurs s\'échangent des titres d\'occasion ; l\'émetteur n\'y voit pas passer un centime.',
    rectoEn: 'Primary vs secondary market: what is the difference?',
    versoEn: 'Primary: new securities against fresh money — the only moment cash actually reaches the issuer (IPO, capital increase, bond issue). Secondary: investors trade second-hand securities among themselves; the issuer never sees a cent.',
  },
  {
    id: 'm1-fc-002',
    moduleId: M1,
    tags: ['definition', 'fonctions-marches'],
    recto: 'Marché organisé vs gré à gré (OTC) : quelle différence ?',
    verso: 'La bourse centralise les ordres dans un carnet unique : prix publics, contrats standardisés, garantie d\'une chambre de compensation. L\'OTC : transactions bilatérales cotées à la demande par des dealers — sur-mesure, mais opaque et exposé à la solidité de chaque contrepartie.',
    rectoEn: 'Exchange-traded vs over-the-counter (OTC): what is the difference?',
    versoEn: 'An exchange centralises orders in a single book: public prices, standardised contracts, CCP guarantee. OTC: bilateral trades quoted on demand by dealers — bespoke, but opaque and reliant on each counterparty\'s solidity.',
  },
  {
    id: 'm1-fc-003',
    moduleId: M1,
    tags: ['piege', 'fonctions-marches'],
    recto: '« Le marché secondaire n\'apporte rien aux émetteurs : un casino qu\'on pourrait fermer. » Vrai ?',
    verso: 'Faux : on ne souscrit au primaire que ce qu\'on pourra revendre. La liquidité du secondaire abaisse le rendement exigé à l\'émission — 10 pb économisés sur ~2 800 Md€ de dette française ≈ 2,8 Md€ d\'intérêts par an. Le « casino » subventionne le primaire.',
    rectoEn: '"The secondary market brings issuers nothing: a casino we could shut down." True?',
    versoEn: 'False: investors only subscribe at the primary what they can resell. Secondary liquidity lowers the yield demanded at issuance — 10 bp saved on ~€2,800bn of French debt ≈ €2.8bn of interest a year. The "casino" subsidises the primary.',
  },
  {
    id: 'm1-fc-004',
    moduleId: M1,
    tags: ['reflexe-jury', 'fonctions-marches'],
    recto: 'Le jury : « À quoi servent les marchés financiers ? »',
    verso: 'Quatre fonctions : financer (primaire), rendre liquide (secondaire), découvrir les prix (agréger l\'information dispersée — l\'intuition de Hayek), transférer les risques (dérivés). Répondre « à spéculer » disqualifie ; réciter sans articuler ne vaut guère mieux.',
    rectoEn: 'The panel: "What are financial markets for?"',
    versoEn: 'Four functions: financing (primary), providing liquidity (secondary), price discovery (aggregating dispersed information — Hayek\'s insight), risk transfer (derivatives). Answering "to speculate" disqualifies; reciting without linking is hardly better.',
  },
  {
    id: 'm1-fc-005',
    moduleId: M1,
    tags: ['reflexe-jury', 'fonctions-marches'],
    recto: 'Le jury : « Le secondaire ne finance personne. Fermons-le ? »',
    verso: 'Sans revente possible, souscrire à 30 ans immobilise l\'épargne 30 ans : prime prohibitive ou refus. Le secondaire permet de sortir à tout moment, donc d\'accepter un rendement plus faible au primaire — sa liquidité est la condition d\'un primaire bon marché.',
    rectoEn: 'The panel: "The secondary market funds no one. Shall we close it?"',
    versoEn: 'With no resale, a 30-year subscription locks savings up for 30 years: prohibitive premium or refusal. The secondary lets investors exit at any time, hence accept a lower primary yield — its liquidity is the condition for cheap primary funding.',
  },
  {
    id: 'm1-fc-006',
    moduleId: M1,
    tags: ['reflexe-jury', 'fonctions-marches'],
    recto: 'Le jury : « Le trading ne sert à rien. » Votre réponse chiffrée ?',
    verso: 'Pour 1 € d\'argent frais levé, des centaines d\'euros tournent au secondaire — et ce brassage se paie en rendement : 10 pb économisés grâce à la profondeur, sur ~2 800 Md€ de dette française, ≈ 2,8 Md€ par an. Une subvention permanente au financement du primaire.',
    rectoEn: 'The panel: "Trading is useless." Your numbers-based reply?',
    versoEn: 'For every €1 of fresh money raised, hundreds of euros change hands on the secondary — and that churn is paid in yield: 10 bp saved thanks to depth, on ~€2,800bn of French debt, ≈ €2.8bn a year. A permanent subsidy to primary funding.',
  },
  {
    id: 'm1-fc-007',
    moduleId: M1,
    tags: ['formule', 'fonctions-marches'],
    recto: 'Que vaut 1 point de base d\'économie de rendement sur un encours de dette ? Formule et exemple.',
    verso: 'Économie annuelle = encours × pb / 10 000. Ex. du cours : 10 pb × 2 800 Md€ de dette française négociable = 2 800 × 0,001 = 2,8 Md€ d\'intérêts économisés chaque année grâce à la profondeur du secondaire.',
    rectoEn: 'What is 1 basis point of yield savings worth on a debt stock? Formula and example.',
    versoEn: 'Annual saving = outstanding × bp / 10,000. Course example: 10 bp × €2,800bn of tradable French debt = 2,800 × 0.001 = €2.8bn of interest saved every year thanks to secondary-market depth.',
  },
  {
    id: 'm1-fc-008',
    moduleId: M1,
    tags: ['calcul-mental', 'fonctions-marches'],
    recto: 'De tête : 1 pb sur 2 800 Md€ de dette ?',
    verso: '1 pb = 0,01 % = 10⁻⁴. 2 800 Md€ × 10⁻⁴ = 280 M€ par an. Routine : 1 pb sur 1 Md€ = 100 k€, puis multiplier. Chaque point de base sur la dette française se compte en centaines de millions.',
    rectoEn: 'In your head: 1 bp on €2,800bn of debt?',
    versoEn: '1 bp = 0.01% = 10⁻⁴. €2,800bn × 10⁻⁴ = €280m a year. Routine: 1 bp on €1bn = €100k, then scale up. Every basis point on French debt counts in hundreds of millions.',
  },
  {
    id: 'm1-fc-009',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'fonctions-marches'],
    recto: 'Volume quotidien du marché des changes ?',
    verso: '≈ 7 500 Md$ par jour (enquête triennale BRI 2022) ; l\'enquête 2025 pointe vers ≈ 9 600 Md$. De très loin le plus grand marché du monde en volume — il « tourne » l\'équivalent du stock obligataire mondial en une vingtaine de jours.',
    rectoEn: 'Daily volume of the FX market?',
    versoEn: '≈ $7,500bn a day (BIS 2022 triennial survey); the 2025 survey points to ≈ $9,600bn. By far the world\'s largest market by volume — it "turns over" the equivalent of the global bond stock in about twenty days.',
  },
  {
    id: 'm1-fc-010',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'fonctions-marches'],
    recto: 'Capitalisation boursière mondiale des actions ?',
    verso: '≈ 120 à 130 000 Md$ début 2026 — un STOCK, à connaître à 20 % près. Le jury ne demande pas la décimale : il vérifie que vous savez si la réponse se compte en milliers ou en centaines de milliers de milliards.',
    rectoEn: 'Global equity market capitalisation?',
    versoEn: '≈ $120–130 trillion in early 2026 — a STOCK, to be known within 20%. The panel does not ask for decimals: it checks whether you know if the answer counts in thousands or hundreds of thousands of billions.',
  },
  {
    id: 'm1-fc-011',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'fonctions-marches'],
    recto: 'Encours du marché obligataire mondial ?',
    verso: '≈ 140 000 Md$ d\'encours, dont de l\'ordre de la moitié de dette publique — l\'autre versant étant le crédit (entreprises, banques). Légèrement supérieur à la capitalisation actions mondiale (≈ 120-130 000 Md$).',
    rectoEn: 'Outstanding size of the global bond market?',
    versoEn: '≈ $140 trillion outstanding, roughly half of it government debt — the other side being credit (corporates, banks). Slightly larger than global equity capitalisation (≈ $120–130tn).',
  },
  {
    id: 'm1-fc-012',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'fonctions-marches'],
    recto: 'Dérivés de gré à gré : notionnel vs valeur de marché brute ?',
    verso: 'Notionnel > 600 000 Md$ (BRI) — mais valeur de marché brute ≈ 15 à 20 000 Md$, trente à quarante fois moins ; et exposition nette après compensation : quelques milliers de Md$. Devant tout chiffre sur les dérivés, demander duquel il s\'agit.',
    rectoEn: 'OTC derivatives: notional vs gross market value?',
    versoEn: 'Notional > $600 trillion (BIS) — but gross market value ≈ $15–20tn, thirty to forty times less; and net credit exposure after netting: a few trillion. Faced with any derivatives figure, ask which one is being quoted.',
  },
  {
    id: 'm1-fc-013',
    moduleId: M1,
    tags: ['piege', 'fonctions-marches'],
    recto: '600 000 Md$ de dérivés = 600 000 Md$ de risque ?',
    verso: 'Non : le notionnel est une assiette de calcul, pas une somme en jeu. Dans un swap de 100 M€ de notionnel, on n\'échange jamais les 100 M€ — seulement des flux d\'intérêts nets calculés dessus. Le risque se lit dans la valeur de marché (15-20 000 Md$) et l\'exposition nette.',
    rectoEn: '$600tn of derivatives = $600tn of risk?',
    versoEn: 'No: notional is a calculation base, not money at stake. In a €100m notional swap, the €100m never changes hands — only net interest flows computed on it. Risk shows in gross market value ($15–20tn) and net exposure.',
  },
  {
    id: 'm1-fc-014',
    moduleId: M1,
    tags: ['piege', 'fonctions-marches'],
    recto: 'Le change traite 7 500 Md$/jour, les actions « pèsent » 120-130 000 Md$ : le FX est-il ~15 fois plus petit ?',
    verso: 'Non : on compare un FLUX quotidien à un STOCK de capitalisation — un débit à un réservoir. En volume d\'échanges, le change est le plus grand marché du monde. Réflexe : identifier la nature du chiffre (encours, volume, notionnel) avant de comparer.',
    rectoEn: 'FX trades $7.5tn/day, equities "weigh" $120–130tn: is FX ~15 times smaller?',
    versoEn: 'No: that compares a daily FLOW with a STOCK of capitalisation — a flow rate with a reservoir. By trading volume, FX is the world\'s largest market. Reflex: identify the figure\'s nature (stock, volume, notional) before comparing.',
  },
  {
    id: 'm1-fc-015',
    moduleId: M1,
    tags: ['calcul-mental', 'fonctions-marches'],
    recto: 'De tête : flux annuel net d\'un swap de taux de 100 M€ de notionnel, différentiel de taux 0,5 % ?',
    verso: '100 M€ × 0,5 % = 500 000 € par an — quelques centaines de milliers d\'euros, jamais les 100 M€. Tout l\'écart entre notionnel (assiette) et argent réellement échangé : un facteur 200 ici.',
    rectoEn: 'In your head: annual net flow of a €100m notional interest rate swap, 0.5% rate differential?',
    versoEn: '€100m × 0.5% = €500,000 a year — a few hundred thousand euros, never the €100m. The whole gap between notional (a base) and money actually exchanged: a factor of 200 here.',
  },
  {
    id: 'm1-fc-016',
    moduleId: M1,
    tags: ['calcul-mental', 'fonctions-marches'],
    recto: 'De tête : en combien de jours le FX « tourne »-t-il l\'équivalent du stock obligataire mondial ?',
    verso: '140 000 / 7 500 ≈ 19 — une vingtaine de jours. Le calcul mental qui fixe les ordres de grandeur : le change brasse en un mois ce que le marché obligataire a mis des décennies à émettre.',
    rectoEn: 'In your head: in how many days does FX "turn over" the equivalent of the global bond stock?',
    versoEn: '140,000 / 7,500 ≈ 19 — about twenty days. The mental shortcut that anchors the orders of magnitude: FX churns in a month what the bond market took decades to issue.',
  },
  {
    id: 'm1-fc-017',
    moduleId: M1,
    tags: ['piege', 'fonctions-marches'],
    recto: 'L\'intuition place tous les marchés en bourse. Où vivent réellement le change et les obligations ?',
    verso: 'En gré à gré : le plus grand marché du monde (FX) n\'a pas de bourse centrale, et une obligation s\'achète en mettant des dealers en concurrence. En bourse : actions et dérivés listés seulement. Raisons structurelles : souches multiples, blocs énormes, sur-mesure.',
    rectoEn: 'Intuition puts every market on an exchange. Where do FX and bonds actually live?',
    versoEn: 'Over the counter: the world\'s largest market (FX) has no central exchange, and bonds are bought by putting dealers in competition. On-exchange: only equities and listed derivatives. Structural reasons: multiple bond lines, huge blocks, bespoke needs.',
  },
  {
    id: 'm1-fc-018',
    moduleId: M1,
    tags: ['reflexe-jury', 'fonctions-marches'],
    recto: 'Le jury : « 600 000 Md$ de dérivés, six à sept fois le PIB mondial. Votre réaction ? »',
    verso: 'Réflexe : demander de quel chiffre on parle. Le notionnel est une assiette, pas un risque ; la valeur de marché brute est de 15-20 000 Md$ (BRI), l\'exposition nette après compensation bien moindre encore. Dérouler les trois niveaux classe immédiatement.',
    rectoEn: 'The panel: "$600tn of derivatives, six to seven times world GDP. Your reaction?"',
    versoEn: 'Reflex: ask which figure we are talking about. Notional is a base, not a risk; gross market value is $15–20tn (BIS), net exposure after netting smaller still. Walking through the three levels marks you out immediately.',
  },
  {
    id: 'm1-fc-019',
    moduleId: M1,
    tags: ['piege', 'fonctions-marches'],
    recto: 'La liquidité des marchés est-elle un acquis permanent ?',
    verso: 'Non, elle est procyclique : abondante quand personne n\'en a besoin, évaporée quand tout le monde veut vendre. 2008 : des pans du crédit cessent de coter ; mars 2020 : même les Treasuries dysfonctionnent quelques jours. Des modes de défaillance connus et récurrents.',
    rectoEn: 'Is market liquidity a permanent given?',
    versoEn: 'No, it is procyclical: plentiful when nobody needs it, gone when everyone wants to sell. 2008: parts of the credit market stopped quoting; March 2020: even US Treasuries malfunctioned for days. Known, recurring failure modes.',
  },
  // ───────────────────────── Chapitre 2 — La carte des acteurs ─────────────────────────
  {
    id: 'm1-fc-020',
    moduleId: M1,
    tags: ['definition', 'acteurs'],
    recto: 'Sell-side vs buy-side : qui est qui ?',
    verso: 'Le sell-side VEND les services de marché : banques d\'investissement et courtiers (Goldman Sachs, BNP Paribas) — accès au primaire, liquidité, recherche, structuration. Le buy-side gère l\'argent des autres et ACHÈTE ces services : gérants, hedge funds, assureurs, fonds souverains.',
    rectoEn: 'Sell side vs buy side: who is who?',
    versoEn: 'The sell side SELLS market services: investment banks and brokers (Goldman Sachs, BNP Paribas) — primary access, liquidity, research, structuring. The buy side manages other people\'s money and BUYS those services: asset managers, hedge funds, insurers, sovereign funds.',
  },
  {
    id: 'm1-fc-021',
    moduleId: M1,
    tags: ['definition', 'acteurs'],
    recto: 'Un gérant d\'actifs (asset manager), c\'est quoi ?',
    verso: 'Il gère l\'épargne pour compte de tiers via fonds et mandats, rémunéré en % des encours : 0,05-0,3 % en indiciel/ETF, 1-2 % en gestion active grand public. BlackRock ≈ 11 500 Md$ fin 2024, Vanguard ≈ 10 000 Md$, Amundi (1er européen) ≈ 2 200 Md€.',
    rectoEn: 'What is an asset manager?',
    versoEn: 'It manages savings on behalf of clients via funds and mandates, paid as a % of assets: 0.05–0.3% for index/ETF, 1–2% for retail active management. BlackRock ≈ $11.5tn end-2024, Vanguard ≈ $10tn, Amundi (Europe\'s #1) ≈ €2.2tn.',
  },
  {
    id: 'm1-fc-022',
    moduleId: M1,
    tags: ['definition', 'acteurs'],
    recto: 'Un hedge fund, c\'est quoi ?',
    verso: 'Fonds de gestion alternative réservé aux investisseurs avertis : levier, vente à découvert et dérivés autorisés. Quatre familles : long/short equity, global macro, event driven, relative value. ≈ 4 500-5 000 Md$ d\'encours — modestes, mais démultipliés par le levier.',
    rectoEn: 'What is a hedge fund?',
    versoEn: 'An alternative fund reserved for sophisticated investors: leverage, short selling and derivatives allowed. Four families: long/short equity, global macro, event driven, relative value. ≈ $4.5–5tn under management — modest, but amplified by leverage.',
  },
  {
    id: 'm1-fc-023',
    moduleId: M1,
    tags: ['definition', 'acteurs'],
    recto: 'Un fonds souverain, c\'est quoi ?',
    verso: 'Un fonds qui place les excédents d\'un État — rente pétrolière ou excédents commerciaux. Norvège : ≈ 1 700-1 800 Md$ fin 2024, premier mondial ; suivent ADIA (Abou Dabi), GIC et Temasek (Singapour), CIC (Chine). Catégorie ≈ 13 000 Md$ : du très long terme.',
    rectoEn: 'What is a sovereign wealth fund?',
    versoEn: 'A fund investing a state\'s surpluses — oil rent or trade surpluses. Norway: ≈ $1.7–1.8tn end-2024, world #1; then ADIA (Abu Dhabi), GIC and Temasek (Singapore), CIC (China). The category nears $13tn: very long-term money.',
  },
  {
    id: 'm1-fc-024',
    moduleId: M1,
    tags: ['piege', 'acteurs'],
    recto: '« BlackRock, plus de 11 000 Md$ : la plus grande banque du monde. » Où est l\'erreur ?',
    verso: 'Ces encours appartiennent aux CLIENTS : fonds juridiquement séparés, conservés chez des dépositaires indépendants. BlackRock encaisse des frais ; une banque porte dépôts et crédits à SON bilan. La vraie question : la concentration du pouvoir actionnarial des Big Three.',
    rectoEn: '"BlackRock, over $11tn: the world\'s biggest bank." Where is the mistake?',
    versoEn: 'Those assets belong to CLIENTS: legally separate funds, held with independent custodians. BlackRock earns fees; a bank carries deposits and loans on ITS own balance sheet. The real issue: the Big Three\'s concentration of shareholder power.',
  },
  {
    id: 'm1-fc-025',
    moduleId: M1,
    tags: ['reflexe-jury', 'acteurs'],
    recto: 'Le jury : « BlackRock gère 11 500 Md$. Peut-il faire faillite sur ces positions ? »',
    verso: 'Non au sens bancaire : gains et pertes reviennent aux clients, le bilan propre de BlackRock est minuscule face aux encours. Réflexe : distinguer gérer (compte de tiers) et porter (bilan propre) — puis pivoter sur le vrai débat, le pouvoir actionnarial concentré.',
    rectoEn: 'The panel: "BlackRock manages $11.5tn. Can it go bankrupt on those positions?"',
    versoEn: 'Not in the banking sense: gains and losses accrue to the clients, and BlackRock\'s own balance sheet is tiny next to its AUM. Reflex: distinguish managing (third-party money) from carrying (own balance sheet) — then pivot to the real debate, concentrated shareholder power.',
  },
  {
    id: 'm1-fc-026',
    moduleId: M1,
    tags: ['reflexe-jury', 'acteurs'],
    recto: 'Le jury : « Classez en une seconde : Amundi, LCH, Goldman Sachs, l\'ESMA. »',
    verso: 'Amundi : buy-side (1er gérant européen, ≈ 2 200 Md€). Goldman Sachs : sell-side. LCH : infrastructure — chambre de compensation. ESMA : régulateur européen des marchés. L\'exercice attendu : placer n\'importe quel nom dans la bonne case, ordre de grandeur à l\'appui.',
    rectoEn: 'The panel: "Classify in one second: Amundi, LCH, Goldman Sachs, ESMA."',
    versoEn: 'Amundi: buy side (Europe\'s #1 manager, ≈ €2.2tn). Goldman Sachs: sell side. LCH: infrastructure — a clearing house. ESMA: the EU markets regulator. The expected drill: put any name in the right box, with an order of magnitude attached.',
  },
  {
    id: 'm1-fc-027',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'acteurs'],
    recto: 'Encours gérés par BlackRock ?',
    verso: '≈ 11 500 Md$ fin 2024 — numéro un mondial, l\'équivalent de près de quatre PIB français — en croissance depuis. Vanguard suit autour de 10 000 Md$ ; le premier européen, Amundi, gère de l\'ordre de 2 200 Md€.',
    rectoEn: 'Assets under management at BlackRock?',
    versoEn: '≈ $11.5tn at end-2024 — world number one, nearly four French GDPs — and growing since. Vanguard follows around $10tn; Europe\'s largest, Amundi, manages about €2.2tn.',
  },
  {
    id: 'm1-fc-028',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'acteurs'],
    recto: 'Encours de l\'industrie des hedge funds ?',
    verso: '≈ 4 500 à 5 000 Md$ pour l\'ensemble de l\'industrie — moins de la moitié de BlackRock seul. Mais levier et vitesse de rotation démultiplient leur empreinte sur les prix : ne pas juger l\'influence aux seuls encours.',
    rectoEn: 'Assets of the hedge fund industry?',
    versoEn: '≈ $4.5–5tn for the whole industry — less than half of BlackRock alone. But leverage and turnover speed multiply their footprint on prices: do not judge influence by AUM alone.',
  },
  {
    id: 'm1-fc-029',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'acteurs'],
    recto: 'Taille du fonds souverain norvégien ?',
    verso: '≈ 1 700 à 1 800 Md$ fin 2024, premier fonds souverain mondial — environ 350 000 $ par Norvégien courant 2025. Alimenté par la rente pétrolière, investi en actions et obligations mondiales.',
    rectoEn: 'Size of Norway\'s sovereign wealth fund?',
    versoEn: '≈ $1.7–1.8tn at end-2024, the world\'s largest sovereign fund — about $350,000 per Norwegian as of 2025. Funded by oil revenue, invested in global equities and bonds.',
  },
  {
    id: 'm1-fc-030',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'acteurs'],
    recto: 'Prix d\'un terminal Bloomberg ?',
    verso: '≈ 30 000 $ par an et par poste, pour ≈ 350 000 abonnés — soit ≈ 10 Md$ de revenus annuels. Sa messagerie est le vrai réseau social des salles, où se négocie une bonne partie du gré à gré. Grand concurrent : LSEG (ex-Refinitiv).',
    rectoEn: 'Price of a Bloomberg terminal?',
    versoEn: '≈ $30,000 per year per seat, for ≈ 350,000 subscribers — i.e. ≈ $10bn of annual revenue. Its messaging system is the trading floors\' true social network, where much of the OTC market is negotiated. Main rival: LSEG (ex-Refinitiv).',
  },
  {
    id: 'm1-fc-031',
    moduleId: M1,
    tags: ['calcul-mental', 'acteurs'],
    recto: 'De tête : 30 000 $/an × 350 000 abonnés Bloomberg ?',
    verso: '3 × 3,5 = 10,5 → ≈ 10,5 Md$ par an. Technique : 3 × 10⁴ × 3,5 × 10⁵ = 10,5 × 10⁹. L\'ordre de grandeur des revenus du terminal — la donnée de marché est un péage, pas un accessoire.',
    rectoEn: 'In your head: $30,000/yr × 350,000 Bloomberg subscribers?',
    versoEn: '3 × 3.5 = 10.5 → ≈ $10.5bn a year. Technique: 3 × 10⁴ × 3.5 × 10⁵ = 10.5 × 10⁹. The order of magnitude of terminal revenue — market data is a toll booth, not an accessory.',
  },
  {
    id: 'm1-fc-032',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'acteurs'],
    recto: 'Le « 2/20 » des hedge funds : niveau réel aujourd\'hui ?',
    verso: 'La formule historique — 2 % de frais de gestion + 20 % de la performance — s\'érode : la moyenne de l\'industrie est plus près de 1,4 % et 16 %, sous la double pression des institutionnels et de la gestion passive à ≈ 0,1 %.',
    rectoEn: 'Hedge funds\' "2 and 20": actual level today?',
    versoEn: 'The historic formula — 2% management fee + 20% of performance — is eroding: the industry average sits closer to 1.4% and 16%, under twin pressure from institutional investors and passive management at ≈ 0.1%.',
  },
  {
    id: 'm1-fc-033',
    moduleId: M1,
    tags: ['reflexe-jury', 'acteurs'],
    recto: 'Le jury : « Pourquoi payer un hedge fund 2/20 quand un ETF coûte 0,1 % ? »',
    verso: 'Un fonds vingt fois plus cher doit prouver qu\'il délivre ce que l\'indice n\'offre pas : décorrélation, stratégies inaccessibles (levier, vente à découvert, relative value). D\'où l\'érosion vers 1,4/16 — et le renvoi au débat d\'efficience : l\'alpha persistant est rare.',
    rectoEn: 'The panel: "Why pay a hedge fund 2 and 20 when an ETF costs 0.1%?"',
    versoEn: 'A fund twenty times more expensive must prove it delivers what the index cannot: decorrelation, inaccessible strategies (leverage, shorting, relative value). Hence the erosion towards 1.4/16 — and the efficiency debate: persistent alpha is rare.',
  },
  {
    id: 'm1-fc-034',
    moduleId: M1,
    tags: ['calcul-mental', 'acteurs'],
    recto: 'De tête : frais 2/20 sur un fonds qui fait +10 % brut ?',
    verso: '2 % de gestion + 20 % × 10 % = 2 % de performance → 4 % de frais au total : l\'investisseur garde 6 %, le gérant prend 4 — soit 40 % du gain brut. Le 2/20 ne choque que rapporté au rendement, pas aux encours.',
    rectoEn: 'In your head: 2 and 20 fees on a fund returning +10% gross?',
    versoEn: '2% management + 20% × 10% = 2% performance → 4% total fees: the investor keeps 6%, the manager takes 4 — i.e. 40% of the gross gain. 2/20 only shocks once compared to the return, not to assets.',
  },
  {
    id: 'm1-fc-035',
    moduleId: M1,
    tags: ['formule', 'acteurs'],
    recto: 'Frais annuels f prélevés pendant n années : quelle ponction sur le capital final ? Formule et exemple.',
    verso: 'Le capital final est divisé par (1+f)ⁿ. Ex. : f = 1 % sur 30 ans → 1,01³⁰ ≈ 1,35 → on abandonne ≈ 26 % du capital final (1 − 1/1,35 ≈ 0,26). Les frais composent exactement comme les intérêts — contre vous.',
    rectoEn: 'Annual fees f charged for n years: what bite out of final capital? Formula and example.',
    versoEn: 'Final capital is divided by (1+f)ⁿ. E.g.: f = 1% over 30 years → 1.01³⁰ ≈ 1.35 → you give up ≈ 26% of final capital (1 − 1/1.35 ≈ 0.26). Fees compound exactly like interest — against you.',
  },
  {
    id: 'm1-fc-036',
    moduleId: M1,
    tags: ['calcul-mental', 'acteurs'],
    recto: 'De tête : 1 % de frais par an pendant 30 ans, ça coûte quoi ?',
    verso: '≈ 26 % du capital final : 1,01³⁰ ≈ 1,35 et 1 − 1/1,35 ≈ 0,26. Routine : petits taux sur longues durées → composer, jamais additionner (30 × 1 % = 30 % est faux, et l\'erreur grossit avec la durée).',
    rectoEn: 'In your head: 1% annual fees for 30 years — what does it cost?',
    versoEn: '≈ 26% of final capital: 1.01³⁰ ≈ 1.35 and 1 − 1/1.35 ≈ 0.26. Routine: small rates over long horizons → compound, never add (30 × 1% = 30% is wrong, and the error grows with the horizon).',
  },
  {
    id: 'm1-fc-037',
    moduleId: M1,
    tags: ['formule', 'acteurs'],
    recto: 'Coût annuel de la gestion : formule, et exemple sur 1 M€ ?',
    verso: 'Coût = encours × taux de frais, chaque année. Ex. du cours : 1 M€ en fonds institutionnel à 0,3 % → 3 000 €/an ; en fonds actif grand public à 1,5 % → 15 000 €/an. À comparer aux ≈ 800 € du coût d\'exécution, payés une seule fois.',
    rectoEn: 'Annual cost of management: formula, and example on €1m?',
    versoEn: 'Cost = assets × fee rate, every single year. Course example: €1m in an institutional fund at 0.3% → €3,000/yr; in a retail active fund at 1.5% → €15,000/yr. Compare with the ≈ €800 execution cost, paid once.',
  },
  {
    id: 'm1-fc-038',
    moduleId: M1,
    tags: ['formule', 'acteurs'],
    recto: 'Autopsie du coût d\'exécution d\'un ordre institutionnel de 1 M€ : les trois étages et le total ?',
    verso: 'Courtage ≈ 5 pb (500 €) + demi-spread ≈ 2 pb (200 €) + bourse/compensation/règlement ≈ 1 pb (100 €) = ≈ 8 pb, soit 800 €. L\'exécution est une industrie de volume à marges fines — la valeur se capte à l\'étage de la gestion.',
    rectoEn: 'Cost autopsy of a €1m institutional order: the three layers and the total?',
    versoEn: 'Brokerage ≈ 5 bp (€500) + half-spread ≈ 2 bp (€200) + exchange/clearing/settlement ≈ 1 bp (€100) = ≈ 8 bp, i.e. €800. Execution is a thin-margin volume industry — value is captured at the management layer.',
  },
  {
    id: 'm1-fc-039',
    moduleId: M1,
    tags: ['calcul-mental', 'acteurs'],
    recto: 'De tête : que valent 5 pb sur 1 M€ ? Et 8 pb ?',
    verso: '1 pb sur 1 M€ = 100 €. Donc 5 pb = 500 €, 8 pb = 800 €. La conversion à connaître par cœur : pb × 100 € par million — elle chiffre instantanément commissions et coûts d\'exécution.',
    rectoEn: 'In your head: what are 5 bp on €1m? And 8 bp?',
    versoEn: '1 bp on €1m = €100. So 5 bp = €500, 8 bp = €800. The conversion to know cold: bp × €100 per million — it instantly prices commissions and execution costs.',
  },
  // ───────────────────────── Chapitre 3 — Dans une salle des marchés ─────────────────────────
  {
    id: 'm1-fc-040',
    moduleId: M1,
    tags: ['definition', 'salle-marches'],
    recto: 'La muraille de Chine (Chinese wall), c\'est quoi ?',
    verso: 'Barrière d\'information interne séparant les équipes détenant de l\'information privilégiée (M&A, parfois la recherche) des équipes de marché : étages séparés, accès cloisonnés, listes de surveillance, wall-crossing formalisé. La franchir, c\'est s\'exposer au délit d\'initié.',
    rectoEn: 'What is the Chinese wall?',
    versoEn: 'An internal information barrier separating teams holding inside information (M&A, sometimes research) from market-facing teams: separate floors, segregated IT access, watch lists, formalised wall-crossing. Breaching it means exposure to insider dealing.',
  },
  {
    id: 'm1-fc-041',
    moduleId: M1,
    tags: ['piege', 'salle-marches'],
    recto: '« Le trader est un parieur professionnel. » Pourquoi ce contresens est-il si pénalisant ?',
    verso: '≈ 90 % du flux d\'un desk bancaire est du flux client et de la couverture : coter, exécuter, neutraliser le risque absorbé. Le revenu vient de la fourchette × le volume, pas de la direction du marché. La bonne réponse parle de cotation, d\'inventaire et de service au client.',
    rectoEn: '"A trader is a professional gambler." Why is this misconception so damaging?',
    versoEn: '≈ 90% of a bank desk\'s flow is client flow and hedging: quote, execute, neutralise the absorbed risk. Revenue comes from the spread × volume, not from market direction. The right answer talks about quoting, inventory and client service.',
  },
  {
    id: 'm1-fc-042',
    moduleId: M1,
    tags: ['piege', 'salle-marches'],
    recto: 'Le prop trading a quasiment disparu des banques. Parce qu\'il n\'était plus rentable ?',
    verso: 'Non : la réglementation post-2008 (règle Volcker dans le Dodd-Frank Act, équivalents européens) a interdit ou rendu prohibitif le compte propre des banques de dépôt. L\'activité — et les équipes — ont migré vers hedge funds et firmes de trading indépendantes.',
    rectoEn: 'Prop trading has all but vanished from banks. Because it stopped being profitable?',
    versoEn: 'No: post-2008 regulation (the Volcker rule in the Dodd-Frank Act, European equivalents) banned or priced out proprietary trading at deposit-taking banks. The activity — and the teams — migrated to hedge funds and independent trading firms.',
  },
  {
    id: 'm1-fc-043',
    moduleId: M1,
    tags: ['reflexe-jury', 'salle-marches'],
    recto: 'Le jury : « Décrivez-moi une salle des marchés. »',
    verso: 'Trois lignes de défense : front office (traders, sales, structureurs, quants — face au marché, génère le revenu), middle office (P&L indépendant, limites de risque), back office (règlement-livraison, réconciliations). Citer l\'affaire Kerviel : un middle office non écouté.',
    rectoEn: 'The panel: "Describe a trading floor to me."',
    versoEn: 'Three lines of defence: front office (traders, sales, structurers, quants — facing the market, generating revenue), middle office (independent P&L, risk limits), back office (settlement, reconciliations). Mention the Kerviel affair: a middle office that went unheeded.',
  },
  {
    id: 'm1-fc-044',
    moduleId: M1,
    tags: ['reflexe-jury', 'salle-marches'],
    recto: '« J\'aime le trading parce que j\'aime le risque. » Pourquoi cette phrase élimine-t-elle ?',
    verso: 'Parce qu\'elle décrit un parieur, pas un teneur de marché : le desk vit de la fourchette et du volume sur ≈ 90 % de flux client, en neutralisant le risque absorbé. Réponse attendue : cotation, gestion d\'inventaire, service au client — pas l\'adrénaline.',
    rectoEn: '"I love trading because I love risk." Why does this line get you eliminated?',
    versoEn: 'Because it describes a gambler, not a market maker: a desk lives off the spread and volume on ≈ 90% client flow, neutralising the risk it absorbs. Expected answer: quoting, inventory management, client service — not adrenaline.',
  },
  {
    id: 'm1-fc-045',
    moduleId: M1,
    tags: ['reflexe-jury', 'salle-marches'],
    recto: 'Le jury : « Un client veut un prix sur 50 M€ d\'obligations. Qui cote, qui gère la relation ? »',
    verso: 'Le trader cote — seul à pouvoir engager le bilan de la banque — puis porte et couvre la position. Le sales tient la relation : il connaît le client, transmet la demande, diffuse les « axes » du desk. Le middle office contrôle a posteriori, ne cote jamais.',
    rectoEn: 'The panel: "A client wants a price on €50m of bonds. Who quotes, who owns the relationship?"',
    versoEn: 'The trader quotes — the only one who can commit the bank\'s balance sheet — then carries and hedges the position. The sales owns the relationship: knows the client, relays the request, broadcasts the desk\'s axes. The middle office checks after the fact, never quotes.',
  },
  {
    id: 'm1-fc-046',
    moduleId: M1,
    tags: ['reflexe-jury', 'salle-marches'],
    recto: 'Le jury : « Front, middle, back office : qui fait quoi ? »',
    verso: 'Front : face au marché et aux clients, génère le revenu (traders, sales, structureurs, quants). Middle : valide le P&L en indépendant, surveille limites et conformité. Back : règlement-livraison, réconciliations, référentiels. Trois lignes de défense successives.',
    rectoEn: 'The panel: "Front, middle, back office: who does what?"',
    versoEn: 'Front: faces the market and clients, generates revenue (traders, sales, structurers, quants). Middle: validates P&L independently, polices limits and compliance. Back: settlement, reconciliations, reference data. Three successive lines of defence.',
  },
  {
    id: 'm1-fc-047',
    moduleId: M1,
    tags: ['calcul-mental', 'salle-marches'],
    recto: 'Recruteur, sans stylo : « 17 × 24 ? »',
    verso: '408. Voie rapide : 17 × 25 = 425, moins 17 = 408. Ou (20 − 3) × 24 = 480 − 72. Le test ne mesure pas l\'arithmétique mais le calme sous pression — toujours annoncer une méthode, jamais un silence.',
    rectoEn: 'Recruiter, no pen: "17 × 24?"',
    versoEn: '408. Fast route: 17 × 25 = 425, minus 17 = 408. Or (20 − 3) × 24 = 480 − 72. The test is not about arithmetic but composure under pressure — always state a method, never go silent.',
  },
  // ───────────────────────── Chapitre 4 — Les ordres et leur exécution ─────────────────────────
  {
    id: 'm1-fc-048',
    moduleId: M1,
    tags: ['definition', 'ordres-execution'],
    recto: 'Le carnet d\'ordres, c\'est quoi ?',
    verso: 'Le registre central qui rassemble tous les ordres à cours limité en attente : bids (achats, du plus haut au plus bas) face aux asks (ventes, du plus bas au plus haut). Règle unique : la priorité prix-temps — meilleur prix d\'abord, puis premier arrivé, premier servi.',
    rectoEn: 'What is the order book?',
    versoEn: 'The central register of all resting limit orders: bids (buys, highest to lowest) facing asks (sells, lowest to highest). One rule: price-time priority — best price first, then first come, first served.',
  },
  {
    id: 'm1-fc-049',
    moduleId: M1,
    tags: ['definition', 'ordres-execution'],
    recto: 'Le bid-ask spread, c\'est quoi ?',
    verso: 'L\'écart entre meilleur prix acheteur et meilleur prix vendeur ; leur moyenne est le milieu de fourchette, meilleure estimation instantanée de la valeur. Lecture économique : le prix de l\'immédiateté — l\'aller-retour instantané coûte exactement le spread.',
    rectoEn: 'What is the bid-ask spread?',
    versoEn: 'The gap between the best buying and best selling price; their average is the mid, the best instant estimate of value. Economic reading: the price of immediacy — an instant round trip costs exactly the spread.',
  },
  {
    id: 'm1-fc-050',
    moduleId: M1,
    tags: ['formule', 'ordres-execution'],
    recto: 'Formule du spread en points de base, et l\'exemple du cours ?',
    verso: 'spread (pb) = (ask − bid) / milieu × 10 000. Ex. : 99,95 / 100,05 → spread 0,10 €, milieu 100,00 → 10 pb : titre très liquide. Une petite valeur peut coter 50-100 pb : l\'immédiateté y est dix fois plus chère.',
    rectoEn: 'Spread in basis points: formula and the course example?',
    versoEn: 'spread (bp) = (ask − bid) / mid × 10,000. E.g.: 99.95 / 100.05 → spread €0.10, mid 100.00 → 10 bp: a very liquid stock. A small cap can quote 50–100 bp: immediacy there is ten times dearer.',
  },
  {
    id: 'm1-fc-051',
    moduleId: M1,
    tags: ['calcul-mental', 'ordres-execution'],
    recto: 'De tête : fourchette 99,95 / 100,05 — spread en pb ? Et la règle générale autour de 100 ?',
    verso: '0,10 / 100 × 10 000 = 10 pb. Règle : sur un titre cotant vers 100, un centime de fourchette = un point de base. Conversion instantanée à dégainer en entretien.',
    rectoEn: 'In your head: 99.95 / 100.05 quote — spread in bp? And the general rule around 100?',
    versoEn: '0.10 / 100 × 10,000 = 10 bp. Rule: on a stock trading near 100, one cent of spread = one basis point. An instant conversion to fire off in interviews.',
  },
  {
    id: 'm1-fc-052',
    moduleId: M1,
    tags: ['definition', 'ordres-execution'],
    recto: 'Ordre au marché vs ordre à cours limité : quel arbitrage ?',
    verso: 'Au marché : « exécutez maintenant, au mieux du carnet » — exécution quasi certaine, prix incertain. Limite : « achetez à 99,93 € ou moins » — prix garanti, exécution incertaine. Aucun ordre n\'offre les deux garanties à la fois.',
    rectoEn: 'Market order vs limit order: what trade-off?',
    versoEn: 'Market: "execute now, at whatever the book holds" — near-certain execution, uncertain price. Limit: "buy at €99.93 or better" — guaranteed price, uncertain execution. No order offers both guarantees at once.',
  },
  {
    id: 'm1-fc-053',
    moduleId: M1,
    tags: ['definition', 'ordres-execution'],
    recto: 'L\'ordre stop et le stop-limite : comment fonctionnent-ils ?',
    verso: 'Le stop dort jusqu\'au seuil, puis se réveille en ordre AU MARCHÉ — usage : couper une perte (« si ça casse 95 €, vendez »). Le stop-limite se réveille en ordre limité : prix de sortie borné, au risque de ne pas sortir du tout.',
    rectoEn: 'Stop and stop-limit orders: how do they work?',
    versoEn: 'A stop sleeps until the trigger, then wakes up as a MARKET order — use: cutting a loss ("if it breaks €95, sell"). A stop-limit wakes as a limit order: exit price capped, at the risk of not exiting at all.',
  },
  {
    id: 'm1-fc-054',
    moduleId: M1,
    tags: ['piege', 'ordres-execution'],
    recto: 'Un stop de vente à 95 € garantit-il une sortie à 95 € ?',
    verso: 'Non — AUCUN prix n\'est garanti : déclenché, il devient ordre au marché. Si le titre ouvre en gap à 88 € (jamais coté entre 95 et 88), le stop vend vers 88 €. Octobre 1987 : des stops servis des dizaines de % sous leurs seuils. Le stop borne la décision, jamais le prix.',
    rectoEn: 'Does a sell stop at €95 guarantee an exit at €95?',
    versoEn: 'No — NO price is guaranteed: once triggered, it becomes a market order. If the stock gaps open at €88 (never trading between 95 and 88), the stop sells near €88. October 1987: stops filled tens of % below their triggers. A stop bounds the decision, never the price.',
  },
  {
    id: 'm1-fc-055',
    moduleId: M1,
    tags: ['reflexe-jury', 'ordres-execution'],
    recto: 'Le jury : « Stop à 95 €, ouverture en gap à 88 €, vente à 88 €. Qui est responsable ? »',
    verso: 'Personne n\'a fauté : le stop a fonctionné comme conçu — un déclencheur, pas une garantie de prix. Devenu ordre au marché, il est servi aux prix disponibles. Seul un stop-limite aurait borné le prix… au risque de ne pas vendre du tout. Réciter cette mécanique calmement classe.',
    rectoEn: 'The panel: "Stop at €95, gap open at €88, sold at 88. Who is to blame?"',
    versoEn: 'No one failed: the stop worked as designed — a trigger, not a price guarantee. Turned into a market order, it fills at available prices. Only a stop-limit would have capped the price… at the risk of not selling at all. Calmly reciting this mechanism sets you apart.',
  },
  {
    id: 'm1-fc-056',
    moduleId: M1,
    tags: ['piege', 'ordres-execution'],
    recto: 'L\'ordre limite garantit le prix. Garantit-il aussi l\'exécution ?',
    verso: 'Non : posé dans le carnet, il attend qu\'une contrepartie vienne à lui — et peut attendre indéfiniment si le marché s\'éloigne. C\'est l\'ordre du patient, payé par les pressés. La question d\'arbitrage : qu\'est-ce qui coûte plus cher — ne pas être exécuté, ou mal exécuté ?',
    rectoEn: 'A limit order guarantees the price. Does it also guarantee execution?',
    versoEn: 'No: resting in the book, it waits for a counterparty to come to it — possibly forever if the market drifts away. It is the patient trader\'s order, paid by the hurried. The trade-off question: which costs more — not executing, or executing badly?',
  },
  {
    id: 'm1-fc-057',
    moduleId: M1,
    tags: ['reflexe-jury', 'ordres-execution'],
    recto: 'Le jury : « Vous devez impérativement avoir vendu avant ce soir. Quel ordre, et que sacrifiez-vous ? »',
    verso: 'Ordre au marché : la certitude d\'exécution s\'achète en sacrifiant la garantie de prix — demi-fourchette plus slippage de profondeur. La limite risque la non-exécution, le stop n\'est qu\'un déclencheur, et rien ne garantit prix ET exécution à la fois.',
    rectoEn: 'The panel: "You absolutely must be out by tonight. Which order, and what do you give up?"',
    versoEn: 'Market order: execution certainty is bought by giving up any price guarantee — half-spread plus depth slippage. A limit risks non-execution, a stop is just a trigger, and nothing guarantees both price AND execution.',
  },
  {
    id: 'm1-fc-058',
    moduleId: M1,
    tags: ['definition', 'ordres-execution'],
    recto: 'Le slippage, c\'est quoi ?',
    verso: 'L\'écart entre le prix moyen réellement obtenu et le prix affiché au moment de l\'ordre, quand un gros ordre traverse plusieurs niveaux du carnet. Ex. : 800 titres achetés à 100,10625 € de moyenne contre un meilleur ask à 100,05 → 0,05625 €/titre de slippage.',
    rectoEn: 'What is slippage?',
    versoEn: 'The gap between the average price actually obtained and the price displayed when the order was sent, as a large order eats through several book levels. E.g.: 800 shares bought at an average of 100.10625 vs a best ask of 100.05 → €0.05625/share of slippage.',
  },
  {
    id: 'm1-fc-059',
    moduleId: M1,
    tags: ['formule', 'ordres-execution'],
    recto: 'Carnet à la vente : 300 à 100,05, 300 à 100,10, 500 à 100,20. Coût d\'un achat au marché de 800 titres ?',
    verso: '300 × 100,05 + 300 × 100,10 + 200 × 100,20 = 80 085 €. L\'ordre consomme trois niveaux : le prix affiché (100,05) n\'est obtenu que pour les 300 premiers titres.',
    rectoEn: 'Ask side: 300 at 100.05, 300 at 100.10, 500 at 100.20. Cost of a market buy of 800 shares?',
    versoEn: '300 × 100.05 + 300 × 100.10 + 200 × 100.20 = €80,085. The order eats through three levels: the displayed price (100.05) is only obtained for the first 300 shares.',
  },
  {
    id: 'm1-fc-060',
    moduleId: M1,
    tags: ['formule', 'ordres-execution'],
    recto: 'Prix moyen de l\'achat au marché de 800 titres (80 085 € au total) ?',
    verso: '80 085 / 800 = 100,10625 €. Face au milieu à 100,00 € : surcoût de 0,10625 €/titre, soit 85 €. La moyenne est pondérée par les quantités consommées à chaque niveau — jamais la moyenne simple des prix.',
    rectoEn: 'Average price of the 800-share market buy (€80,085 in total)?',
    versoEn: '80,085 / 800 = €100.10625. Against the 100.00 mid: an extra €0.10625/share, i.e. €85. The average is weighted by the quantities consumed at each level — never the simple average of prices.',
  },
  {
    id: 'm1-fc-061',
    moduleId: M1,
    tags: ['piege', 'ordres-execution'],
    recto: 'Prix moyen des 800 titres : (100,05 + 100,10 + 100,20) / 3 = 100,1167 € ?',
    verso: 'Non : la moyenne SIMPLE ignore les quantités. La bonne moyenne est pondérée : (300 × 100,05 + 300 × 100,10 + 200 × 100,20) / 800 = 100,10625 €. Petit écart ici — mais l\'erreur de méthode, elle, se voit immédiatement à l\'oral.',
    rectoEn: 'Average price of the 800 shares: (100.05 + 100.10 + 100.20) / 3 = 100.1167?',
    versoEn: 'No: the SIMPLE average ignores quantities. The correct one is weighted: (300 × 100.05 + 300 × 100.10 + 200 × 100.20) / 800 = 100.10625. A small gap here — but the methodological error shows instantly at the oral.',
  },
  {
    id: 'm1-fc-062',
    moduleId: M1,
    tags: ['formule', 'ordres-execution'],
    recto: 'Décomposez les 85 € de surcoût des 800 titres (milieu 100,00, meilleur ask 100,05, prix moyen 100,10625).',
    verso: 'Demi-fourchette : 800 × 0,05 = 40 €. Slippage de profondeur : 800 × (100,10625 − 100,05) = 800 × 0,05625 = 45 €. Total 85 € — avant commission. Deux étages distincts : le péage d\'immédiateté, puis la traversée des niveaux.',
    rectoEn: 'Break down the €85 excess cost of the 800 shares (mid 100.00, best ask 100.05, average 100.10625).',
    versoEn: 'Half-spread: 800 × 0.05 = €40. Depth slippage: 800 × (100.10625 − 100.05) = 800 × 0.05625 = €45. Total €85 — before commission. Two distinct layers: the immediacy toll, then crossing the levels.',
  },
  {
    id: 'm1-fc-063',
    moduleId: M1,
    tags: ['calcul-mental', 'ordres-execution'],
    recto: 'De tête : demi-spread de 5 centimes × 800 titres ?',
    verso: '800 × 0,05 = 40 €. Routine : demi-spread × quantité = coût d\'immédiateté d\'un aller simple. Pour l\'aller-retour, spread entier : 800 × 0,10 = 80 €.',
    rectoEn: 'In your head: half-spread of 5 cents × 800 shares?',
    versoEn: '800 × 0.05 = €40. Routine: half-spread × quantity = the immediacy cost of a one-way trade. For the round trip, full spread: 800 × 0.10 = €80.',
  },
  {
    id: 'm1-fc-064',
    moduleId: M1,
    tags: ['calcul-mental', 'ordres-execution'],
    recto: 'De tête : slippage de profondeur sur 800 titres, prix moyen 100,10625, meilleur ask 100,05 ?',
    verso: 'Écart : 0,05625 €/titre → 800 × 0,05625 = 45 €. Astuce : 0,05625 × 800 = 56,25 × 0,8 = 45. C\'est le coût des niveaux 2 et 3 traversés — il disparaît si l\'ordre tient dans la première ligne du carnet.',
    rectoEn: 'In your head: depth slippage on 800 shares, average price 100.10625, best ask 100.05?',
    versoEn: 'Gap: €0.05625/share → 800 × 0.05625 = €45. Trick: 0.05625 × 800 = 56.25 × 0.8 = 45. It is the cost of crossing levels 2 and 3 — it vanishes if the order fits in the book\'s first line.',
  },
  {
    id: 'm1-fc-065',
    moduleId: M1,
    tags: ['piege', 'ordres-execution'],
    recto: 'L\'aller-retour instantané coûte le spread. Et l\'aller simple ?',
    verso: 'Le DEMI-spread : acheter à l\'ask quand la valeur est au milieu coûte (ask − milieu), la moitié de la fourchette. Confondre spread entier et moitié double l\'estimation du coût — l\'erreur de chiffrage classique sur les coûts de transaction.',
    rectoEn: 'An instant round trip costs the spread. And a one-way trade?',
    versoEn: 'The HALF-spread: buying at the ask when value sits at the mid costs (ask − mid), half the quote. Mixing up full and half spread doubles your cost estimate — the classic transaction-cost miscount.',
  },
  {
    id: 'm1-fc-066',
    moduleId: M1,
    tags: ['formule', 'ordres-execution'],
    recto: 'Commission de courtage « 2 pb, minimum 25 € » sur 80 085 € : formule et résultat ?',
    verso: 'Commission = max(notionnel × taux ; minimum). 80 085 × 2 / 10 000 = 16,02 € < 25 € → c\'est le minimum qui mord : 25 €. Les minima transforment les petits ordres en ordres chers en relatif.',
    rectoEn: 'Brokerage fee "2 bp, €25 minimum" on €80,085: formula and result?',
    versoEn: 'Fee = max(notional × rate; minimum). 80,085 × 2 / 10,000 = €16.02 < €25 → the minimum bites: €25. Minimum fees turn small orders into expensive ones in relative terms.',
  },
  {
    id: 'm1-fc-067',
    moduleId: M1,
    tags: ['calcul-mental', 'ordres-execution'],
    recto: 'De tête : 2 pb sur 80 000 € ? Le minimum de 25 € s\'applique-t-il ?',
    verso: '2 pb = 2 × 10⁻⁴ → 80 000 × 0,0002 = 16 €. 16 < 25 : le minimum s\'applique, on paie 25 €. Seuil d\'indifférence : 25 / 0,0002 = 125 000 € — en dessous, c\'est toujours le forfait qui mord.',
    rectoEn: 'In your head: 2 bp on €80,000? Does the €25 minimum apply?',
    versoEn: '2 bp = 2 × 10⁻⁴ → 80,000 × 0.0002 = €16. 16 < 25: the minimum applies, you pay €25. Break-even: 25 / 0.0002 = €125,000 — below that, the flat fee always bites.',
  },
  {
    id: 'm1-fc-068',
    moduleId: M1,
    tags: ['piege', 'ordres-execution'],
    recto: 'Commission affichée « 2 pb » : payez-vous vraiment 2 pb sur un ordre de 80 000 € ?',
    verso: 'Non : avec un minimum de 25 €, vous payez 25 €, soit ≈ 3,1 pb — plus de 50 % au-dessus du tarif affiché. Le taux nominal ne dit rien sous le seuil du minimum (125 000 € ici) : toujours calculer le coût effectif.',
    rectoEn: 'Posted fee "2 bp": do you really pay 2 bp on an €80,000 order?',
    versoEn: 'No: with a €25 minimum you pay €25, i.e. ≈ 3.1 bp — over 50% above the posted rate. The headline rate means nothing below the minimum\'s threshold (€125,000 here): always compute the effective cost.',
  },
  {
    id: 'm1-fc-069',
    moduleId: M1,
    tags: ['formule', 'ordres-execution'],
    recto: 'Coût de friction total de l\'achat de 800 titres (≈ 80 000 €) : les trois étages et le total en pb ?',
    verso: 'Demi-fourchette 40 € + slippage de profondeur 45 € + commission (minimum) 25 € = 110 €, soit ≈ 13,75 pb du notionnel (110 / 80 085 × 10 000). Une « petite » exécution laisse 110 € sur la table avant même que le marché ait bougé.',
    rectoEn: 'Total friction cost of the 800-share buy (≈ €80,000): the three layers and the total in bp?',
    versoEn: 'Half-spread €40 + depth slippage €45 + commission (the minimum) €25 = €110, i.e. ≈ 13.75 bp of notional (110 / 80,085 × 10,000). A "small" execution leaves €110 on the table before the market even moves.',
  },
  {
    id: 'm1-fc-070',
    moduleId: M1,
    tags: ['definition', 'ordres-execution'],
    recto: 'VWAP et TWAP : à quoi servent ces algorithmes d\'exécution ?',
    verso: 'Découper les gros ordres pour ne jamais traverser plusieurs niveaux d\'un coup. VWAP : étaler au prorata des volumes habituels de la journée, viser la moyenne pondérée par les volumes. TWAP : tranches régulières dans le temps. Contrepartie : porter le risque de marché pendant l\'exécution.',
    rectoEn: 'VWAP and TWAP: what are these execution algorithms for?',
    versoEn: 'Slicing large orders so as never to cross several levels at once. VWAP: spreading pro-rata to the day\'s usual volumes, targeting the volume-weighted average price. TWAP: regular time slices. The trade-off: carrying market risk during the execution.',
  },
  {
    id: 'm1-fc-071',
    moduleId: M1,
    tags: ['definition', 'ordres-execution'],
    recto: 'Le fixing (enchère d\'ouverture / de clôture), c\'est quoi ?',
    verso: 'Pendant quelques minutes, les ordres s\'accumulent sans s\'exécuter, puis le système calcule le prix unique qui maximise le volume échangeable — tout le monde est servi à ce prix. Idéal pour agréger l\'information (ouverture) ou produire un cours officiel (clôture).',
    rectoEn: 'What is the fixing (opening / closing auction)?',
    versoEn: 'For a few minutes orders accumulate without executing, then the system computes the single price that maximises tradable volume — everyone is filled at that price. Ideal for aggregating information (open) or producing an official price (close).',
  },
  {
    id: 'm1-fc-072',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'ordres-execution'],
    recto: 'Quelle part des volumes actions européens se traite au fixing de clôture ?',
    verso: 'Souvent estimée entre un quart et un tiers selon les places et les années — en croissance régulière. Moteur : les indices se calculent sur les cours de clôture, donc les fonds indiciels exécutent au fixing pour coller à leur référence.',
    rectoEn: 'What share of European equity volumes trades at the closing auction?',
    versoEn: 'Commonly estimated between a quarter and a third depending on venue and year — steadily growing. Driver: indices are computed on closing prices, so index funds execute at the auction to track their benchmark.',
  },
  {
    id: 'm1-fc-073',
    moduleId: M1,
    tags: ['reflexe-jury', 'ordres-execution'],
    recto: 'Le jury : « Pourquoi le fixing de clôture concentre-t-il un quart à un tiers des volumes ? »',
    verso: 'Mécanique : indices et valorisations de fonds se calculent sur la clôture → les fonds indiciels, dont le poids croît sans cesse, exécutent au fixing pour coller à l\'indice → la liquidité attire la liquidité : volume garanti en face, au prix officiel.',
    rectoEn: 'The panel: "Why does the closing auction concentrate a quarter to a third of volumes?"',
    versoEn: 'Mechanics: indices and fund NAVs are computed on the close → ever-growing index funds execute at the auction to track their benchmark → liquidity attracts liquidity: guaranteed volume on the other side, at the official price.',
  },
  {
    id: 'm1-fc-074',
    moduleId: M1,
    tags: ['reflexe-jury', 'ordres-execution'],
    recto: 'Le jury : « Que se passe-t-il exactement quand j\'achète une action ? »',
    verso: 'Dérouler la chaîne : l\'ordre part au carnet (priorité prix-temps), croise le meilleur ask — coût réel = demi-fourchette + slippage + commission (ex. : 110 € ≈ 13,75 pb sur 80 000 €) — puis confirmation, compensation, règlement-livraison à T+1/T+2.',
    rectoEn: 'The panel: "What exactly happens when I buy a share?"',
    versoEn: 'Walk the chain: the order hits the book (price-time priority), crosses the best ask — true cost = half-spread + slippage + commission (e.g. €110 ≈ 13.75 bp on €80,000) — then confirmation, clearing, settlement at T+1/T+2.',
  },
  // ───────────────────────── Chapitre 5 — Microstructure ─────────────────────────
  {
    id: 'm1-fc-075',
    moduleId: M1,
    tags: ['definition', 'microstructure'],
    recto: 'Le market maker (teneur de marché), c\'est quoi ?',
    verso: 'Un commerçant de liquidité : il affiche en permanence un bid et un ask et vit de l\'écart, multiplié par la rotation — pas du pari directionnel. Ses deux risques : l\'inventaire (le stock se déprécie pendant qu\'il le porte) et la sélection adverse.',
    rectoEn: 'What is a market maker?',
    versoEn: 'A liquidity merchant: it permanently displays a bid and an ask and lives off the gap, multiplied by turnover — not directional bets. Its two risks: inventory (the stock depreciates while held) and adverse selection.',
  },
  {
    id: 'm1-fc-076',
    moduleId: M1,
    tags: ['formule', 'microstructure'],
    recto: 'P&L d\'un market maker : formule, et exemple sur une cote 99,98 / 100,02 ?',
    verso: 'P&L ≈ spread × taille × nombre d\'allers-retours − pertes d\'inventaire et de sélection adverse. Ex. : spread 4 centimes ; acheté à 99,98, revendu à 100,02 → 0,04 €/titre sans la moindre vue sur le marché. Multiplié par des millions de transactions, c\'est un métier.',
    rectoEn: 'Market maker P&L: formula, and example on a 99.98 / 100.02 quote?',
    versoEn: 'P&L ≈ spread × size × number of round trips − inventory and adverse-selection losses. E.g.: 4-cent spread; bought at 99.98, resold at 100.02 → €0.04/share with no view on the market whatsoever. Times millions of trades, it is a business.',
  },
  {
    id: 'm1-fc-077',
    moduleId: M1,
    tags: ['calcul-mental', 'microstructure'],
    recto: 'De tête : un MM gagne le spread de 4 centimes sur 200 allers-retours de 1 000 titres. P&L brut ?',
    verso: '0,04 × 1 000 × 200 = 8 000 €. Décomposer : 0,04 × 1 000 = 40 € par aller-retour, × 200 = 8 000 €. Brut : avant pertes d\'inventaire et de sélection adverse — qui peuvent tout manger.',
    rectoEn: 'In your head: a MM earns the 4-cent spread on 200 round trips of 1,000 shares. Gross P&L?',
    versoEn: '0.04 × 1,000 × 200 = €8,000. Decompose: 0.04 × 1,000 = €40 per round trip, × 200 = €8,000. Gross: before inventory and adverse-selection losses — which can eat it all.',
  },
  {
    id: 'm1-fc-078',
    moduleId: M1,
    tags: ['piege', 'microstructure'],
    recto: 'Le spread du market maker est-il un péage arbitraire ?',
    verso: 'Non : une prime d\'assurance contre l\'asymétrie d\'information. Les gains sur le flux ordinaire doivent couvrir les pertes systématiques face aux mieux informés (sélection adverse), plus le risque d\'inventaire. D\'où l\'élargissement avant les annonces.',
    rectoEn: 'Is the market maker\'s spread an arbitrary toll?',
    versoEn: 'No: an insurance premium against information asymmetry. Gains on ordinary flow must cover the systematic losses to better-informed traders (adverse selection), plus inventory risk. Hence the widening before announcements.',
  },
  {
    id: 'm1-fc-079',
    moduleId: M1,
    tags: ['reflexe-jury', 'microstructure'],
    recto: 'Le jury : « Le spread, c\'est le prix de quoi ? »',
    verso: 'De l\'immédiateté — l\'aller-retour instantané coûte le spread — et de la sélection adverse : il est calibré pour que le flux ordinaire finance les pertes face aux informés. Bonus : citer l\'inventaire, troisième composante. Deux mots-clés, pas une récitation.',
    rectoEn: 'The panel: "The spread is the price of what?"',
    versoEn: 'Of immediacy — the instant round trip costs the spread — and of adverse selection: it is calibrated so ordinary flow funds the losses to informed traders. Bonus: mention inventory, the third component. Two key words, not a recital.',
  },
  {
    id: 'm1-fc-080',
    moduleId: M1,
    tags: ['formule', 'microstructure'],
    recto: 'Mini-modèle de sélection adverse : titre à 101 ou 99 € équiprobables, 10 % d\'informés. Où coter ?',
    verso: 'Conditionnellement à un achat, la valeur espérée monte à 100,10 € : l\'ask doit être ≥ 100,10, le bid ≤ 99,90 par symétrie. Spread : 20 centimes, sans coût d\'inventaire ni de traitement — la sélection adverse à l\'état pur (logique Glosten-Milgrom).',
    rectoEn: 'Adverse-selection mini-model: stock worth 101 or 99 with equal odds, 10% informed traders. Where to quote?',
    versoEn: 'Conditional on a buy, expected value rises to €100.10: the ask must be ≥ 100.10, the bid ≤ 99.90 by symmetry. Spread: 20 cents, with zero inventory or processing cost — adverse selection in its purest form (Glosten-Milgrom logic).',
  },
  {
    id: 'm1-fc-081',
    moduleId: M1,
    tags: ['calcul-mental', 'microstructure'],
    recto: 'De tête : dans le mini-modèle (101/99 équiprobables), on passe de 10 % à 20 % d\'informés. Le spread ?',
    verso: 'Il double : ask 100,20, bid 99,80 → 40 centimes contre 20. Règle mentale : le spread croît avec la part de flux informé — c\'est pourquoi il s\'élargit mécaniquement avant les annonces.',
    rectoEn: 'In your head: in the mini-model (101/99 equally likely), informed share goes from 10% to 20%. The spread?',
    versoEn: 'It doubles: ask 100.20, bid 99.80 → 40 cents versus 20. Mental rule: the spread grows with the share of informed flow — which is why it mechanically widens before announcements.',
  },
  {
    id: 'm1-fc-082',
    moduleId: M1,
    tags: ['reflexe-jury', 'microstructure'],
    recto: 'Le jury : « Pourquoi le spread s\'élargit-il avant une annonce de résultats ? »',
    verso: 'Parce que la probabilité de croiser un informé augmente : le market maker recalibre sa prime d\'assurance. Dans le mini-modèle, passer de 10 % à 20 % d\'informés double le spread (20 → 40 centimes). Le spread est un thermomètre d\'asymétrie d\'information.',
    rectoEn: 'The panel: "Why does the spread widen before an earnings release?"',
    versoEn: 'Because the odds of meeting an informed trader rise: the market maker recalibrates its insurance premium. In the mini-model, going from 10% to 20% informed doubles the spread (20 → 40 cents). The spread is a thermometer of information asymmetry.',
  },
  {
    id: 'm1-fc-083',
    moduleId: M1,
    tags: ['definition', 'microstructure'],
    recto: 'Le trading haute fréquence (HFT), c\'est quoi ?',
    verso: 'Pas une stratégie : une technologie — décider et exécuter en microsecondes. L\'essentiel est du market making électronique (inventaires ramenés vers zéro en fin de journée) ; le reste, de l\'arbitrage de latence entre plateformes ou entre un indice et ses composants.',
    rectoEn: 'What is high-frequency trading (HFT)?',
    versoEn: 'Not a strategy: a technology — deciding and executing in microseconds. Most of it is electronic market making (inventories flattened by day-end); the rest, latency arbitrage between venues or between an index and its components.',
  },
  {
    id: 'm1-fc-084',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'microstructure'],
    recto: 'Part du HFT dans les volumes actions ?',
    verso: 'De l\'ordre de la moitié des volumes sur les actions américaines, un peu moins en Europe — ordre de grandeur prudent. L\'essentiel de cette activité est de la tenue de marché électronique, pas du pari directionnel.',
    rectoEn: 'HFT\'s share of equity volumes?',
    versoEn: 'Around half of US equity volumes, somewhat less in Europe — a cautious order of magnitude. Most of that activity is electronic market making, not directional betting.',
  },
  {
    id: 'm1-fc-085',
    moduleId: M1,
    tags: ['piege', 'microstructure'],
    recto: 'Le HFT : prédateur à interdire, ou bienfaiteur des marchés ?',
    verso: 'Ni l\'un ni l\'autre — les deux colonnes sont vraies ensemble : spreads jamais aussi serrés et coûts des particuliers en chute (crédit) ; mais liquidité conditionnelle qui s\'évapore en stress (débit). Quand les signaux déraillent, les machines coupent — flash crash.',
    rectoEn: 'HFT: a predator to ban, or a benefactor of markets?',
    versoEn: 'Neither — both columns are true at once: spreads tighter than ever and retail costs collapsing (credit side); but conditional liquidity that evaporates under stress (debit side). When signals go haywire, the machines switch off — flash crash.',
  },
  {
    id: 'm1-fc-086',
    moduleId: M1,
    tags: ['reflexe-jury', 'microstructure'],
    recto: 'Le jury : « Le HFT, bon ou mauvais pour les marchés ? »',
    verso: 'La nuance attendue : il a rendu la liquidité ordinaire moins chère ET la liquidité de crise moins fiable — les deux affirmations sont vraies en même temps. Illustrer par le 6 mai 2010 : −9 % en quelques minutes, retour en vingt minutes. Ni angélisme ni diabolisation.',
    rectoEn: 'The panel: "Is HFT good or bad for markets?"',
    versoEn: 'The expected nuance: it made ordinary liquidity cheaper AND crisis liquidity less reliable — both statements are true at the same time. Illustrate with 6 May 2010: −9% in minutes, recovered in twenty. Neither idealise nor demonise.',
  },
  {
    id: 'm1-fc-087',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'microstructure'],
    recto: 'Le flash crash du 6 mai 2010 : l\'ampleur et la leçon ?',
    verso: 'Le Dow perd près de 1 000 points — environ −9 % — en quelques minutes ; des actions traitent à 1 centime, d\'autres à 100 000 $ ; l\'essentiel est effacé vingt minutes plus tard. Leçon : la liquidité électronique est conditionnelle — elle avait cessé d\'exister un quart d\'heure.',
    rectoEn: 'The 6 May 2010 flash crash: scale and lesson?',
    versoEn: 'The Dow drops nearly 1,000 points — about −9% — in minutes; stocks print at 1 cent, others at $100,000; most of it is erased twenty minutes later. Lesson: electronic liquidity is conditional — it had simply ceased to exist for a quarter of an hour.',
  },
  {
    id: 'm1-fc-088',
    moduleId: M1,
    tags: ['piege', 'microstructure'],
    recto: 'Volume record aujourd\'hui = titre dix fois plus liquide ?',
    verso: 'Non : le volume mesure le passé (ce qui s\'est échangé), la liquidité un potentiel (ce que vous pourriez échanger sans déplacer le prix). Trois dimensions : spread, profondeur, résilience. Le 6 mai 2010 : volumes records, liquidité nulle.',
    rectoEn: 'Record volume today = a stock ten times more liquid?',
    versoEn: 'No: volume measures the past (what traded), liquidity a potential (what you could trade without moving the price). Three dimensions: spread, depth, resilience. On 6 May 2010: record volumes, zero liquidity.',
  },
  {
    id: 'm1-fc-089',
    moduleId: M1,
    tags: ['definition', 'microstructure'],
    recto: 'Un MTF, et la fragmentation des marchés : de quoi parle-t-on ?',
    verso: 'MTF : plateforme alternative de négociation multilatérale (Cboe Europe, Aquis), née de l\'ouverture à la concurrence (MiFID, 2007). Conséquence : la même action se traite sur la bourse historique, des MTF, des internalisateurs et des dark pools — l\'ordre a dix adresses.',
    rectoEn: 'An MTF, and market fragmentation: what are we talking about?',
    versoEn: 'MTF: an alternative multilateral trading facility (Cboe Europe, Aquis), born of the competition opened by MiFID (2007). Consequence: the same share trades on the legacy exchange, MTFs, internalisers and dark pools — an order has ten addresses.',
  },
  {
    id: 'm1-fc-090',
    moduleId: M1,
    tags: ['definition', 'microstructure'],
    recto: 'Un dark pool, c\'est quoi ?',
    verso: 'Une plateforme SANS transparence pré-négociation : les ordres ne sont affichés à personne avant l\'exécution, le plus souvent croisés au prix milieu du marché public. Raison d\'être : exécuter de gros blocs sans impact de marché. Part de marché plafonnée par la réglementation.',
    rectoEn: 'What is a dark pool?',
    versoEn: 'A venue with NO pre-trade transparency: orders are displayed to no one before execution, usually crossed at the public market\'s mid price. Purpose: executing large blocks without market impact. Market share capped by regulation.',
  },
  {
    id: 'm1-fc-091',
    moduleId: M1,
    tags: ['piege', 'microstructure'],
    recto: '« Dark pool » = trading illégal ou dissimulé au régulateur ?',
    verso: 'Non : des plateformes légales et régulées, sans transparence PRÉ-négociation seulement — les transactions sont déclarées. Utilité : croiser des blocs sans faire fuir la contrepartie. La limite : si trop de flux traite dans le noir, le prix public se dégrade — d\'où les plafonds.',
    rectoEn: '"Dark pool" = illegal trading hidden from the regulator?',
    versoEn: 'No: legal, regulated venues, lacking only PRE-trade transparency — trades are reported. Use: crossing blocks without scaring the other side away. The limit: too much flow in the dark degrades the public price — hence the caps.',
  },
  {
    id: 'm1-fc-092',
    moduleId: M1,
    tags: ['reflexe-jury', 'microstructure'],
    recto: 'Le jury : « Faut-il interdire les dark pools ? »',
    verso: 'Poser le dilemme : ils protègent les gros ordres de l\'impact de marché (croisement au milieu, discrétion), mais trop de noir dégrade la découverte des prix publics. Réponse d\'équilibre : non — encadrer, c\'est le choix de MiFID II avec les plafonds de part de marché.',
    rectoEn: 'The panel: "Should dark pools be banned?"',
    versoEn: 'Frame the dilemma: they shield large orders from market impact (mid-price crossing, discretion), but too much dark flow degrades public price discovery. Balanced answer: no — cap them, MiFID II\'s choice with market-share ceilings.',
  },
  // ───────────────────────── Chapitre 6 — La régulation ─────────────────────────
  {
    id: 'm1-fc-093',
    moduleId: M1,
    tags: ['definition', 'regulation'],
    recto: 'MiFID II (2018), c\'est quoi ?',
    verso: 'La remise à plat européenne du fonctionnement des marchés : best execution durcie (démontrable ordre par ordre), transparence pré/post-négociation et plafonds sur les dark pools, recherche facturée séparément (unbundling), protection de l\'investisseur (coûts, enregistrements).',
    rectoEn: 'What is MiFID II (2018)?',
    versoEn: 'Europe\'s overhaul of market functioning: hardened best execution (provable order by order), pre/post-trade transparency and dark pool caps, research priced separately (unbundling), investor protection (costs, recorded communications).',
  },
  {
    id: 'm1-fc-094',
    moduleId: M1,
    tags: ['definition', 'regulation'],
    recto: 'La best execution, c\'est quoi ?',
    verso: 'L\'obligation de se procurer le meilleur résultat possible pour le client — prix, coûts, rapidité, probabilité d\'exécution — et de pouvoir le PROUVER : politique écrite, contrôles, démonstration ordre par ordre. Le smart order router en est la matérialisation technique.',
    rectoEn: 'What is best execution?',
    versoEn: 'The duty to obtain the best possible result for the client — price, costs, speed, likelihood of execution — and to be able to PROVE it: written policy, controls, order-by-order demonstration. The smart order router is its technical embodiment.',
  },
  {
    id: 'm1-fc-095',
    moduleId: M1,
    tags: ['piege', 'regulation'],
    recto: 'L\'unbundling MiFID II a rendu les coûts de recherche transparents. Sans effet pervers ?',
    verso: 'Si : budgets recherche comprimés, analystes en moins, couverture des petites capitalisations appauvrie — au point que le législateur européen a rouvert le dossier et assoupli la règle. Toute réforme a ses effets de bord : les citer crédibilise.',
    rectoEn: 'MiFID II unbundling made research costs transparent. No side effects?',
    versoEn: 'There were: research budgets squeezed, fewer analysts, small-cap coverage impoverished — to the point the EU legislator reopened the file and softened the rule. Every reform has side effects: naming them builds credibility.',
  },
  {
    id: 'm1-fc-096',
    moduleId: M1,
    tags: ['definition', 'regulation'],
    recto: 'EMIR (2012), c\'est quoi ?',
    verso: 'La réponse européenne au G20 post-Lehman : compensation centrale obligatoire des dérivés OTC standardisés (swaps de taux, CDS indiciels), déclaration de tous les dérivés aux référentiels centraux, échanges de marges sur le non-compensé. Deux banques ne se font plus face : la CCP s\'interpose.',
    rectoEn: 'What is EMIR (2012)?',
    versoEn: 'Europe\'s answer to the post-Lehman G20: mandatory central clearing of standardised OTC derivatives (rate swaps, index CDS), reporting of all derivatives to trade repositories, margin exchange on the uncleared rest. Two banks no longer face each other: the CCP steps in.',
  },
  {
    id: 'm1-fc-097',
    moduleId: M1,
    tags: ['reflexe-jury', 'regulation'],
    recto: 'Le jury : « Pourquoi imposer la compensation centrale des dérivés après 2008 ? »',
    verso: 'Lehman tombe : personne ne sait qui est exposé à qui ; AIG a vendu de la protection sans déposer de garanties. La toile bilatérale opaque a propagé le défaut. Réponse du G20 (Pittsburgh 2009), traduite par EMIR : CCP interposée, marges quotidiennes, déclaration.',
    rectoEn: 'The panel: "Why mandate central clearing of derivatives after 2008?"',
    versoEn: 'Lehman falls: nobody knows who is exposed to whom; AIG sold protection without posting collateral. The opaque bilateral web spread the default. G20 answer (Pittsburgh 2009), translated by EMIR: CCP interposed, daily margins, reporting.',
  },
  {
    id: 'm1-fc-098',
    moduleId: M1,
    tags: ['definition', 'regulation'],
    recto: 'Le règlement Abus de marché (MAR), c\'est quoi ?',
    verso: 'Le texte européen (2014, applicable depuis juillet 2016) qui structure les abus de marché en deux familles : les opérations d\'initiés (usage, transmission ou recommandation sur information privilégiée) et la manipulation de cours (fausse apparence d\'offre ou de demande).',
    rectoEn: 'What is the Market Abuse Regulation (MAR)?',
    versoEn: 'The EU text (2014, applicable since July 2016) organising market abuse into two families: insider dealing (using, passing on or recommending on inside information) and market manipulation (creating a false appearance of supply or demand).',
  },
  {
    id: 'm1-fc-099',
    moduleId: M1,
    tags: ['definition', 'regulation'],
    recto: 'L\'information privilégiée et le délit d\'initié : définitions ?',
    verso: 'Information privilégiée : précise + non publique + susceptible d\'influencer sensiblement le cours. Délit d\'initié : en faire usage, la transmettre ou recommander sur sa base — du banquier M&A au beau-frère tuyauté au dîner, et celui qui l\'a tuyauté.',
    rectoEn: 'Inside information and insider dealing: definitions?',
    versoEn: 'Inside information: precise + non-public + likely to significantly move the price. Insider dealing: using it, passing it on or recommending on its basis — from the M&A banker to the brother-in-law tipped at dinner, and the tipper himself.',
  },
  {
    id: 'm1-fc-100',
    moduleId: M1,
    tags: ['reflexe-jury', 'regulation'],
    recto: 'Le jury : « Qu\'est-ce qui rend une information "privilégiée" ? »',
    verso: 'Trois critères cumulatifs : précise (pas une rumeur de couloir), non publique, et susceptible d\'influencer sensiblement le cours. Les trois usages interdits : traiter, transmettre, recommander. Réciter les trois critères dans l\'ordre est un marqueur de rigueur juridique.',
    rectoEn: 'The panel: "What makes information \'inside information\'?"',
    versoEn: 'Three cumulative tests: precise (not a corridor rumour), non-public, and likely to significantly affect the price. The three banned uses: trading, disclosing, recommending. Reciting the three tests in order is a marker of legal rigour.',
  },
  {
    id: 'm1-fc-101',
    moduleId: M1,
    tags: ['piege', 'regulation'],
    recto: 'Vendre sur information privilégiée, puis le cours remonte : aucun gain, aucune perte évitée. Infraction quand même ?',
    verso: 'Oui : le manquement est constitué par l\'USAGE de l\'information au moment de l\'ordre, pas par le profit. Une perte évitée est un avantage, et même un trade finalement perdant reste fautif. L\'infraction se juge à l\'information détenue, jamais au résultat du trade.',
    rectoEn: 'Selling on inside information, then the price recovers: no gain, no loss avoided. Still an offence?',
    versoEn: 'Yes: the offence lies in the USE of the information at the moment of the order, not in profit. An avoided loss is a benefit, and even a losing trade remains unlawful. The offence is judged on the information held, never on the trade\'s outcome.',
  },
  {
    id: 'm1-fc-102',
    moduleId: M1,
    tags: ['definition', 'regulation'],
    recto: 'Le spoofing et le layering, c\'est quoi ?',
    verso: 'Manipulation de cours : afficher de gros ordres SANS intention de les exécuter pour pousser les autres à traiter, puis les annuler (spoofing) ; en mille-feuille de couches échelonnées (layering). Cas Sarao : des dizaines de M$ depuis un pavillon de Hounslow, arrêté en 2015.',
    rectoEn: 'What are spoofing and layering?',
    versoEn: 'Market manipulation: posting large orders with NO intent to execute, to push others to trade, then cancelling them (spoofing); in stacked, price-laddered layers (layering). The Sarao case: tens of $m from a Hounslow semi, arrested in 2015.',
  },
  {
    id: 'm1-fc-103',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'regulation'],
    recto: 'Pouvoir de sanction de la commission des sanctions de l\'AMF ?',
    verso: 'Amendes jusqu\'à 100 M€ ou dix fois l\'avantage retiré. En pratique : centaines de k€ à quelques M€ pour les dossiers courants ; record ≈ 75 M€ (H2O AM, 2023). Publication nominative — souvent la sanction la plus coûteuse — et bascule au pénal pour les cas graves.',
    rectoEn: 'Sanctioning power of the AMF\'s enforcement committee?',
    versoEn: 'Fines up to €100m or ten times the benefit derived. In practice: hundreds of k€ to a few €m for routine cases; record ≈ €75m (H2O AM, 2023). Named publication — often the costliest penalty — and criminal referral for the gravest cases.',
  },
  {
    id: 'm1-fc-104',
    moduleId: M1,
    tags: ['piege', 'regulation'],
    recto: 'Aux États-Unis, la SEC et la CFTC se partagent-elles conduite et prudentiel, comme AMF/ACPR ?',
    verso: 'Non — la coupure américaine sépare TITRES et DÉRIVÉS : la SEC régule actions et obligations, la CFTC futures et swaps. Un future sur le S&P 500 relève de la CFTC, les actions de l\'indice de la SEC. Héritage des marchés agricoles de Chicago.',
    rectoEn: 'In the US, do the SEC and CFTC split conduct and prudential, like AMF/ACPR?',
    versoEn: 'No — the American split separates SECURITIES from DERIVATIVES: the SEC covers stocks and bonds, the CFTC futures and swaps. An S&P 500 future falls to the CFTC, the index\'s stocks to the SEC. A legacy of Chicago\'s agricultural markets.',
  },
  {
    id: 'm1-fc-105',
    moduleId: M1,
    tags: ['reflexe-jury', 'regulation'],
    recto: 'Le jury : « Un future sur le S&P 500 : SEC ou CFTC ? »',
    verso: 'CFTC — les dérivés, héritage des futures nés sur le blé à Chicago ; les actions composant l\'indice relèvent de la SEC. La bizarrerie à servir avec le sourire : deux agences pour un même marché, une coupure titres/dérivés qui ne recoupe ni conduite ni prudentiel.',
    rectoEn: 'The panel: "An S&P 500 future: SEC or CFTC?"',
    versoEn: 'CFTC — derivatives, a legacy of futures born on Chicago wheat; the index\'s constituent stocks belong to the SEC. Serve the quirk with a smile: two agencies for one market, a securities/derivatives split matching neither conduct nor prudential.',
  },
  // ───────────────────────── Chapitre 7 — Le post-marché ─────────────────────────
  {
    id: 'm1-fc-106',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'Une chambre de compensation (CCP), c\'est quoi ?',
    verso: 'La contrepartie centrale qui s\'interpose dans les transactions : acheteuse de tout vendeur, vendeuse de tout acheteur. Si un membre fait défaut, elle honore le contrat — protégée par marges initiales, appels de marge au moins quotidiens et cascade de défaut.',
    rectoEn: 'What is a central counterparty (CCP)?',
    versoEn: 'The central counterparty interposing itself in trades: buyer to every seller, seller to every buyer. If a member defaults, it honours the contract — protected by initial margins, at least daily margin calls and a default waterfall.',
  },
  {
    id: 'm1-fc-107',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'La novation, c\'est quoi ?',
    verso: 'Le mécanisme juridique de la compensation : dès l\'acceptation du trade, le contrat entre A et B est REMPLACÉ par deux contrats face à la CCP. A et B ne sont plus exposés l\'un à l\'autre — tout le risque de contrepartie du marché se concentre sur la chambre.',
    rectoEn: 'What is novation?',
    versoEn: 'Clearing\'s legal mechanism: once the trade is accepted, the contract between A and B is REPLACED by two contracts facing the CCP. A and B are no longer exposed to each other — the market\'s entire counterparty risk concentrates on the clearing house.',
  },
  {
    id: 'm1-fc-108',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'Marge initiale vs marge de variation : quelle différence ?',
    verso: 'Initiale : dépôt de garantie calibré pour couvrir la liquidation d\'une position en conditions dégradées — quelques jours de mouvement extrême. Variation : règlement quotidien (parfois intrajournalier), en cash, des gains et pertes latents — les pertes ne s\'accumulent jamais.',
    rectoEn: 'Initial vs variation margin: what is the difference?',
    versoEn: 'Initial: a guarantee deposit sized to cover liquidating a position in stressed conditions — a few days of extreme moves. Variation: daily (sometimes intraday) cash settlement of unrealised gains and losses — losses never pile up.',
  },
  {
    id: 'm1-fc-109',
    moduleId: M1,
    tags: ['piege', 'post-marche'],
    recto: 'La CCP élimine-t-elle le risque de contrepartie ?',
    verso: 'Elle le RÉDUIT (novation, netting, marges) et le CONCENTRE à la fois : les CCP sont devenues les nœuds systémiques du marché — « too big to fail » assumé, d\'où plans de rétablissement et de résolution. Une grande CCP qui tomberait ferait passer Lehman pour une répétition.',
    rectoEn: 'Does a CCP eliminate counterparty risk?',
    versoEn: 'It REDUCES it (novation, netting, margins) and CONCENTRATES it at once: CCPs have become the market\'s systemic nodes — accepted "too big to fail", hence recovery and resolution plans. A major CCP failing would make Lehman look like a dress rehearsal.',
  },
  {
    id: 'm1-fc-110',
    moduleId: M1,
    tags: ['reflexe-jury', 'post-marche'],
    recto: 'Le jury : « Un membre d\'une chambre de compensation fait défaut. Que se passe-t-il ? »',
    verso: 'Dérouler la cascade : marges du défaillant → sa contribution au fonds de défaut → skin in the game de la CCP → fonds mutualisé des survivants → appels supplémentaires. Citer Lehman 2008 (réglé à la première marche) et Nasdaq 2018 (~100 M€ du fonds mutualisé consommés).',
    rectoEn: 'The panel: "A clearing house member defaults. What happens?"',
    versoEn: 'Walk the waterfall: defaulter\'s margins → its default fund contribution → the CCP\'s skin in the game → survivors\' mutualised fund → further calls. Cite Lehman 2008 (settled at step one) and Nasdaq 2018 (~€100m of the mutual fund consumed).',
  },
  {
    id: 'm1-fc-111',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'post-marche'],
    recto: 'Lehman 2008 : quel portefeuille de swaps la chambre LCH a-t-elle débouclé, et avec quelles pertes ?',
    verso: '≈ 9 000 Md$ de notionnel de swaps de taux, débouclés SANS même épuiser la marge initiale du défaillant. La meilleure publicité jamais faite aux CCP — et l\'argument central du G20 pour imposer la compensation centrale.',
    rectoEn: 'Lehman 2008: what swap portfolio did the LCH clearing house unwind, and at what loss?',
    versoEn: '≈ $9tn notional of interest rate swaps, unwound WITHOUT even exhausting the defaulter\'s initial margin. The best advertisement CCPs ever had — and the G20\'s core argument for mandating central clearing.',
  },
  {
    id: 'm1-fc-112',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'Le dépositaire central de titres (CSD), c\'est quoi ?',
    verso: 'Le notaire du marché : il tient le registre ultime de qui détient quoi, et c\'est dans ses livres que s\'opère le règlement-livraison. Deux géants européens : Euroclear (Bruxelles, ≈ 40 000 Md€ conservés — dont les avoirs russes gelés) et Clearstream (Luxembourg).',
    rectoEn: 'What is a central securities depository (CSD)?',
    versoEn: 'The market\'s notary: it keeps the ultimate register of who owns what, and settlement happens in its books. Two European giants: Euroclear (Brussels, ≈ €40tn in custody — including the frozen Russian assets) and Clearstream (Luxembourg).',
  },
  {
    id: 'm1-fc-113',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'Un custodian (conservateur), c\'est quoi ?',
    verso: 'Il tient les comptes-titres des institutionnels sous le dépositaire central et gère la vie quotidienne des portefeuilles : encaissement des coupons et dividendes, opérations sur titres, droits de vote. BNP Paribas, CACEIS, State Street. Votre PEA s\'inscrit dans la même pyramide.',
    rectoEn: 'What is a custodian?',
    versoEn: 'It keeps institutional securities accounts beneath the CSD and runs daily portfolio life: collecting coupons and dividends, corporate actions, voting rights. BNP Paribas, CACEIS, State Street. Your retail account sits in the same pyramid.',
  },
  {
    id: 'm1-fc-114',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'Le principe DvP (delivery versus payment), c\'est quoi ?',
    verso: 'Livraison contre paiement : titres et cash changent de mains SIMULTANÉMENT dans les livres du dépositaire central — aucune des deux jambes ne part sans l\'autre. La protection de base contre le risque de livrer sans être payé (ou l\'inverse).',
    rectoEn: 'What is the DvP (delivery versus payment) principle?',
    versoEn: 'Delivery versus payment: securities and cash change hands SIMULTANEOUSLY in the central depository\'s books — neither leg moves without the other. The basic protection against delivering without being paid (or the reverse).',
  },
  {
    id: 'm1-fc-115',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'Le cycle de règlement T+1 / T+2, c\'est quoi, et pourquoi le raccourcir ?',
    verso: 'Le délai conventionnel entre exécution et règlement-livraison. Pendant cette fenêtre, la contrepartie peut faire défaut : plus elle est longue et volatile, plus les marges exigées par la CCP sont lourdes. Raccourcir = moins de risque et moins de collatéral immobilisé.',
    rectoEn: 'What is the T+1 / T+2 settlement cycle, and why shorten it?',
    versoEn: 'The conventional lag between execution and settlement. During that window your counterparty can default: the longer and more volatile it is, the heavier the CCP\'s margin requirements. Shortening = less risk and less collateral tied up.',
  },
  {
    id: 'm1-fc-116',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'post-marche'],
    recto: 'Où en est le passage à T+1 ?',
    verso: 'États-Unis : T+1 depuis fin mai 2024. Europe : encore T+2, bascule annoncée pour octobre 2027 (Royaume-Uni et Suisse alignés). Effet de bord : un fonds européen achetant des actions US doit trouver ses dollars en quelques heures, fuseaux horaires compris.',
    rectoEn: 'Where does the move to T+1 stand?',
    versoEn: 'United States: T+1 since end of May 2024. Europe: still T+2, with a switch announced for October 2027 (UK and Switzerland aligned). Side effect: a European fund buying US equities must now source its dollars within hours, time zones included.',
  },
  {
    id: 'm1-fc-117',
    moduleId: M1,
    tags: ['definition', 'post-marche'],
    recto: 'Un fail de règlement, c\'est quoi ?',
    verso: 'Le vendeur ne livre pas les titres à la date prévue — titres prêtés non rappelés à temps, maillon d\'une chaîne qui saute. Bénin en temps calme, pénalisé en Europe depuis février 2022 (discipline de règlement CSDR) ; en stress, les fails s\'accumulent : un thermomètre des tensions.',
    rectoEn: 'What is a settlement fail?',
    versoEn: 'The seller fails to deliver the securities on the due date — lent stock not recalled in time, a broken link in a settlement chain. Benign in calm times, fined in Europe since February 2022 (CSDR settlement discipline); under stress, fails pile up: a tension thermometer.',
  },
  {
    id: 'm1-fc-118',
    moduleId: M1,
    tags: ['piege', 'post-marche'],
    recto: 'GameStop, janvier 2021 : Robinhood a bloqué les achats pour sauver les hedge funds ?',
    verso: 'Non — l\'enquête parlementaire n\'a documenté AUCUNE pression. L\'explication est post-marché : sous T+2, l\'appel de marge NSCC passe de ~700 M$ à 3,7 Md$ en une nuit, plusieurs fois le coussin du courtier. Bloquer les achats réduisait mécaniquement l\'exigence.',
    rectoEn: 'GameStop, January 2021: did Robinhood block buys to save the hedge funds?',
    versoEn: 'No — the congressional inquiry documented NO pressure. The explanation is post-trade: under T+2, the NSCC margin call jumped from ~$700m to $3.7bn overnight, several times the broker\'s buffer. Blocking new buys mechanically cut the requirement.',
  },
  {
    id: 'm1-fc-119',
    moduleId: M1,
    tags: ['ordre-de-grandeur', 'post-marche'],
    recto: 'GameStop, 28 janvier 2021 : l\'appel de marge notifié à Robinhood ?',
    verso: '3,7 Md$ au matin, contre ≈ 700 M$ la veille — recalculé sur la volatilité et la concentration des positions. La CCP renonce à un supplément, l\'exigence retombe vers 1,4 Md$, et Robinhood lève ≈ 3,4 Md$ en quelques jours. L\'épisode a accéléré le passage américain à T+1.',
    rectoEn: 'GameStop, 28 January 2021: the margin call served on Robinhood?',
    versoEn: '$3.7bn that morning, versus ≈ $700m the day before — recomputed on volatility and position concentration. The CCP waived a top-up, the requirement fell back to ~$1.4bn, and Robinhood raised ≈ $3.4bn within days. The episode hastened the US move to T+1.',
  },
  {
    id: 'm1-fc-120',
    moduleId: M1,
    tags: ['reflexe-jury', 'post-marche'],
    recto: 'Le jury : « Pourquoi Robinhood a-t-il bloqué les ACHATS de GameStop, mais pas les ventes ? »',
    verso: 'Dérouler la chaîne : volatilité extrême → marges NSCC recalculées (~700 M$ → 3,7 Md$) → capital du courtier insuffisant → seule parade immédiate : bloquer les achats, qui augmentent l\'exposition à couvrir — les ventes la réduisent, d\'où l\'asymétrie. Mécanique, pas complot.',
    rectoEn: 'The panel: "Why did Robinhood block GameStop BUYS but not sells?"',
    versoEn: 'Walk the chain: extreme volatility → NSCC margins recomputed (~$700m → $3.7bn) → broker\'s capital insufficient → only immediate fix: block buys, which raise the exposure to cover — sells reduce it, hence the asymmetry. Mechanics, not conspiracy.',
  },
];
