import type { Formule } from '../../../engine/types';

const M1 = '01-panorama-marches';

export const formules: Formule[] = [
  {
    id: 'm1-f-01',
    moduleId: M1,
    nom: 'Fourchette en points de base',
    nomEn: 'Bid-ask spread in basis points',
    latex: '\\text{spread}_{\\text{pb}} = \\frac{a - b}{m} \\times 10\\,000',
    commentaire: 'Pour comparer le coût d\'immédiateté de titres qui ne cotent pas au même niveau (a = ask, b = bid, m = milieu) — sur un titre autour de 100 €, un centime de fourchette = un point de base.',
    commentaireEn: 'To compare the cost of immediacy across securities that do not quote at the same level (a = ask, b = bid, m = mid) — on a stock around €100, one cent of spread = one basis point.',
  },
  {
    id: 'm1-f-02',
    moduleId: M1,
    nom: 'Milieu de fourchette',
    nomEn: 'Mid-quote',
    latex: 'm = \\frac{b + a}{2}',
    commentaire: 'Pour estimer « la » valeur instantanée du titre : c\'est la référence contre laquelle tout coût d\'exécution se mesure.',
    commentaireEn: 'To estimate the instantaneous value of the security: the reference against which every execution cost is measured.',
  },
  {
    id: 'm1-f-03',
    moduleId: M1,
    nom: 'Coût de traversée de la fourchette',
    nomEn: 'Cost of crossing the spread',
    latex: 'C_{\\rightarrow} = Q \\times \\frac{s}{2} \\qquad C_{\\leftrightarrow} = Q \\times s',
    commentaire: 'Pour chiffrer le prix de l\'immédiateté : acheter tout de suite coûte la demi-fourchette (s/2 par titre), l\'aller-retour instantané coûte le spread entier — ce que le preneur de liquidité paie au teneur de marché.',
    commentaireEn: 'To price immediacy: buying right now costs the half-spread (s/2 per share), an instant round trip costs the full spread — what the liquidity taker pays the market maker.',
  },
  {
    id: 'm1-f-04',
    moduleId: M1,
    nom: 'Prix moyen d\'un ordre traversant le carnet',
    nomEn: 'Average price of an order walking the book',
    latex: '\\bar{P} = \\frac{\\sum_i q_i\\,p_i}{\\sum_i q_i}',
    commentaire: 'Pour le prix moyen d\'un ordre au marché qui consomme plusieurs niveaux : la moyenne pondérée par les quantités, jamais la moyenne simple des prix — 800 titres sur trois niveaux du chapitre 4 : 100,10625 €.',
    commentaireEn: 'For the average price of a market order consuming several levels: the quantity-weighted average, never the simple average of prices — 800 shares over three levels in chapter 4: €100.10625.',
  },
  {
    id: 'm1-f-05',
    moduleId: M1,
    nom: 'Slippage décomposé',
    nomEn: 'Slippage decomposition',
    latex: 'Q\\,(\\bar{P} - m) = Q\\,(a - m) + Q\\,(\\bar{P} - a)',
    commentaire: 'Pour décomposer le surcoût d\'une exécution face au milieu : demi-fourchette (a − m) + slippage de profondeur (P̄ − a) — sur l\'exemple du module : 85 € = 40 € + 45 €.',
    commentaireEn: 'To split the execution cost versus the mid: half-spread (a − m) + depth slippage (P̄ − a) — on the module\'s example: €85 = €40 + €45.',
  },
  {
    id: 'm1-f-06',
    moduleId: M1,
    nom: 'Commission avec minimum',
    nomEn: 'Commission with a minimum',
    latex: 'C_{\\text{com}} = \\max(\\tau \\times N,\\; C_{\\min})',
    commentaire: 'Pour la commission du courtier : un taux τ en pb du notionnel N, plancher par un minimum — 2 pb × 80 085 € = 16 €, en dessous du minimum de 25 € : c\'est le minimum qui mord sur les petits ordres.',
    commentaireEn: 'For the broker\'s commission: a rate τ in bp of the notional N, floored by a minimum — 2 bp × €80,085 = €16, below the €25 minimum: the minimum bites on small orders.',
  },
  {
    id: 'm1-f-07',
    moduleId: M1,
    nom: 'Coût total d\'exécution',
    nomEn: 'Total execution cost',
    latex: 'C_{\\text{total}} = Q\\,(a - m) + Q\\,(\\bar{P} - a) + C_{\\text{com}}',
    commentaire: 'Pour le coût complet d\'une exécution, friction et commission comprises : 40 + 45 + 25 = 110 € sur l\'ordre de 80 000 € du chapitre 4 — avant même que le marché ait bougé.',
    commentaireEn: 'For the full cost of an execution, friction and commission included: €40 + €45 + €25 = €110 on the €80,000 order of chapter 4 — before the market has even moved.',
  },
  {
    id: 'm1-f-08',
    moduleId: M1,
    nom: 'Coût d\'exécution en points de base',
    nomEn: 'Execution cost in basis points',
    latex: '\\text{coût}_{\\text{pb}} = \\frac{C_{\\text{total}}}{N} \\times 10\\,000',
    commentaire: 'Pour normaliser un coût d\'exécution par le notionnel et le comparer entre ordres : 110 € sur ≈ 80 000 € ≈ 13,75 pb — des points de base qui composent vite pour un fonds qui tourne son portefeuille.',
    commentaireEn: 'To normalise an execution cost by the notional and compare across orders: €110 on ≈ €80,000 ≈ 13.75 bp — basis points that compound fast for a fund turning over its portfolio.',
  },
  {
    id: 'm1-f-09',
    moduleId: M1,
    nom: 'P&L du market maker',
    nomEn: 'Market maker P&L',
    latex: '\\text{P\\&L}_{MM} = s \\times Q_{\\text{rot}} + I \\times \\Delta P',
    commentaire: 'Pour le revenu du teneur de marché : la fourchette s × le volume tourné en aller-retour, plus (ou moins) la réévaluation de l\'inventaire I porté pendant que le marché bouge de ΔP — le revenu vient de la rotation, pas de la direction.',
    commentaireEn: 'For the market maker\'s revenue: the spread s × the round-trip volume, plus (or minus) the revaluation of the inventory I carried while the market moves by ΔP — revenue comes from turnover, not direction.',
  },
  {
    id: 'm1-f-10',
    moduleId: M1,
    nom: 'Spread de sélection adverse',
    nomEn: 'Adverse-selection spread',
    latex: 'a = \\mu + \\pi\\,\\delta \\qquad b = \\mu - \\pi\\,\\delta \\qquad s^{*} = 2\\,\\pi\\,\\delta',
    commentaire: 'Pour calibrer le spread minimal face aux mieux informés : π part de flux informé, δ demi-amplitude de la nouvelle — 10 % d\'informés sur une valeur à ±1 € imposent 20 centimes de spread ; doublez π, le spread double. C\'est pourquoi il s\'élargit avant les annonces.',
    commentaireEn: 'To calibrate the minimum spread against better-informed traders: π share of informed flow, δ half-amplitude of the news — 10% informed on a ±€1 value force a 20-cent spread; double π and the spread doubles. This is why it widens before announcements.',
  },
];
