import type { Formule } from '../../../engine/types';

const M5 = '05-credit';

export const formules: Formule[] = [
  {
    id: 'm5-f-01',
    moduleId: M5,
    nom: 'Spread de crédit en points de base',
    nomEn: 'Credit spread in basis points',
    latex: 's = (y_{\\text{risqué}} - r_{\\text{sans risque}}) \\times 100',
    commentaire: 'Le thermomètre du module : le supplément de rendement annuel que le marché exige pour porter le doute, en points de base (100 pb = 1 %). L\'ancre : une corporate 5 ans à 5,5 % contre un État à 3,5 % traite à (5,5 − 3,5) × 100 = 200 pb. Les repères de temps calme à réciter : corporate IG euro 80-150 pb, high yield 300-500 pb, distressed > 1 000 pb ; iTraxx Main ~50-80 pb, Crossover ~250-400 pb. Ce spread ne paie pas que le défaut moyen : il empile la perte attendue, la prime de risque (les défauts arrivent en grappes dans les récessions) et la prime de liquidité — c\'est le credit spread puzzle du ch. 1.',
    commentaireEn: 'The module\'s thermometer: the extra annual yield the market demands for carrying the doubt, in basis points (100 bps = 1%). The anchor: a 5-year corporate at 5.5% against a 3.5% government bond trades at (5.5 − 3.5) × 100 = 200 bps. The calm-times benchmarks to recite: euro IG corporate 80-150 bps, high yield 300-500 bps, distressed above 1,000 bps; iTraxx Main ~50-80 bps, Crossover ~250-400 bps. This spread does not only pay for the average default: it stacks the expected loss, the risk premium (defaults come in clusters, in recessions) and the liquidity premium — chapter 1\'s credit spread puzzle.',
  },
  {
    id: 'm5-f-02',
    moduleId: M5,
    nom: 'LGD : la perte en cas de défaut',
    nomEn: 'LGD: loss given default',
    latex: 'LGD = 100 - R',
    commentaire: 'Ce qu\'on perd vraiment au défaut, en % du nominal : le complément du taux de recouvrement R. La convention de marché : R ≈ 40 % pour du senior unsecured, donc LGD = 60 % — et c\'est la séniorité qui fait bouger R : 60-70 % pour du secured, ~20 % ou moins pour du subordonné profond, 8,625 % pour Lehman à l\'enchère de 2008 (une moyenne de temps calme n\'est pas une loi). Même émetteur, même PD : le rang dans la file d\'attente de la faillite change tout le prix. Réflexe du ch. 1 : on ne prête pas à une entreprise, on prête à un RANG de son passif.',
    commentaireEn: 'What you really lose at default, in % of face value: the complement of the recovery rate R. The market convention: R ≈ 40% for senior unsecured, hence LGD = 60% — and seniority is what moves R: 60-70% for secured, ~20% or less for deep subordinated, 8.625% for Lehman at the 2008 auction (a calm-times average is not a law). Same issuer, same PD: the rank in the bankruptcy queue changes the whole price. Chapter 1\'s reflex: you do not lend to a company, you lend to a RANK of its liability structure.',
  },
  {
    id: 'm5-f-03',
    moduleId: M5,
    nom: 'La perte attendue : EL = PD × LGD',
    nomEn: 'Expected loss: EL = PD × LGD',
    latex: 'EL = PD \\times LGD',
    commentaire: 'La formule centrale du module — trois lettres qui résument le métier : combien je m\'attends à perdre par an en portant ce nom. Le cas d\'école : PD 2 %/an, R 40 % donc LGD 60 %, et EL = 1,2 % du nominal par an. C\'est une ESPÉRANCE : l\'année réelle donne 0 (l\'immense majorité des cas) ou −60 % d\'un coup, jamais −1,2 — d\'où les spreads observés systématiquement au-dessus, 5 à 15 fois l\'EL sur l\'investment grade. On ne gagne presque rien à avoir raison, on perd 60 % à avoir tort : c\'est l\'asymétrie qui fait du crédit un métier d\'évitement des perdants (ch. 3).',
    commentaireEn: 'The module\'s central formula — three letters that sum up the trade: how much I expect to lose per year by carrying this name. The textbook case: PD 2%/year, R 40% hence LGD 60%, and EL = 1.2% of face value per year. It is an EXPECTATION: the actual year gives 0 (the vast majority of cases) or −60% at once, never −1.2 — hence observed spreads systematically above it, 5 to 15 times the EL on investment grade. You earn almost nothing for being right, you lose 60% for being wrong: the asymmetry that makes credit a loser-avoidance business (ch. 3).',
  },
  {
    id: 'm5-f-04',
    moduleId: M5,
    nom: 'Spread actuariel théorique',
    nomEn: 'Theoretical actuarial spread',
    latex: 's_{\\text{théorique}} \\approx PD \\times LGD \\quad (\\text{en pb})',
    commentaire: 'La perte attendue convertie dans la langue du desk : PD 2 % et R 40 % « méritent » 120 pb. Le spread observé est SYSTÉMATIQUEMENT au-dessus : une BBB à PD historique ~0,3 %/an mérite 18 pb et cote 120-150 pb — le marché paie cinq à huit fois le défaut moyen. L\'écart n\'est pas une anomalie mais une facture : prime de risque (la perte tombe dans les récessions, quand tout le portefeuille souffre) et prime de liquidité (la moitié du spread IG environ, selon les études). Quiconque encaisse cet écart en portera le coût au pire moment (ch. 1, 3).',
    commentaireEn: 'The expected loss converted into desk language: PD 2% and R 40% "deserve" 120 bps. The observed spread is SYSTEMATICALLY above it: a BBB with a ~0.3%/year historical PD deserves 18 bps and quotes at 120-150 bps — the market pays five to eight times the average default. The gap is not an anomaly but an itemised bill: a risk premium (the loss lands in recessions, when the whole portfolio suffers) and a liquidity premium (roughly half the IG spread, per transaction-data studies). Whoever pockets that gap will bear its cost at the worst moment (ch. 1, 3).',
  },
  {
    id: 'm5-f-05',
    moduleId: M5,
    nom: 'PD implicite dans un spread',
    nomEn: 'Spread-implied PD',
    latex: 'PD_{\\text{implicite}} = \\frac{s}{LGD}',
    commentaire: 'La lecture inverse, celle du desk : « le marché price quoi ? ». Une obligation à 300 pb avec R = 40 % : PD = 3 %/0,60 = 5 % par an — un défaut tous les vingt ans-émetteur. Attention à la nature de ce nombre : c\'est une PD RISQUE-NEUTRE, celle qui rend le spread actuariellement juste, prime de risque comprise — elle surestime la fréquence historique des défauts, souvent d\'un facteur 2 à 5. À l\'oral : « le marché price 5 % de défaut par an » est juste, « le marché prévoit 5 % de défauts » est le piège (ch. 3).',
    commentaireEn: 'The inverse reading, the desk\'s reading: "what is the market pricing?". A bond at 300 bps with R = 40%: PD = 3%/0.60 = 5% per year — one default every twenty issuer-years. Mind what this number is: a RISK-NEUTRAL PD, the one that makes the spread actuarially fair, risk premium included — it overstates the historical default frequency, often by a factor of 2 to 5. In an oral: "the market prices 5% default per year" is correct, "the market forecasts 5% of defaults" is the trap (ch. 3).',
  },
  {
    id: 'm5-f-06',
    moduleId: M5,
    nom: 'Survie cumulée sur n années',
    nomEn: 'Cumulative survival over n years',
    latex: 'P(\\text{survie}) = (1 - PD)^n',
    commentaire: 'La composition discrète annuelle, l\'exact analogue des intérêts composés du m4 — mais en probabilités de survie. L\'ancre : PD 2 % sur 5 ans donne (0,98)^5 = 90,392080 % de survie. La survie ne décroît PAS linéairement : survivre 10 ans à PD 5 % n\'a rien d\'un « 50/50 », c\'est 59,873694 %. Chaque année de survie réduit la population encore exposée au défaut — le fondement du piège additif de la formule suivante (ch. 3).',
    commentaireEn: 'Discrete annual compounding, the exact analogue of m4\'s compound interest — but in survival probabilities. The anchor: PD 2% over 5 years gives (0.98)^5 = 90.392080% survival. Survival does NOT decline linearly: surviving 10 years at PD 5% is nothing like "50/50", it is 59.873694%. Each year of survival shrinks the population still exposed to default — the foundation of the additive trap in the next formula (ch. 3).',
  },
  {
    id: 'm5-f-07',
    moduleId: M5,
    nom: 'Défaut cumulé sur n années',
    nomEn: 'Cumulative default over n years',
    latex: 'P(\\text{défaut cumulé}) = 1 - (1 - PD)^n',
    commentaire: 'LE piège du chapitre 3 : le réflexe additif n × PD est faux, car il compte comme exposés au défaut de l\'année 4 des émetteurs déjà morts en année 2. PD 2 % sur 5 ans : 9,607920 % — pas 10 % ; PD 5 % sur 10 ans : 40,126306 % — pas 50 %. L\'écart grandit avec l\'horizon et avec la PD : les défauts ne s\'additionnent pas, ils se composent. Le mantra à réciter : il faut être vivant pour mourir. C\'est aussi cette formule qui relie les lettres du ch. 2 aux PD annuelles : une BBB à ~0,3 %/an donne ~1,5 % de défaut cumulé à 5 ans, une B à ~4 %/an donne ~18,5 %.',
    commentaireEn: 'THE chapter 3 trap: the additive reflex n × PD is wrong, because it counts issuers already dead in year 2 as exposed to year 4\'s default. PD 2% over 5 years: 9.607920% — not 10%; PD 5% over 10 years: 40.126306% — not 50%. The gap grows with the horizon and with the PD: defaults do not add up, they compound. The mantra to recite: you must be alive to die. This formula is also what links chapter 2\'s letters to annual PDs: a BBB at ~0.3%/year gives ~1.5% cumulative default at 5 years, a B at ~4%/year gives ~18.5%.',
  },
  {
    id: 'm5-f-08',
    moduleId: M5,
    nom: 'Prix d\'une obligation risquée : actualiser à y = r + s',
    nomEn: 'Risky bond price: discount at y = r + s',
    latex: 'P = \\sum_{t=1}^{n} \\frac{c}{(1+y)^t} + \\frac{100}{(1+y)^n}, \\qquad y = r + s',
    commentaire: 'La méthode du desk, d\'une simplicité désarmante : les flux contractuels restent INTACTS — coupons pleins, nominal plein — et tout le risque de défaut est comprimé dans le taux d\'actualisation, gonflé du spread. Le fil rouge du ch. 4 : coupon 5 %, r 3 %, s 200 pb ⇒ y = 5 % = coupon ⇒ prix 100 exactement, l\'ancre « coupon = rendement ⇒ pair » du m4. Baissez le coupon à 4 % : 95,670523 ; le même sans spread vaut 104,579707 — le spread « coûte » 8,909184 points de prix, sans qu\'aucun défaut n\'ait eu lieu. C\'est le pricer du m4 avec une seule nouveauté : le s.',
    commentaireEn: 'The desk\'s method, disarmingly simple: the contractual cash flows stay INTACT — full coupons, full principal — and all the default risk is compressed into the discount rate, inflated by the spread. Chapter 4\'s running example: coupon 5%, r 3%, s 200 bps ⇒ y = 5% = coupon ⇒ price exactly 100, m4\'s "coupon = yield ⇒ par" anchor. Cut the coupon to 4%: 95.670523; the same bond without the spread is worth 104.579707 — the spread "costs" 8.909184 price points, without a single default having occurred. It is m4\'s pricer with one novelty: the s.',
  },
  {
    id: 'm5-f-09',
    moduleId: M5,
    nom: 'Spread duration : le choc de spread sur le prix',
    nomEn: 'Spread duration: the spread shock on price',
    latex: '\\frac{\\Delta P}{P} \\approx -D_{\\text{mod}} \\times \\Delta s',
    commentaire: 'La même dérivée que la duration du m4, mais le choc vient du crédit : une obligation de duration modifiée 4,5 qui s\'écarte de 50 pb perd −2,25 %. Le repère de crise : un portefeuille HY de duration 7 dans un écartement de +300 pb perd −21 % — un book obligataire qui perd comme un book actions, sans qu\'un seul défaut n\'ait eu lieu. Attention à la conversion : 300 pb = 3 %, pas 0,3 %. Et retenez que le corporate se dérive DEUX fois — taux et spread, parfois en sens inverse (flight to quality) : un IG long peut finir une crise presque inchangé, un HY n\'a aucun coussin (ch. 4).',
    commentaireEn: 'The same derivative as m4\'s duration, but the shock comes from credit: a bond with modified duration 4.5 widening by 50 bps loses −2.25%. The crisis benchmark: an HY portfolio of duration 7 in a +300 bps widening loses −21% — a bond book losing like an equity book, without a single default having occurred. Watch the conversion: 300 bps = 3%, not 0.3%. And remember the corporate differentiates TWICE — rates and spread, sometimes in opposite directions (flight to quality): a long IG book can end a crisis almost flat, an HY book has no cushion (ch. 4).',
  },
  {
    id: 'm5-f-10',
    moduleId: M5,
    nom: 'Rendement net des défauts',
    nomEn: 'Default-adjusted net yield',
    latex: '\\text{rendement net} = \\text{rendement nominal} - PD \\times LGD',
    commentaire: 'L\'arithmétique qui démonte le piège du gros coupon : on compare le NET au sans-risque, jamais le brut. Milieu de cycle : 7 % de nominal, PD 3 %, R 40 % ⇒ 7 − 1,8 = 5,2 % net — le risque est payé face à une OAT à 3 %. Retournement : la PD monte à 8 % ⇒ 7 − 4,8 = 2,2 % — MOINS que le sans-risque, pour infiniment plus de risque ; et à PD 5 %, 7 − 3 = 4 % perd déjà contre un sans-risque à 4,5 %. Le gros coupon n\'était pas du rendement : c\'était un remboursement anticipé de pertes quasi certaines, déguisé en revenu. La question du desk devant chaque idée de trade : « net des défauts, il reste quoi ? » (ch. 4, 7).',
    commentaireEn: 'The arithmetic that dismantles the big-coupon trap: you compare the NET to the risk-free rate, never the gross. Mid-cycle: 7% nominal, PD 3%, R 40% ⇒ 7 − 1.8 = 5.2% net — the risk is paid versus a 3% government bond. At the turn: PD rises to 8% ⇒ 7 − 4.8 = 2.2% — LESS than the risk-free rate, for infinitely more risk; and at PD 5%, 7 − 3 = 4% already loses to a 4.5% risk-free. The big coupon was not yield: it was an advance repayment of near-certain losses, disguised as income. The desk\'s question on every trade idea: "net of defaults, what is left?" (ch. 4, 7).',
  },
  {
    id: 'm5-f-11',
    moduleId: M5,
    nom: 'Prime annuelle d\'un CDS (jambe fixe)',
    nomEn: 'Annual CDS premium (fixed leg)',
    latex: '\\text{prime annuelle} = \\text{notionnel} \\times \\frac{s_{\\text{pb}}}{10\\,000}',
    commentaire: 'Ce que paie l\'acheteur de protection tant que l\'entité de référence survit. L\'ancre : 10 M de notionnel à 200 pb = 200 000 € par an, versés par quarts trimestriels aux dates standardisées (20 mars, 20 juin, 20 septembre, 20 décembre). L\'ordre de grandeur en tête : 100 pb = 0,1 M€ par an pour 10 M de notionnel — la protection se compte en dixièmes de pour cent. Depuis le Big Bang ISDA de 2009, le contrat paie un coupon FIXE (100 pb IG, 500 pb HY) et l\'écart avec le juste spread se règle en soulte upfront ≈ Δspread × duration risquée (~4,5 sur un 5 ans) (ch. 5).',
    commentaireEn: 'What the protection buyer pays as long as the reference entity survives. The anchor: 10M of notional at 200 bps = €200,000 per year, paid in quarterly instalments on the standardised dates (20 March, 20 June, 20 September, 20 December). The order of magnitude to keep in mind: 100 bps = €0.1M per year per 10M of notional — protection is counted in tenths of a percent. Since the 2009 ISDA Big Bang, the contract pays a FIXED coupon (100 bps IG, 500 bps HY) and the gap to the fair spread is settled through an upfront ≈ Δspread × risky duration (~4.5 on a 5-year) (ch. 5).',
  },
  {
    id: 'm5-f-12',
    moduleId: M5,
    nom: 'Paiement du CDS au défaut (jambe de protection)',
    nomEn: 'CDS payout at default (protection leg)',
    latex: '\\text{paiement au défaut} = \\text{notionnel} \\times (1 - R)',
    commentaire: 'Le vendeur de protection paie la PERTE, jamais le notionnel : sur 10 M avec R = 40 %, il verse 6 M — le CDS remet l\'acheteur dans la situation d\'un créancier indemnisé, pas d\'un gagnant au loto. Le R est fixé pour tous les contrats à la fois par l\'enchère ISDA : Lehman, octobre 2008 — recouvrement 8,625 %, les vendeurs ont payé 91,375 % du notionnel, et malgré les notionnels bruts les règlements nets n\'ont fait qu\'environ 5,2 Md$. Mesurez l\'asymétrie : encaisser petit et régulier contre une perte rare et massive — le profil du vendeur d\'options du m8, et la position AIG en miniature (ch. 5).',
    commentaireEn: 'The protection seller pays the LOSS, never the notional: on 10M with R = 40%, they pay 6M — the CDS puts the buyer back in the position of a compensated creditor, not a lottery winner. R is set for all contracts at once by the ISDA auction: Lehman, October 2008 — recovery 8.625%, sellers paid 91.375% of notional, and despite the gross notionals net settlements came to only about $5.2bn. Measure the asymmetry: collecting small and regular against a rare, massive loss — m8\'s option-seller profile, and the AIG position in miniature (ch. 5).',
  },
  {
    id: 'm5-f-13',
    moduleId: M5,
    nom: 'Base cash-CDS',
    nomEn: 'Cash-CDS basis',
    latex: '\\text{base} = s_{\\text{CDS}} - s_{\\text{obligation}}',
    commentaire: 'Le même défaut pricé sur deux marchés — l\'écart devrait être nul, et il ne l\'est pas. L\'ancre : CDS 180 pb, obligation 200 pb ⇒ base = −20 pb. Le negative basis trade — acheter l\'obligation, acheter la protection, empocher 20 pb « sans risque de crédit » — n\'est pas sans risque : la position se finance en repo au jour le jour, se valorise chaque soir, et si la base passe de −20 à −80 pb (fin 2008 : plusieurs centaines de pb sur des financières), les appels de marge tombent tout de suite quand la convergence n\'arrive qu\'à maturité. La leçon LTCM du m11 : un arbitrage certain à terme peut tuer son porteur avant l\'échéance — la base négative rémunère le bilan (ch. 5).',
    commentaireEn: 'The same default priced on two markets — the gap should be zero, and it is not. The anchor: CDS 180 bps, bond 200 bps ⇒ basis = −20 bps. The negative basis trade — buy the bond, buy the protection, pocket 20 bps "without credit risk" — is not riskless: the position is funded in overnight repo, marked every evening, and if the basis moves from −20 to −80 bps (late 2008: several hundred bps on financials), margin calls land immediately while convergence only arrives at maturity. M11\'s LTCM lesson: an arbitrage certain at maturity can kill its holder before the end — the negative basis pays for balance sheet (ch. 5).',
  },
  {
    id: 'm5-f-14',
    moduleId: M5,
    nom: 'Perte d\'une tranche de titrisation',
    nomEn: 'Loss on a securitisation tranche',
    latex: '\\text{perte de tranche} = \\min\\!\\left(100,\\ \\max\\!\\left(0,\\ \\frac{L - A}{D - A} \\times 100\\right)\\right)',
    commentaire: 'Tout l\'effet de la titrisation tient dans ce clamp : L est la perte cumulée du pool, A et D les points d\'attache et de détachement de la tranche. Les ancres sur la structure canonique (equity 0-3 %, mezzanine 3-6 %, senior 6-100 %) : à L = 2 %, la mezzanine est intacte ; à L = 5 %, elle a perdu 66,666667 % de SON notionnel ; à L = 8 %, elle est rasée et le senior s\'entame. La tranche transforme une perte continue du pool en falaise — c\'est pourquoi un AAA de CDO pouvait passer de 100 à 30 sans un défaut supplémentaire réalisé : le marché re-priçait la corrélation, donc la forme de la distribution (ch. 6, m11 ch. 5).',
    commentaireEn: 'The entire effect of securitisation sits in this clamp: L is the pool\'s cumulative loss, A and D the tranche\'s attachment and detachment points. The anchors on the canonical structure (equity 0-3%, mezzanine 3-6%, senior 6-100%): at L = 2%, the mezzanine is intact; at L = 5%, it has lost 66.666667% of ITS notional; at L = 8%, it is wiped out and the senior starts eroding. The tranche turns a continuous pool loss into a cliff — which is why a CDO AAA could go from 100 to 30 without one more realised default: the market was repricing correlation, i.e. the shape of the distribution (ch. 6, m11 ch. 5).',
  },
  {
    id: 'm5-f-15',
    moduleId: M5,
    nom: 'Le levier de la tranche : du levier sans emprunt',
    nomEn: 'Tranche leverage: leverage without borrowing',
    latex: '\\text{levier} = \\frac{100}{D - A} \\ \\text{(\\% de tranche par point de pool dans la bande)}',
    commentaire: 'Dans la bande [A, D], chaque point de perte supplémentaire du pool détruit 100/(D − A) % de la tranche : la mezzanine 3-6 % encaisse 33,3 % de destruction par point de pool — une sensibilité de 33 pour 1, sans avoir emprunté un centime. C\'est du levier logé dans la STRUCTURE, invisible dans les ratios classiques : la subordination concentre le risque exactement comme le ferait de la dette. Comparez à l\'investisseur du pool non tranché, qui perd 1 pour 1 : même portefeuille, même perte agrégée — la titrisation ne réduit pas le risque d\'un iota, elle le redistribue le long de la distribution (ch. 6).',
    commentaireEn: 'Inside the [A, D] band, each additional point of pool loss destroys 100/(D − A)% of the tranche: the 3-6% mezzanine takes 33.3% of destruction per point of pool — a 33-to-1 sensitivity, without borrowing a cent. It is leverage lodged in the STRUCTURE, invisible to classic ratios: subordination concentrates risk exactly as debt would. Compare with the untranched pool investor, who loses 1 for 1: same portfolio, same aggregate loss — securitisation does not reduce risk one iota, it redistributes it along the distribution (ch. 6).',
  },
  {
    id: 'm5-f-16',
    moduleId: M5,
    nom: 'Intensité de défaut λ : la survie continue',
    nomEn: 'Default intensity λ: continuous survival',
    latex: 'P(\\text{survie jusqu\'à } t) = e^{-\\lambda t}, \\qquad \\lambda = -\\ln(1 - PD)',
    commentaire: 'La version continue des modèles professionnels (GoFurther du ch. 3) : le défaut est le premier saut d\'un processus de Poisson, et la survie devient une exponentielle — l\'analogue exact du passage à la composition continue du m4. Le lien avec la version discrète : e^(−λ) = 1 − PD, donc pour PD 2 %, λ = 2,0203 % — quasi identique, car ln(1 − x) ≈ −x pour x petit. Le rendement du détour, c\'est le triangle du crédit : sous intensité constante, s ≈ λ × LGD — EL = PD × LGD n\'en était que la version discrète, et tout le bootstrapping des courbes de survie des CDS repose sur ce λ. À l\'oral, la version discrète annuelle suffit : l\'examinateur veut vérifier que vous composez la survie, pas que vous savez intégrer une exponentielle.',
    commentaireEn: 'The continuous version used by professional models (ch. 3\'s GoFurther): default is the first jump of a Poisson process, and survival becomes an exponential — the exact analogue of m4\'s move to continuous compounding. The link with the discrete version: e^(−λ) = 1 − PD, so for PD 2%, λ = 2.0203% — nearly identical, since ln(1 − x) ≈ −x for small x. The payoff of the detour is the credit triangle: under constant intensity, s ≈ λ × LGD — EL = PD × LGD was only its discrete version, and all CDS survival-curve bootstrapping rests on this λ. In an oral, the discrete annual version is enough: the examiner wants to check you compound survival, not that you can integrate an exponential.',
  },
];
