import type { Formule } from '../../../engine/types';

const M9 = '09-produits-structures';

export const formules: Formule[] = [
  {
    id: 'm9-f-01',
    moduleId: M9,
    nom: 'Prix du zéro-coupon',
    nomEn: 'Zero-coupon price',
    latex: '\\text{ZC} = 100 \\cdot e^{-rT}',
    commentaire: 'La brique qui garantit le capital : placer 86,07 aujourd\'hui (r = 3 %, T = 5 ans) redonne 100 à l\'échéance, quoi qu\'il arrive à la Bourse — un placement de taux, pas un tour de magie. Conventions du desk : actualisation CONTINUE, prix en % du nominal. Et la banque n\'achète pas ce zéro-coupon, elle l\'EST : le client lui prête 100, c\'est du funding — plus la signature est fragile, plus la formule est belle (ch. 1).',
    commentaireEn: 'The brick that guarantees the capital: investing 86.07 today (r = 3%, T = 5 years) returns 100 at maturity, whatever the stock market does — a rates investment, not a magic trick. Desk conventions: CONTINUOUS discounting, prices in % of notional. And the bank does not buy this zero-coupon, it IS it: the client lends it 100, that is funding — the weaker the signature, the prettier the formula (ch. 1).',
  },
  {
    id: 'm9-f-02',
    moduleId: M9,
    nom: 'Budget d\'options',
    nomEn: 'Options budget',
    latex: '\\text{budget} = 100 - \\text{ZC} - \\text{marge}',
    commentaire: 'La contrainte centrale du métier : 100 − 86,07 − 1 = 12,93. Sur 100 confiés par le client, 86,07 dorment dans la garantie, 1 rémunère la chaîne, et 12,93 seulement partent acheter de la promesse conditionnelle. Fonction croissante des taux : taux hauts, ZC bon marché, budget confortable ; taux nuls, budget squelettique — une décennie d\'histoire du marché tient dans cette soustraction (ch. 1).',
    commentaireEn: 'The central constraint of the trade: 100 − 86.07 − 1 = 12.93. Of the client\'s 100, 86.07 sleep in the guarantee, 1 pays the chain, and only 12.93 go out to buy conditional promises. An increasing function of rates: high rates, cheap ZC, comfortable budget; zero rates, skeletal budget — a decade of market history fits in this subtraction (ch. 1).',
  },
  {
    id: 'm9-f-03',
    moduleId: M9,
    nom: 'Participation d\'un capital garanti',
    nomEn: 'Participation rate of a capital-guaranteed product',
    latex: 'p = \\frac{\\text{budget}}{\\text{prix du call ATM}}',
    commentaire: 'LA formule du module : combien de calls le budget peut-il payer ? 12,93/24,33 = 0,531, soit 53,1 % de la hausse (r = 3 %, 5 ans, vol 20 %). À r = 5 % : 21,12/29,14 = 72,5 % — la chaîne à réciter : taux ↑ ⇒ ZC ↓ ⇒ budget ↑ ⇒ participation ↑. Détecteur du ratio inversé : si le budget est plus petit que le prix du call, la participation doit être inférieure à 100 % (ch. 2).',
    commentaireEn: 'THE formula of the module: how many calls can the budget pay for? 12.93/24.33 = 0.531, i.e. 53.1% of the upside (r = 3%, 5 years, vol 20%). At r = 5%: 21.12/29.14 = 72.5% — the chain to recite: rates ↑ ⇒ ZC ↓ ⇒ budget ↑ ⇒ participation ↑. Inverted-ratio detector: if the budget is smaller than the call price, the participation must be below 100% (ch. 2).',
  },
  {
    id: 'm9-f-04',
    moduleId: M9,
    nom: 'Payoff du capital garanti',
    nomEn: 'Capital-guaranteed payoff',
    latex: '\\text{remboursement} = 100 + p \\times \\max\\!\\left(\\frac{S_T - S_0}{S_0},\\ 0\\right) \\times 100',
    commentaire: 'Le payoff lu terme à terme : les 100 fermes sont le zéro-coupon, le max(·, 0) sur la performance est un call ATM — le coude du module 8, ni plus ni moins. Lecture client (p = 53,1 %) : indice à +40 %, remboursement 100 + 0,531 × 40 = 121,26 ; indice à −30 %, remboursement 100 tout rond — le pire scénario est un coût d\'opportunité, pas une perte de capital (ch. 2).',
    commentaireEn: 'The payoff read term by term: the firm 100 is the zero-coupon, the max(·, 0) on performance is an ATM call — module 8\'s kink, nothing more. Client reading (p = 53.1%): index at +40%, redemption 100 + 0.531 × 40 = 121.26; index at −30%, redemption exactly 100 — the worst case is an opportunity cost, not a capital loss (ch. 2).',
  },
  {
    id: 'm9-f-05',
    moduleId: M9,
    nom: 'Coupon d\'un reverse convertible',
    nomEn: 'Reverse convertible coupon',
    latex: '\\text{coupon annuel} = \\frac{100 - \\text{ZC} + \\text{prime du put}}{e^{-rT} \\cdot T}',
    commentaire: 'Le disponible du structureur — le client prête 100 (ZC à 95,12) et VEND un put ATM (prime 5,57) — capitalisé jusqu\'à maturité puis réparti par année : 10,45/0,9512 = 10,99 % (canonique du m8 : S = K = 100, r = 5 %, vol 20 %, 1 an). Décomposition qui dit tout : 5,13 de taux sans risque capitalisé + 5,86 de prime — tout coupon au-dessus du taux est le prix d\'un risque vendu (ch. 3).',
    commentaireEn: 'The structurer\'s available cash — the client lends 100 (ZC at 95.12) and SELLS an ATM put (premium 5.57) — compounded to maturity then spread per year: 10.45/0.9512 = 10.99% (m8 canonical: S = K = 100, r = 5%, vol 20%, 1 year). The decomposition that says it all: 5.13 of compounded risk-free rate + 5.86 of premium — any coupon above the rate is the price of a risk sold (ch. 3).',
  },
  {
    id: 'm9-f-06',
    moduleId: M9,
    nom: 'Payoff du reverse convertible à maturité',
    nomEn: 'Reverse convertible payoff at maturity',
    latex: '\\text{flux} = \\text{coupon} + \\begin{cases} 100 & \\text{si } S_T \\geq K \\\\ 100 \\times S_T / K & \\text{sinon (remise en titres)} \\end{cases}',
    commentaire: 'Le coupon tombe TOUJOURS — la brochure ne ment pas ; c\'est le capital qui porte le risque : sous le strike, remise en titres (100/K actions valant S_T chacune). À S_T = 70 : 70 + 10,99 = 80,99, soit −19,01 — moins que l\'actionnaire (−30), mais le coupon était le PRIX du risque, pas une consolation par-dessus. Gain plafonné à 110,99, point mort vers 89 (ch. 3).',
    commentaireEn: 'The coupon ALWAYS lands — the brochure does not lie; the capital carries the risk: below the strike, physical settlement (100/K shares worth S_T each). At S_T = 70: 70 + 10.99 = 80.99, i.e. −19.01 — less than the shareholder (−30), but the coupon was the PRICE of that risk, not a consolation on top. Gain capped at 110.99, break-even near 89 (ch. 3).',
  },
  {
    id: 'm9-f-07',
    moduleId: M9,
    nom: 'Payoff du down-and-in put',
    nomEn: 'Down-and-in put payoff',
    latex: '\\text{DIP}_T = \\max(K - S_T,\\ 0) \\times \\mathbb{1}\\!\\left\\{\\min_{t \\le T} S_t \\le B\\right\\}',
    commentaire: 'Le put qui doit NAÎTRE : il ne paie que si le minimum de la trajectoire a touché la barrière. Payoff inférieur ou égal à la vanille sur chaque trajectoire, donc prix inférieur ou égal, sans aucun modèle : 5,57 pour la vanille canonique, 0,24 à barrière 60. Et si B ≥ K, tout payoff positif implique la barrière touchée (min ≤ S_T < K ≤ B) : le DIP redevient exactement le put vanille — un test de cohérence du pricer (ch. 5).',
    commentaireEn: 'The put that must be BORN: it pays only if the path\'s minimum has touched the barrier. Payoff less than or equal to the vanilla\'s on every path, hence a price less than or equal, with no model at all: 5.57 for the canonical vanilla, 0.24 at barrier 60. And if B ≥ K, any positive payoff implies the barrier was hit (min ≤ S_T < K ≤ B): the DIP becomes exactly the vanilla put again — one of the pricer\'s consistency tests (ch. 5).',
  },
  {
    id: 'm9-f-08',
    moduleId: M9,
    nom: 'Payoff de l\'autocall (Athena)',
    nomEn: 'Autocall (Athena) payoff',
    latex: '\\text{flux} = \\begin{cases} 100 + c \\times i & \\text{rappel à la première date } i \\text{ où } S_i \\geq S_0 \\\\ 100 & \\text{jamais rappelé et } S_N \\geq B_{\\text{prot}} \\\\ 100 \\times S_N / S_0 & \\text{jamais rappelé et } S_N < B_{\\text{prot}} \\end{cases}',
    commentaire: 'La mécanique Athena : rappel automatique dès que le sous-jacent repasse au niveau initial à une date d\'observation, coupon à effet mémoire (100 + 7 × 3 = 121 pour un rappel à l\'an 3 après 93 et 97), barrière de protection observée à maturité seulement. Le remboursement dégradé S_N/S_0 sous la barrière EST un put down-and-in vendu par le client — c\'est là que loge le rendement (ch. 4).',
    commentaireEn: 'The Athena mechanics: automatic call as soon as the underlying is back at its initial level on an observation date, memory coupon (100 + 7 × 3 = 121 for a call in year 3 after 93 and 97), protection barrier observed at maturity only. The degraded redemption S_N/S_0 below the barrier IS a down-and-in put sold by the client — that is where the yield lives (ch. 4).',
  },
  {
    id: 'm9-f-09',
    moduleId: M9,
    nom: 'Prix de l\'autocall : espérance actualisée du flux',
    nomEn: 'Autocall price: discounted expected cash flow',
    latex: '\\text{prix} = \\mathbb{E}^{\\mathbb{Q}}\\!\\left[\\, e^{-r\\tau} \\times \\text{flux}_\\tau \\,\\right]',
    commentaire: 'Le principe du module 8, intact : le prix est l\'espérance risque-neutre du flux, actualisé en continu à sa date τ — ALÉATOIRE ici, car le rappel peut tomber à chaque anniversaire. Aucune formule fermée : Monte-Carlo. Sur l\'Athena du cours (coupon 7 %, r = 3 %, vol 20 %), 200 000 trajectoires donnent ≈ 98,0 pour un produit vendu 100 — les 2 points sont la marge, et le coupon équitable serait ≈ 8,65 % (ch. 4).',
    commentaireEn: 'Module 8\'s principle, intact: the price is the risk-neutral expectation of the cash flow, continuously discounted at its date τ — RANDOM here, since the call can land on any anniversary. No closed formula: Monte Carlo. On the course\'s Athena (7% coupon, r = 3%, vol 20%), 200,000 paths give ≈ 98.0 for a product sold at 100 — the 2 points are the margin, and the fair coupon would be ≈ 8.65% (ch. 4).',
  },
  {
    id: 'm9-f-10',
    moduleId: M9,
    nom: 'Payoff du call worst-of',
    nomEn: 'Worst-of call payoff',
    latex: '\\text{payoff} = 100 \\times \\max\\!\\left(\\min\\!\\left(\\frac{S_T^{(1)}}{S_0^{(1)}},\\ \\frac{S_T^{(2)}}{S_0^{(2)}}\\right) - k,\\ 0\\right)',
    commentaire: 'Seul le MINIMUM des performances compte (strike k en ratio, 1 = ATM) : pour gagner, il faut que tous montent ; pour décevoir, il suffit qu\'un seul trébuche. Sur deux jumeaux (100, vol 20 %, r = 5 %, 1 an, strike 100 %) : 10,43 à ρ = 1 — le call vanille retrouvé —, 5,40 à ρ = 0,5, 3,31 à ρ = 0. La dispersion enfonce le pire, et le desk exploite les deux faces : participation affichée plus grosse, DIP vendu plus cher (ch. 5).',
    commentaireEn: 'Only the MINIMUM of the performances counts (strike k as a ratio, 1 = ATM): to win, all must rise; to disappoint, one stumble is enough. On two twins (100, vol 20%, r = 5%, 1 year, 100% strike): 10.43 at ρ = 1 — the vanilla call recovered —, 5.40 at ρ = 0.5, 3.31 at ρ = 0. Dispersion sinks the worst, and the desk exploits both faces: bigger displayed participation, dearer DIP sold (ch. 5).',
  },
  {
    id: 'm9-f-11',
    moduleId: M9,
    nom: 'Corrélation par Cholesky en dimension 2',
    nomEn: '2D Cholesky correlation',
    latex: 'z_2 = \\rho\\, z_1 + \\sqrt{1 - \\rho^2}\\,\\varepsilon',
    commentaire: 'La recette pour corréler deux aléas : une part ρ de choc commun, une part √(1 − ρ²) de choc propre (ε indépendant de z₁). Trois vérifications : V(z₂) = ρ² + (1 − ρ²) = 1, corr(z₁, z₂) = ρ exactement, et les limites — ρ = 1 ⇒ z₂ = z₁ (le panier redevient mono sous-jacent), ρ = 0 ⇒ indépendance. En dimension supérieure, la même idée devient la factorisation LLᵀ de la matrice de corrélation (ch. 5).',
    commentaireEn: 'The recipe for correlating two random draws: a share ρ of common shock, a share √(1 − ρ²) of own shock (ε independent of z₁). Three checks: V(z₂) = ρ² + (1 − ρ²) = 1, corr(z₁, z₂) = ρ exactly, and the limits — ρ = 1 ⇒ z₂ = z₁ (the basket becomes single-underlying again), ρ = 0 ⇒ independence. In higher dimensions, the same idea becomes the LLᵀ factorisation of the correlation matrix (ch. 5).',
  },
  {
    id: 'm9-f-12',
    moduleId: M9,
    nom: 'Pas lognormal sous le drift risque-neutre',
    nomEn: 'Lognormal step under the risk-neutral drift',
    latex: 'S_{t+\\Delta t} = S_t \\times \\exp\\!\\left[\\left(r - \\frac{\\sigma^2}{2}\\right)\\Delta t + \\sigma\\sqrt{\\Delta t}\\,z\\right]',
    commentaire: 'Le pas de simulation du pricer, avec deux choix qui sont des points d\'oral. Le drift est r — pas le rendement espéré réel : on price sous le monde risque-neutre du module 8. Et il est amputé de σ²/2, la correction de convexité de la lognormale : sans elle, E[S_T] vaudrait S₀·e^{(r+σ²/2)T} et l\'actif battrait le taux sans risque — violation de la martingale. Avec elle : E[S_T] = S₀·e^{rT}, le forward — testé : moyenne simulée 105,13 pour 100·e^{0,05} (ch. 6).',
    commentaireEn: 'The pricer\'s simulation step, with two choices that are oral-exam points. The drift is r — not the real expected return: we price under module 8\'s risk-neutral world. And it is docked by σ²/2, the lognormal\'s convexity correction: without it, E[S_T] would be S₀·e^{(r+σ²/2)T} and the asset would beat the risk-free rate — a martingale violation. With it: E[S_T] = S₀·e^{rT}, the forward — tested: simulated mean 105.13 for 100·e^{0.05} (ch. 6).',
  },
  {
    id: 'm9-f-13',
    moduleId: M9,
    nom: 'Prix Monte-Carlo',
    nomEn: 'Monte Carlo price',
    latex: '\\hat{V} = e^{-rT} \\times \\frac{1}{n}\\sum_{i=1}^{n} \\text{payoff}_i',
    commentaire: 'Les quatre gestes de tout pricer : simuler des trajectoires risque-neutres, calculer le payoff de chacune, moyenner (la loi des grands nombres fait converger vers l\'espérance), actualiser en continu. Le test avant tout usage : braqué sur le call canonique (Black-Scholes 10,4506), le moteur du cours donne 10,4500 au million de tirages — on ne fait confiance à la machine sur ce qu\'on ne sait pas calculer que parce qu\'elle est juste sur ce qu\'on sait calculer (ch. 6).',
    commentaireEn: 'Every pricer\'s four moves: simulate risk-neutral paths, compute each payoff, average (the law of large numbers converges to the expectation), discount continuously. The test before any use: aimed at the canonical call (Black-Scholes 10.4506), the course\'s engine gives 10.4500 at one million draws — we only trust the machine on what we cannot compute because it is right on what we can (ch. 6).',
  },
  {
    id: 'm9-f-14',
    moduleId: M9,
    nom: 'Erreur-type du prix Monte-Carlo',
    nomEn: 'Monte Carlo standard error',
    latex: '\\text{erreur-type} = \\frac{\\sigma_{\\text{payoff}}}{\\sqrt{n}}',
    commentaire: 'Le théorème central limite appliqué au pricing : σ_payoff ≈ 14,8 sur le call canonique, donc 0,15 à dix mille tirages, 0,047 à cent mille, 0,015 au million — diviser l\'erreur par 10 exige CENT fois plus de simulations, et de temps. Un prix MC sans son erreur-type ne veut rien dire : la phrase complète est « 10,50 ± 0,09 à 95 % » — et comparer deux prix dont l\'écart est sous les erreurs-types, c\'est lire du bruit (ch. 6).',
    commentaireEn: 'The central limit theorem applied to pricing: σ_payoff ≈ 14.8 on the canonical call, hence 0.15 at ten thousand draws, 0.047 at a hundred thousand, 0.015 at a million — dividing the error by 10 requires a HUNDRED times more simulations, and time. An MC price without its standard error means nothing: the full sentence is "10.50 ± 0.09 at 95%" — and comparing two prices whose gap is below their standard errors is reading noise (ch. 6).',
  },
  {
    id: 'm9-f-15',
    moduleId: M9,
    nom: 'Marge commerciale annualisée',
    nomEn: 'Annualised commercial margin',
    latex: '\\text{marge annualisée} = \\frac{\\text{marge totale}}{T}',
    commentaire: 'La convention d\'affichage des desks : la marge totale, encaissée le jour 1, répartie linéairement sur la durée FACIALE — 2,5 % sur 5 ans « coûte » 0,5 % par an au client. Finesse d\'oral sur l\'autocall : rappelé en 2,2 ans en moyenne, la marge annualisée sur la vie EFFECTIVE dépasse 1 % — et chaque rappel ramène le client vers un nouveau produit, avec une nouvelle marge (ch. 7).',
    commentaireEn: 'The desks\' display convention: the total margin, pocketed on day 1, spread linearly over the STATED life — 2.5% over 5 years "costs" the client 0.5% per year. Oral-exam nuance on the autocall: called after 2.2 years on average, the margin annualised over the EFFECTIVE life exceeds 1% — and every call brings the client back for a new product, with a new margin (ch. 7).',
  },
  {
    id: 'm9-f-16',
    moduleId: M9,
    nom: 'Décomposition du prix à l\'émission',
    nomEn: 'Issue-price decomposition',
    latex: '\\underbrace{100}_{\\text{payé par le client}} = \\underbrace{\\text{ZC}}_{\\text{capital}} + \\underbrace{\\text{options}}_{\\text{rendement}} + \\underbrace{\\text{marge}}_{\\text{structureur + distributeur}}',
    commentaire: 'L\'équation-bilan de l\'émission : la marge n\'est pas une ligne de frais payée en plus, elle est À L\'INTÉRIEUR du prix — chaque euro de marge est un euro de budget d\'options en moins, donc un coupon plus bas ou une barrière moins protectrice. D\'où une valeur à l\'émission de 97 à 99 pour 100 payés (97,5 sur l\'Athéna du cours), publiée depuis 2018 dans le KID du règlement PRIIPs (ch. 7).',
    commentaireEn: 'The issuance balance-sheet equation: the margin is not a fee line paid on top, it sits INSIDE the price — every euro of margin is one euro less of options budget, hence a lower coupon or a less protective barrier. Whence an issue value of 97 to 99 for 100 paid (97.5 on the course\'s Athena), published since 2018 in the PRIIPs regulation\'s KID (ch. 7).',
  },
];
