import type { Flashcard } from '../../../engine/types';

const M3 = '03-actions-indices';

// 120 cartes : 30 definitions, 16 formules, 14 ordres de grandeur, 24 pieges,
// 22 reflexes jury, 14 calculs mentaux.
// Couverture : ch1 l'action, ch2 DDM & DCF, ch3 multiples, ch4 indices,
// ch5 vie du titre, ch6 IPO, ch7 short selling & efficience.
export const flashcards: Flashcard[] = [
  // ───────────────────────── Chapitre 1 — L'action, part de propriété ─────────────────────────
  {
    id: 'm3-fc-001',
    moduleId: M3,
    tags: ['definition', 'action'],
    recto: 'Une action, c\'est quoi ?',
    verso: 'Un titre de propriété sur une fraction du capital social, avec trois droits : les bénéfices, le vote en AG, l\'actif net en liquidation. Aucune promesse : ni revenu garanti, ni remboursement, ni échéance — et dernier rang en cas de faillite.',
    rectoEn: 'What is a share?',
    versoEn: 'A title of ownership over a fraction of the share capital, with three rights: profits, the vote at the general meeting, net assets in liquidation. No promise: no guaranteed income, no repayment, no maturity — and last in line in bankruptcy.',
  },
  {
    id: 'm3-fc-002',
    moduleId: M3,
    tags: ['definition', 'action'],
    recto: 'Le dividende, c\'est quoi — et qu\'advient-il du reste du bénéfice ?',
    verso: 'La part du bénéfice distribuée, votée chaque année en AG, jamais garantie. Le reste est mis en réserve : il grossit les fonds propres et finance la croissance — une société sans dividende peut parfaitement enrichir ses actionnaires.',
    rectoEn: 'What is a dividend — and what happens to the rest of the profit?',
    versoEn: 'The distributed share of profit, voted each year at the general meeting, never guaranteed. The rest goes to reserves: it grows equity and funds growth — a company paying no dividend can perfectly well enrich its shareholders.',
  },
  {
    id: 'm3-fc-003',
    moduleId: M3,
    tags: ['definition', 'action'],
    recto: 'Le BPA (bénéfice par action), c\'est quoi ?',
    verso: 'Bénéfice net divisé par le nombre de titres — 8 € chez Valmer. La brique du PER. En anglais : EPS. Vigilance : il arrive après les choix comptables, et les rachats d\'actions le gonflent en réduisant le dénominateur.',
    rectoEn: 'What is EPS (earnings per share)?',
    versoEn: 'Net profit divided by the number of shares — €8 at Valmer. The building block of the P/E. Caution: it comes after accounting choices, and share buybacks inflate it by shrinking the denominator.',
  },
  {
    id: 'm3-fc-004',
    moduleId: M3,
    tags: ['definition', 'action'],
    recto: 'La capitalisation boursière, c\'est quoi — et sur quels titres se calcule-t-elle ?',
    verso: 'Cours × nombre TOTAL de titres émis, blocs verrouillés compris : Valmer, 120 € × 50 M = 6 Md€. C\'est la valeur des capitaux propres — un stock, à ne jamais comparer à un volume quotidien.',
    rectoEn: 'What is market capitalization — and on which shares is it computed?',
    versoEn: 'Price × TOTAL number of shares issued, locked-up blocks included: Valmer, €120 × 50M = €6bn. It is the value of equity — a stock variable, never to be compared with a daily volume.',
  },
  {
    id: 'm3-fc-005',
    moduleId: M3,
    tags: ['definition', 'action'],
    recto: 'Le flottant (free float), c\'est quoi ?',
    verso: 'La part du capital réellement négociable, hors blocs stables (État, familles, autocontrôle). Valmer : 65 % de 6 Md€ = 3,9 Md€ disponibles. C\'est sur le flottant que les grands indices pondèrent leurs constituants.',
    rectoEn: 'What is the free float?',
    versoEn: 'The share of capital actually tradable, excluding stable blocks (state, founding families, treasury shares). Valmer: 65% of €6bn = €3.9bn available. Major indices weight their constituents on the float.',
  },
  {
    id: 'm3-fc-006',
    moduleId: M3,
    tags: ['definition', 'action'],
    recto: 'La valeur d\'entreprise (EV), c\'est quoi ?',
    verso: 'Capitalisation + dette nette : le prix de l\'outil économique entier, ce que débourse l\'acquéreur qui rachète les actions ET reprend la dette. 900 M€ de capi + 300 M€ de dette nette = 1 200 M€. Une trésorerie nette diminue l\'EV.',
    rectoEn: 'What is enterprise value (EV)?',
    versoEn: 'Market cap + net debt: the price of the entire economic asset, what an acquirer pays to buy the shares AND take on the debt. €900m cap + €300m net debt = €1,200m. Net cash reduces EV.',
  },
  {
    id: 'm3-fc-007',
    moduleId: M3,
    tags: ['definition', 'action'],
    recto: 'Le taux de distribution (payout), c\'est quoi ?',
    verso: 'Le rapport dividende/bénéfice : un payout de 45 % distribue 45 centimes par euro de bénéfice, le reste est réinvesti. Son complément est le taux de rétention b = 1 − payout — le moteur de la croissance soutenable g = ROE × b.',
    rectoEn: 'What is the payout ratio?',
    versoEn: 'The dividend-to-earnings ratio: a 45% payout distributes 45 cents per euro of profit, the rest is reinvested. Its complement is the retention rate b = 1 − payout — the engine of sustainable growth g = ROE × b.',
  },
  {
    id: 'm3-fc-008',
    moduleId: M3,
    tags: ['formule', 'action'],
    recto: 'Formule du taux de distribution, avec l\'exemple de la ligne de cote ?',
    verso: 'Payout = dividende / BPA. Valmer : 3,60 / 8,00 = 45 % — et le taux de rétention vaut b = 1 − 45 % = 55 %, la part du bénéfice qui reste travailler dans l\'entreprise.',
    rectoEn: 'Payout ratio formula, with the quote-line example?',
    versoEn: 'Payout = dividend / EPS. Valmer: 3.60 / 8.00 = 45% — and the retention rate is b = 1 − 45% = 55%, the share of profit left working inside the company.',
  },
  {
    id: 'm3-fc-009',
    moduleId: M3,
    tags: ['formule', 'action'],
    recto: 'Formule du rendement du dividende — et sa cohérence avec le PER ?',
    verso: 'Rendement = dividende / cours : 3,60 / 120 = 3 %. Vérification croisée : rendement = payout / PER = 45 % / 15 = 3 %. Une ligne de cote est un système cohérent, pas une liste de chiffres indépendants.',
    rectoEn: 'Dividend yield formula — and its consistency with the P/E?',
    versoEn: 'Yield = dividend / price: 3.60 / 120 = 3%. Cross-check: yield = payout / P/E = 45% / 15 = 3%. A quote line is a coherent system, not a list of independent numbers.',
  },
  {
    id: 'm3-fc-010',
    moduleId: M3,
    tags: ['piege', 'action'],
    recto: 'Acheter 100 % des actions de Valmer coûte 6 Md€. L\'entreprise « coûte » donc 6 Md€ ?',
    verso: 'Non : l\'acquéreur récupère aussi la dette. Avec 2 Md€ de dette nette, l\'affaire coûte économiquement 8 Md€ — la valeur d\'entreprise. Capitalisation = capitaux propres seulement. Réflexe : au mot « capitalisation », demandez où est passée la dette.',
    rectoEn: 'Buying 100% of Valmer\'s shares costs €6bn. So the company "costs" €6bn?',
    versoEn: 'No: the acquirer also inherits the debt. With €2bn of net debt, the deal economically costs €8bn — the enterprise value. Market cap = equity only. Reflex: at the word "capitalization", ask where the debt went.',
  },
  {
    id: 'm3-fc-011',
    moduleId: M3,
    tags: ['piege', 'action'],
    recto: 'La capitalisation se calcule-t-elle sur le flottant ?',
    verso: 'Non : sur la TOTALITÉ des titres émis, blocs verrouillés compris. Le flottant, lui, sert à pondérer les indices — Hermès, contrôlée aux deux tiers par la famille, pèse dans le CAC 40 bien moins que sa capitalisation totale ne le suggère.',
    rectoEn: 'Is market cap computed on the free float?',
    versoEn: 'No: on ALL shares issued, locked blocks included. The float is what weights indices — Hermès, two-thirds family-controlled, weighs far less in the CAC 40 than its total capitalization would suggest.',
  },
  {
    id: 'm3-fc-012',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'action'],
    recto: 'Capitalisation boursière mondiale : ordre de grandeur et hiérarchie ?',
    verso: '≈ 130 000 Md$ — un stock. Les États-Unis ≈ la moitié ; plusieurs méga-capitalisations dépassent chacune 3 000 Md$ (plus que le PIB français) ; tout le CAC 40 pèse ≈ 2 500 Md€. Retenez la hiérarchie plus que les chiffres exacts.',
    rectoEn: 'World market capitalization: order of magnitude and hierarchy?',
    versoEn: '≈ $130tn — a stock variable. The United States ≈ half; several mega-caps each exceed $3tn (more than France\'s GDP); the entire CAC 40 weighs ≈ €2.5tn. Remember the hierarchy more than the exact figures.',
  },
  {
    id: 'm3-fc-013',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'action'],
    recto: 'La prime de risque actions : ordre de grandeur historique ?',
    verso: '4 à 6 points de plus par an que le sans-risque, sur longue période, pour les grands marchés développés — un ordre de grandeur historique, variable selon les périodes et les méthodes, à citer avec prudence. Capitalisé sur des décennies : des écarts de patrimoine considérables.',
    rectoEn: 'The equity risk premium: historical order of magnitude?',
    versoEn: '4 to 6 points a year above the risk-free rate, over the long run, on major developed markets — a historical order of magnitude, varying with periods and methods, to be quoted with caution. Compounded over decades: massive wealth gaps.',
  },
  {
    id: 'm3-fc-014',
    moduleId: M3,
    tags: ['reflexe-jury', 'action'],
    recto: 'Le jury : « Comparez méthodiquement une action et une obligation. »',
    verso: 'Réflexe : cinq lignes. Créance vs propriété ; coupon contractuel vs dividende jamais garanti ; maturité fixée vs aucune échéance ; créancier servi selon son rang vs dernier servi ; potentiel plafonné vs illimité à la hausse, perte bornée à la mise. Tout est dans les deux premières : promesse contre espérance.',
    rectoEn: 'The panel: "Compare a share and a bond methodically."',
    versoEn: 'Reflex: five lines. Claim vs ownership; contractual coupon vs never-guaranteed dividend; fixed maturity vs no horizon; creditor ranked in line vs paid last; capped upside vs unlimited upside, loss bounded by the stake. The first two say it all: a promise versus a hope.',
  },
  {
    id: 'm3-fc-015',
    moduleId: M3,
    tags: ['reflexe-jury', 'action'],
    recto: 'Le jury : « Pourquoi une action doit-elle rapporter plus qu\'une obligation du même émetteur ? »',
    verso: 'Réflexe : l\'actionnaire ne détient aucune promesse — revenu incertain, pas d\'échéance, dernier rang. Personne n\'accepte ce risque sans supplément d\'espérance de rendement : la prime de risque actions, ≈ 4 à 6 points par an sur longue période.',
    rectoEn: 'The panel: "Why must a share yield more than a bond from the same issuer?"',
    versoEn: 'Reflex: the shareholder holds no promise — uncertain income, no maturity, last rank. Nobody accepts that risk without an extra expected return: the equity risk premium, ≈ 4 to 6 points a year over the long run.',
  },
  {
    id: 'm3-fc-016',
    moduleId: M3,
    tags: ['calcul-mental', 'action'],
    recto: 'De tête : 50 millions de titres à 120 €, flottant 65 % — capitalisation et capital négociable ?',
    verso: 'Capi = 120 × 50 M = 6 Md€ ; négociable = 6 × 0,65 = 3,9 Md€. Routine : cours × titres TOTAUX pour la capi, puis × flottant pour ce que le marché peut réellement acheter.',
    rectoEn: 'In your head: 50 million shares at €120, 65% float — market cap and tradable capital?',
    versoEn: 'Cap = 120 × 50M = €6bn; tradable = 6 × 0.65 = €3.9bn. Routine: price × TOTAL shares for the cap, then × float for what the market can actually buy.',
  },

  // ───────────────────────── Chapitre 2 — Valoriser par les flux : DDM et DCF ─────────────────────────
  {
    id: 'm3-fc-017',
    moduleId: M3,
    tags: ['definition', 'valorisation'],
    recto: 'Le DDM (dividend discount model), c\'est quoi ?',
    verso: 'La valeur d\'une action = la somme de ses dividendes espérés actualisés : $V_0 = \\sum E[D_t]/(1+r)^t$. Le prix de revente n\'est que la valeur des dividendes suivants : tout se ramène aux dividendes. Gordon en est la version à croissance constante.',
    rectoEn: 'What is the DDM (dividend discount model)?',
    versoEn: 'A share\'s value = the sum of its expected dividends discounted: $V_0 = \\sum E[D_t]/(1+r)^t$. The resale price is just the value of the following dividends: everything reduces to dividends. Gordon is its constant-growth version.',
  },
  {
    id: 'm3-fc-018',
    moduleId: M3,
    tags: ['definition', 'valorisation'],
    recto: 'Le DCF (discounted cash flows), c\'est quoi ?',
    verso: 'Actualiser les FCF que l\'entreprise génère — distribués ou non — au WACC : horizon explicite de 3 à 10 ans + valeur terminale. Le résultat est une valeur d\'ENTREPRISE : retranchez la dette nette pour obtenir la valeur des actions.',
    rectoEn: 'What is the DCF (discounted cash flows)?',
    versoEn: 'Discount the FCF the company generates — distributed or not — at the WACC: an explicit horizon of 3 to 10 years + a terminal value. The result is an ENTERPRISE value: subtract net debt to get the equity value.',
  },
  {
    id: 'm3-fc-019',
    moduleId: M3,
    tags: ['definition', 'valorisation'],
    recto: 'Le FCF (free cash flow), c\'est quoi ?',
    verso: 'Le flux de trésorerie disponible après investissements — ce que l\'entreprise génère réellement, qu\'elle le distribue ou non. Il revient aux deux financeurs à la fois, actionnaires et créanciers : d\'où son actualisation au WACC, et son usage quand les dividendes sont rares.',
    rectoEn: 'What is FCF (free cash flow)?',
    versoEn: 'The cash flow available after investments — what the company actually generates, whether distributed or not. It accrues to both financiers at once, shareholders and creditors: hence discounting at the WACC, and its use when dividends are scarce.',
  },
  {
    id: 'm3-fc-020',
    moduleId: M3,
    tags: ['definition', 'valorisation'],
    recto: 'La valeur terminale (VT), c\'est quoi ?',
    verso: 'La valeur, en fin d\'horizon explicite, de tous les flux au-delà — généralement un Gordon sur le premier flux de la phase stable. Elle pèse couramment 60 à 80 % d\'un DCF, repose sur deux hypothèses perpétuelles invérifiables, et s\'exprime en euros de l\'année N : à actualiser.',
    rectoEn: 'What is the terminal value (TV)?',
    versoEn: 'The value, at the end of the explicit horizon, of all flows beyond — usually a Gordon on the first stable-phase flow. It commonly weighs 60 to 80% of a DCF, rests on two unverifiable perpetual assumptions, and is expressed in year-N euros: discount it.',
  },
  {
    id: 'm3-fc-021',
    moduleId: M3,
    tags: ['definition', 'valorisation'],
    recto: 'Le WACC, c\'est quoi — en version simple ?',
    verso: 'Le coût moyen pondéré du capital : la moyenne du coût des fonds propres et du coût de la dette, pondérée par leur poids au bilan. C\'est le taux du DCF, car les FCF reviennent aux deux financeurs. Sa construction détaillée : module 12.',
    rectoEn: 'What is the WACC — simple version?',
    versoEn: 'The weighted average cost of capital: the average of the cost of equity and the cost of debt, weighted by their balance-sheet shares. It is the DCF\'s discount rate, since FCF accrues to both financiers. Detailed construction: module 12.',
  },
  {
    id: 'm3-fc-022',
    moduleId: M3,
    tags: ['formule', 'valorisation'],
    recto: 'Formule de Gordon-Shapiro, avec l\'exemple canonique du cours ?',
    verso: '$V_0 = \\frac{D_1}{r-g}$, sous condition r > g. Ex. : D₁ = 5 €, r = 8 %, g = 3 % → 5/0,05 = 100 € — on paie 20 fois le dividende, le multiple 1/(r−g). Et si g = 0, retour à la perpétuité simple : 5/0,08 = 62,50 €.',
    rectoEn: 'Gordon-Shapiro formula, with the course\'s canonical example?',
    versoEn: '$V_0 = \\frac{D_1}{r-g}$, under the condition r > g. E.g.: D₁ = €5, r = 8%, g = 3% → 5/0.05 = €100 — you pay 20 times the dividend, the 1/(r−g) multiple. And if g = 0, back to the simple perpetuity: 5/0.08 = €62.50.',
  },
  {
    id: 'm3-fc-023',
    moduleId: M3,
    tags: ['formule', 'valorisation'],
    recto: 'Formule de la croissance soutenable ?',
    verso: '$g = ROE \\times b$, avec b = 1 − payout le taux de rétention. Ex. : ROE 12 %, payout 60 % → b = 40 % et g = 4,8 %. Les bénéfices retenus grossissent les fonds propres, qui produisent au taux ROE. Un g au-delà de ce que soutient le couple ROE-payout doit alerter.',
    rectoEn: 'Sustainable growth formula?',
    versoEn: '$g = ROE \\times b$, with b = 1 − payout the retention rate. E.g.: ROE 12%, payout 60% → b = 40% and g = 4.8%. Retained earnings grow equity, which earns at the ROE rate. A g beyond what the ROE-payout pair sustains should raise a flag.',
  },
  {
    id: 'm3-fc-024',
    moduleId: M3,
    tags: ['piege', 'valorisation'],
    recto: 'Gordon : l\'énoncé donne un dividende de 5 €. D₁ ou D₀ — et qu\'est-ce que ça change ?',
    verso: 'Gordon s\'applique au dividende attendu DANS UN AN. Si 5 € est D₀ (dernier versé), il faut d\'abord le faire croître : D₁ = 5 × (1+g). Si c\'est déjà D₁, le faire croître une fois de plus est l\'erreur classique. Toujours vérifier la date du flux.',
    rectoEn: 'Gordon: the problem gives a €5 dividend. D₁ or D₀ — and what difference does it make?',
    versoEn: 'Gordon applies to the dividend expected IN ONE YEAR. If €5 is D₀ (last paid), grow it first: D₁ = 5 × (1+g). If it is already D₁, growing it once more is the classic mistake. Always check the date of the flow.',
  },
  {
    id: 'm3-fc-025',
    moduleId: M3,
    tags: ['piege', 'valorisation'],
    recto: 'Que se passe-t-il dans Gordon quand g se rapproche de r — et pourquoi ?',
    verso: 'La valeur explose : tout tient dans le dénominateur r − g, et sous 1 point d\'écart elle sort du cadre. r > g est la condition de convergence de la série géométrique — si g rattrapait r, la somme divergerait. Un g perpétuel proche de r n\'est jamais crédible.',
    rectoEn: 'What happens in Gordon when g approaches r — and why?',
    versoEn: 'The value explodes: everything sits in the r − g denominator, and below a 1-point gap it goes off the chart. r > g is the geometric series\' convergence condition — if g caught up with r, the sum would diverge. A perpetual g close to r is never credible.',
  },
  {
    id: 'm3-fc-026',
    moduleId: M3,
    tags: ['piege', 'valorisation'],
    recto: 'DDM deux étapes : les deux fautes éliminatoires sur la valeur terminale ?',
    verso: '1) Construire la VT sur D₃ au lieu de D₄ — Gordon s\'applique au flux SUIVANT la date d\'évaluation. 2) Oublier de l\'actualiser : VT₃ = 45,254 € est en euros de l\'année 3 → 45,254/1,08³ = 35,92 €. Les deux coûtent l\'exercice.',
    rectoEn: 'Two-stage DDM: the two disqualifying mistakes on the terminal value?',
    versoEn: '1) Building the TV on D₃ instead of D₄ — Gordon applies to the flow FOLLOWING the valuation date. 2) Forgetting to discount it: TV₃ = €45.254 is in year-3 euros → 45.254/1.08³ = €35.92. Either one costs you the exercise.',
  },
  {
    id: 'm3-fc-027',
    moduleId: M3,
    tags: ['reflexe-jury', 'valorisation'],
    recto: 'Un évaluateur annonce « l\'action vaut 103,27 € ». Qu\'est-ce qui cloche ?',
    verso: 'La fausse précision : personne ne connaît g ou r à un point près, et la valeur y réagit de façon explosive. Toute valorisation Gordon/DCF se présente en fourchette, avec une matrice de sensibilité croisant taux et croissance — jamais en chiffre unique au centime.',
    rectoEn: 'An appraiser announces "the share is worth €103.27". What is wrong?',
    versoEn: 'False precision: nobody knows g or r to within a point, and the value reacts explosively to both. Any Gordon/DCF valuation is presented as a range, with a sensitivity matrix crossing rate and growth — never a single figure to the cent.',
  },
  {
    id: 'm3-fc-028',
    moduleId: M3,
    tags: ['piege', 'valorisation'],
    recto: 'Dans g = ROE × b, b est-il le payout ?',
    verso: 'Non — b est le taux de RÉTENTION, la part mise en réserve : b = 1 − payout. Payout 60 % → b = 40 % → g = 12 % × 0,40 = 4,8 %. Brancher le payout à la place de b (12 % × 0,60 = 7,2 %) surestime la croissance — confusion classique.',
    rectoEn: 'In g = ROE × b, is b the payout?',
    versoEn: 'No — b is the RETENTION rate, the share kept in reserves: b = 1 − payout. Payout 60% → b = 40% → g = 12% × 0.40 = 4.8%. Plugging the payout instead of b (12% × 0.60 = 7.2%) overstates growth — a classic mix-up.',
  },
  {
    id: 'm3-fc-029',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'valorisation'],
    recto: 'Quel poids pèse la valeur terminale dans un DCF réel ?',
    verso: 'Couramment 60 à 80 % de la valeur totale. Dans l\'exemple du cours : VA(VT) = 1 500/1,1³ = 1 126,97 sur 1 399,70, soit ≈ 80 %. Et dans le DDM deux étapes : 35,92 sur 42,15, soit 85 %. L\'essentiel de la valeur repose sur deux hypothèses perpétuelles.',
    rectoEn: 'How much does the terminal value weigh in a real DCF?',
    versoEn: 'Commonly 60 to 80% of total value. In the course example: PV(TV) = 1,500/1.1³ = 1,126.97 out of 1,399.70, i.e. ≈ 80%. And in the two-stage DDM: 35.92 out of 42.15, i.e. 85%. Most of the value rests on two perpetual assumptions.',
  },
  {
    id: 'm3-fc-030',
    moduleId: M3,
    tags: ['reflexe-jury', 'valorisation'],
    recto: 'Le jury : « Votre DCF sort 1 400, et la valeur terminale pèse 80 % — réaction ? »',
    verso: 'Réflexe : c\'est normal — 60 à 80 % est la norme — mais cela signifie que la valeur repose sur deux hypothèses perpétuelles invérifiables (croissance terminale, taux). Donc : pas de chiffre unique, une matrice de sensibilité WACC × g, et une fourchette. Le DCF est une machine à hypothèses.',
    rectoEn: 'The panel: "Your DCF prints 1,400, and the terminal value weighs 80% — reaction?"',
    versoEn: 'Reflex: that is normal — 60 to 80% is standard — but it means the value rests on two unverifiable perpetual assumptions (terminal growth, rate). So: no single figure, a WACC × g sensitivity matrix, and a range. A DCF is an assumption machine.',
  },
  {
    id: 'm3-fc-031',
    moduleId: M3,
    tags: ['reflexe-jury', 'valorisation'],
    recto: 'Le jury : « Gordon avec g = 7,5 % et r = 8 % : qu\'en dites-vous ? »',
    verso: 'Réflexe : refuser le chiffre. 1/(r−g) = 200 — le modèle affiche 200 € pour 1 € de dividende, et ce chiffre ne signifie rien : une hypercroissance n\'est jamais PERPÉTUELLE. Gordon est inadapté ; on passe au modèle en deux étapes, croissance forte temporaire puis rythme assagi.',
    rectoEn: 'The panel: "Gordon with g = 7.5% and r = 8%: your take?"',
    versoEn: 'Reflex: reject the number. 1/(r−g) = 200 — the model prints €200 per €1 of dividend, and that figure means nothing: hypergrowth is never PERPETUAL. Gordon is unfit; switch to the two-stage model, strong temporary growth then a calmer pace.',
  },
  {
    id: 'm3-fc-032',
    moduleId: M3,
    tags: ['reflexe-jury', 'valorisation'],
    recto: 'Le jury : « Déroulez un DDM deux étapes : D₀ = 2 €, +10 % pendant 3 ans, puis 2 %, r = 8 %. »',
    verso: 'Réflexe en 3 étapes : 1) D₁ = 2,20 ; D₂ = 2,42 ; D₃ = 2,662. 2) VT₃ sur D₄ = 2,662 × 1,02 = 2,71524 → VT₃ = 2,71524/0,06 = 45,254 €. 3) Tout actualiser à 8 % : 6,22 + 35,92 = 42,15 €. La VT pèse 85 % — à signaler spontanément.',
    rectoEn: 'The panel: "Walk through a two-stage DDM: D₀ = €2, +10% for 3 years, then 2%, r = 8%."',
    versoEn: 'Reflex in 3 steps: 1) D₁ = 2.20; D₂ = 2.42; D₃ = 2.662. 2) TV₃ on D₄ = 2.662 × 1.02 = 2.71524 → TV₃ = 2.71524/0.06 = €45.254. 3) Discount everything at 8%: 6.22 + 35.92 = €42.15. The TV weighs 85% — point it out unprompted.',
  },
  {
    id: 'm3-fc-033',
    moduleId: M3,
    tags: ['calcul-mental', 'valorisation'],
    recto: 'De tête : Gordon avec D₁ = 5 €, r = 8 %, g = 3 % ? Et D₁ = 4 €, r = 9 %, g = 1 % ?',
    verso: 'D₁/(r−g) en points : 5/(8−3) = 5/0,05 = 100 € ; 4/(9−1) = 4/0,08 = 50 €. Routine : soustraire les pourcentages de tête, puis diviser le dividende par l\'écart — la perpétuité qui pousse, en une seconde.',
    rectoEn: 'In your head: Gordon with D₁ = €5, r = 8%, g = 3%? And D₁ = €4, r = 9%, g = 1%?',
    versoEn: 'D₁/(r−g) in points: 5/(8−3) = 5/0.05 = €100; 4/(9−1) = 4/0.08 = €50. Routine: subtract the percentages in your head, then divide the dividend by the gap — the growing perpetuity, in one second.',
  },
  {
    id: 'm3-fc-034',
    moduleId: M3,
    tags: ['calcul-mental', 'valorisation'],
    recto: 'De tête : Gordon vaut 100 € (5 €, 8 %, 3 %). Effet de +1 point de g ? De +1 point de r ?',
    verso: 'g à 4 % : 5/0,04 = 125 €, soit +25 %. r à 9 % : 5/0,06 = 83,33 €, soit −17 %. Notez l\'asymétrie +25/−17 — la convexité qui revient. Un point d\'hypothèse, un quart de valeur : d\'où la fourchette obligatoire.',
    rectoEn: 'In your head: Gordon is worth €100 (€5, 8%, 3%). Effect of +1 point of g? Of +1 point of r?',
    versoEn: 'g at 4%: 5/0.04 = €125, i.e. +25%. r at 9%: 5/0.06 = €83.33, i.e. −17%. Note the +25/−17 asymmetry — convexity again. One point of assumption, a quarter of the value: hence the mandatory range.',
  },
  {
    id: 'm3-fc-035',
    moduleId: M3,
    tags: ['calcul-mental', 'valorisation'],
    recto: 'De tête : le « multiple de dividende » pour r − g = 5 % ? 4 % ? 2 % ?',
    verso: '1/(r−g) : 5 % → ×20 ; 4 % → ×25 ; 2 % → ×50. Le multiple explose quand l\'écart se resserre — sentir cette non-linéarité de tête, c\'est comprendre pourquoi toute la valeur tient dans un dénominateur minuscule.',
    rectoEn: 'In your head: the "dividend multiple" for r − g = 5%? 4%? 2%?',
    versoEn: '1/(r−g): 5% → ×20; 4% → ×25; 2% → ×50. The multiple explodes as the gap narrows — feeling that non-linearity in your head is understanding why all the value sits in a tiny denominator.',
  },

  // ───────────────────────── Chapitre 3 — Valoriser par les multiples ─────────────────────────
  {
    id: 'm3-fc-036',
    moduleId: M3,
    tags: ['definition', 'multiples'],
    recto: 'Le PER, c\'est quoi — et comment se lit-il ?',
    verso: 'Cours/BPA : 120/8 = 15 — au bénéfice courant, on paie quinze années de profits. Son inverse, le rendement bénéficiaire (1/15 ≈ 6,7 %), se compare à un taux obligataire. Muet pour une société en perte : le ratio devient négatif.',
    rectoEn: 'What is the P/E — and how does it read?',
    versoEn: 'Price/EPS: 120/8 = 15 — at current earnings, you pay fifteen years of profits. Its inverse, the earnings yield (1/15 ≈ 6.7%), compares directly to a bond yield. Mute for a loss-making company: the ratio turns negative.',
  },
  {
    id: 'm3-fc-037',
    moduleId: M3,
    tags: ['definition', 'multiples'],
    recto: 'L\'EBITDA, c\'est quoi — et pourquoi est-ce le bon dénominateur de l\'EV ?',
    verso: 'Le résultat opérationnel avant amortissements et dépréciations, mesuré AVANT frais financiers : il revient à tous les bailleurs de fonds, actionnaires et créanciers. D\'où la cohérence d\'EV/EBITDA : prix de tous les capitaux au numérateur, profit qui les rémunère tous au dénominateur.',
    rectoEn: 'What is EBITDA — and why is it EV\'s right denominator?',
    versoEn: 'Operating profit before depreciation and amortization, measured BEFORE financial expenses: it accrues to all capital providers, shareholders and creditors. Hence EV/EBITDA\'s coherence: the price of all capital on top, the profit that pays all of it below.',
  },
  {
    id: 'm3-fc-038',
    moduleId: M3,
    tags: ['definition', 'multiples'],
    recto: 'Le P/B (price-to-book), c\'est quoi — et où est-il central ?',
    verso: 'Capitalisation/fonds propres comptables. Central pour banques et assurances, dont le bilan est l\'outil de production. P/B > 1 : le marché attend un ROE durablement au-dessus du coût des fonds propres ; < 1 : l\'inverse — les banques européennes ont passé les années 2010 sous 1.',
    rectoEn: 'What is the P/B (price-to-book) — and where is it central?',
    versoEn: 'Market cap / book equity. Central for banks and insurers, whose balance sheet is their production tool. P/B > 1: the market expects an ROE durably above the cost of equity; < 1: the opposite — European banks spent the 2010s below 1.',
  },
  {
    id: 'm3-fc-039',
    moduleId: M3,
    tags: ['definition', 'multiples'],
    recto: 'La méthode des comparables, en quatre temps ?',
    verso: '1) Échantillon de 6 à 10 sociétés proches — l\'étape décisive et la plus subjective. 2) Multiples calculés proprement (mêmes exercices, mêmes retraitements). 3) Synthèse par la MÉDIANE, robuste aux extrêmes. 4) Application à la cible + ajustements : décote d\'illiquidité, prime de contrôle.',
    rectoEn: 'The comparables method, in four steps?',
    versoEn: '1) A sample of 6 to 10 similar companies — the decisive and most subjective step. 2) Multiples computed cleanly (same fiscal years, same adjustments). 3) Synthesis by the MEDIAN, robust to outliers. 4) Application to the target + adjustments: illiquidity discount, control premium.',
  },
  {
    id: 'm3-fc-040',
    moduleId: M3,
    tags: ['formule', 'multiples'],
    recto: 'Formule du PER, avec l\'exemple du cours ?',
    verso: '$\\text{PER} = \\frac{\\text{cours}}{\\text{BPA}}$ : 120/8 = 15. Lecture : quinze années de bénéfice courant. Inverse : rendement bénéficiaire 1/15 ≈ 6,7 %, directement comparable à un taux obligataire — la passerelle actions-taux.',
    rectoEn: 'P/E formula, with the course example?',
    versoEn: '$P/E = \\frac{\\text{price}}{\\text{EPS}}$: 120/8 = 15. Reading: fifteen years of current earnings. Inverse: earnings yield 1/15 ≈ 6.7%, directly comparable to a bond yield — the equity-rates bridge.',
  },
  {
    id: 'm3-fc-041',
    moduleId: M3,
    tags: ['formule', 'multiples'],
    recto: 'Formule de l\'EV/EBITDA, avec l\'exemple du cours ?',
    verso: '$\\frac{\\text{capi} + \\text{dette nette}}{\\text{EBITDA}} = \\frac{900 + 300}{200} = 6$ : acheter l\'entreprise entière coûte six années d\'EBITDA, quelle que soit sa structure de financement. Les deux erreurs types : oublier la dette (4,5) ou la soustraire (3,0).',
    rectoEn: 'EV/EBITDA formula, with the course example?',
    versoEn: '$\\frac{\\text{cap} + \\text{net debt}}{\\text{EBITDA}} = \\frac{900 + 300}{200} = 6$: buying the whole company costs six years of EBITDA, whatever its financing structure. The two typical errors: forgetting the debt (4.5) or subtracting it (3.0).',
  },
  {
    id: 'm3-fc-042',
    moduleId: M3,
    tags: ['formule', 'multiples'],
    recto: 'Le PER théorique caché dans Gordon — formule et application du cours ?',
    verso: '$\\text{PER} = \\frac{d\\,(1+g)}{r-g}$ avec d le payout. Ex. : d = 60 %, g = 3 %, r = 8 % → 0,60 × 1,03/0,05 = 12,36 ; r à 7 % → 15,45. Moralité : un multiple est un DCF compressé — payer 25 fois les bénéfices, c\'est acheter implicitement un couple (r, g).',
    rectoEn: 'The theoretical P/E hidden in Gordon — formula and course application?',
    versoEn: '$P/E = \\frac{d\\,(1+g)}{r-g}$ with d the payout. E.g.: d = 60%, g = 3%, r = 8% → 0.60 × 1.03/0.05 = 12.36; r at 7% → 15.45. Moral: a multiple is a compressed DCF — paying 25 times earnings is implicitly buying an (r, g) pair.',
  },
  {
    id: 'm3-fc-043',
    moduleId: M3,
    tags: ['piege', 'multiples'],
    recto: 'Un cyclique affiche un PER de 4 au sommet du cycle. Une affaire ?',
    verso: 'Non : les bénéfices sont gonflés au pic, et le marché refuse de les payer cher car il anticipe leur retombée. Quand le cycle se retourne, le dénominateur fond et le PER explose. L\'adage : un cyclique s\'achète sur PER ÉLEVÉ (creux) et se vend sur PER BAS (pic).',
    rectoEn: 'A cyclical shows a P/E of 4 at the top of the cycle. A bargain?',
    versoEn: 'No: earnings are inflated at the peak, and the market refuses to pay up because it expects them to fall. When the cycle turns, the denominator melts and the P/E explodes. The adage: a cyclical is bought on a HIGH P/E (trough) and sold on a LOW P/E (peak).',
  },
  {
    id: 'm3-fc-044',
    moduleId: M3,
    tags: ['piege', 'multiples'],
    recto: '« Le titre cote dans la moyenne de ses comparables, donc le prix est correct. » La faille ?',
    verso: 'L\'argument est circulaire : les multiples mesurent des PRIX, pas des valeurs. En 1999-2000, chaque société internet était « raisonnable » face à des comparables eux-mêmes en bulle — les multiples se validaient mutuellement. Coter 30× dans un secteur à 40×, c\'est être moins cher dans une bulle.',
    rectoEn: '"The stock trades in line with its comparables, so the price is right." The flaw?',
    versoEn: 'The argument is circular: multiples measure PRICES, not values. In 1999-2000, every internet company looked "reasonable" against comparables that were themselves in a bubble — multiples validated one another. Trading at 30× in a 40× sector is being cheaper inside a bubble.',
  },
  {
    id: 'm3-fc-045',
    moduleId: M3,
    tags: ['piege', 'multiples'],
    recto: 'Un bel EV/EBITDA de 5 suffit-il à conclure que l\'entreprise est bon marché ?',
    verso: 'Non : l\'EBITDA ignore les investissements de MAINTIEN. Pour une activité qui doit réinvestir lourdement chaque année, un bel EV/EBITDA peut décorer une machine à consommer du capital. Toujours regarder ce qu\'il reste après le capex obligatoire.',
    rectoEn: 'Is a nice EV/EBITDA of 5 enough to conclude the company is cheap?',
    versoEn: 'No: EBITDA ignores MAINTENANCE capex. For a business that must reinvest heavily every year, a flattering EV/EBITDA can decorate a capital-eating machine. Always look at what is left after mandatory capex.',
  },
  {
    id: 'm3-fc-046',
    moduleId: M3,
    tags: ['piege', 'multiples'],
    recto: 'Le BPA progresse de 11 % : l\'entreprise va-t-elle forcément mieux ?',
    verso: 'Pas sûr : le BPA est manipulable. Le résultat net arrive après les choix comptables — provisions, « exceptionnels » qui se répètent — et les rachats d\'actions gonflent le BPA en réduisant le dénominateur sans qu\'un client de plus soit facturé. Décomposer : bénéfice ou dénominateur ?',
    rectoEn: 'EPS grows 11%: is the company necessarily doing better?',
    versoEn: 'Not necessarily: EPS can be engineered. Net profit comes after accounting choices — provisions, oddly recurring "one-offs" — and buybacks inflate EPS by shrinking the denominator without one more customer billed. Decompose: profit or denominator?',
  },
  {
    id: 'm3-fc-047',
    moduleId: M3,
    tags: ['piege', 'multiples'],
    recto: 'Un rendement du dividende très supérieur à celui du secteur : une aubaine ?',
    verso: 'Rarement : le plus souvent, le cours a déjà chuté parce que le marché juge le dividende condamné — le rendement affiché vit ses derniers mois. Même lecture inversée que le PER cyclique : un ratio « trop beau » est un message, pas un cadeau.',
    rectoEn: 'A dividend yield far above the sector\'s: a windfall?',
    versoEn: 'Rarely: most often the price has already fallen because the market deems the dividend doomed — the displayed yield is living its last months. Same inverted reading as the cyclical P/E: a "too good" ratio is a message, not a gift.',
  },
  {
    id: 'm3-fc-048',
    moduleId: M3,
    tags: ['reflexe-jury', 'multiples'],
    recto: 'Le jury : « Un PER de 25, c\'est cher ? »',
    verso: 'Réflexe : « cher par rapport à quoi ? » Trois moteurs : croissance attendue, qualité/visibilité des profits, niveau des taux — un PER de 25 ne se lit pas pareil à taux sans risque de 1 % ou de 5 %. Et la phrase qui classe : payer 25 fois, c\'est acheter implicitement un couple (r, g).',
    rectoEn: 'The panel: "Is a P/E of 25 expensive?"',
    versoEn: 'Reflex: "expensive relative to what?" Three drivers: expected growth, quality/visibility of profits, the level of rates — a P/E of 25 does not read the same with risk-free rates at 1% or 5%. And the line that ranks you: paying 25 times is implicitly buying an (r, g) pair.',
  },
  {
    id: 'm3-fc-049',
    moduleId: M3,
    tags: ['reflexe-jury', 'multiples'],
    recto: 'Le jury : « Un armateur cote 4 fois ses bénéfices au sommet d\'un cycle de fret exceptionnel. Vous achetez ? »',
    verso: 'Réflexe : non sans situer le cycle. Le PER est optiquement bas parce que les bénéfices sont au pic ; le marché anticipe leur retombée. Quand le fret se normalise, le dénominateur fond, le PER recalculé explose — et l\'action « pas chère » a perdu 40 %.',
    rectoEn: 'The panel: "A shipping company trades at 4 times earnings at the top of an exceptional freight cycle. Do you buy?"',
    versoEn: 'Reflex: not without locating the cycle. The P/E is optically low because earnings are at the peak; the market expects them to fall. When freight normalizes, the denominator melts, the recomputed P/E explodes — and the "cheap" stock has lost 40%.',
  },
  {
    id: 'm3-fc-050',
    moduleId: M3,
    tags: ['reflexe-jury', 'multiples'],
    recto: 'Le jury : « Deux jumelles industrielles, l\'une sans dette, l\'autre très endettée. Quel multiple pour les comparer ? »',
    verso: 'Réflexe : EV/EBITDA. Le bénéfice net — donc le PER — se mesure APRÈS frais financiers : les leviers différents rendent les PER non comparables. L\'EV intègre la dette au numérateur, l\'EBITDA se mesure avant intérêts : la structure de financement ne biaise plus la comparaison.',
    rectoEn: 'The panel: "Two industrial twins, one debt-free, one heavily levered. Which multiple to compare them?"',
    versoEn: 'Reflex: EV/EBITDA. Net profit — hence the P/E — is measured AFTER financial expenses: different leverage makes P/Es non-comparable. EV includes debt in the numerator, EBITDA is measured before interest: the financing structure no longer skews the comparison.',
  },
  {
    id: 'm3-fc-051',
    moduleId: M3,
    tags: ['reflexe-jury', 'multiples'],
    recto: 'Le jury : « Quel multiple pour valoriser une banque, et comment le lire ? »',
    verso: 'Réflexe : le P/B. Le bilan d\'une banque est son outil de production, fait d\'actifs et passifs financiers proches de leur valeur de marché. Lecture par la rentabilité : P/B > 1 si le marché attend un ROE au-dessus du coût des fonds propres, < 1 sinon — l\'Europe bancaire des années 2010.',
    rectoEn: 'The panel: "Which multiple to value a bank, and how do you read it?"',
    versoEn: 'Reflex: the P/B. A bank\'s balance sheet is its production tool, made of financial assets and liabilities close to market value. Read through profitability: P/B > 1 if the market expects ROE above the cost of equity, < 1 otherwise — European banks in the 2010s.',
  },
  {
    id: 'm3-fc-052',
    moduleId: M3,
    tags: ['calcul-mental', 'multiples'],
    recto: 'De tête : rendement bénéficiaire pour un PER de 15 ? De 25 ? De 10 ?',
    verso: '1/PER : 15 → ≈ 6,7 % ; 25 → 4 % ; 10 → 10 %. Routine : inverser le multiple donne le « taux » que paie l\'action au bénéfice courant — directement comparable, avec prudence, à un taux obligataire.',
    rectoEn: 'In your head: earnings yield for a P/E of 15? Of 25? Of 10?',
    versoEn: '1/P/E: 15 → ≈ 6.7%; 25 → 4%; 10 → 10%. Routine: inverting the multiple gives the "rate" the share pays at current earnings — directly comparable, with caution, to a bond yield.',
  },
  {
    id: 'm3-fc-053',
    moduleId: M3,
    tags: ['calcul-mental', 'multiples'],
    recto: 'De tête : payout 45 % et PER 15 — rendement du dividende ? Et payout 60 %, PER 12 ?',
    verso: 'Rendement = payout/PER : 45/15 = 3 % ; 60/12 = 5 %. La relation qui verrouille la ligne de cote : dividende/cours = (dividende/BPA) × (BPA/cours).',
    rectoEn: 'In your head: 45% payout and P/E 15 — dividend yield? And 60% payout, P/E 12?',
    versoEn: 'Yield = payout/P/E: 45/15 = 3%; 60/12 = 5%. The relationship that locks the quote line together: dividend/price = (dividend/EPS) × (EPS/price).',
  },
  {
    id: 'm3-fc-054',
    moduleId: M3,
    tags: ['calcul-mental', 'multiples'],
    recto: 'De tête : PER du marché à 20, taux 10 ans à 4 % — la comparaison en une ligne ?',
    verso: '1/PER = 5 % de rendement bénéficiaire contre 4 % sans risque : 1 point d\'écart. C\'est le « Fed model » en une ligne — un ordre de grandeur utile, PAS un modèle : il ignore croissance et inflation, à manier avec prudence à l\'oral.',
    rectoEn: 'In your head: market P/E at 20, 10-year yield at 4% — the one-line comparison?',
    versoEn: '1/P/E = 5% earnings yield versus 4% risk-free: a 1-point gap. That is the "Fed model" in one line — a useful order of magnitude, NOT a model: it ignores growth and inflation, handle with care at the oral.',
  },
  {
    id: 'm3-fc-055',
    moduleId: M3,
    tags: ['calcul-mental', 'multiples'],
    recto: 'De tête : capi 900 M€, dette nette 300 M€, EBITDA 200 M€ — EV/EBITDA ? Et si trésorerie nette de 100 M€ ?',
    verso: 'EV = 900 + 300 = 1 200 → 1 200/200 = 6×. Avec 100 de trésorerie nette : EV = 900 − 100 = 800 → 4×. Routine : additionner la dette, soustraire le cash, puis diviser.',
    rectoEn: 'In your head: cap €900m, net debt €300m, EBITDA €200m — EV/EBITDA? And with €100m net cash?',
    versoEn: 'EV = 900 + 300 = 1,200 → 1,200/200 = 6×. With 100 of net cash: EV = 900 − 100 = 800 → 4×. Routine: add the debt, subtract the cash, then divide.',
  },

  // ───────────────────────── Chapitre 4 — Les indices : thermomètres et produits ─────────────────────────
  {
    id: 'm3-fc-056',
    moduleId: M3,
    tags: ['definition', 'indices'],
    recto: 'Indice prix vs indice de rendement total : la différence ?',
    verso: 'L\'indice PRIX (CAC 40) encaisse la baisse au détachement des dividendes sans jamais les créditer. L\'indice de RENDEMENT TOTAL les réinvestit : GR en brut (CAC 40 GR), NR net de retenue à la source — la référence contractuelle de la plupart des ETF. Le DAX est TR par défaut : l\'exception.',
    rectoEn: 'Price index vs total return index: the difference?',
    versoEn: 'A PRICE index (CAC 40) absorbs the drop at dividend detachment without ever crediting it. A TOTAL RETURN index reinvests dividends: GR gross (CAC 40 GR), NR net of withholding — the contractual benchmark of most ETFs. The DAX is TR by default: the exception.',
  },
  {
    id: 'm3-fc-057',
    moduleId: M3,
    tags: ['definition', 'indices'],
    recto: 'Le diviseur d\'un indice, c\'est quoi ?',
    verso: 'Le nombre qui transforme la capitalisation du panier en niveau : Indice = Σ pᵢnᵢfᵢ / D. Il fixe la base (CAC 40 : 1 000 fin 1987) puis absorbe tout ce qui n\'est pas une variation de prix — entrées-sorties, opérations — via D\' = D × capi après/capi avant : le principe de continuité.',
    rectoEn: 'What is an index divisor?',
    versoEn: 'The number that turns the basket\'s capitalization into a level: Index = Σ pᵢnᵢfᵢ / D. It sets the base (CAC 40: 1,000 at end-1987) then absorbs everything that is not a price move — additions, deletions, capital events — via D\' = D × cap after/cap before: the continuity principle.',
  },
  {
    id: 'm3-fc-058',
    moduleId: M3,
    tags: ['formule', 'indices'],
    recto: 'Formules des poids d\'indice : pondération par les prix vs par la capi flottante ?',
    verso: 'Prix : poids = cours/somme des cours — PetiteTech à 800 € pèse 80 % du panier avec 16 Md€ de capi, la plus petite société. Capi flottante : poids = (cours × titres × flottant)/total — MegaCorp et ses 100 Md€ dominent. Même panier, hiérarchie inversée : la règle EST l\'indice.',
    rectoEn: 'Index weight formulas: price weighting vs float-cap weighting?',
    versoEn: 'Price: weight = price/sum of prices — PetiteTech at €800 weighs 80% of the basket with a €16bn cap, the smallest company. Float cap: weight = (price × shares × float)/total — MegaCorp and its €100bn dominate. Same basket, inverted hierarchy: the rule IS the index.',
  },
  {
    id: 'm3-fc-059',
    moduleId: M3,
    tags: ['formule', 'indices'],
    recto: 'Quel facteur cumulent des dividendes de 3 % par an réinvestis sur près de 40 ans ?',
    verso: 'Facteur ≈ (1+y)ⁿ : 1,03⁴⁰ ≈ 3,3 — la mise multipliée par plus de trois par les seuls dividendes réinvestis. Exactement l\'écart CAC 40 prix (~8 000) vs CAC 40 GR (> 25 000) depuis la base commune de 1 000 fin 1987.',
    rectoEn: 'What factor do 3% annual dividends compound to, reinvested over nearly 40 years?',
    versoEn: 'Factor ≈ (1+y)ⁿ: 1.03⁴⁰ ≈ 3.3 — the stake multiplied by more than three by reinvested dividends alone. Exactly the CAC 40 price (~8,000) vs CAC 40 GR (> 25,000) gap from their common base of 1,000 at end-1987.',
  },
  {
    id: 'm3-fc-060',
    moduleId: M3,
    tags: ['piege', 'indices'],
    recto: '« Depuis trente ans, le DAX écrase le CAC 40 : les entreprises allemandes surperforment. » Vrai ?',
    verso: 'Biais structurel : le DAX RÉINVESTIT les dividendes (indice TR), le CAC non (indice prix). À ~3 % de rendement annuel composé d\'un côté et rien de l\'autre, l\'avantage est mécanique et ne dit rien des entreprises. Comparaison honnête : CAC 40 GR contre DAX, ou prix contre prix.',
    rectoEn: '"For thirty years the DAX has crushed the CAC 40: German companies outperform." True?',
    versoEn: 'Structural bias: the DAX REINVESTS dividends (TR index), the CAC does not (price index). With ~3% a year compounding on one side and nothing on the other, the edge is mechanical and says nothing about the companies. Honest comparison: CAC 40 GR vs DAX, or price vs price.',
  },
  {
    id: 'm3-fc-061',
    moduleId: M3,
    tags: ['piege', 'indices'],
    recto: 'Un épargnant en MSCI World se croit « diversifié monde ». Que lui manque-t-il ?',
    verso: 'Le « World » ne couvre que les 23 marchés DÉVELOPPÉS — aucun émergent (eux sont dans le MSCI EM ; l\'ensemble forme l\'ACWI) — et les États-Unis pèsent de l\'ordre de 70 % : un « diversifié monde » est d\'abord exposé à Wall Street.',
    rectoEn: 'An MSCI World investor believes he is "globally diversified". What is he missing?',
    versoEn: 'The "World" covers only the 23 DEVELOPED markets — no emerging ones (those sit in MSCI EM; together they form the ACWI) — and the United States weighs around 70%: a "world-diversified" saver is first and foremost exposed to Wall Street.',
  },
  {
    id: 'm3-fc-062',
    moduleId: M3,
    tags: ['piege', 'indices'],
    recto: '« Mon tracker détient 500 sociétés, je suis parfaitement diversifié. » Vraiment ?',
    verso: 'Non : début 2026, le top 10 du S&P 500 pèse 35 à 40 % de l\'indice, largement exposé au même facteur technologique. La diversification exige des positions nombreuses ET peu corrélées — le nombre de lignes ne suffit pas. Et la capi-pondération surpondère mécaniquement ce qui a monté.',
    rectoEn: '"My tracker holds 500 companies, I am perfectly diversified." Really?',
    versoEn: 'No: in early 2026, the S&P 500\'s top 10 weighs 35 to 40% of the index, largely exposed to the same technology factor. Diversification requires positions that are numerous AND weakly correlated — line count is not enough. And cap-weighting mechanically overweights what has already risen.',
  },
  {
    id: 'm3-fc-063',
    moduleId: M3,
    tags: ['piege', 'indices'],
    recto: 'Un split 2:1 frappe un indice pondéré par les prix et un indice capi-pondéré. Qui doit s\'ajuster ?',
    verso: 'Le pondéré par les prix : sans retouche du diviseur, l\'indice chuterait (180 → 130 de somme des cours, −28 % fictifs) et le poids du titre s\'effondre (55,6 % → 38,5 %) — un non-événement redistribue les poids. L\'indice capi-pondéré, lui, ne bouge pas : capitalisation inchangée.',
    rectoEn: 'A 2:1 split hits a price-weighted index and a cap-weighted index. Which one must adjust?',
    versoEn: 'The price-weighted one: without touching the divisor, the index would drop (price sum 180 → 130, a fictitious −28%) and the stock\'s weight collapses (55.6% → 38.5%) — a non-event redistributes weights. The cap-weighted index does not move: capitalization unchanged.',
  },
  {
    id: 'm3-fc-064',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'indices'],
    recto: 'Le CAC 40 : base et date de naissance ?',
    verso: '1 000 points au 31 décembre 1987, par convention — c\'est le diviseur qui fixe la base. 40 valeurs d\'Euronext Paris, capi flottante, poids plafonné à 15 %, indice PRIX (sa version dividendes réinvestis : CAC 40 GR).',
    rectoEn: 'The CAC 40: base and birth date?',
    versoEn: '1,000 points on 31 December 1987, by convention — the divisor sets the base. 40 Euronext Paris stocks, float-cap weighted, 15% weight cap, a PRICE index (its reinvested-dividends version: CAC 40 GR).',
  },
  {
    id: 'm3-fc-065',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'indices'],
    recto: 'CAC 40 prix vs CAC 40 GR début 2026 : les niveaux ?',
    verso: 'Prix ≈ 8 000 points, GR > 25 000 — plus de trois fois plus haut, depuis la MÊME base de 1 000 fin 1987. L\'écart, c\'est ~3 % de dividendes par an réinvestis, capitalisés sur près de quarante ans : la moitié du rendement que le journal télévisé ne montre jamais.',
    rectoEn: 'CAC 40 price vs CAC 40 GR in early 2026: the levels?',
    versoEn: 'Price ≈ 8,000 points, GR > 25,000 — more than three times higher, from the SAME base of 1,000 at end-1987. The gap is ~3% of dividends a year reinvested, compounded over nearly forty years: the half of returns the evening news never shows.',
  },
  {
    id: 'm3-fc-066',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'indices'],
    recto: 'Poids du top 10 dans le S&P 500 début 2026 — et il y a dix ans ?',
    verso: 'De l\'ordre de 35 à 40 %, contre ≈ 20 % au milieu des années 2010 — concentration portée par les méga-capitalisations technologiques et le thème de l\'IA. Plus d\'un tiers d\'un tracker « 500 sociétés » tient en dix lignes.',
    rectoEn: 'Top-10 weight in the S&P 500 in early 2026 — and ten years ago?',
    versoEn: 'Around 35 to 40%, versus ≈ 20% in the mid-2010s — concentration driven by technology mega-caps and the AI theme. More than a third of a "500-company" tracker sits in ten lines.',
  },
  {
    id: 'm3-fc-067',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'indices'],
    recto: 'Le MSCI World : combien de valeurs, quelle couverture, quel poids américain ?',
    verso: '≈ 1 400 valeurs sur 23 marchés développés ; il vise ≈ 85 % de la capi flottante de chaque marché. Les États-Unis pèsent de l\'ordre de 70 % du total. « World » sans les émergents — combiné au MSCI EM, il donne l\'ACWI.',
    rectoEn: 'The MSCI World: how many stocks, what coverage, what US weight?',
    versoEn: '≈ 1,400 stocks across 23 developed markets; it targets ≈ 85% of each market\'s float capitalization. The United States weighs around 70% of the total. "World" without emerging markets — combined with MSCI EM, it forms the ACWI.',
  },
  {
    id: 'm3-fc-068',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'indices'],
    recto: 'Quelle part du rendement total des actions vient des dividendes, à long terme ?',
    verso: 'De l\'ordre de la MOITIÉ, selon les marchés et les époques — formulation prudente à retenir. C\'est la part invisible dans un indice prix : le CAC à 8 000 ne montre que l\'autre moitié du travail accompli depuis 1987.',
    rectoEn: 'What share of equities\' total return comes from dividends, long term?',
    versoEn: 'Around HALF, depending on markets and eras — the cautious phrasing to remember. It is the invisible part in a price index: the CAC at 8,000 only shows the other half of the work done since 1987.',
  },
  {
    id: 'm3-fc-069',
    moduleId: M3,
    tags: ['reflexe-jury', 'indices'],
    recto: 'Le jury : « Le Dow Jones est-il un bon indice ? »',
    verso: 'Réflexe nuancé : non méthodologiquement — pondéré par les PRIX depuis 1896, le poids suit le niveau facial de l\'action, sans lien avec la taille ; un split redistribue les poids ; 30 valeurs seulement. Mais il survit par la force de l\'habitude médiatique. Dire « fossile méthodologique », et citer le S&P 500 capi-flottant comme référence.',
    rectoEn: 'The panel: "Is the Dow Jones a good index?"',
    versoEn: 'Nuanced reflex: methodologically no — PRICE-weighted since 1896, weight follows the share\'s face level, unrelated to company size; a split redistributes weights; only 30 stocks. But it survives on media habit. Say "methodological fossil", and cite the float-cap S&P 500 as the benchmark.',
  },
  {
    id: 'm3-fc-070',
    moduleId: M3,
    tags: ['reflexe-jury', 'indices'],
    recto: 'Le jury : « Un graphique compare le DAX et le CAC 40 sur trente ans. Votre premier réflexe ? »',
    verso: 'Demander : prix ou rendement total ? Le DAX est TR par défaut, le CAC est un indice prix — l\'écart est mécanique (~3 %/an composés). Tout graphique, backtest ou plaquette qui compare des indices sans préciser prix ou TR doit éveiller le soupçon : l\'erreur de débutant la plus rentable à détecter.',
    rectoEn: 'The panel: "A chart compares the DAX and the CAC 40 over thirty years. Your first reflex?"',
    versoEn: 'Ask: price or total return? The DAX is TR by default, the CAC is a price index — the gap is mechanical (~3%/yr compounded). Any chart, backtest or sales deck comparing indices without stating price or TR should raise suspicion: the most profitable rookie error to catch.',
  },
  {
    id: 'm3-fc-071',
    moduleId: M3,
    tags: ['reflexe-jury', 'indices'],
    recto: 'Le jury : « Pourquoi pondérer les indices par la capitalisation FLOTTANTE et non totale ? »',
    verso: 'Réflexe : les blocs stables — État, familles, autocontrôle — ne se négocient pas. Un ETF qui réplique l\'indice achète du flottant, pas des titres verrouillés dans un pacte familial. Exemple à dégainer : Hermès, ~2/3 familial, pèse dans le CAC bien moins que sa capi totale ne le suggère.',
    rectoEn: 'The panel: "Why weight indices by FLOAT capitalization rather than total?"',
    versoEn: 'Reflex: stable blocks — state, families, treasury shares — do not trade. An ETF replicating the index buys float, not shares locked in a family pact. Example to draw: Hermès, ~2/3 family-held, weighs far less in the CAC than its total cap would suggest.',
  },
  {
    id: 'm3-fc-072',
    moduleId: M3,
    tags: ['calcul-mental', 'indices'],
    recto: 'De tête : 3 % de dividendes réinvestis chaque année — multiplication de la mise en 40 ans ?',
    verso: 'Règle de 72 : double en 72/3 = 24 ans → ×2 à 24 ans, ×3+ vers 40 ans (1,03⁴⁰ ≈ 3,3). C\'est exactement le rapport CAC 40 GR/CAC 40 prix : > 25 000 contre ~8 000.',
    rectoEn: 'In your head: 3% dividends reinvested each year — how much does the stake multiply in 40 years?',
    versoEn: 'Rule of 72: doubles in 72/3 = 24 years → ×2 at 24 years, ×3+ around 40 years (1.03⁴⁰ ≈ 3.3). Exactly the CAC 40 GR/CAC 40 price ratio: > 25,000 versus ~8,000.',
  },

  // ───────────────────────── Chapitre 5 — La vie du titre ─────────────────────────
  {
    id: 'm3-fc-073',
    moduleId: M3,
    tags: ['definition', 'vie-du-titre'],
    recto: 'Les quatre dates du calendrier du dividende — et laquelle compte économiquement ?',
    verso: 'Annonce (conseil puis AG) ; date de DÉTACHEMENT (ex-date) : acheter ne donne plus droit au dividende ; record date : photo des actionnaires payés, un jour ouvré après l\'ex-date en T+2 (confondues en T+1 américain) ; paiement. La date économique est l\'ex-date : le cours s\'y ajuste.',
    rectoEn: 'The four dates of the dividend calendar — and which one matters economically?',
    versoEn: 'Announcement (board then AGM); EX-DATE: buying no longer carries the dividend; record date: snapshot of paid shareholders, one business day after the ex-date under T+2 (merged under US T+1); payment. The economic date is the ex-date: the price adjusts there.',
  },
  {
    id: 'm3-fc-074',
    moduleId: M3,
    tags: ['definition', 'vie-du-titre'],
    recto: 'Un split, c\'est quoi — et pourquoi le faire si rien ne change ?',
    verso: 'Division du nominal : N fois plus de titres, cours ÷ N, capitalisation inchangée — mêmes parts du même gâteau. Raisons : liquidité et accès (lots d\'options de 100 aux US), psychologie, signal de trajectoire. Le regroupement (reverse split) porte le message inverse : souvent la détresse du penny stock.',
    rectoEn: 'What is a split — and why do it if nothing changes?',
    versoEn: 'Dividing the par value: N times more shares, price ÷ N, capitalization unchanged — same slices of the same cake. Reasons: liquidity and access (100-share option lots in the US), psychology, a trajectory signal. The reverse split carries the opposite message: often penny-stock distress.',
  },
  {
    id: 'm3-fc-075',
    moduleId: M3,
    tags: ['definition', 'vie-du-titre'],
    recto: 'Le DPS (droit préférentiel de souscription), c\'est quoi ?',
    verso: 'Le droit attaché à chaque action ancienne lors d\'une augmentation de capital : il matérialise la dilution et la rend NÉGOCIABLE. Qui souscrit paie 40 € un titre qui en vaudra 48 ; qui ne suit pas vend ses droits et encaisse la compensation. Un DPS s\'exerce ou se vend — jamais ne s\'oublie.',
    rectoEn: 'What is a subscription right (rights issue)?',
    versoEn: 'The right attached to each old share in a rights issue: it materializes the dilution and makes it TRADABLE. Subscribers pay €40 for a share soon worth €48; those not following sell their rights and pocket the compensation. A right is exercised or sold — never forgotten.',
  },
  {
    id: 'm3-fc-076',
    moduleId: M3,
    tags: ['definition', 'vie-du-titre'],
    recto: 'Le TERP (cours théorique ex-droit), c\'est quoi ?',
    verso: 'Le cours d\'équilibre après une augmentation de capital avec droits : la moyenne pondérée des anciennes actions et des nouvelles. Ex. du cours : 4 anciennes à 50 € + 1 nouvelle à 40 € → (4×50 + 40)/5 = 48 €. La décote du cours (50 → 48) est exactement la valeur du droit : 2 €.',
    rectoEn: 'What is the TERP (theoretical ex-rights price)?',
    versoEn: 'The equilibrium price after a rights issue: the weighted average of old and new shares. Course example: 4 old at €50 + 1 new at €40 → (4×50 + 40)/5 = €48. The price markdown (50 → 48) is exactly the right\'s value: €2.',
  },
  {
    id: 'm3-fc-077',
    moduleId: M3,
    tags: ['definition', 'vie-du-titre'],
    recto: 'Le buyback (rachat d\'actions), c\'est quoi ?',
    verso: 'L\'augmentation de capital à l\'envers : la société rachète ses propres actions — le plus souvent annulées. Effet RELUTIF sur le BPA : même bénéfice, moins de titres. Atouts vs dividende : flexibilité (se suspend sans drame), signal, fiscalité souvent favorable. S&P 500 : souvent > 800 Md$/an.',
    rectoEn: 'What is a buyback?',
    versoEn: 'A capital increase in reverse: the company buys back its own shares — usually cancelled. ACCRETIVE effect on EPS: same profit, fewer shares. Edges vs the dividend: flexibility (paused without drama), signalling, often favourable taxation. S&P 500: frequently > $800bn a year.',
  },
  {
    id: 'm3-fc-078',
    moduleId: M3,
    tags: ['formule', 'vie-du-titre'],
    recto: 'Formule de l\'ajustement du cours au détachement du dividende ?',
    verso: '$P_{ex} = P - D$ : une action à 100 € qui détache 2,50 € vaut théoriquement 97,50 € le jour ex. Le cours d\'ouverture réel s\'en écarte (le marché vit), mais c\'est cette mécanique que chambres de compensation et fournisseurs d\'indices appliquent.',
    rectoEn: 'Price adjustment formula at the dividend ex-date?',
    versoEn: '$P_{ex} = P - D$: a €100 share detaching €2.50 is theoretically worth €97.50 on the ex-day. The actual opening price drifts from it (markets live), but this is the mechanics clearing houses and index providers apply.',
  },
  {
    id: 'm3-fc-079',
    moduleId: M3,
    tags: ['formule', 'vie-du-titre'],
    recto: 'Formule du split, avec l\'exemple du cours ?',
    verso: '$P_{après} = P/N$ : un titre à 750 € divisé par 5 → 150 €. Titres × 5 (10 M → 50 M), capitalisation inchangée à 7,5 Md€ — et le BPA est lui aussi divisé par 5. Aucune valeur créée ni détruite.',
    rectoEn: 'Split formula, with the course example?',
    versoEn: '$P_{after} = P/N$: a €750 share split 5-for-1 → €150. Shares × 5 (10M → 50M), capitalization unchanged at €7.5bn — and EPS is also divided by 5. No value created or destroyed.',
  },
  {
    id: 'm3-fc-080',
    moduleId: M3,
    tags: ['formule', 'vie-du-titre'],
    recto: 'Formule de la valeur théorique du DPS, avec l\'exemple du cours ?',
    verso: '$DPS = \\frac{P_{coté} - P_{émission}}{n + 1}$ avec n anciennes pour 1 nouvelle : (50 − 40)/(4 + 1) = 2 €. C\'est exactement la baisse du cours au détachement des droits : 50 − 48 (TERP) = 2 €.',
    rectoEn: 'Theoretical subscription-right value formula, with the course example?',
    versoEn: '$Right = \\frac{P_{quoted} - P_{issue}}{n + 1}$ with n old shares per new one: (50 − 40)/(4 + 1) = €2. Exactly the price drop when rights detach: 50 − 48 (TERP) = €2.',
  },
  {
    id: 'm3-fc-081',
    moduleId: M3,
    tags: ['formule', 'vie-du-titre'],
    recto: 'Formule du TERP, avec l\'exemple du cours — et la vérification croisée ?',
    verso: '$TERP = \\frac{n \\times P + P_{émission}}{n + 1} = \\frac{4 \\times 50 + 40}{5} = 48$ €. Vérification : DPS = P − TERP = 50 − 48 = 2 € — les deux formules racontent la même dilution, vue du cours ou vue du droit.',
    rectoEn: 'TERP formula, with the course example — and the cross-check?',
    versoEn: '$TERP = \\frac{n \\times P + P_{issue}}{n + 1} = \\frac{4 \\times 50 + 40}{5} = €48$. Check: right = P − TERP = 50 − 48 = €2 — both formulas tell the same dilution, seen from the price or from the right.',
  },
  {
    id: 'm3-fc-082',
    moduleId: M3,
    tags: ['formule', 'vie-du-titre'],
    recto: 'Formule de la relution du BPA après rachat, avec l\'exemple du cours ?',
    verso: 'BPA = bénéfice/titres : 100 M€/10 M = 10 €. Rachat et annulation de 1 M de titres → 100/9 ≈ 11,11 €, soit +11 % sans qu\'un client de plus soit facturé. Réflexe : décomposer toute croissance du BPA entre bénéfice et dénominateur.',
    rectoEn: 'EPS accretion formula after a buyback, with the course example?',
    versoEn: 'EPS = profit/shares: €100m/10M = €10. Buy back and cancel 1M shares → 100/9 ≈ €11.11, i.e. +11% without one more customer billed. Reflex: decompose any EPS growth between profit and denominator.',
  },
  {
    id: 'm3-fc-083',
    moduleId: M3,
    tags: ['piege', 'vie-du-titre'],
    recto: 'Acheter la veille du détachement pour « toucher le dividende » : bonne affaire ?',
    verso: 'Non : détacher n\'est pas gagner. 2,50 € de cash reçus, mais le titre vaut 2,50 € de moins — transfert de la poche titre vers la poche espèces, neutre avant frais, perdant après frais et fiscalité. Si le dividend capture rapportait, il serait arbitré depuis longtemps — c\'est l\'efficience.',
    rectoEn: 'Buying the day before the ex-date to "catch the dividend": good deal?',
    versoEn: 'No: detaching is not earning. €2.50 of cash received, but the share is worth €2.50 less — a transfer from the share pocket to the cash pocket, neutral before costs, losing after fees and taxes. If dividend capture paid, it would have been arbitraged away — that is efficiency.',
  },
  {
    id: 'm3-fc-084',
    moduleId: M3,
    tags: ['piege', 'vie-du-titre'],
    recto: 'Placement accéléré (ABB) à 46 € pour un titre à 50 € : que subissent les actionnaires en place ?',
    verso: 'Une dilution sans compensation : 500 M€ levés → ~10,87 M de titres neufs, cours d\'équilibre ≈ 49,61 €. L\'actionnaire à 1 % tombe à 0,90 % et perd ~0,8 % : ~39 M€ transférés aux entrants servis à 46 €. C\'est exactement le transfert que le DPS neutralise.',
    rectoEn: 'Accelerated bookbuild (ABB) at €46 for a €50 stock: what do existing shareholders suffer?',
    versoEn: 'Uncompensated dilution: €500m raised → ~10.87M new shares, equilibrium price ≈ €49.61. The 1% shareholder falls to 0.90% and loses ~0.8%: ~€39m transferred to newcomers served at €46. Exactly the transfer that subscription rights neutralize.',
  },
  {
    id: 'm3-fc-085',
    moduleId: M3,
    tags: ['piege', 'vie-du-titre'],
    recto: 'Un rachat d\'actions fait bondir le BPA de 11 % : de la valeur a-t-elle été créée ?',
    verso: 'Non — relutif n\'est pas créateur de valeur : même bénéfice, moins de titres, effet purement mécanique. Le cash est sorti de l\'entreprise. La critique récurrente — racheter au plus haut du cycle, doper cosmétiquement le BPA plutôt qu\'investir — mérite d\'être citée, sans réquisitoire.',
    rectoEn: 'A buyback lifts EPS by 11%: was value created?',
    versoEn: 'No — accretive is not value-creating: same profit, fewer shares, a purely mechanical effect. The cash has left the company. The recurring critique — buying back at cycle peaks, cosmetically boosting EPS instead of investing — deserves a mention, without turning prosecutor.',
  },
  {
    id: 'm3-fc-086',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'vie-du-titre'],
    recto: 'Les rachats d\'actions du S&P 500 : ordre de grandeur annuel ?',
    verso: 'Souvent plus de 800 Md$ par an ces dernières années — généralement davantage que les dividendes versés. L\'Amérique des grandes capitalisations rend l\'essentiel du cash par les buybacks, pas par le dividende.',
    rectoEn: 'S&P 500 buybacks: annual order of magnitude?',
    versoEn: 'Often more than $800bn a year in recent years — generally more than dividends paid. Large-cap America returns most of its cash through buybacks, not dividends.',
  },
  {
    id: 'm3-fc-087',
    moduleId: M3,
    tags: ['reflexe-jury', 'vie-du-titre'],
    recto: 'Le jury : « Vous avez 400 actions à 50 €. Augmentation de capital 1 pour 4 à 40 €. Vos options ? »',
    verso: 'Réflexe, les trois comptes : souscrire — 4 000 € versés, 500 actions à 48 = 24 000 € (mise + apport) ; vendre les droits — 400 × 2 = 800 € + ligne de 19 200 = 20 000 €, neutre ; ne rien faire — 19 200 €, 800 € évaporés. Morale : un DPS s\'exerce ou se vend, jamais ne s\'oublie.',
    rectoEn: 'The panel: "You hold 400 shares at €50. 1-for-4 rights issue at €40. Your options?"',
    versoEn: 'Reflex, the three tallies: subscribe — €4,000 paid, 500 shares at 48 = €24,000 (stake + contribution); sell the rights — 400 × 2 = €800 + a €19,200 line = €20,000, neutral; do nothing — €19,200, €800 evaporated. Moral: a right is exercised or sold, never forgotten.',
  },
  {
    id: 'm3-fc-088',
    moduleId: M3,
    tags: ['reflexe-jury', 'vie-du-titre'],
    recto: 'Le jury : « Buyback ou dividende : que doit choisir une direction ? »',
    verso: 'Réflexe : les deux camps. Rachat : flexibilité (un dividende coupé est sanctionné, un programme se suspend sans drame), signal « titre bon marché », fiscalité souvent favorable — prudence, ça varie. Dividende : discipline du rendez-vous, clientèle de rendement. Contexte US : rachats > 800 Md$/an, plus que les dividendes.',
    rectoEn: 'The panel: "Buyback or dividend: what should management choose?"',
    versoEn: 'Reflex: both sides. Buyback: flexibility (a cut dividend is punished, a programme pauses without drama), the "cheap stock" signal, often favourable taxation — carefully, it varies. Dividend: the discipline of the rendezvous, an income clientele. US context: buybacks > $800bn/yr, more than dividends.',
  },
  {
    id: 'm3-fc-089',
    moduleId: M3,
    tags: ['calcul-mental', 'vie-du-titre'],
    recto: 'De tête : split 5:1 d\'un titre à 750 € ? Regroupement 10:1 d\'un titre à 0,80 € ?',
    verso: '÷N ou ×N sur le cours, l\'inverse sur le nombre de titres : 750/5 = 150 € ; 0,80 × 10 = 8 €. Capitalisation et valeur de la ligne inchangées dans les deux cas — seul le message diffère : le split signale le succès, le regroupement souvent la détresse.',
    rectoEn: 'In your head: 5:1 split of a €750 share? 10:1 reverse split of a €0.80 share?',
    versoEn: '÷N or ×N on the price, the inverse on the share count: 750/5 = €150; 0.80 × 10 = €8. Capitalization and position value unchanged in both cases — only the message differs: a split signals success, a reverse split often distress.',
  },
  {
    id: 'm3-fc-090',
    moduleId: M3,
    tags: ['calcul-mental', 'vie-du-titre'],
    recto: 'De tête : titre à 50 €, émission à 40 €, 1 pour 4 — DPS et TERP en deux secondes ?',
    verso: 'DPS = écart/(n+1) = 10/5 = 2 € ; TERP = cours − DPS = 50 − 2 = 48 €. Le raccourci évite la moyenne pondérée : l\'écart de prix se partage entre n+1 actions.',
    rectoEn: 'In your head: €50 stock, €40 issue, 1-for-4 — right value and TERP in two seconds?',
    versoEn: 'Right = gap/(n+1) = 10/5 = €2; TERP = price − right = 50 − 2 = €48. The shortcut skips the weighted average: the price gap is shared across n+1 shares.',
  },
  {
    id: 'm3-fc-091',
    moduleId: M3,
    tags: ['calcul-mental', 'vie-du-titre'],
    recto: 'De tête : relution du BPA si la société rachète 10 % de ses actions ? Et 5 % ?',
    verso: 'Relution ≈ % racheté/(1 − %) : 10 % → 0,10/0,90 ≈ +11,1 % ; 5 % → 0,05/0,95 ≈ +5,3 %. Vérification du cours : 100/9 = 11,11 contre BPA de 10. Toujours un peu PLUS que le pourcentage racheté.',
    rectoEn: 'In your head: EPS accretion if the company buys back 10% of its shares? And 5%?',
    versoEn: 'Accretion ≈ % bought/(1 − %): 10% → 0.10/0.90 ≈ +11.1%; 5% → 0.05/0.95 ≈ +5.3%. Course check: 100/9 = 11.11 versus an EPS of 10. Always slightly MORE than the percentage bought back.',
  },

  // ───────────────────────── Chapitre 6 — IPO : l'entrée en bourse ─────────────────────────
  {
    id: 'm3-fc-092',
    moduleId: M3,
    tags: ['definition', 'ipo'],
    recto: 'Une IPO, c\'est quoi — et pourquoi (ou pourquoi pas) s\'introduire en bourse ?',
    verso: 'La première vente d\'actions au public — l\'archétype du marché primaire. Quatre motifs : lever du capital, offrir une sortie aux actionnaires (souvent la vraie raison), une monnaie d\'acquisition, la notoriété. En face : frais de 3 à 7 %, transparence totale, court-termisme du trimestre.',
    rectoEn: 'What is an IPO — and why (or why not) go public?',
    versoEn: 'The first sale of shares to the public — the primary market\'s archetype. Four motives: raise capital, give shareholders an exit (often the real reason), an acquisition currency, visibility. On the other side: 3 to 7% fees, full transparency, quarterly short-termism.',
  },
  {
    id: 'm3-fc-093',
    moduleId: M3,
    tags: ['definition', 'ipo'],
    recto: 'Le book-building, c\'est quoi ?',
    verso: 'La construction du livre d\'ordres : les banques recueillent les intentions des institutionnels — quantité, sensibilité au prix — sur une fourchette indicative, puis fixent le prix final au vu de la demande, souvent la veille au soir. La syndication obligataire appliquée à un actif sans prix de marché préexistant.',
    rectoEn: 'What is book building?',
    versoEn: 'Building the order book: banks collect institutional intentions — quantity, price sensitivity — over an indicative range, then set the final price based on demand, often the night before listing. Bond syndication applied to an asset with no pre-existing market price.',
  },
  {
    id: 'm3-fc-094',
    moduleId: M3,
    tags: ['definition', 'ipo'],
    recto: 'La greenshoe (option de surallocation), c\'est quoi ?',
    verso: 'Le syndicat place 115 % des titres — short de 15 % — avec une option d\'achat à 30 jours au prix d\'IPO consentie par l\'émetteur. Cours faible : il rachète en marché (soutien du cours) ; cours fort : il exerce l\'option. Soutien de cours organisé, légal car annoncé au prospectus. Nom : Green Shoe Manufacturing, 1963.',
    rectoEn: 'What is the greenshoe (over-allotment option)?',
    versoEn: 'The syndicate places 115% of the shares — short 15% — with a 30-day call option at the IPO price granted by the issuer. Weak price: it buys back in the market (price support); strong price: it exercises the option. Organized price support, legal because disclosed in the prospectus. Name: Green Shoe Manufacturing, 1963.',
  },
  {
    id: 'm3-fc-095',
    moduleId: M3,
    tags: ['definition', 'ipo'],
    recto: 'Le lock-up, c\'est quoi — et pourquoi son expiration est-elle surveillée ?',
    verso: 'L\'engagement des dirigeants et actionnaires historiques de ne pas vendre pendant 90 à 180 jours après l\'IPO, pour éviter un déferlement de titres d\'initiés. À l\'expiration — date connue de tous —, une offre massive devient libre d\'un coup : le cours est fréquemment sous pression à l\'approche.',
    rectoEn: 'What is the lock-up — and why is its expiry watched?',
    versoEn: 'The commitment by executives and historical shareholders not to sell for 90 to 180 days after the IPO, to avoid a flood of insider shares. At expiry — a date everyone knows —, a massive potential supply is freed at once: the price is frequently under pressure as it approaches.',
  },
  {
    id: 'm3-fc-096',
    moduleId: M3,
    tags: ['piege', 'ipo'],
    recto: 'Le « pop » du premier jour d\'une IPO : une bonne nouvelle pour tout le monde ?',
    verso: 'Non : chaque euro de hausse est un euro que l\'émetteur et les vendeurs auraient pu encaisser — le money left on the table. Une IPO de 1 Md€ qui pope de 15 % offre 150 M€ aux investisseurs servis. Le folklore célèbre ce que l\'émetteur devrait pleurer.',
    rectoEn: 'An IPO\'s first-day "pop": good news for everyone?',
    versoEn: 'No: every euro of rise is a euro the issuer and sellers could have pocketed — the money left on the table. A €1bn IPO popping 15% hands €150m to the investors who got allocations. The folklore celebrates what the issuer should mourn.',
  },
  {
    id: 'm3-fc-097',
    moduleId: M3,
    tags: ['piege', 'ipo'],
    recto: 'Vous souscrivez toutes les IPO et l\'une vous sert à 100 %. Pourquoi vous méfier ?',
    verso: 'La malédiction du gagnant : les allocations sont rationnées sur les bonnes opérations et généreuses sur les mauvaises — être servi largement suggère que les informés n\'en voulaient pas. Corrigée de ce biais d\'allocation, la stratégie « souscrire tout » perd l\'essentiel de son attrait.',
    rectoEn: 'You subscribe to every IPO and one fills you at 100%. Why worry?',
    versoEn: 'The winner\'s curse: allocations are rationed on good deals and generous on bad ones — being served in full suggests informed investors did not want it. Corrected for this allocation bias, the "subscribe to everything" strategy loses most of its appeal.',
  },
  {
    id: 'm3-fc-098',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'ipo'],
    recto: 'Les frais directs d\'une IPO : ordre de grandeur ?',
    verso: '3 à 7 % du montant levé pour la commission du syndicat — le haut de la fourchette remarquablement stable aux États-Unis pour les opérations moyennes — sans compter avocats, auditeurs et communication.',
    rectoEn: 'An IPO\'s direct fees: order of magnitude?',
    versoEn: '3 to 7% of the amount raised for the syndicate\'s fee — the top of the range remarkably sticky in the US for mid-sized deals — not counting lawyers, auditors and communication.',
  },
  {
    id: 'm3-fc-099',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'ipo'],
    recto: 'Le pop moyen du premier jour d\'une IPO : ordre de grandeur ?',
    verso: '10 à 20 % selon les marchés et les époques — le fait stylisé le plus célèbre de la littérature financière. Excès spectaculaires : plus de 50 % en moyenne aux États-Unis au pic de la bulle internet de 1999-2000.',
    rectoEn: 'The average first-day IPO pop: order of magnitude?',
    versoEn: '10 to 20% depending on markets and eras — the most famous stylized fact in the finance literature. Spectacular excesses: over 50% on average in the US at the peak of the 1999-2000 internet bubble.',
  },
  {
    id: 'm3-fc-100',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'ipo'],
    recto: 'La greenshoe et le lock-up : les chiffres clés à connaître ?',
    verso: 'Greenshoe : surallocation de 15 % des titres, option exerçable 30 jours au prix d\'IPO. Lock-up : 90 à 180 jours d\'interdiction de vente pour les initiés. Deux garde-fous des premiers mois de cotation.',
    rectoEn: 'The greenshoe and the lock-up: the key figures?',
    versoEn: 'Greenshoe: 15% over-allotment, option exercisable for 30 days at the IPO price. Lock-up: 90 to 180 days of no selling for insiders. The two guardrails of the first months of trading.',
  },
  {
    id: 'm3-fc-101',
    moduleId: M3,
    tags: ['reflexe-jury', 'ipo'],
    recto: 'Le jury : « Pourquoi la décote d\'IPO persiste-t-elle depuis des décennies, sur tous les marchés ? »',
    verso: 'Réflexe, trois moteurs cumulés : asymétrie d\'information (la décote dédommage les non-informés qui restent au jeu), assurance contre l\'échec (casser son prix le jour 1 entame durablement la confiance), incitations des banques (sous-pricer réduit leur risque et sert leurs clients récurrents — l\'émetteur ne fait une IPO qu\'une fois). Poids respectifs débattus ; même sens pour les trois.',
    rectoEn: 'The panel: "Why has IPO underpricing persisted for decades, on every market?"',
    versoEn: 'Reflex, three stacked drivers: information asymmetry (the discount compensates the uninformed for staying in the game), insurance against failure (breaking the price on day 1 durably dents confidence), banks\' incentives (underpricing cuts their placement risk and pleases recurring clients — the issuer only IPOs once). Respective weights debated; all three pull the same way.',
  },
  {
    id: 'm3-fc-102',
    moduleId: M3,
    tags: ['reflexe-jury', 'ipo'],
    recto: 'Le jury : « Spotify n\'a pas fait d\'IPO classique. Qu\'a-t-elle fait, et pourquoi ? »',
    verso: 'Réflexe : un direct listing (2018, puis Slack en 2019) — cotation des actions existantes sans émission, sans syndicat ni book-building. Pas de levée de fonds, mais ni décote d\'IPO ni frais de placement : la voie des sociétés connues qui n\'ont pas besoin d\'argent frais. Autre alternative : le SPAC — boom 2020-2021 (600+ véhicules en 2021), retombé en niche.',
    rectoEn: 'The panel: "Spotify did not do a classic IPO. What did it do, and why?"',
    versoEn: 'Reflex: a direct listing (2018, then Slack in 2019) — listing existing shares with no issuance, no syndicate, no book building. No funds raised, but no IPO discount and no placement fees: the route for well-known companies that need no fresh money. Other alternative: the SPAC — 2020-2021 boom (600+ vehicles in 2021), now back to a niche.',
  },
  {
    id: 'm3-fc-103',
    moduleId: M3,
    tags: ['reflexe-jury', 'ipo'],
    recto: 'Le jury : « IPO de 10 M de titres à 20 €. Déroulez la greenshoe si le titre va à 19 €, puis à 24 €. »',
    verso: 'Réflexe : le syndicat a placé 11,5 M de titres, short de 1,5 M. À 19 € : il rachète 1,5 M en marché — demande qui amortit la baisse —, solde son short avec ~1,5 M€ de gain, l\'option expire. À 24 € : racheter serait perdant, il exerce l\'option à 20 € — l\'émetteur lève 15 % de plus. La banque ne peut pas perdre : c\'est voulu, on la paie pour stabiliser sans risque.',
    rectoEn: 'The panel: "IPO of 10M shares at €20. Walk the greenshoe through €19, then €24."',
    versoEn: 'Reflex: the syndicate placed 11.5M shares, short 1.5M. At €19: it buys 1.5M back in the market — demand that cushions the fall —, closes its short with ~€1.5m of gain, the option lapses. At €24: buying back would lose, it exercises the option at €20 — the issuer raises 15% more. The bank cannot lose: by design, it is paid to stabilize risk-free.',
  },
  {
    id: 'm3-fc-104',
    moduleId: M3,
    tags: ['calcul-mental', 'ipo'],
    recto: 'De tête : IPO de 1 Md€, pop de 15 % — argent laissé sur la table ? Et les frais à 3-7 % ?',
    verso: 'Money left = 1 Md€ × 15 % = 150 M€ offerts aux investisseurs servis. Frais : 3 à 7 % de 1 Md€ = 30 à 70 M€ pour le syndicat. L\'entrée en bourse coûte des deux côtés : la décote ET la commission.',
    rectoEn: 'In your head: €1bn IPO, 15% pop — money left on the table? And the 3-7% fees?',
    versoEn: 'Money left = €1bn × 15% = €150m handed to allocated investors. Fees: 3 to 7% of €1bn = €30 to 70m for the syndicate. Going public costs on both sides: the discount AND the commission.',
  },

  // ───────────────────────── Chapitre 7 — Short selling et efficience ─────────────────────────
  {
    id: 'm3-fc-105',
    moduleId: M3,
    tags: ['definition', 'short-efficience'],
    recto: 'La vente à découvert, en quatre temps ?',
    verso: 'Emprunter les titres (prêt-emprunt, contre collatéral et commission — le repo des actions), vendre au marché, racheter après la baisse espérée, rendre au prêteur. Le coût d\'emprunt court pendant TOUTE la position, en base Exact/360, et il est dû quoi qu\'il arrive.',
    rectoEn: 'Short selling, in four steps?',
    versoEn: 'Borrow the shares (securities lending, against collateral and a fee — the repo of equities), sell in the market, buy back after the hoped-for fall, return to the lender. The borrow cost runs for the WHOLE position, on an Act/360 basis, and is owed no matter what.',
  },
  {
    id: 'm3-fc-106',
    moduleId: M3,
    tags: ['definition', 'short-efficience'],
    recto: 'Short interest et short squeeze : définitions liées ?',
    verso: 'Le short interest est l\'encours des positions vendeuses, lu en % du flottant — le carburant. Le squeeze est l\'incendie : la hausse inflige des pertes aux vendeurs, les appels de marge forcent des rachats, qui font monter le cours, qui aggrave les pertes des autres. GameStop 2021 : ~140 % du flottant.',
    rectoEn: 'Short interest and short squeeze: linked definitions?',
    versoEn: 'Short interest is the outstanding stock of short positions, read as % of the float — the fuel. The squeeze is the fire: the rise inflicts losses on sellers, margin calls force buy-backs, which push the price up, worsening the others\' losses. GameStop 2021: ~140% of the float.',
  },
  {
    id: 'm3-fc-107',
    moduleId: M3,
    tags: ['definition', 'short-efficience'],
    recto: 'L\'hypothèse d\'efficience des marchés (EMH) : les trois formes ?',
    verso: 'Formalisée par Fama (années 1960), trois formes emboîtées. Faible : les cours passés sont dans les prix — les graphiques ne prédisent rien. Semi-forte : toute l\'information PUBLIQUE est dans les prix quelques instants après publication. Forte : même l\'information privée — rejetée par tous : sinon, pas besoin d\'interdire le délit d\'initié.',
    rectoEn: 'The efficient market hypothesis (EMH): the three forms?',
    versoEn: 'Formalized by Fama (1960s), three nested forms. Weak: past prices are in the price — charts predict nothing. Semi-strong: all PUBLIC information is in the price moments after release. Strong: even private information — rejected by everyone: otherwise insider trading would not need banning.',
  },
  {
    id: 'm3-fc-108',
    moduleId: M3,
    tags: ['formule', 'short-efficience'],
    recto: 'P&L d\'un short : 1 000 titres vendus à 100 €, rachetés à 90 € après 90 jours, emprunt à 2 % ?',
    verso: 'Brut : (100 − 90) × 1 000 = 10 000 €. Frais : 100 000 × 2 % × 90/360 = 500 €. Net : 9 500 €. Et si le titre était remonté à 110 € : perte de 10 500 € nets — les frais sont dus quoi qu\'il arrive.',
    rectoEn: 'Short P&L: 1,000 shares sold at €100, bought back at €90 after 90 days, 2% borrow?',
    versoEn: 'Gross: (100 − 90) × 1,000 = €10,000. Fees: 100,000 × 2% × 90/360 = €500. Net: €9,500. And had the stock risen to €110: a €10,500 net loss — the fees are owed no matter what.',
  },
  {
    id: 'm3-fc-109',
    moduleId: M3,
    tags: ['formule', 'short-efficience'],
    recto: 'Formule du coût d\'emprunt de titres — et que signale un taux qui s\'envole ?',
    verso: 'Frais = notionnel vendu × taux × jours/360 : 100 000 € × 2 % × 90/360 = 500 €. 2 % = grande capitalisation liquide ; un titre hard to borrow monte à des dizaines de % annualisés — l\'équivalent du titre « spécial » au repo : la rareté à l\'emprunt a un prix, et ce prix est un signal.',
    rectoEn: 'Securities borrow cost formula — and what does a soaring rate signal?',
    versoEn: 'Fee = notional sold × rate × days/360: €100,000 × 2% × 90/360 = €500. 2% = liquid large cap; a hard-to-borrow stock climbs to tens of percent annualized — the equivalent of a bond trading "special" in repo: scarcity at the borrow has a price, and that price is a signal.',
  },
  {
    id: 'm3-fc-110',
    moduleId: M3,
    tags: ['piege', 'short-efficience'],
    recto: 'Short à 100 € : combien pouvez-vous gagner au mieux ? Et perdre au pire ?',
    verso: 'Gain plafonné à 100 € par titre (faillite, titre à zéro) ; perte ILLIMITÉE — aucun plafond ne borne la hausse : à 300 €, vous perdez 200 €. Aggravants : le prêteur peut rappeler ses titres (recall), et les appels de marge forcent à remettre du cash chaque jour ou à couper. C\'est l\'asymétrie qui rend les squeezes possibles.',
    rectoEn: 'Short at €100: how much can you make at best? Lose at worst?',
    versoEn: 'Gain capped at €100 per share (bankruptcy, stock at zero); UNLIMITED loss — no ceiling bounds a rise: at €300, you lose €200. Aggravators: the lender can recall its shares, and margin calls force daily cash top-ups or a cut. That asymmetry is what makes squeezes possible.',
  },
  {
    id: 'm3-fc-111',
    moduleId: M3,
    tags: ['piege', 'short-efficience'],
    recto: 'Le titre que vous shortez détache un dividende de 2,50 €. Le cours baisse d\'autant : gain ?',
    verso: 'Non : pendant le prêt, le prêteur reste l\'investisseur économique — le vendeur à découvert doit lui reverser l\'équivalent du dividende détaché. La baisse mécanique du cours est exactement compensée par ce versement : détachement neutre pour le short, comme pour l\'actionnaire.',
    rectoEn: 'The stock you short detaches a €2.50 dividend. The price drops by as much: profit?',
    versoEn: 'No: during the loan, the lender remains the economic investor — the short seller must pay them the equivalent of the detached dividend. The mechanical price drop is exactly offset by that payment: the detachment is neutral for the short, as for the shareholder.',
  },
  {
    id: 'm3-fc-112',
    moduleId: M3,
    tags: ['piege', 'short-efficience'],
    recto: 'Un short interest à 140 % du flottant : impossible, puisqu\'on ne peut pas vendre plus que ce qui existe ?',
    verso: 'Possible : un titre emprunté puis vendu peut être RÉEMPRUNTÉ à son nouveau détenteur et revendu — la chaîne compte double. C\'était GameStop en janvier 2021 : l\'encours vendeur dépassait le flottant, de l\'ordre de 140 % selon les données de l\'époque.',
    rectoEn: 'Short interest at 140% of the float: impossible, since you cannot sell more than exists?',
    versoEn: 'Possible: a share borrowed then sold can be RE-BORROWED from its new holder and sold again — the chain counts twice. That was GameStop in January 2021: short interest exceeded the float, around 140% according to data at the time.',
  },
  {
    id: 'm3-fc-113',
    moduleId: M3,
    tags: ['piege', 'short-efficience'],
    recto: '« Les marchés sont efficients » : faut-il le dire sans nuance à l\'oral ?',
    verso: 'Non — efficients LA PLUPART DU TEMPS, pas tout le temps. Assez pour que battre l\'indice soit exceptionnellement difficile (SPIVA : 80-90 % des gérants sous l\'indice à 10 ans) ; pas assez pour empêcher bulles et anomalies (momentum, value, petites capis — qui s\'érodent une fois publiées). Tenir les deux faits.',
    rectoEn: '"Markets are efficient": should you say it without nuance at the oral?',
    versoEn: 'No — efficient MOST of the time, not all the time. Enough that beating the index is exceptionally hard (SPIVA: 80-90% of managers below the index over 10 years); not enough to prevent bubbles and anomalies (momentum, value, small caps — which erode once published). Hold both facts.',
  },
  {
    id: 'm3-fc-114',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'short-efficience'],
    recto: 'GameStop, janvier 2021 : les chiffres à connaître ?',
    verso: 'Short interest ≈ 140 % du flottant ; le titre passe d\'environ 20 $ à près de 500 $ en séance ; Melvin Capital, le fonds le plus exposé, perd plusieurs milliards et ferme l\'année suivante. Et la suspension des achats chez certains courtiers : appels de marge de la chambre de compensation, pas complot.',
    rectoEn: 'GameStop, January 2021: the numbers to know?',
    versoEn: 'Short interest ≈ 140% of the float; the stock goes from about $20 to nearly $500 intraday; Melvin Capital, the most exposed fund, loses billions and shuts the following year. And the buying halt at some brokers: clearing-house margin calls, not a conspiracy.',
  },
  {
    id: 'm3-fc-115',
    moduleId: M3,
    tags: ['ordre-de-grandeur', 'short-efficience'],
    recto: 'Les décomptes SPIVA : quel chiffre, et que prouve-t-il ?',
    verso: 'De l\'ordre de 80 à 90 % des gérants actions font moins bien que leur indice sur dix ans, selon catégories et périodes — et la surperformance passée ne persiste guère. La preuve empirique la plus parlante de la forme semi-forte : l\'information publique ne laisse pas de billets par terre.',
    rectoEn: 'The SPIVA scorecards: what figure, and what does it prove?',
    versoEn: 'Around 80 to 90% of equity managers underperform their index over ten years, depending on categories and periods — and past outperformance barely persists. The most telling empirical evidence for the semi-strong form: public information leaves no banknotes on the ground.',
  },
  {
    id: 'm3-fc-116',
    moduleId: M3,
    tags: ['reflexe-jury', 'short-efficience'],
    recto: 'Le jury : « Racontez GameStop en 60 secondes. »',
    verso: 'Réflexe : janvier 2021, short interest ≈ 140 % du flottant — la chaîne d\'emprunt compte double. Des acheteurs coordonnés sur les réseaux font monter le cours : pertes des vendeurs, appels de marge, rachats forcés qui alimentent la hausse — le squeeze. ~20 $ → près de 500 $ en séance ; Melvin perd des milliards. Finale qui classe : les courtiers ont bloqué les achats sur appels de marge de la chambre, pas par complot.',
    rectoEn: 'The panel: "Tell GameStop in 60 seconds."',
    versoEn: 'Reflex: January 2021, short interest ≈ 140% of the float — the borrow chain counts twice. Coordinated buyers on social media push the price up: sellers\' losses, margin calls, forced buy-backs feeding the rise — the squeeze. ~$20 → nearly $500 intraday; Melvin loses billions. The closing line that ranks you: brokers halted buying on clearing-house margin calls, not conspiracy.',
  },
  {
    id: 'm3-fc-117',
    moduleId: M3,
    tags: ['reflexe-jury', 'short-efficience'],
    recto: 'Le jury : « À quoi servent les vendeurs à découvert ? »',
    verso: 'Réflexe, trois services : la liquidité (les teneurs de marché ne peuvent coter à la vente que parce que le short permet de livrer) ; la découverte des prix (sans short, seuls les optimistes votent) ; la chasse aux fraudes — Wirecard : shorts et FT documentent dès 2015, la BaFin interdit le short et attaque les journalistes, juin 2020 : 1,9 Md€ de trésorerie inexistants. Et les interdictions en panique : liquidité dégradée, sans soutien clair des cours.',
    rectoEn: 'The panel: "What are short sellers for?"',
    versoEn: 'Reflex, three services: liquidity (market makers can only quote offers because shorting lets them deliver); price discovery (without shorts, only optimists vote); fraud hunting — Wirecard: shorts and the FT document from 2015, BaFin bans shorting and sues the journalists, June 2020: €1.9bn of cash does not exist. And panic bans: degraded liquidity, no clear price support.',
  },
  {
    id: 'm3-fc-118',
    moduleId: M3,
    tags: ['reflexe-jury', 'short-efficience'],
    recto: 'Le jury : « Alors, les marchés sont-ils efficients ? »',
    verso: 'Réflexe : les trois formes (faible, semi-forte, forte), puis les deux faits. Pour : SPIVA, 80-90 % des gérants sous l\'indice à 10 ans. Contre : momentum, value, petites capis — et les bulles qui reviennent siècle après siècle. Synthèse qui classe : « efficients la plupart du temps, pas tout le temps » — assez pour l\'humilité, pas assez pour la foi aveugle.',
    rectoEn: 'The panel: "So, are markets efficient?"',
    versoEn: 'Reflex: the three forms (weak, semi-strong, strong), then both facts. For: SPIVA, 80-90% of managers below the index over 10 years. Against: momentum, value, small caps — and bubbles returning century after century. The closing synthesis: "efficient most of the time, not all the time" — enough for humility, not enough for blind faith.',
  },
  {
    id: 'm3-fc-119',
    moduleId: M3,
    tags: ['reflexe-jury', 'short-efficience'],
    recto: 'Le jury : « 3Com/Palm, mars 2000 : une inefficience flagrante a coté des mois. Pourquoi ? »',
    verso: 'Réflexe : les 95 % de Palm détenus par 3Com valaient plus que 3Com entière — le reste valait ≈ −60 $ par action (Lamont-Thaler). L\'arbitrage (acheter 3Com, shorter Palm) crevait les yeux mais était impraticable : titres Palm introuvables à l\'emprunt, coûts prohibitifs. Leçon : l\'efficience est FABRIQUÉE par des arbitragistes qui ont besoin de la tuyauterie du prêt-emprunt — « le marché peut rester irrationnel plus longtemps que vous ne pouvez rester solvable ».',
    rectoEn: 'The panel: "3Com/Palm, March 2000: a flagrant inefficiency traded for months. Why?"',
    versoEn: 'Reflex: 3Com\'s 95% stake in Palm was worth more than all of 3Com — the rest priced at ≈ −$60 per share (Lamont-Thaler). The arbitrage (buy 3Com, short Palm) was blindingly obvious yet impracticable: Palm shares nearly unborrowable, prohibitive costs. Lesson: efficiency is MANUFACTURED by arbitrageurs who need the securities-lending plumbing — "the market can stay irrational longer than you can stay solvent".',
  },
  {
    id: 'm3-fc-120',
    moduleId: M3,
    tags: ['calcul-mental', 'short-efficience'],
    recto: 'De tête : frais d\'emprunt sur 100 000 € de notionnel, 90 jours à 2 % ? Et à 20 % (hard to borrow) ?',
    verso: '90/360 = un quart d\'année : 2 % × ¼ = 0,5 % du notionnel → 500 €. À 20 % : 5 % du notionnel → 5 000 € — la moitié du gain de 10 000 € de l\'exemple du cours partie en commission. Le taux d\'emprunt peut tuer la thèse.',
    rectoEn: 'In your head: borrow fees on €100,000 notional, 90 days at 2%? And at 20% (hard to borrow)?',
    versoEn: '90/360 = a quarter of a year: 2% × ¼ = 0.5% of notional → €500. At 20%: 5% of notional → €5,000 — half of the course example\'s €10,000 gain gone in fees. The borrow rate can kill the thesis.',
  },
];
