import type { Formule } from '../../../engine/types';

const M3 = '03-actions-indices';

export const formules: Formule[] = [
  {
    id: 'm3-f-01',
    moduleId: M3,
    nom: 'Gordon-Shapiro (perpétuité croissante)',
    nomEn: 'Gordon growth model (growing perpetuity)',
    latex: 'V_0 = \\frac{D_1}{r - g} \\qquad (r > g)',
    commentaire: 'Pour valoriser un dividende en croissance perpétuelle : D₁ est le dividende attendu dans un an — pas le dernier versé. Exemple canonique : 5/(0,08 − 0,03) = 100 €.',
    commentaireEn: 'To value a dividend growing forever: D₁ is the dividend expected one year out — not the last one paid. Canonical example: 5/(0.08 − 0.03) = €100.',
  },
  {
    id: 'm3-f-02',
    moduleId: M3,
    nom: 'Croissance soutenable',
    nomEn: 'Sustainable growth',
    latex: 'g = ROE \\times b \\qquad b = 1 - d',
    commentaire: 'Pour ancrer g : une entreprise ne croît durablement qu\'au rythme de ce qu\'elle réinvestit — b est le taux de rétention, d le payout. ROE 12 %, payout 60 % : g = 4,8 %.',
    commentaireEn: 'To anchor g: a firm can only grow durably at the pace of what it reinvests — b is the retention rate, d the payout. ROE 12%, payout 60%: g = 4.8%.',
  },
  {
    id: 'm3-f-03',
    moduleId: M3,
    nom: 'DDM en deux étapes',
    nomEn: 'Two-stage DDM',
    latex: 'V_0 = \\sum_{t=1}^{n} \\frac{D_t}{(1+r)^t} + \\frac{VT_n}{(1+r)^n} \\qquad VT_n = \\frac{D_{n+1}}{r - g_2}',
    commentaire: 'Pour une croissance forte mais temporaire : projeter les dividendes explicites, fermer par Gordon sur le premier flux stable (D, indice n+1), puis tout actualiser — la valeur terminale aussi.',
    commentaireEn: 'For strong but temporary growth: project the explicit dividends, close with Gordon on the first stable flow (D, subscript n+1), then discount everything — the terminal value included.',
  },
  {
    id: 'm3-f-04',
    moduleId: M3,
    nom: 'DCF : valeur d\'entreprise par les flux disponibles',
    nomEn: 'DCF: enterprise value from free cash flows',
    latex: 'EV = \\sum_{t=1}^{n} \\frac{FCF_t}{(1+WACC)^t} + \\frac{VT_n}{(1+WACC)^n}',
    commentaire: 'Pour valoriser l\'entreprise entière par ses flux de trésorerie disponibles, actualisés au WACC ; valeur des actions = EV − dette nette. La valeur terminale pèse couramment 60 à 80 % du total.',
    commentaireEn: 'To value the whole firm through its free cash flows, discounted at the WACC; equity value = EV − net debt. The terminal value usually accounts for 60 to 80% of the total.',
  },
  {
    id: 'm3-f-05',
    moduleId: M3,
    nom: 'PER (ratio cours sur bénéfice)',
    nomEn: 'P/E ratio',
    latex: '\\text{PER} = \\frac{\\text{cours}}{\\text{BPA}}',
    commentaire: 'Pour lire combien d\'années de bénéfice le marché paie : 120 €/8 € = 15. Son inverse, le rendement bénéficiaire (1/15 ≈ 6,7 %), se compare directement à un taux obligataire.',
    commentaireEn: 'To read how many years of earnings the market pays: €120/€8 = 15. Its inverse, the earnings yield (1/15 ≈ 6.7%), compares directly with a bond yield.',
  },
  {
    id: 'm3-f-06',
    moduleId: M3,
    nom: 'PER théorique (issu de Gordon)',
    nomEn: 'Theoretical P/E (from Gordon)',
    latex: '\\text{PER} = \\frac{d\\,(1+g)}{r - g}',
    commentaire: 'Le PER caché dans Gordon, avec d = 1 − b le payout : un multiple est un DCF compressé — payer 25 fois les bénéfices, c\'est acheter implicitement un couple (r, g). d = 60 %, g = 3 %, r = 8 % : PER de 12,36.',
    commentaireEn: 'The P/E hidden in Gordon, with d = 1 − b the payout: a multiple is a compressed DCF — paying 25 times earnings is implicitly buying an (r, g) pair. d = 60%, g = 3%, r = 8%: P/E of 12.36.',
  },
  {
    id: 'm3-f-07',
    moduleId: M3,
    nom: 'EV/EBITDA',
    nomEn: 'EV/EBITDA',
    latex: '\\text{EV/EBITDA} = \\frac{\\text{capitalisation} + \\text{dette nette}}{\\text{EBITDA}}',
    commentaire: 'Pour comparer des outils économiques sans biais de structure financière : le prix de tous les capitaux au numérateur, le profit qui les rémunère tous au dénominateur. (900 + 300)/200 = 6 fois.',
    commentaireEn: 'To compare economic engines without capital-structure bias: the price of all capital on top, the profit that pays all of it below. (900 + 300)/200 = 6 times.',
  },
  {
    id: 'm3-f-08',
    moduleId: M3,
    nom: 'Rendement du dividende et payout',
    nomEn: 'Dividend yield and payout',
    latex: '\\text{rendement} = \\frac{D}{P} = \\frac{\\text{payout}}{\\text{PER}}',
    commentaire: 'Pour ce que rapporte chaque euro investi — et le contrôle de cohérence d\'une ligne de cote : payout 45 %, PER 15, rendement 3 %. Un rendement très au-dessus du secteur signale souvent un dividende condamné.',
    commentaireEn: 'For what each euro invested brings back — and the consistency check of a quote line: payout 45%, P/E 15, yield 3%. A yield far above the sector often signals a doomed dividend.',
  },
  {
    id: 'm3-f-09',
    moduleId: M3,
    nom: 'Ajustement ex-dividende',
    nomEn: 'Ex-dividend adjustment',
    latex: 'P_{\\text{ex}} = P - D',
    commentaire: 'Au détachement, le titre vaut le dividende de moins : transfert de la poche « titre » vers la poche « espèces » — détacher n\'est pas gagner. Sous le T+1 américain, ex-date et record date coïncident.',
    commentaireEn: 'On the ex-date, the share is worth the dividend less: a transfer from the "share" pocket to the "cash" pocket — going ex is not a gain. Under US T+1, ex-date and record date coincide.',
  },
  {
    id: 'm3-f-10',
    moduleId: M3,
    nom: 'Split k pour 1',
    nomEn: 'k-for-1 split',
    latex: 'P\' = \\frac{P}{k} \\qquad n\' = k \\times n',
    commentaire: 'Cours divisé par k, nombre de titres multiplié par k : capitalisation inchangée, BPA divisé par k — rien ne change économiquement. Seul un indice pondéré par les prix est perturbé.',
    commentaireEn: 'Price divided by k, share count multiplied by k: market cap unchanged, EPS divided by k — nothing changes economically. Only a price-weighted index is disturbed.',
  },
  {
    id: 'm3-f-11',
    moduleId: M3,
    nom: 'Cours théorique ex-droit et valeur du DPS',
    nomEn: 'Theoretical ex-rights price (TERP) and value of the right',
    latex: 'P_{\\text{ex-droit}} = \\frac{n\\,P + P_E}{n + 1} \\qquad \\text{DPS} = \\frac{P - P_E}{n + 1}',
    commentaire: 'Pour une augmentation de capital à n anciennes pour 1 nouvelle émise à P_E : le droit vaut la décote subie par le cours. (50 − 40)/5 = 2 € — un DPS s\'exerce ou se vend, jamais ne s\'oublie.',
    commentaireEn: 'For a rights issue at n old shares for 1 new one issued at P_E: the right is worth the discount suffered by the price. (50 − 40)/5 = €2 — a right is exercised or sold, never forgotten.',
  },
  {
    id: 'm3-f-12',
    moduleId: M3,
    nom: 'Poids dans un indice capi-pondéré',
    nomEn: 'Weight in a cap-weighted index',
    latex: 'w_i = \\frac{p_i\\,n_i\\,f_i}{\\sum_j p_j\\,n_j\\,f_j}',
    commentaire: 'Pour le poids d\'un constituant : cours × nombre de titres × flottant, rapporté au total du panier — le flottant aligne le poids sur le capital réellement achetable par les flux indiciels.',
    commentaireEn: 'For a constituent\'s weight: price × share count × free float, over the basket total — the float aligns the weight with the capital index flows can actually buy.',
  },
  {
    id: 'm3-f-13',
    moduleId: M3,
    nom: 'Niveau d\'indice et continuité du diviseur',
    nomEn: 'Index level and divisor continuity',
    latex: '\\text{Indice} = \\frac{\\sum_i p_i\\,n_i\\,f_i}{D} \\qquad D\' = D \\times \\frac{\\text{capi après}}{\\text{capi avant}}',
    commentaire: 'Le diviseur transforme une capitalisation en niveau et absorbe tout ce qui n\'est pas une variation de prix (entrées-sorties, opérations de capital) : l\'indice ne bouge que quand les prix bougent.',
    commentaireEn: 'The divisor turns a capitalisation into a level and absorbs everything that is not a price move (additions, deletions, capital operations): the index only moves when prices move.',
  },
  {
    id: 'm3-f-14',
    moduleId: M3,
    nom: 'P&L d\'une vente à découvert',
    nomEn: 'P&L of a short sale',
    latex: '\\text{P\\&L} = (P_v - P_r) \\times Q - N \\times t \\times \\frac{j}{360}',
    commentaire: 'Gain de la baisse (vente P_v, rachat P_r, Q titres) moins les frais d\'emprunt sur le notionnel vendu N, au taux t en Exact/360 — dus quoi qu\'il arrive. Exemple canonique : 10 000 − 500 = 9 500 € (pas 9 507 €, la base 365 est la mauvaise convention).',
    commentaireEn: 'Gain from the fall (sale P_v, buy-back P_r, Q shares) minus borrowing fees on the notional sold N, at rate t on Actual/360 — due whatever happens. Canonical example: 10,000 − 500 = €9,500 (not €9,507, the 365 base is the wrong convention).',
  },
  {
    id: 'm3-f-15',
    moduleId: M3,
    nom: 'Relution du BPA après rachat d\'actions',
    nomEn: 'EPS accretion after a buyback',
    latex: '\\text{BPA} = \\frac{\\text{bénéfice net}}{\\text{nombre de titres}} \\qquad \\text{BPA}\' = \\frac{\\text{BPA}}{1 - x}',
    commentaire: 'Racheter et annuler une fraction x des titres relue mécaniquement le BPA : x = 10 % → +11,1 % sans un client de plus. Relutif n\'est pas créateur de valeur — décomposer toute croissance du BPA.',
    commentaireEn: 'Buying back and cancelling a fraction x of the shares mechanically accretes EPS: x = 10% → +11.1% without a single extra customer. Accretive is not value-creating — decompose any EPS growth.',
  },
];
